---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/complete-preparation-for-upgrade.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 스토리지 암호화를 구성 및 관리하고 인증 키를 관리하며, ARL을 사용하여 동일한 섀시에서 컨트롤러 모델을 업그레이드할 때 SnapMirror 관계를 중지합니다. 
---
= 업그레이드 준비를 완료합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 라이선싱 및 온보드 키 관리자(OKM)를 사용한 스토리지 암호화 관리 방법에 대해 알아보세요. 필요에 따라 SnapMirror 관계를 중지할 수 있습니다.



== ONTAP 라이센스에 대해 알아보십시오

클러스터의 각 노드에는 고유한 NetApp 라이센스 파일(NLF)이 있어야 합니다.

NLF가 없는 경우 클러스터에서 현재 라이센스가 부여된 기능을 새 컨트롤러에서 사용할 수 있습니다. 그러나 컨트롤러에 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 업그레이드가 완료된 후 새 컨트롤러에 대해 NLF를 설치해야 합니다.

link:other-references.html["참조"]를 참조하여 NLF를 얻을 수 있는 _NetApp Support Site_에 연결하십시오. NLF는 _Software licenses_ 아래의 _My Support_ 섹션에서 사용할 수 있습니다. 사이트에 필요한 NLF가 없는 경우 NetApp 영업 담당자에게 문의하십시오.

ONTAP 라이센스에 대한 자세한 내용은 link:other-references.html["참조"]를 참조하여 _시스템 관리 참조_에 연결하십시오.



== Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다

Onboard Key Manager(OKM)를 사용하여 암호화 키를 관리하십시오. OKM이 설정되어 있는 경우 업그레이드를 시작하기 전에 암호와 백업 자료를 기록해야 합니다.

.단계
. 클러스터 전체 암호를 기록합니다.
+
OKM을 구성하거나 CLI 또는 REST API를 사용하여 업데이트할 때 입력한 암호입니다.

. 암호와 키 관리자 작동을 확인하십시오.
+
`security key-manager onboard sync`

+
메시지가 표시되면 이전 단계에서 기록한 클러스터 전체 OKM 암호를 입력합니다.

. 다음 명령의 출력을 검토하여 cc-mode가 활성화되었는지 확인하십시오.
+
`security key-manager config show`

. 키 관리자 정보를 백업합니다.
+
`security key-manager onboard show-backup`





== 선택적으로 SnapMirror 관계를 중지할 수 있습니다

절차를 계속하기 전에 모든 SnapMirror 관계가 중지되었는지 확인해야 합니다. SnapMirror 관계가 중지되면 재부팅 및 페일오버 시에도 계속 정지됩니다.

.단계
. 대상 클러스터에서 SnapMirror 관계 상태를 확인합니다.
+
`snapmirror show`

+
[NOTE]
====
상태가 "전송 중"인 경우 이러한 전송을 중단해야 합니다.
`snapmirror abort -destination-vserver _vserver_name_`

====
+
SnapMirror 관계가 "전송 중" 상태가 아니면 중단이 실패합니다.

. 클러스터 간의 모든 관계 중지:
+
`snapmirror quiesce -destination-vserver *`



.다음 단계
업그레이드 준비를 마친 후 link:relocate-non-root-aggr-and-nas-data-lifs-node1-node2.html["node1이 소유한 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 node2로 재배치합니다"].
