---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 동일한 섀시에 있는 컨트롤러 모델의 ARL 업그레이드 중에 노드 2에 교체 시스템 모듈을 설치합니다. 
---
= 노드2에 AFF A30, AFF A50, AFF C30 또는 AFF C60 모듈을 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드2에서 업그레이드를 위해 받은 교체용 컨트롤러 모듈을 설치합니다. 노드 2는 시스템 후면에서 컨트롤러를 볼 때 섀시 하단 절반에 위치한 컨트롤러 B입니다.

.단계
. 기억 장치 시스템을 캐비닛 또는 통신 랙의 중간에 있는 레일에 놓은 다음, 하단에서 기억 장치 시스템을 지지하고 제자리에 밀어 넣습니다.
+

NOTE: 절차의 뒷부분에서 지시가 있을 때까지 컨트롤러 모듈을 섀시에 완전히 삽입하지 마십시오.

. 노드2 컨트롤러 모듈에 관리 및 콘솔 포트를 케이블로 연결합니다.
+

NOTE: 섀시의 전원이 이미 켜져 있으므로, 노드2는 BIOS 초기화를 시작한 후 완전히 장착되자마자 AUTOBOOT를 시작합니다.  노드2 부팅을 중단하려면 컨트롤러 모듈을 슬롯에 완전히 삽입하기 전에 직렬 콘솔과 관리 케이블을 노드2 컨트롤러 모듈에 연결하는 것이 좋습니다.

. 캠 핸들을 열린 위치에 둔 상태에서 컨트롤러 모듈이 중앙판과 만나 완전히 장착될 때까지 단단히 밀어 넣습니다. 컨트롤러 모듈이 완전히 장착되면 잠금 래치가 올라갑니다. 캠 핸들을 잠금 위치로 닫습니다.
+

NOTE: 커넥터 손상을 방지하려면 컨트롤러 모듈을 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

. 모듈이 장착되면 즉시 직렬 콘솔을 연결하고 node2의 AUTOBOOT를 중단할 준비를 하세요.
. 자동 부팅을 중단하고 나면 로더 프롬프트에서 노드 2가 중지됩니다. 자동 부팅을 중지하고 노드2의 부팅을 시작하는 경우, 프롬프트가 표시될 때까지 기다린 다음 Ctrl-C를 눌러 부팅 메뉴로 이동합니다. 부팅 메뉴에서 노드가 중지되면 옵션을 사용하여 `8` 노드를 재부팅하고 재부팅 중 자동 부팅을 중단합니다.
. node2의 Loader> 프롬프트에서 기본 환경 변수를 설정합니다.
+
`set-defaults`

. 기본 환경 변수 설정을 저장합니다.
+
`saveenv`

. 2노드 스위치리스 구성의 경우, 노드 2의 슬롯 1에 X60132A 4포트 10/25GbE 카드가 있는지 확인하십시오. 업그레이드 중 클러스터 상호 연결을 위해 X60132A 카드가 필요합니다.

