---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/set-up-storage-encryption-new-module.html 
keywords: set up storage, encryption, controller, module, node 
summary: 필요한 경우 ARL을 사용하여 동일한 섀시에서 컨트롤러 모델을 업그레이드할 때 스토리지 암호화를 구성하고, SSL 인증서를 설치하고, 키 관리 서버를 설정합니다. 
---
= 새 컨트롤러 모듈에서 스토리지 암호화를 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
교체된 컨트롤러 또는 새 컨트롤러의 HA 파트너가 Storage Encryption을 사용하는 경우, SSL 인증서 설치 및 키 관리 서버 설정을 포함하여 Storage Encryption에 대한 새 컨트롤러 모듈을 구성해야 합니다.

.이 작업에 대해
이 절차에는 새 컨트롤러 모듈에서 수행되는 단계가 포함됩니다. 올바른 노드에 명령을 입력해야 합니다.

.단계
. 키 관리 서버를 계속 사용할 수 있는지, 해당 상태 및 인증 키 정보를 확인합니다.
+
`security key-manager external show-status`

+
`security key-manager onboard show-backup`

. 이전 단계에 나열된 키 관리 서버를 새 컨트롤러의 키 관리 서버 목록에 추가합니다.
+
.. 키 관리 서버를 추가합니다.
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

.. 나열된 각 키 관리 서버에 대해 이전 단계를 반복합니다. 최대 4개의 키 관리 서버를 연결할 수 있습니다.
.. 키 관리 서버가 성공적으로 추가되었는지 확인합니다.
+
`security key-manager external show`



. 새 컨트롤러 모듈에서 키 관리 설정 마법사를 실행하여 키 관리 서버를 설정하고 설치합니다.
+
기존 컨트롤러 모듈에 설치된 것과 동일한 키 관리 서버를 설치해야 합니다.

+
.. 새 노드에서 키 관리 서버 설정 마법사를 시작합니다.
+
`security key-manager external enable`

.. 마법사의 단계를 완료하여 키 관리 서버를 구성합니다.


. 연결된 모든 키 관리 서버에서 새 노드로 인증 키 복원:
+
`security key-manager external restore -node _new_controller_name_`


