---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/verify-rcf-configuration.html 
keywords: aggregate, relocation, cluster, switch, rcf, shared 
summary: 스위치에 연결된 클러스터 업그레이드를 위한 새로운 컨트롤러에 대한 공유 클러스터/HA 포트를 클러스터 스위치 RCF가 지원하는지 확인하세요. 
---
= 클러스터 스위치에서 RCF 구성을 확인하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
업그레이드 절차의 이 단계에서는 모든 데이터 집계가 node1에 있어야 합니다.  스위치에 연결된 클러스터로 구성을 업그레이드하는 경우 클러스터 스위치 참조 구성 파일(RCF)이 새 컨트롤러에 대한 공유 클러스터/HA 포트를 지원하는지 확인해야 합니다.

2노드 스위치리스 클러스터 구성으로 업그레이드하는 경우 이 섹션을 건너뛰고 다음으로 이동할 수 있습니다.link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2로 다시 이동합니다"] .

.단계
. 고급 권한 모드로 전환:
+
`set advanced`

. "IC RDMA" 상태를 확인하세요:
+
`ha interconnect status show`

+
출력에서 "IC RDMA 연결"의 상태는 다음과 같아야 합니다. `Up` .

+
[cols="50,50"]
|===
| "IC RDMA 연결" 상태가 ...인 경우 | 그러면... 


| `Up` | 로 가다link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2로 다시 이동합니다"] . 


| `Down` | 로 가다<<verify-rcf-step3,3단계>> . 
|===
. [[verify-rcf-step3]]클러스터 포트와 스위치 RCF를 확인하세요.
+
자세한 내용은 을 link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["스위치 연결 클러스터에 연결합니다"]참조하십시오.

. "IC RDMA 연결" 상태가 변경되었는지 확인하십시오. `Up` :
+
`ha interconnect status show`



.다음은 무엇입니까?
link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2로 다시 이동합니다"]
