---
permalink: upgrade/upgrade_move_delete_recreate_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lif, re-create, move san lifs, create 
summary: 클러스터 콘텐츠 및 클러스터 환경에 따라 SAN LIF를 이동, 삭제 또는 생성하거나 삭제된 SAN LIF를 다시 생성해야 합니다. 
---
= SAN LIF를 이동, 삭제 또는 생성합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 콘텐츠 및 클러스터 환경에 따라 SAN LIF를 이동, 삭제 또는 생성하거나 삭제된 SAN LIF를 다시 생성해야 합니다.



== SAN LIF 이동을 위한 고려 사항

클러스터에 노드를 추가하거나 클러스터에서 노드를 삭제하는 등 클러스터의 콘텐츠를 변경하는 경우에만 SAN LIF를 이동해야 합니다. LIF를 이동할 때 FC 패브릭을 재조닝하거나 클러스터의 연결된 호스트와 새로운 타겟 인터페이스 간에 새 iSCSI 세션을 생성할 필요가 없습니다.

을 사용하여 SAN LIF를 이동할 수 있습니다 `network interface modify` 명령. SAN LIF를 이동하려면 LIF를 오프라인 상태로 전환하고 LIF를 다른 홈 노드 또는 포트로 이동한 다음, 새 위치에서 다시 온라인 상태로 전환해야 합니다. ALUA(Asymmetric Logical Unit Access)는 모든 ONTAP SAN 솔루션의 일부로 이중 경로 및 자동 경로 선택을 제공합니다. 따라서 LIF가 이동을 위해 오프라인 상태로 전환되면 I/O 중단이 없습니다. 호스트는 간단히 재시도하여 I/O를 다른 LIF로 이동합니다.

LIF 이동 중에 다음 작업을 중단 없이 수행할 수 있습니다.

* LUN 데이터에 액세스하는 호스트에 전혀 영향을 주지 않고 클러스터의 HA 쌍 중 하나를 업그레이드된 HA 쌍으로 교체합니다
* 대상 인터페이스 카드를 업그레이드합니다
* SVM(스토리지 가상 시스템)의 리소스를 클러스터의 한 노드 세트에서 동일한 클러스터의 다른 노드 세트로 이동합니다
* 호스트 서버가 온라인 상태일 때 LUN 데이터에 대한 호스트 서버 액세스를 중단하지 않고 SAN LUN을 새로운 HA 쌍으로 이동할 수 있습니다


자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["SAN LIF 이동"^] SAN 스토리지 관리_설명서의 절차.



== 더 이상 필요하지 않은 SAN LIF 삭제

클러스터가 SAN 환경에 있을 경우 원래 노드의 연결을 해제하려면 먼저 원래 노드에서 더 이상 필요하지 않은 SAN LIF를 삭제해야 합니다.

.단계
. iSCSI 이니시에이터가 있는 경우 다음 단계를 완료합니다.
+
.. 원래 노드의 SVM에 현재 연결되어 있는 활성 이니시에이터 목록을 이전의 각 LIF에 대해 한 번씩 표시합니다. +
`iscsi connection show -vserver _Vserver_name_ -lif _old_lif_`
+
다음 예에서는 SVM VS1 에 연결된 활성 이니시에이터와 함께 명령의 출력을 보여 줍니다.

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. 원래 노드에 여전히 로그인되어 있는 이니시에이터가 있으면 호스트 컴퓨터에서 세션을 로그아웃합니다.


. 포트 세트 목록을 표시하여 원래 노드의 iSCSI 또는 FC LIF가 포트 세트에 속하는지 확인합니다.
+
`lun portset show`

+
다음 예제는 의 출력을 보여 줍니다 `lun portset show` 명령:

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. 원래 노드의 iSCSi 또는 FC LIF가 포트 세트의 구성원인 경우 포트 세트에서 제거합니다.
+
`lun portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _lif_name_`

. 원본 노드에서 LIF 삭제:
+
`network interface delete -vserver _vserver_name_ -lif _lif_name_`





== 새로운 SAN LIF를 생성하거나 삭제된 SAN LIF를 다시 생성하십시오

클러스터 환경 요구사항에 따라 이 절차 이전에 삭제한 SAN LIF를 새로 생성하거나 SAN LIF를 다시 생성할 수 있습니다. 를 사용하여 SAN LIF를 생성하거나 재생성할 수 있습니다 https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_network_interfaces.html["네트워크 인터페이스 생성"^] OnCommand ® System Manager_documentation을 사용한 _Cluster 관리 절차
