---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: '노드 2의 논리 인터페이스(LIF) 및 데이터 애그리게이트를 노드 1로 마이그레이션합니다.' 
---
= 노드 2의 LIF 및 데이터 애그리게이트를 노드 1로 마이그레이션합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 node2를 드라이브 쉘프로 변환하기 전에 노드 2의 논리 인터페이스(LIF) 및 데이터 애그리게이트를 노드 1로 마이그레이션합니다.

.시작하기 전에
다음 요구 사항을 충족하는지 확인합니다.

* AFF A250 및 AFF A400 컨트롤러에는 동일한 ONTAP 릴리스 및 패치 버전이 설치됩니다.
* 두 AFF A400 컨트롤러는 에서 대기 상태로 있습니다 `Maintenance Mode` 메시지가 표시됩니다.
* 적절한 모든 케이블을 직접 연결할 수 있습니다.


.이 작업에 대해
AFF A250 node1에서 다음 단계를 수행합니다.

.단계
. 클러스터 페일오버 자동 반환 비활성화:
+
`storage failover modify -node _node_name_ -auto-giveback false`

. HA 쌍의 두 노드에서 LIF 자동 되돌리기 기능 해제:
+
`network interface modify -lif * -auto-revert false`

. 모든 데이터 네트워크 LIF의 상태를 표시합니다.
+
`network interface show -role data`

. 클러스터 관리 LIF의 상태를 표시합니다.
+
`network interface show cluster_mgmt`

. 노드 2에 호스팅된 스토리지 가상 머신에서 모든 데이터 LIF 마이그레이션:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node_name_ -destination-port _port_name_`

+

NOTE: 이 명령은 비 SAN LIF만 마이그레이션합니다. iSCSI 및 FCP LIF를 마이그레이션할 때는 사용할 수 없습니다.

. 클러스터에 있는 모든 데이터 LIF의 상태를 표시합니다.
+
`network interface show -role data`

. LIF가 하나라도 다운되면 LIF의 관리 상태를 로 설정합니다 `up` 다음 명령을 각 LIF에 대해 한 번 입력합니다.
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -home-node _node_name_ -status-admin up`

. 클러스터의 모든 데이터 애그리게이트 상태 표시:
+
`storage aggregate show`

. 페일오버 자격 표시:
+
`storage failover show`

. 노드 2의 데이터 애그리게이트를 노드 1로 마이그레이션:
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`

. 클러스터의 모든 데이터 애그리게이트 상태 표시:
+
`storage aggregate show`

. 클러스터의 모든 데이터 볼륨 상태를 표시합니다.
+
`volume show`

. 를 표시합니다 `ha` epsilon의 상태 및 소유권:
+
`cluster show`

. 사용 안 함 `cluster ha`:
+
`cluster ha modify -configured false`

. 를 표시합니다 `ha` epsilon의 상태 및 소유권:
+
`cluster show`

. 노드2 중단:
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`


