---
permalink: upgrade/upgrade-unjoin-original-nodes-move-volumes.html 
sidebar: sidebar 
keywords: volume, move, node, unjoin, original, cluster, configuration, disk, initialize, unjoin the original nodes from the cluster 
summary: 볼륨을 새 노드로 이동한 후에는 클러스터의 원래 노드를 연결 해제합니다. 노드의 연결을 해제하면 노드의 구성이 지워지고 모든 디스크가 초기화됩니다. 
---
= 클러스터에서 원래 노드의 연결을 해제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 새 노드로 이동한 후에는 클러스터의 원래 노드를 연결 해제합니다. 노드의 연결을 해제하면 노드의 구성이 지워지고 모든 디스크가 초기화됩니다.

.단계
. 원래 노드의 고가용성 구성 'storage failover modify -node_original_node_name_ -enabled false'를 비활성화합니다
. 고급 권한 수준 액세스:
+
세트 프리빌리지 고급

. epsilon이 있는 노드를 식별합니다.
+
'클러스터 쇼'

+
다음 예에서 "Node0"은 현재 epsilon을 보유합니다.

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. 원래 노드 중 하나에 epsilon가 있으면 epsilon을 다른 노드로 이동합니다.
+
.. 원본 노드에서 epsilon을 제거합니다. + "cluster modify -node_original_node_name_-epsilon FALSE
.. epsilon을 다른 노드에 할당합니다. + "cluster modify -node_new_node_name_-epsilon TRUE"


. 클러스터에 남아 있는 노드에서 클러스터의 각 원래 노드 연결을 해제합니다(고급 권한 레벨).
+
'cluster unjoin-node_original_node_name_'

+
다음과 유사한 메시지가 표시됩니다.

+
[listing]
----
Warning: This command will unjoin node node_name from the cluster. You
         must unjoin the failover partner as well. After the node is
         successfully unjoined, erase its configuration and initialize all
         disks by using the "Clean configuration and initialize all disks (4)"
         option from the boot menu.
         Do you want to continue? {y|n}: y
----
. 계속하려면 y를 입력하십시오.
+
연결되지 않은 노드는 자동으로 재부팅되고 부팅 메뉴에서 중지됩니다.

. 연결되지 않은 노드의 부팅 메뉴에서 * (4) Clean configuration and initialize all disks * 옵션을 선택하여 노드 구성을 지우고 모든 디스크를 초기화합니다.
+
다음과 유사한 메시지가 표시됩니다.

+
[listing]
----
Zero disks, reset config and install a new file system?:
This will erase all the data on the disks, are you sure?:
----
. 양쪽 프롬프트에 y를 입력합니다.
. 클러스터에 노드가 2개만 남아 있는 경우 2노드 클러스터의 고가용성을 구성합니다.
+
군산하수정-구성 진실


