---
permalink: upgrade/upgrade-map-network-ports-ontap-9-8.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, correct, configure, setting, data, map network ports using ontap 9.8 
summary: 업그레이드 후 노드 3과 노드 4가 클러스터의 상호 및 네트워크와 통신할 수 있도록 하려면 물리적 포트가 클러스터, 데이터 등과 같은 사용 목적에 맞게 올바르게 구성되었는지 확인해야 합니다. 
---
= ONTAP 9.8을 사용하여 네트워크 포트를 매핑합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 후 노드 3과 노드 4가 클러스터의 상호 및 네트워크와 통신하도록 하려면 물리적 포트가 클러스터, 데이터 등과 같은 사용 목적에 맞게 올바르게 구성되었는지 확인해야 합니다.

다음 단계는 ONTAP 9.8을 실행하는 시스템에 적용됩니다. ONTAP 9.7 이하를 실행하는 경우 의 절차를 사용해야 합니다 xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[ONTAP 9.7 이하를 사용하여 네트워크 포트를 매핑합니다].

노드 3과 노드 4에서 이러한 단계를 수행해야 합니다.


NOTE: 다음 명령 예제에서는 프로시저의 이 단계에서 교체 노드 "node3"과 "node4"는 실제로 "node1"과 "node2"로 명명되므로 "node1"을 참조합니다.

.단계
. 시스템에서 ONTAP 9.7 이하를 실행 중인 경우 * STOP * 을 사용합니다. 의 절차를 사용해야 합니다 xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[ONTAP 9.7 이하를 사용하여 네트워크 포트를 매핑합니다].
. 스토리지 _ 을(를) 이동할 때 _prepare for upgrade에 기록한 노드 1 및 노드 2의 포트 및 LIF 구성 정보를 찾습니다. link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["3단계"].
. 에서 기록한 포트, 브로드캐스트 도메인 및 IPspace용 정보 찾기 _ 스토리지 이동 시 업그레이드 준비 _, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["3단계"].
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

. 다음과 같이 변경합니다.
+
.. 아직 로그인하지 않은 경우 노드 3과 노드 4에 부팅하고 로그인합니다.
.. 클러스터 브로드캐스트 도메인에 포함될 포트 수정:
+
'network port modify -node <node_name> -port <port_name> - MTU 9000 - IPSpace Cluster'

+
이 예에서는 "node1"에 "Cluster" 포트 e1b를 추가합니다.

+
네트워크 포트 수정 노드 노드1-포트 e1b-IPSpace 클러스터-MTU 9000

.. 클러스터 LIF를 각 LIF에 대해 한 번씩 새 포트로 마이그레이션합니다.
+
'network interface migrate -vserver <vserver_name> -lif <lif_name> -source-node node1 -destination-node node1 -destination-port <port_name>'

+
모든 클러스터 LIF가 마이그레이션되고 클러스터 통신이 설정되면 클러스터가 쿼럼에 들어가야 합니다.

.. 클러스터 LIF의 홈 포트를 수정합니다.
+
'network interface modify -vserver Cluster-lif <lif_name> – home-port <port_name>'

.. '클러스터' 브로드캐스트 도메인에서 이전 포트를 제거합니다.
+
'network port broadcast-domain remove-ports-IPSpace Cluster-broadcast-domain Cluster-ports <node1:port>'

.. 노드 3과 노드 4의 상태를 표시합니다.
+
'cluster show-node <node1> - 필드 상태

.. 각 클러스터 LIF는 포트 7700에서 수신 대기 중이어야 합니다. 클러스터 LIF가 포트 7700에서 수신 중인지 확인합니다.
+
'::> 네트워크 연결 수신 표시 - vserver 클러스터'

+
클러스터 포트에서 수신 대기하는 포트 7700은 2노드 클러스터의 다음 예에 표시된 대로 예상되는 결과입니다.

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 필요한 경우 포트 7700에서 청취하지 않는 각 클러스터 LIF에 대해 LIF의 관리 상태를 '소유'로 설정한 다음 '설정'으로 설정합니다.
+
'::> net int modify -vserver Cluster-lif <cluster-lif> -status-admin down;net int modify -vserver Cluster-lif <cluster-lif> -status-admin up'

+
하위 단계(g)를 반복하여 클러스터 LIF가 포트 7700에서 청취 중인지 확인합니다.



. [[MAP_9.8_5]] 데이터 LIF를 호스팅하는 물리적 포트의 브로드캐스트 도메인 구성원을 수정합니다. 에서와 같이 수동으로 이 작업을 수행할 수 있습니다 link:upgrade-map-network-ports-ontap-9-7-or-earlier.html#map_9.7_7["ONTAP 9.7 이전 버전인 7단계를 사용하여 네트워크 포트를 매핑합니다"]. 권장되는 접근 방식은 다음 5단계, 하위 단계(a)에서 (g)까지 ONTAP 9.8에 도입된 향상된 네트워크 도달 가능성 스캔 및 수리 절차를 사용하는 것입니다.
+
.. 모든 포트의 도달 가능성 상태를 나열합니다.
+
네트워크 포트 도달 가능성

.. 각 포트에서 한 번에 하나씩 다음 명령을 실행하여 물리적 포트 및 VLAN 포트의 연결 기능을 복구합니다.
+
복구 가능성 -노드 <node_name> -port <port_name>'입니다

+
다음과 같은 경고가 예상됩니다. 검토 후 적절한 "y" 또는 "n"을 입력합니다.

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a
different broadcast domain, which can cause LIFs to be re-homed away
from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP가 복구를 완료할 수 있도록 하려면 마지막 포트에서 "복구 가능성" 명령을 실행한 후 약 1분 정도 기다립니다.
.. 클러스터의 모든 브로드캐스트 도메인 나열:
+
방송-도메인 쇼

.. 도달 가능성 복구가 수행되면 ONTAP는 포트를 올바른 브로드캐스트 도메인에 배치하려고 시도합니다. 그러나 포트의 도달 가능 여부를 확인할 수 없고 기존 브로드캐스트 도메인과 일치하지 않는 경우 ONTAP는 이러한 포트에 대한 새 브로드캐스트 도메인을 생성합니다. 필요에 따라 새로 생성된 브로드캐스트 도메인을 삭제할 수 있습니다. 모든 구성원 포트가 인터페이스 그룹의 구성원 포트가 될 수 있습니다. 브로드캐스트 도메인 삭제:
+
'broadcast-domain delete-broadcast-domain <broadcast_domain>'을 선택합니다

.. 인터페이스 그룹 구성을 검토하고 필요에 따라 구성원 포트를 추가 또는 삭제합니다. 인터페이스 그룹 포트에 구성원 포트 추가:
+
'ifgrp add-port-node <node_name> -ifgrp <ifgrp_port> -port <port_name>'

+
인터페이스 그룹 포트에서 구성원 포트 제거:

+
'ifgrp remove-port-node <node_name> -ifgrp <ifgrp_port> -port <port_name>'

.. 필요에 따라 VLAN 포트를 삭제하고 다시 생성합니다. VLAN 포트 삭제:
+
'VLAN delete-node <node_name>-vlan-name <VLAN_port>'

+
VLAN 포트 생성:

+
'VLAN create-node <node_name>-vlan-name <VLAN_port>'

+

NOTE: 업그레이드하는 시스템의 네트워킹 구성의 복잡성에 따라 필요한 경우 모든 포트가 올바르게 배치될 때까지 5단계, (a)에서 (g)까지의 하위 단계를 반복해야 할 수 있습니다.



. 시스템에 구성된 VLAN이 없는 경우 로 이동합니다 <<map_98_7,7단계>>. 구성된 VLAN이 있으면 더 이상 존재하지 않거나 다른 브로드캐스트 도메인으로 이동된 포트에서 구성되었던 교체된 VLAN을 복원하십시오.
+
.. 교체된 VLAN을 표시합니다.
+
디세퍼드-VLAN 쇼

.. 교체된 VLAN을 원하는 대상 포트로 복구합니다.
+
dissplaced-vLANs restore-node <node_name> -port <port_name> -destination-port <destination_port>'입니다

.. 교체된 모든 VLAN이 복원되었는지 확인합니다.
+
디세퍼드-VLAN 쇼

.. VLAN은 생성된 후 1분 정도 적절한 브로드캐스트 도메인에 자동으로 배치됩니다. 복구된 VLAN이 적절한 브로드캐스트 도메인에 배치되었는지 확인합니다.
+
네트워크 포트 도달 가능성



. [[MAP_98_7]] ONTAP 9.8부터 ONTAP는 네트워크 포트 도달 가능성 복구 절차 중에 포트가 브로드캐스트 도메인 간에 이동하는 경우 LIF의 홈 포트를 자동으로 수정합니다. LIF의 홈 포트를 다른 노드로 이동하거나 할당되지 않은 경우 해당 LIF는 대체된 LIF로 표시됩니다. 홈 포트가 더 이상 존재하지 않거나 다른 노드로 재배치된 교체된 LIF의 홈 포트를 복구합니다.
+
.. 홈 포트가 다른 노드로 이동했거나 더 이상 존재하지 않는 LIF 표시:
+
디시퍼인터페이스 쇼

.. 각 LIF의 홈 포트를 복원합니다.
+
dissplaced-interface restore-vserver <vserver_name>-lif-name <lif_name>'입니다

.. 모든 LIF 홈 포트가 복구되었는지 확인합니다.
+
디시퍼인터페이스 쇼

+
모든 포트가 올바르게 구성되고 올바른 브로드캐스트 도메인에 추가되면 네트워크 포트 도달 가능성 표시 명령이 연결된 모든 포트에 대해 연결 가능 상태를 '정상'으로 보고하고 물리적 연결이 없는 포트에 대한 상태가 '사용 불가'로 표시되어야 합니다. 이 두 포트가 아닌 다른 상태를 보고하는 포트가 있는 경우 에 설명된 대로 내 상태를 복구합니다 <<map_98_5,5단계>>.



. 모든 LIF가 올바른 브로드캐스트 도메인에 속한 포트에서 관리적으로 작동하는지 확인합니다.
+
.. 관리상 다운되는 LIF가 있는지 확인합니다.
+
'network interface show -vserver <vserver_name> -status -admin down'

.. ''network interface show -vserver <vserver_name>-status-oper down'''(네트워크 인터페이스 show -vserver_name> -status -oper down)
.. 다른 홈 포트를 가지도록 수정해야 하는 모든 LIF를 수정합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif> -home-port <home_port>'

+

NOTE: iSCSI LIF의 경우 홈 포트를 수정하려면 LIF를 관리 방식으로 중지해야 합니다.

.. 홈 포트가 아닌 LIF 되돌리기:
+
'네트워크 인터페이스 복원 *'





물리적 포트 매핑을 완료했습니다. 업그레이드를 완료하려면 로 이동합니다 xref:upgrade-final-upgrade-steps-in-ontap-9-8.adoc[ONTAP 9.8에서 최종 업그레이드 단계를 수행합니다].
