---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: 노드 1과 노드 2에 속한 디스크를 노드 3과 노드 4에 각각 재할당해야 합니다. 
---
= 스토리지 쉘프를 연결하고 디스크 소유권을 다시 할당합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 1과 노드 2에 속한 디스크를 노드 3과 노드 4에 각각 재할당해야 합니다.

.이 작업에 대해
이 섹션의 단계는 노드3과 노드4에서 수행합니다. 각 단계를 노드3에서 완료한 다음 노드4에서 완료한 후 다음 단계로 진행하십시오.

[[reassign-spare-disks-step1]]
.단계
. 이전에 연결되어 있던 스토리지 쉘프의 케이블을 연결합니다.
+
** 노드1의 케이블을 노드3에 연결합니다.
** 노드2의 케이블을 노드4에 연결합니다.
+

CAUTION: 이 업그레이드 절차를 진행하는 동안에는 노드 3 또는 노드 4에 새 셸프를 연결하지 마십시오. 컨트롤러 업그레이드가 완료된 후에는 시스템에 중단 없이 새 셸프를 연결할 수 있습니다.



. 전원 공급 장치 및 쉘프의 물리적 연결을 확인합니다.
. node3 Loader 프롬프트에서 유지보수 모드로 부팅합니다.
+
`boot_ontap maint`

. 노드 3의 시스템 ID를 표시합니다.
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
노드3의 시스템 ID를 기록하여 <<reassign-disks-and-aggregates,5단계>>에서 사용합니다.

. [[reassign-disks-and-aggregates]]디스크 및 데이터 집합체를 재할당합니다.
+
[role="tabbed-block"]
====
.노드3으로 재할당
--
노드1의 여유 디스크, 루트 애그리게이트에 속하는 디스크 및 모든 데이터 애그리게이트를 노드3으로 재할당합니다.

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** 해당 매개변수  `node1_sysid`는 _원래 노드 종료_에서 기록한 값입니다. link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["5단계"].
** 매개변수 `-p <node2_sysid>`는 공유 디스크가 있는 경우에만 지정하십시오.


--
.노드4로 재할당
--
노드2의 여유 디스크, 루트 애그리게이트에 속하는 디스크 및 모든 데이터 애그리게이트를 노드4로 재할당합니다.

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** 매개변수  `node2_sysid`는 _원래 노드 종료_에서 기록한 값입니다. link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["5단계"].
** 매개변수 `-p <node3_sysid>`는 공유 디스크가 있는 경우에만 지정하십시오.


--
====
+
다음과 유사한 메시지가 표시됩니다.

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. 를 입력합니다 `y` 를 눌러 계속합니다.
+
다음과 유사한 메시지가 표시됩니다.

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. 를 입력합니다 `y` 를 눌러 계속합니다.
. 노드 1의 루트 애그리게이트가 으로 설정되어 있는지 확인합니다 `root` 옵션 필드와 다른 애그리게이트는 온라인 상태입니다.
+
`aggr status`

+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]유지 관리 모드 종료:
+
`halt`

. node4에서 <<reassign-spare-disks-step1,1단계>>부터 <<reassign-spare-disks-step9,9단계>>까지 반복합니다.


.다음 단계
스토리지 셸프를 연결하고 디스크 소유권을 다시 할당한 후, link:upgrade-restore-root-volume-config.html["루트 볼륨 구성 복원"].
