---
permalink: upgrade/upgrade-remove-disk-ownership-new-nodes.html 
sidebar: sidebar 
keywords: node, internal, disk, add-on, shelves, attach, system, interfere, controller, upgrade, remove, ownership, node3, node4, node, remove ownership of disks attached to the new nodes 
summary: 새 노드에 내부 디스크 또는 애드온 쉘프가 시스템에 연결된 경우 컨트롤러 업그레이드에 방해가 될 수 있습니다. 다음 단계를 수행하여 node3/node4와 함께 제공된 새 디스크의 소유권을 제거합니다. 
---
= 새 노드에 연결된 디스크의 소유권을 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 노드에 내부 디스크 또는 애드온 쉘프가 시스템에 연결된 경우 컨트롤러 업그레이드에 방해가 될 수 있습니다. 다음 단계를 수행하여 node3/node4와 함께 제공된 새 디스크의 소유권을 제거합니다.

.이 작업에 대해
이러한 단계는 노드 3과 노드 4에서 하나씩 수행합니다. 노드 시퀀스는 중요하지 않습니다.

[NOTE]
====
* 이 단계에서는 노드 1과 노드 2의 쉘프가 노드 3 및 노드 4에 물리적으로 연결되어 있지 않습니다.
* 새 컨트롤러와 함께 제공되는 디스크 및 쉘프의 디스크 소유권을 제거하면 됩니다.
* 기존 컨트롤러의 섀시 및 디스크를 유지하면서 기존 컨트롤러를 내부 드라이브 플랫폼의 새 컨트롤러로 교체하여 하드웨어를 업그레이드하는 경우에는 디스크 소유권을 제거할 필요가 없습니다.
+
예를 들어, 이전 A200의 섀시 및 디스크를 제자리에 유지하면서 이전 A200 컨트롤러 모듈을 새 A220 컨트롤러 모듈과 교체만 하여 A200에서 A220으로 시스템을 업그레이드할 경우 새 노드에 연결된 디스크 소유권 제거 섹션에 설명된 대로 새 A220 컨트롤러 모듈의 디스크 소유권을 제거하지 않을 것입니다.

+
컨트롤러 업그레이드 중 디스크 소유권을 제거하는 방법에 대한 질문이 있는 경우 NetApp 기술 지원 부서에 문의하십시오.

+
다음은 내부 스토리지가 있는 시스템 목록입니다. FAS2520, FAS2552, FAS2554, FAS2620, FAS2650, FAS2720, FAS2750, AFF A200, AFF A220, AFF A700s, AFF A800, AFF A250

+
시스템이 위에 나열되지 않은 경우 를 참조하십시오 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 내부 드라이브가 있는지 확인합니다.



====
.단계
. 노드의 LOADER 프롬프트에서 명령을 입력합니다.
+
`boot_ontap menu`

. 부팅 메뉴 프롬프트에서 를 입력합니다 `9a` Enter 키를 누릅니다.
+
다음 화면은 부팅 메뉴 프롬프트를 표시합니다.

+
[listing]
----
Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  9a
----
. 를 입력하여 디스크 소유권을 제거합니다 `y` 다음과 유사한 메시지가 표시되는 경우:
+
[listing]
----

########## WARNING ##########

This is a disruptive operation and will result in the
    loss of all filesystem data. Before proceeding further,
    make sure that:
    1) This option (9a) has been executed or will be executed
    on the HA partner node, prior to reinitializing either
    system in the HA-pair.
    2) The HA partner node is currently in a halted state or
    at the LOADER prompt.


    Do you still want to continue (yes/no)? yes
----
+
디스크 소유권이 제거되고 부팅 메뉴로 돌아갑니다.

. 부팅 메뉴에서 를 입력합니다 `5` 를 눌러 유지보수 모드로 전환합니다.
. 유지보수 모드에서 를 실행합니다 `disk show` 명령.
+
디스크가 나열되지 않아야 합니다.

. ' 명령을 실행합니다
+
`disk show -a`

+
나열된 모든 디스크는 할당 해제되어야 합니다.

. 유지보수 모드 종료:
+
`halt`


