---
permalink: upgrade/upgrade-prepare-when-moving-storage.html 
sidebar: sidebar 
keywords: licenses 
summary: 스토리지를 이동하여 업그레이드하기 전에 원래 노드에서 라이센스 정보를 수집하고, 네트워크 구성을 계획하고, 시스템 ID를 기록하고, netboot에 필요한 파일을 준비해야 합니다. 
---
= 스토리지를 이동할 때 업그레이드를 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지를 이동하여 업그레이드하기 전에 원래 노드에서 라이센스 정보를 수집하고, 네트워크 구성을 계획하고, 시스템 ID를 기록하고, netboot에 필요한 파일을 준비해야 합니다.

.단계
. 원래 노드, 노드 1 및 노드 2의 라이센스 정보를 표시하고 기록합니다.
+
'시스템 사용권 프로그램'

. 노드 1/노드 2 HA 쌍에서 스토리지 암호화를 사용하고 새 노드에 암호화가 활성화된 디스크가 있는 경우 원래 노드의 디스크가 올바르게 입력되었는지 확인하십시오.
+
.. SED(자체 암호화 디스크)에 대한 정보 표시
+
스토리지 암호화 디스크 표시

.. 비제조 보안 ID(비 MSID) 키와 연결된 디스크가 있는 경우 MSID 키로 키를 다시 입력하다
+
스토리지 암호화 디스크 수정



. [[prepare_move_store_3]]노드1/노드2 HA 쌍의 레코드 포트 및 LIF 구성 정보:
+
[cols="1,2"]
|===
| 정보를 표시하려면... | 입력... 


 a| 
쉘프, 각 쉘프의 디스크 수, 플래시 스토리지 세부 정보, 메모리, NVRAM 및 네트워크 카드
 a| 
'system node run-node_node_name_sysconfig'



 a| 
클러스터 네트워크 및 노드 관리 LIF
 a| 
네트워크 인터페이스 show-role cluster, node-mgmt



 a| 
물리적 포트
 a| 
'network port show-node_node_name_-type physical



 a| 
페일오버 그룹
 a| 
'network interface failover-groups show -vserver_vserver_name _'

클러스터 차원 이 아닌 페일오버 그룹의 이름과 포트를 기록합니다.



 a| 
VLAN 구성
 a| 
'network port vlan show-node_node_name_'

각 네트워크 포트 및 VLAN ID 페어링을 기록합니다.



 a| 
인터페이스 그룹 구성
 a| 
'network port ifgrp show -node_node_name_-instance'

인터페이스 그룹 및 그룹에 할당된 포트의 이름을 기록합니다.



 a| 
브로드캐스트 도메인
 a| 
네트워크 포트 브로드캐스트 도메인 쇼



 a| 
IPspace 정보
 a| 
네트워크 IPspace 쇼

|===
. 업그레이드할 각 새 노드의 기본 클러스터 포트, 데이터 포트 및 노드 관리 포트에 대한 정보를 얻습니다. https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]
. [[prepare_move_store_5]] netboot 수행에 사용되는 파일을 다운로드 및 준비합니다.
+
새 노드를 설치한 후 새 노드가 원래 노드와 동일한 버전의 ONTAP를 실행 중인지 확인하기 위해 netboot를 수행해야 할 수 있습니다. netboot라는 용어는 원격 서버에 저장된 ONTAP 이미지에서 부팅됨을 의미합니다. netboot를 준비할 때 시스템이 액세스할 수 있는 웹 서버에 ONTAP 9 부트 이미지 사본을 넣어야 합니다.

+
.. 에 액세스합니다 https://mysupport.netapp.com/site/["NetApp Support 사이트"^] 시스템의 Netboot 수행에 사용되는 파일을 다운로드합니다.
.. NetApp Support 사이트의 소프트웨어 다운로드 섹션에서 해당 ONTAP 소프트웨어를 다운로드하고 웹 액세스 가능한 디렉토리에 '<ONTAP_version>_image.tgz' 파일을 저장합니다.
.. 웹 액세스 가능 디렉토리로 변경하고 필요한 파일을 사용할 수 있는지 확인합니다.


+
[cols="1,2"]
|===
| 대상... | 그러면... 


 a| 
* FAS2200, FAS2500, FAS3200, FAS6200, FAS/AFF8000 시리즈 시스템 *
 a| 
'<ONTAP_VERSION>_IMAGE.tgz' 파일의 내용을 타겟 디렉토리 'tar-zxvf<ONTAP_VERSION>_IMAGE.tgz'에 추출합니다

* 참고: * Windows에서 컨텐트를 추출하는 경우 7-Zip 또는 WinRAR을 사용하여 netboot 이미지를 추출합니다.

디렉토리 목록에는 커널 파일 'netboot/kernel'이 있는 netboot 폴더가 포함되어야 합니다



 a| 
* 다른 모든 시스템 *
 a| 
디렉토리 목록에는 다음 파일이 포함되어야 합니다.

'<ONTAP_VERSION>_IMAGE.tgz'


NOTE: '<ONTAP_VERSION>_IMAGE.tgz' 파일의 내용은 추출할 필요가 없습니다.

|===


디렉터리에 있는 정보를 사용하여 로 이동합니다 xref:upgrade-set-up-new-nodes.adoc[새 노드를 설정합니다].
