---
permalink: upgrade/upgrade-map-network-ports-ontap-9-7-or-earlier.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, configure, setting, intend, data, map, map network ports using ontap 9.7 or earlier 
summary: 업그레이드 후 노드 3과 노드 4가 클러스터의 상호 및 네트워크와 통신하도록 하려면 물리적 포트가 클러스터, 데이터 등과 같은 사용 목적에 맞게 올바르게 구성되었는지 확인해야 합니다. 
---
= ONTAP 9.7 이하를 사용하여 네트워크 포트를 매핑합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 후 노드 3과 노드 4가 클러스터의 상호 및 네트워크와 통신하도록 하려면 물리적 포트가 클러스터, 데이터 등과 같은 사용 목적에 맞게 올바르게 구성되었는지 확인해야 합니다.

다음 단계는 ONTAP 9.7 이하를 실행하는 시스템에 적용됩니다. ONTAP 9.8을 실행하는 경우 의 절차를 사용해야 합니다 xref:upgrade-map-network-ports-ontap-9-8.adoc[ONTAP 9.8을 사용하여 네트워크 포트를 매핑합니다].

노드 3과 노드 4에서 이러한 단계를 수행해야 합니다.


NOTE: 다음 명령 예제에서는 프로시저의 이 단계에서 교체 노드 "node3"과 "node4"는 실제로 "node1"과 "node2"로 명명되므로 "node1"을 참조합니다.

.단계
. 시스템에서 ONTAP 9.8, * STOP * 을 실행하는 경우 의 절차를 사용해야 합니다 xref:upgrade-map-network-ports-ontap-9-8.adoc[ONTAP 9.8을 사용하여 네트워크 포트를 매핑합니다].
. 스토리지 _ 을(를) 이동할 때 _prepare for upgrade에 기록한 노드 1 및 노드 2의 포트 및 LIF 구성 정보를 찾습니다. link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["3단계"].
. 에서 기록한 포트, 브로드캐스트 도메인 및 IPspace용 정보 찾기 _ 스토리지 이동 시 업그레이드 준비 _, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["3단계"].
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

. 다음과 같이 변경합니다.
+
.. 아직 부팅하지 않은 경우 노드 3과 노드 4를 클러스터 프롬프트로 부팅합니다.
.. '클러스터' 브로드캐스트 도메인에 올바른 포트를 추가합니다.
+
'network port modify -node <node_name> -port <port_name> - MTU 9000 - IPSpace Cluster'

+
이 예에서는 ""node1""에 클러스터 포트 e1b를 추가합니다.

+
네트워크 포트 수정 노드 노드1-포트 e1b-IPSpace 클러스터-MTU 9000

.. LIF를 각 LIF에 대해 한 번씩 새 포트로 마이그레이션합니다.
+
'network interface migrate -vserver <vserver_name> -lif <lif_name> -source-node node1 -destination-node node1 -destination-port <port_name>'

+
SAN 데이터 LIF는 오프라인 상태에서만 마이그레이션할 수 있습니다.

.. 클러스터 LIF의 홈 포트를 수정합니다.
+
'network interface modify -vserver Cluster-lif <lif_name> – home-port <port_name>'

.. 클러스터 브로드캐스트 도메인에서 이전 포트를 제거합니다.
+
'network port broadcast-domain remove-ports-IPSpace Cluster-broadcast-domain Cluster-ports <node1:port>'

.. 노드 3과 노드 4의 상태를 표시합니다.
+
'cluster show-node <node1> - 필드 상태



. VLAN 및 'ifgrp config'를 새 컨트롤러의 물리적 포트 레이아웃과 일치하도록 수정합니다.
. 노드 3과 노드 4에 더 이상 존재하지 않는 노드1과 노드2 포트(고급 권한 수준)를 삭제합니다.
+
'network port delete-node <node1> - port <port_name>'

. [[MAP_97_7]] 노드 관리 브로드캐스트 도메인을 조정하고 필요한 경우 노드 관리 및 클러스터 관리 LIF를 마이그레이션합니다.
+
.. LIF의 홈 포트를 표시합니다.
+
네트워크 인터페이스 보기 필드, 홈 노드, 홈 포트

.. 포트가 포함된 브로드캐스트 도메인을 표시합니다.
+
'network port broadcast-domain show-ports <node_name:port_name>'

.. 필요에 따라 브로드캐스트 도메인에서 포트를 추가하거나 제거합니다.
+
네트워크 포트 브로드캐스트 도메인 추가 포트

+
네트워크 포트 브로드캐스트 도메인 제거 포트

.. 필요한 경우 LIF의 홈 포트를 수정합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> – home-port <port_name>'



. 필요한 경우 의 명령을 사용하여 인터클러스터 브로드캐스트 도메인을 조정하고 인터클러스터 LIF를 마이그레이션합니다 <<map_97_7,7단계>>.
. 다른 브로드캐스트 도메인을 조정하고 필요한 경우 의 명령을 사용하여 데이터 LIF를 마이그레이션합니다 <<map_97_7,7단계>>.
. 모든 LIF 페일오버 그룹을 조정합니다.
+
'network interface modify-failover-group <failover_group> - failover-policy <failover_policy>'

+
다음 명령은 페일오버 정책을 브로드캐스트 도메인 전체에 설정하고 페일오버 그룹 "fg1"의 포트를 "노드 1"의 LIF "data1"의 페일오버 타겟으로 사용합니다.

+
'network interface modify -vserver node1-lif data1-failover-policy broadcast-domain-wide-failover-group fg1'을 참조하십시오

. 노드 3과 노드 4의 네트워크 포트 속성을 표시합니다.
+
네트워크 포트 show-node node1



물리적 포트 매핑을 완료했습니다. 업그레이드를 완료하려면 로 이동합니다 xref:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.adoc[ONTAP 9.7 이전 버전에서 최종 업그레이드 단계를 수행합니다].
