---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 이 내용은 스토리지 또는 볼륨을 이동하여 클러스터에서 AFF 시스템 또는 FAS 시스템의 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다. 
---
= 볼륨이나 스토리지를 이동하여 업그레이드 여부를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 콘텐츠에서는 스토리지 또는 볼륨을 이동하여 클러스터에서 AFF, FAS 또는 ASA 시스템의 컨트롤러 하드웨어를 업그레이드하는 방법에 대해 설명합니다.

다음과 같은 상황에서 컨트롤러 하드웨어를 업그레이드하려면 이 절차를 수행하십시오.


NOTE: ONTAP 9.8에서는 자동 포트 배치 기능이 도입되어 하드웨어 업그레이드 절차가 단순화되었습니다.

* 기존 노드와 새 노드가 호환되고 지원됩니다.
* 원래 노드와 새 노드는 ONTAP 9.0 이상을 실행합니다. NetApp은 가능한 경우 원본 노드와 새 노드에서 동일한 ONTAP 버전을 실행할 것을 권장합니다.
+
컨트롤러 업그레이드에 혼합 ONTAP 버전이 포함된 경우 를 참조하십시오 https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["혼합 버전 ONTAP 클러스터"^] 를 참조하십시오.

* 새 노드에서 원래 노드의 IP 주소, 네트워크 마스크 및 게이트웨이를 재사용하고 있습니다.
* 스토리지를 이동하거나 볼륨을 이동하여 컨트롤러 하드웨어를 업그레이드할 계획이 있습니다.
* 스토리지를 이동하여 업그레이드하는 경우 운영 중단 절차를 수행할 준비가 된 것입니다.
+
볼륨 이동을 통한 업그레이드는 무중단으로 가능합니다.

* 지원되는 모델의 노드를 디스크 쉘프로 변환한 다음, 새 노드에 연결할 계획입니다.


MetroCluster 구성을 업그레이드하는 경우 를 참조하십시오 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 구성을 업그레이드, 새로 고침 또는 확장합니다"^].

.관련 정보
* xref:upgrade-considerations.adoc[컨트롤러 하드웨어 업그레이드에 대한 고려 사항]
* link:../choose_controller_upgrade_procedure.html["컨트롤러 하드웨어를 업그레이드하는 방법을 선택합니다"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["MetroCluster 유지 관리 작업의 절차를 찾는 방법"^]
* https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

