---
permalink: upgrade/upgrade-move-internal-drives.html 
sidebar: sidebar 
keywords: node, support, model, upgrading, upgrade, moving, move, storage, internal, sata, drive, ssd, drive, shelf, attach, cluster, transfer, sas, drive, move internal drives from an original node 
summary: 원래 노드가 지원되는 모델 중 하나인 경우 스토리지를 이동하여 업그레이드하는 동안 노드의 내부 SATA 드라이브, SSD 또는 SAS 드라이브를 동일한 클러스터의 새 노드에 연결된 드라이브 쉘프로 이동할 수 있습니다. 
---
= 원래 노드에서 내부 드라이브를 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원래 노드가 지원되는 모델 중 하나인 경우 스토리지를 이동하여 업그레이드하는 동안 노드의 내부 SATA 드라이브, SSD 또는 SAS 드라이브를 동일한 클러스터의 새 노드에 연결된 드라이브 쉘프로 이동할 수 있습니다.


NOTE: link:upgrade-convert-node-to-shelf.html["시스템을 드라이브 선반으로 변환하여 새 노드에 연결할 수도 있습니다."]..

.시작하기 전에
* 검토를 완료해야 합니다 link:upgrade-considerations.html["컨트롤러 하드웨어 업그레이드에 대한 고려 사항"] 내부 드라이브 이동 정보.
+
구성에 대한 지침이 필요한 경우 기술 지원 부서에 문의하십시오.

* 원래 노드의 SATA, SSD 또는 SAS 드라이브 캐리어는 새 드라이브 쉘프와 호환되어야 합니다.
* 호환되는 드라이브 쉘프가 이미 새 노드에 연결되어 있어야 합니다.
* 드라이브 쉘프에는 원래 노드의 SATA, SSD 또는 SAS 드라이브 캐리어를 수용할 수 있는 충분한 여유 베이가 있어야 합니다.


.이 작업에 대해
동일한 클러스터 내에서만 드라이브를 이동할 수 있습니다.

.단계
. 시스템 전면에서 베젤을 조심스럽게 분리합니다.
. [[move_int_drive_2]] 드라이브 캐리어 왼쪽에 있는 분리 단추를 누릅니다.
+
캐리어의 캠 핸들이 부분적으로 열리고 캐리어가 중앙판에서 해제됩니다.

. 캠 핸들을 완전히 열린 위치로 당겨 캐리어를 미드플레인에서 분리한 다음 캐리어를 드라이브 쉘프에서 조심스럽게 밀어 꺼냅니다.
+

NOTE: 드라이브를 분리, 설치 또는 운반할 때는 항상 두 손을 사용하십시오. 그러나 캐리어 밑면에 노출된 드라이브 보드에 손을 올려 놓지 마십시오.

. 캠 핸들을 열린 위치에 둔 상태에서 캐리어를 새 드라이브 쉘프의 슬롯에 삽입하고 캐리어가 멈출 때까지 세게 밉니다.
+

NOTE: 캐리어를 삽입할 때는 두 손을 사용합니다.

. [[move_int_drive_5]] 캐리어가 미드플레인에 완전히 장착되고 핸들이 제자리에 고정되도록 캠 핸들을 닫습니다.
+
핸들을 천천히 닫아 캐리어의 면과 올바르게 정렬해야 합니다.

. 반복합니다 <<move_int_drive_2,2단계>> 부터 까지 <<move_int_drive_5,5단계>> 새 시스템으로 이동하는 모든 드라이브에 적용됩니다.

