---
permalink: upgrade/upgrade-restore-root-volume-config.html 
sidebar: sidebar 
keywords: Controller Hardware Upgrade Express Guide 
summary: 루트 볼륨에서 부팅 장치로 구성 정보를 복원해야 합니다. 
---
= 루트 볼륨 구성을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
루트 볼륨에서 부팅 장치로 구성 정보를 복원해야 합니다.


NOTE: FAS8300, AFF A400 또는 FAS8700과 같은 고가용성(HA) 상호 연결 포트로 포트 "e0a" 및 "e0b"를 사용하는 시스템으로 데이터 이동 없이 컨트롤러 업그레이드를 수행하는 경우 이 있는지 확인하십시오 link:upgrade-prepare-when-moving-storage.html#assign_lifs["관리 또는 인터클러스터 LIF를 재할당했습니다"] 업그레이드 절차를 시작하기 전에 원래 시스템의 포트 "e0a" 및 "e0b"에 구성되어 있습니다.

.이 작업에 대해
다음 단계로 진행하기 전에 노드 3과 노드 4에서 다음 단계를 수행하여 한 노드에서 각 단계를 완료한 다음 다른 노드에서 다른 단계를 완료해야 합니다.

.단계
. LOADER 프롬프트에서 부팅 메뉴에 액세스합니다.
+
`boot_ontap menu`

. 부팅 메뉴에서 를 선택합니다 `(6) Update flash from backup config` 를 입력하고 을 입력합니다 `y` 계속할 것인지 묻는 메시지가 나타나면 다음 중 하나를 선택하십시오.
+
[listing]
----
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 6
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: y
----
+
업데이트 플래시 프로세스가 몇 분 동안 실행된 후 시스템이 재부팅됩니다.

. 시스템 ID 불일치를 확인하는 메시지가 나타나면 를 입력합니다 `y`.
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id? {y|n} [n] y
----
+
시동 시퀀스가 정상적으로 진행됩니다.



컨트롤러 업그레이드에 실패하고 이 표시됩니다 `rlib_port_ipspace_assign` 오류 메시지: 업그레이드를 되돌리고 교체 시스템의 HA 포트로 사용되는 원래 시스템의 네트워크 포트에서 LIF를 삭제해야 합니다. 자세한 내용은 을 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/PANIC_%3A_rlib_port_ipspace_assign%3A_port_e0a_could_not_be_moved_to_HA_ipspace["이 KB 문서를 참조하십시오"^].
