---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '명령을 사용하여 ARL을 사용하여 ONTAP 9.15.1 이상을 실행하는 컨트롤러를 업그레이드할지 여부를 `system controller replace` 결정합니다.' 
---
= 집계 재배치 절차를 사용할지 여부를 결정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 절차에서는 기존 데이터 및 디스크를 유지하면서 HA 쌍의 스토리지 컨트롤러를 새 컨트롤러와 업그레이드하는 방법을 설명합니다. 이는 숙련된 관리자만 사용해야 하는 복잡한 절차입니다.

다음과 같은 상황에서 이 절차를 사용할 수 있습니다.

* ONTAP 9.15.1 이상을 실행하고 있습니다.
* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동 절차에 따라 데이터를 마이그레이션하지는 않겠습니다.
* ONTAP 관리에 대한 경험이 있으며 진단 권한 모드에서 작업할 때 발생할 수 있는 위험에 대해 잘 알 수 있습니다.



NOTE: 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.

다음과 같은 경우에는 이 절차를 사용할 수 없습니다.

* AFF A800을 AFF A70 또는 AFF A90으로 업그레이드하고 있습니다. 이 AFF A800 업그레이드를 수행하려면 "system controller replace" 명령을 사용하여 같은 섀시에 있는 컨트롤러 모델을 업그레이드하는 링크를 _ 참조하십시오. link:other_references.html["참조"]
* 백엔드 스토리지용 외부 어레이를 사용하여 V 시리즈 시스템 또는 FlexArray 가상화 스토리지 시스템을 업그레이드합니다. V-Series 또는 FlexArray 시스템의 업그레이드 옵션은 기술 지원 부서에 문의하십시오.
* MetroCluster FC 또는 IP 구성을 업그레이드합니다. MetroCluster 구성을 업그레이드하려면 link:other_references.html["참조"] _MetroCluster 업그레이드 및 확장 설명서_ 링크를 참조하십시오.


[[sys_commands_9151_supported_systems]] 다음 표에는 컨트롤러 업그레이드에 지원되는 모델 매트릭스가 나와 있습니다.

|===
| 기존 컨트롤러 | 교체 컨트롤러 | ONTAP부터 지원됨... 


| FAS8200, FAS8300, FAS8700, FAS9000 | FAS70, FAS90 | 9.15.1P3입니다 


| FAS9500 | FAS90 | 9.15.1P3입니다 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90, AFF A1K | 9.15.1 
|===
[NOTE]
====
AFF A70 및 AFF A90는 단일 섀시에 2개의 온보드 디스크와 2개의 컨트롤러가 있는 통합 시스템입니다.

* 내부 드라이브가 있는 AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드하기 전에 이러한 드라이브의 소유권을 제거해야 합니다. 업그레이드가 완료되면 내부 드라이브를 AFF A70 또는 AFF A90 노드에 할당하고 이 드라이브를 사용하여 데이터 애그리게이트를 생성할 수 있습니다. 루트 또는 데이터 애그리게이트를 내부 드라이브로 마이그레이션할 필요는 없습니다.
* 내부 드라이브 없이 AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드를 완료한 후 내부 드라이브를 할당할 필요가 없습니다.


컨트롤러 업그레이드 모델 조합이 위 표에 없는 경우 기술 지원 부서에 문의하십시오.

====
컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

을 참조하십시오 link:other_references.html["참조"] ONTAP 9 제품 설명서에 액세스할 수 있는 _ONTAP 9 문서 센터_에 연결합니다.
