---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'ONTAP 9.15.1 이상 버전에 도입된 컨트롤러로 업그레이드할 때 `system controller replace` 명령어를 사용하여 ARL을 사용할지 여부를 결정하십시오.' 
---
= 이 집계 이전 절차를 사용할지 결정하십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하기 위한 몇 가지 애그리게이트 재배치(ARL) 방법이 있습니다. 이 ARL 절차에서는 기존 디스크와 디스크에 저장된 데이터를 유지하면서 AFF 및 FAS 스토리지 시스템의 HA 컨트롤러 쌍을 ONTAP 9.15.1 이상 버전에 도입된 컨트롤러로 업그레이드하는 방법을 설명합니다. 이 절차는 복잡하므로 숙련된 ONTAP 관리자만 사용해야 합니다.

이 ARL 절차가 컨트롤러 하드웨어 업그레이드에 적합한지 결정하는 데 도움이 되도록 지원되는 업그레이드와 지원되지 않는 업그레이드에 대한 다음 모든 상황을 검토해야 합니다.



[[supported-upgrades-for-this-arl-procedure]]
== 이 ARL 절차에 지원되는 업그레이드

다음과 같은 상황에서 이 ARL 절차를 사용하여 노드 쌍을 업그레이드할 수 있습니다.

* ONTAP 9.15.1 이상을 실행하고 있습니다.
* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동 절차를 사용하여 데이터를 마이그레이션하지는 않겠습니다.
* ONTAP 관리 경험이 있으며 진단 권한 모드에서 작업할 때의 위험에 익숙합니다.
* 귀하의 하드웨어 업그레이드 조합은 다음에 나열되어 있습니다. <<sys_commands_9151_supported_systems,지원되는 모델 매트릭스>> .



NOTE: 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.



[[upgrades-not-supported-for-this-arl-procedure]]
== 이 ARL 절차에는 업그레이드가 지원되지 않습니다.

다음과 같은 상황에서는 이 ARL 절차를 사용하여 노드 쌍을 업그레이드할 수 없습니다.

* 다음 업그레이드 중 하나를 수행하고 있습니다.
+
|===
| 기존 컨트롤러 | 교체 컨트롤러 


| AFF A250 를 참조하십시오 | AFF A50, AFF A30 


| AFF A800 를 참조하십시오 | AFF A70, AFF A90 


| AFF C250 를 참조하십시오 | AFF C30, AFF C60 


| AFF C800 를 참조하십시오 | AFF C80 를 참조하십시오 
|===
+
위 표에 나열된 업그레이드를 수행하려면 link:other-references.html["참조"]을 참조하여 _"system controller replace" 명령을 사용하여 동일 섀시의 컨트롤러 모델 업그레이드_에 연결하십시오.

* MetroCluster FC 또는 IP 구성을 업그레이드하는 중입니다. MetroCluster 구성을 업그레이드하려면 link:other-references.html["참조"]을 참조하여 _MetroCluster 업그레이드 및 확장 문서_로 이동하십시오.




[[supported-system-upgrade-combinations]]
[[sys_commands_9151_supported_systems]]
== 지원되는 시스템 업그레이드 조합

다음 표는 ONTAP 9.15.1 이상에서 도입된 AFF 및 FAS 시스템에 대해 ARL을 사용하여 지원되는 컨트롤러 업그레이드 조합을 보여줍니다. 원하는 컨트롤러 업그레이드 조합이 목록에 없는 경우 기술 지원팀에 문의하십시오.

|===
| 기존 컨트롤러 | 교체 컨트롤러 | ONTAP부터 지원됨... 


| AFF A400 | AFF A50(2부 | 9.16.1 


| AFF A300 | AFF A50(2부 | 9.16.1 


| AFF A220, AFF A150 | AFF A20(2부 | 9.16.1(1) 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | FAS70의 경우 9.15.1P3, FAS50의 경우 FAS90 9.16.1P2 


| FAS8700를 참조하십시오 | FAS70, FAS90 | 9.15.1P3입니다 


| FAS9500 | FAS90 | 9.15.1P3입니다 


| AFF A300, AFF A400, AFF A700 | AFF A70 2, AFF A90 (미국 AFF A1K | 9.15.1 


| AFF A900 | AFF A90 (미국) 2, AFF A1K (미국 | 9.15.1 
|===
AFF A20으로 업그레이드하려면 먼저 컨트롤러 모듈을 IOM12 모듈과 교체하여 AFF A150 또는 AFF A220를 DS224C 쉘프로 변환해야 합니다. 을 link:../upgrade/upgrade-convert-node-to-shelf.html["원래 노드를 드라이브 쉘프로 변환할 수 있습니다"]참조하십시오.

AFF A20, AFF A50, AFF A70 및 AFF A90는 HA 구성의 컨트롤러 2개와 단일 섀시에 온보드 디스크가 있는 통합 시스템입니다.

* 내부 드라이브가 있는 AFF A20, AFF A50, AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드하기 전에 이러한 내부 드라이브의 소유권을 제거해야 합니다. 업그레이드를 완료한 후 내부 드라이브를 AFF A20, AFF A50, AFF A70 또는 AFF A90 노드에 할당하고 이 노드를 사용하여 데이터 애그리게이트를 생성할 수 있습니다. 루트 또는 데이터 애그리게이트를 내부 드라이브로 마이그레이션할 필요가 없습니다.
* 내부 드라이브 없이 AFF A20, AFF A50, AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드를 완료한 후 내부 드라이브를 할당할 필요가 없습니다.




[[choose-a-different-hardware-upgrade-procedure]]
== 다른 하드웨어 업그레이드 절차를 선택하세요

* link:../upgrade-arl/index.html["컨트롤러 하드웨어 업그레이드에 사용 가능한 대체 ARL 방법을 검토하세요."]..
* 컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동 작업을 수행할 의향이 있다면 link:other-references.html["참조"]를 참조하여 _볼륨 또는 스토리지 이동을 통한 업그레이드_로 연결하십시오.


.관련 정보
link:other-references.html["참조"]를 참조하여 _ONTAP 9 Documentation_에 연결하십시오.

.다음 단계
이 ARL 절차를 사용하기로 결정한 후link:required_tools_and_documentation.html["필요한 도구 및 문서에 대해 알아보십시오"].
