---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '명령을 사용하여 ARL을 사용하여 ONTAP 9.15.1 이상을 실행하는 컨트롤러를 업그레이드할지 여부를 `system controller replace` 결정합니다.' 
---
= 집계 재배치 절차를 사용할지 여부를 결정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 절차에서는 기존 데이터 및 디스크를 유지하면서 HA 쌍의 스토리지 컨트롤러를 새 컨트롤러와 업그레이드하는 방법을 설명합니다. 이는 숙련된 관리자만 사용해야 하는 복잡한 절차입니다.



== ARL에 대한 업그레이드가 지원됩니다

다음과 같은 상황에서 노드 쌍을 업그레이드할 수 있습니다.

* ONTAP 9.15.1 이상을 실행하고 있습니다.
* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동 절차를 사용하여 데이터를 마이그레이션하지는 않겠습니다.
* ONTAP 관리 경험이 있으며 진단 권한 모드에서 작업할 때의 위험에 익숙합니다.



NOTE: 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.

[[sys_commands_9151_supported_systems]] 다음 표에는 컨트롤러 업그레이드에 지원되는 모델 매트릭스가 나와 있습니다.

|===
| 기존 컨트롤러 | 교체 컨트롤러 | ONTAP부터 지원됨... 


| AFF A400 | AFF A50(2부 | 9.16.1 


| AFF A300 | AFF A50(2부 | 9.16.1 


| AFF A220, AFF A150 | AFF A20(2부 | 9.16.1(1) 


| FAS8200, FAS8300, FAS8700, FAS9000 | FAS70, FAS90 | 9.15.1P3입니다 


| FAS9500 | FAS90 | 9.15.1P3입니다 


| AFF A300, AFF A400, AFF A700 | AFF A70 2, AFF A90 (미국 AFF A1K | 9.15.1 


| AFF A900 | AFF A90 (미국) 2, AFF A1K (미국 | 9.15.1 
|===
AFF A20으로 업그레이드하려면 먼저 컨트롤러 모듈을 IOM12 모듈과 교체하여 AFF A150 또는 AFF A220를 DS224C 쉘프로 변환해야 합니다. 을 link:../upgrade/upgrade-convert-node-to-shelf.html["원래 노드를 드라이브 쉘프로 변환할 수 있습니다"]참조하십시오.

AFF A20, AFF A50, AFF A70 및 AFF A90는 HA 구성의 컨트롤러 2개와 단일 섀시에 온보드 디스크가 있는 통합 시스템입니다.

* 내부 드라이브가 있는 AFF A20, AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드하기 전에 이러한 내부 드라이브의 소유권을 제거해야 합니다. 업그레이드가 완료되면 내부 드라이브를 AFF A20, AFF A70 또는 AFF A90 노드에 할당하고 이 노드를 사용하여 데이터 애그리게이트를 생성할 수 있습니다. 루트 또는 데이터 애그리게이트를 내부 드라이브로 마이그레이션할 필요가 없습니다.
* 내부 드라이브 없이 AFF A20, AFF A70 또는 AFF A90로 업그레이드하는 경우 업그레이드를 완료한 후 내부 드라이브를 할당할 필요가 없습니다.


컨트롤러 업그레이드 모델 조합이 위 표에 없는 경우 기술 지원 부서에 문의하십시오.



== ARL에 대한 업그레이드가 지원되지 않습니다

다음과 같은 경우에는 ARL을 사용하여 업그레이드를 수행할 수 없습니다.

* 다음 업그레이드 중 하나를 수행하고 있습니다.
+
|===
| 기존 컨트롤러 | 교체 컨트롤러 


| AFF A250 를 참조하십시오 | AFF A50, AFF A30 


| AFF A800 를 참조하십시오 | AFF A70, AFF A90 


| AFF C250 를 참조하십시오 | AFF C30, AFF C60 


| AFF C800 를 참조하십시오 | AFF C80 를 참조하십시오 
|===
+
위의 표에 나열된 업그레이드를 수행하려면 "system controller replace" 명령을 사용하여 동일한 섀시에 있는 컨트롤러 모델을 업그레이드하는 방법(_)을 참조하십시오.link:other_references.html["참조"]

* 백엔드 스토리지용 외부 어레이를 사용하여 V 시리즈 시스템 또는 FlexArray 가상화 스토리지 시스템을 업그레이드합니다. V-Series 또는 FlexArray 시스템의 업그레이드 옵션은 기술 지원 부서에 문의하십시오.
* MetroCluster FC 또는 IP 구성을 업그레이드합니다. MetroCluster 구성을 업그레이드하려면 link:other_references.html["참조"] _MetroCluster 업그레이드 및 확장 설명서_ 링크를 참조하십시오.


컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

.관련 정보
을 참조하십시오 link:other_references.html["참조"] ONTAP 9 제품 설명서에 액세스할 수 있는 _ONTAP 9 문서 센터_에 연결합니다.
