---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: '명령을 사용하여 루트 애그리게이트의 소유권을 재배치함으로써 ONTAP 9.15.1 이상을 실행하는 컨트롤러 하드웨어를 업그레이드할 수 있습니다 `system controller replace` .' 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 절차에서는 다음 시스템 구성에 대해 ARL(Aggregate Relocation)을 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법에 대해 설명합니다.

[cols="40,20,40"]
|===
| 방법 | ONTAP 버전입니다 | 지원되는 시스템 


| 사용 `system controller replace` 명령 | 9.15.1 이상 | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_9151_supported_systems["지원되는 시스템 매트릭스에 대한 링크"] 
|===

NOTE: 다음 절차를 사용하여 MetroCluster FC 또는 IP 구성을 업그레이드할 수 없습니다. MetroCluster 구성을 업그레이드하려면 link:other_references.html["참조"] _MetroCluster 업그레이드 및 확장 설명서_ 링크를 참조하십시오.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 LIF(데이터 논리 인터페이스)를 마이그레이션하고 계속 진행할 때 새 컨트롤러의 네트워크 포트를 인터페이스 그룹에 할당합니다.

.이 정보에 사용된 용어
이 정보에서 원래 노드를 "node1"과 "node2"라고 하며 새 노드를 "node3"과 "node4"라고 합니다. 이 절차를 수행하는 동안 노드 1은 노드 3으로 대체되고 노드 2는 노드 4로 대체됩니다.

"node1", "node2", "node3" 및 "node4"라는 용어는 원래 노드와 새 노드를 구별하는 데만 사용됩니다. 절차를 따를 때는 원래 노드와 새 노드의 실제 이름을 대체해야 합니다. 그러나 실제로 노드 이름은 변경되지 않습니다. node3에는 node1이라는 이름이 있고, node4에는 컨트롤러 하드웨어를 업그레이드한 후 node2라는 이름이 있습니다.

.중요 정보:
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 를 읽고 이해해야 합니다 link:guidelines_for_upgrading_controllers_with_arl.html["ARL을 사용한 컨트롤러 업그레이드 지침"] 및 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 개요"] 섹션을 참조하십시오.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 사용되지 않은 것으로 가정합니다. 명령을 사용하여 사용한 컨트롤러를 준비하는 데 필요한 단계는 `wipeconfig` 이 절차에 포함되지 않습니다. 교체 컨트롤러 하드웨어를 이전에 사용한 경우 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA(고가용성) 쌍에 대해 이 절차를 별도로 수행해야 합니다.
* ONTAP 9.15.1에 도입된 AFF A70, AFF A90 또는 AFF A1K 시스템으로 업그레이드할 때 ONTAP는 스토리지 효율성을 사용하지 않는 볼륨을 포함하여 기존의 모든 씬 프로비저닝된 볼륨의 스토리지 효율성을 변환하고 하드웨어 오프로드 기능을 사용하는 새로운 스토리지 효율성 기능을 적용합니다. 이 프로세스는 자동 백그라운드 프로세스이며 시스템에 성능에 영향을 주지 않습니다. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["자세한 정보"^]..
* AFF A70, AFF A90, AFF A1K 시스템은 클러스터 및 HA 연결 모두에서 100GbE 네트워크 포트를 공유합니다. 이러한 시스템은 기존 클러스터 스위치에 대한 10GbE 또는 25GbE 클러스터 연결을 지원할 수 있습니다. 그러나 NetApp 10GbE 및 25GbE 스위치가 더 이상 필요하지 않은 경우 100GbE 클러스터 속도로 업데이트하는 것이 좋습니다. 자세한 내용은 다음 기술 문서를 참조하십시오.
+
--
** link:https://kb.netapp.com/?title=on-prem%2Fontap%2FOHW%2FOHW-KBs%2FHow_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_A1K%252C_AFF_A90_or_AFF_A70["AFF A1K, AFF A90 또는 AFF A70의 새로운 클러스터 설정에서 10G 또는 25G 클러스터 포트를 구성하는 방법"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_A1K_AFF_A90_or_AFF_A70["기존 클러스터를 AFF A1K, AFF A90 또는 AFF A70의 10G 또는 25G 클러스터 포트에서 40G 또는 100G 클러스터 포트로 변환하는 방법"^]


--
+
기존 노드의 e0a 또는 e0b 클러스터 포트를 새 노드의 클러스터 포트에 연결할 수 없는 경우 를 참조하십시오. link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp 버그 온라인 버그 ID CONTAP-166978"^]

* AFF A70, AFF A90 또는 AFF A1K 시스템으로 업그레이드할 때 ONTAP은 스토리지 효율성을 사용하지 않는 볼륨을 포함하여 기존의 모든 씬 프로비저닝된 볼륨의 스토리지 효율성을 변환하고 하드웨어 오프로드 기능을 사용하는 새로운 스토리지 효율성 기능을 적용합니다. 이 프로세스는 자동 백그라운드 프로세스이며 시스템에 성능에 영향을 주지 않습니다. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["자세한 정보"^]..

