---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: '명령을 사용하여 ONTAP 9.15.1 이상을 실행하는 컨트롤러를 업그레이드할 때 노드3를 설치 및 부팅하고 ONTAP 소프트웨어를 `system controller replace` 설치합니다.' 
---
= 노드3을 설치하고 부팅합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
랙에 node3을 설치하고, node1의 연결을 node3으로 전송하고, node3를 부팅하고, ONTAP를 설치합니다. 그런 다음 이 섹션에 설명된 대로 node1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 프로세스 초기에 node2로 재배치되지 않은 루트가 아닌 애그리게이트를 재할당합니다.

.이 작업에 대해
이 단계를 시작할 때 재배치 작업이 일시 중지됩니다. 이 프로세스는 대부분 자동화되어 있으며 사용자가 상태를 확인할 수 있도록 작업이 일시 중지됩니다. 작업을 수동으로 재개해야 합니다. 또한 SAN LIF가 성공적으로 온라인 상태로 전환되었고 노드 3의 올바른 FC 물리적 포트에 할당되었는지 확인해야 합니다.

노드 1에 설치된 ONTAP 9의 버전이 같지 않으면 노드 3을 netboot 해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 의 지침에 따라 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다 link:prepare_for_netboot.html["netboot를 준비합니다"].

.단계
. [[auto_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
새 노드의 공간 및 높이 요구 사항은 기존 노드와 다를 수 있습니다. 업그레이드 시나리오에 필요한 공간을 계획합니다.

. [[auto_install3_step2]] 노드 모델의 _Installation and Setup Instructions_에 따라 랙에 노드 3을 설치합니다.
. [[auto_install3_step3]] 노드 3을 케이블로 연결하여 노드 1에서 노드 3으로 연결을 이동합니다.
+
ONTAP 9.15.1부터 새로운 컨트롤러 모델에는 베이스보드 관리 컨트롤러(BMC) 및 관리 연결을 위한 "렌치" 포트가 하나만 있습니다. 그에 따라 케이블 변경 사항을 계획합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터와 HA 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** SAS(Serial-Attached SCSI) 및 이더넷 스토리지 포트
** SAN 구성: iSCSI 이더넷, FC 및 NVMe/FC 스위치 포트
+
[NOTE]
====
다른 컨트롤러와 카드 모델 간의 상호 운용성을 위해 이전 컨트롤러와 새 컨트롤러 간의 상호 연결 케이블을 변경해야 할 수 있습니다. 시스템에 대한 이더넷 스토리지 쉘프의 케이블 연결 맵은 을 link:https://docs.netapp.com/us-en/ontap-systems/index.html["시스템 설치 절차"^] 참조하십시오.

ONTAP 9.15.1 이상 버전에서 도입된 컨트롤러의 경우, 클러스터 및 HA 인터커넥트에서 동일한 포트를 사용합니다. 스위치 연결 구성의 경우 유사한 포트를 동일한 클러스터 스위치에 연결해야 합니다. 예를 들어, 기존 컨트롤러에서 AFF A1K로 업그레이드할 경우 두 노드의 E1A 포트를 두 번째 스위치에 연결하고 두 노드의 e7a 포트를 두 번째 스위치에 연결해야 합니다.

====


. [[auto_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]에 경고 메시지가 표시되는 경우 <<auto_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: * 주의: 지연을 무시하지 마십시오. 배터리를 충전하지 않으면 데이터가 손실될 수 있습니다. *

+

NOTE: 을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].





. [[step6]] 다음 작업 중 하나를 선택하여 netboot 연결을 구성합니다.
+

NOTE: 관리 포트와 IP를 netboot 연결로 사용해야 합니다. 업그레이드를 수행하는 동안 데이터 LIF IP를 사용하지 않거나 데이터 중단이 발생할 수 있습니다.

+
[cols="30,70"]
|===
| DHCP(Dynamic Host Configuration Protocol)가 다음과 같은 경우 | 그러면... 


| 실행 중입니다 | 부팅 환경 프롬프트에서 다음 명령을 사용하여 연결을 자동으로 구성합니다.
`ifconfig e0M -auto` 


| 실행 중이 아닙니다  a| 
부팅 환경 프롬프트에서 다음 명령을 사용하여 연결을 수동으로 구성합니다.
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 스토리지 시스템의 IP 주소입니다(필수).
`_netmask_` 스토리지 시스템의 네트워크 마스크입니다(필수).
`_gateway_` 는 스토리지 시스템의 게이트웨이입니다(필수).
`_dns_addr_` 네트워크에 있는 이름 서버의 IP 주소입니다(선택 사항).
`_dns_domain_` DNS(Domain Name Service) 도메인 이름입니다(선택 사항).


NOTE: 인터페이스에 다른 매개 변수가 필요할 수 있습니다. 를 입력합니다 `help ifconfig` 펌웨어 프롬프트에서 세부 정보를 확인합니다.

|===
. [[step7]]노드 3에서 netboot 수행:
+
`netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

+
를 클릭합니다 `<path_to_the_web-accessible_directory>` 에서 다운로드한 위치로 이동합니다 `<ontap_version>_image.tgz` 섹션을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].

+

NOTE: 부팅을 중단하지 마십시오.

. [[step8]] 부팅 메뉴에서 옵션을 선택합니다 `(7) Install new software first`.
+
이 메뉴 옵션은 새 ONTAP 이미지를 다운로드하여 부팅 장치에 설치합니다.

+
다음 메시지는 무시하십시오.

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
참고 사항은 ONTAP의 무중단 업그레이드에는 적용되고 컨트롤러 업그레이드에는 적용되지 않습니다.

+

NOTE: 항상 netboot를 사용하여 새 노드를 원하는 이미지로 업데이트합니다. 다른 방법을 사용하여 새 컨트롤러에 이미지를 설치할 경우 잘못된 이미지가 설치될 수 있습니다. 이 문제는 모든 ONTAP 릴리스에 적용됩니다. 옵션과 결합된 netboot 절차 `(7) Install new software` 부팅 미디어를 지우고 두 이미지 파티션에 동일한 ONTAP 버전을 배치합니다.

. [[step9]] 절차를 계속하라는 메시지가 나타나면 를 입력합니다 `y`, 패키지를 입력하라는 메시지가 나타나면 URL을 입력합니다.
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[10단계]] 다음 하위 단계를 완료하여 컨트롤러 모듈을 재부팅합니다.
+
.. 를 입력합니다 `n` 다음 프롬프트가 표시될 때 백업 복구를 건너뛰려면 다음을 수행합니다.
+
`Do you want to restore the backup configuration now? {y|n}`

.. 를 입력합니다 `y` 다음 메시지가 표시될 때 재부팅하려면 다음을 수행하십시오.
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
부팅 장치가 다시 포맷되어 구성 데이터가 복원되어야 하므로 컨트롤러 모듈이 재부팅되지만 부팅 메뉴에서 중지됩니다.



. [[11단계]] 유지보수 모드를 선택합니다 `5` 를 눌러 부팅 메뉴에서 으로 이동합니다 `y` 부팅 계속 메시지가 표시되면
. [[12단계] 컨트롤러 및 섀시가 ha로 구성되었는지 확인:
+
`ha-config show`

+
다음 예제는 의 출력을 보여 줍니다 `ha-config show` 명령:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: HA 쌍 또는 독립 실행형 구성에 관계없이 PROM에서 시스템 기록. 독립 실행형 시스템 또는 HA 쌍 내의 모든 구성 요소에서 상태가 동일해야 합니다.

. 컨트롤러 및 섀시가 ha로 구성되지 않은 경우 다음 명령을 사용하여 구성을 수정하십시오.
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

. 이더넷 셸프에 연결하는 데 사용되는 모든 이더넷 포트가 스토리지로 구성되었는지 확인합니다.
+
`storage port show`

+
표시되는 출력은 시스템 구성에 따라 다릅니다. 다음 출력 예는 슬롯11에 단일 스토리지 카드가 있는 노드에 대한 것입니다. 시스템의 출력은 다를 수 있습니다.

+
[listing]
----
*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e11a ENET storage 100 Gb/s    enabled  online  30
e11b ENET storage 100 Gb/s    enabled  online  30
----
. 스토리지에 설정되지 않은 포트를 수정합니다.
+
`storage port modify -p <port> -m storage`

+
디스크 및 셸프에 액세스할 수 있도록 스토리지 셸프에 연결된 모든 이더넷 포트를 스토리지로 구성해야 합니다.

. 유지보수 모드 종료:
+
`halt`

+
키를 눌러 자동 부팅을 중단시킵니다 `Ctrl-C` 부팅 환경 프롬프트에서

. 노드 2에서 시스템 날짜, 시간 및 시간대를 확인합니다.
+
`date`

. 노드3에서 부팅 환경 프롬프트에서 다음 명령을 사용하여 날짜를 확인합니다.
+
`show date`

. 필요한 경우 노드3에 날짜를 설정합니다.
+
`set date <mm/dd/yyyy>`

. 노드3에서 부팅 환경 프롬프트에서 다음 명령을 사용하여 시간을 확인합니다.
+
`show time`

. 필요한 경우 node3에서 시간을 설정합니다.
+
`set time <hh:mm:ss>`

. 부팅 로더에서 노드3에 파트너 시스템 ID를 설정합니다.
+
`setenv partner-sysid <node2_sysid>`

+
노드 3의 경우 `partner-sysid` 노드 2의 것이어야 합니다.

+
.. 설정을 저장합니다.
+
`saveenv`



. [[auto_install3_step21]]를 확인합니다 `partner-sysid` 노드 3의 경우:
+
`printenv partner-sysid`

. NSE(NetApp 스토리지 암호화) 드라이브가 설치되어 있는 경우 다음 단계를 수행하십시오.
+

NOTE: 절차의 앞부분에서 아직 수행하지 않은 경우 기술 자료 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["드라이브가 FIPS 인증되었는지 확인하는 방법"^] 사용 중인 자체 암호화 드라이브의 유형을 확인합니다.

+
.. 설정 `bootarg.storageencryption.support` 를 선택합니다 `true` 또는 `false`:
+
[cols="35,65"]
|===
| 다음 드라이브를 사용 중인 경우… | 그러면... 


| NSE 드라이브가 FIPS 140-2 레벨 2 자체 암호화 요구사항을 충족합니다 | `setenv bootarg.storageencryption.support *true*` 


| NetApp 비 FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
.. 특수 부팅 메뉴로 이동하여 옵션을 선택합니다 `(10) Set Onboard Key Manager recovery secrets`.
+
이전 절차에서 기록한 암호 및 백업 정보를 입력합니다. 을 참조하십시오 link:manage_storage_encryption_using_okm.html["Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다"].



. 부팅 메뉴로 노드 부팅:
+
`boot_ontap menu`

. 노드3에서 부팅 메뉴로 이동하여 22/7을 사용하여 숨김 옵션을 선택합니다 `boot_after_controller_replacement`. 다음 예에 따라 프롬프트에 node1을 입력하여 node3에 노드 1의 디스크를 재할당합니다.
+
.콘솔 출력 예를 확장합니다
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: 위의 콘솔 출력 예에서 시스템이 ADP(고급 디스크 파티셔닝) 디스크를 사용하는 경우 ONTAP에서 파트너 노드 이름을 묻는 메시지를 표시합니다.

. 시스템이 재부팅 루프에 들어가고 메시지가 `no disks found`나타나면 디스크 재할당에 문제가 있음을 나타냅니다. 문제를 해결하려면 을 link:troubleshoot_index.html["문제 해결"] 참조하십시오.
. 자동 부팅 중에 을 `Ctrl-C` 눌러 프롬프트에서 노드를 `LOADER>` 중지합니다.
. LOADER 프롬프트에서 유지보수 모드로 전환합니다.
+
`boot_ontap maint`

. 디스크 연결, 컨트롤러 모델 문자열, HA 구성 및 기타 하드웨어 연결 관련 세부 정보를 확인합니다.
. 유지보수 모드 종료:
+
`halt`

. [[auto_check3_step32]] LOADER 프롬프트에서 부팅합니다.
+
`boot_ontap menu`

+
이제 부팅 시 노드에서 이전에 할당되었으며 예상대로 부팅할 수 있는 모든 디스크를 감지할 수 있습니다.

+
교체할 클러스터 노드가 루트 볼륨 암호화를 사용하면 ONTAP가 디스크에서 볼륨 정보를 읽을 수 없습니다. 루트 볼륨의 키를 복원합니다.

+

NOTE: 루트 볼륨이 NetApp 볼륨 암호화를 사용하는 경우에만 적용됩니다.

+
.. 특수 부팅 메뉴로 돌아갑니다.
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Onboard Key Manager 복구 비밀 설정 * 을 선택합니다
.. 를 입력합니다 `y` 다음 프롬프트에서 다음을 수행합니다.
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 프롬프트에서 키 관리자 암호를 입력합니다.
.. 메시지가 표시되면 백업 데이터를 입력합니다.
+

NOTE: 에서 암호 및 백업 데이터를 가져야만 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 섹션을 참조하십시오.

.. 시스템이 특수 부팅 메뉴로 다시 부팅된 후 옵션 * (1) Normal Boot * 를 실행합니다
+

NOTE: 이 단계에서 오류가 발생할 수 있습니다. 오류가 발생하면 시스템이 정상적으로 부팅될 때까지 의 하위 단계를 <<auto_check3_step32,32단계>> 반복합니다.




