---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: '명령을 사용하여 ONTAP 9.15.1 이상을 실행하는 컨트롤러를 업그레이드할 때 노드 2의 노드1 NAS 데이터 LIF가 노드2에서 노드3로 재배치되는지 확인합니다 `system controller replace` .' 
---
= 노드 1이 소유하는 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 3의 네트워크 구성을 확인하고 노드 2에서 노드 3으로 애그리게이트를 재배치된 후에는 노드 2에 있는 노드 1에 속하는 NAS 데이터 LIF가 노드 2에서 노드 3으로 재배치되어 있는지 확인해야 합니다. 또한 노드 3에 SAN LIF가 존재하는지 확인해야 합니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN으로의 트래픽을 처리합니다. 업그레이드 중 클러스터 또는 서비스 상태를 유지하기 위해 SAN LIF를 이동할 필요는 없습니다. SAN LIF는 새 포트에 매핑해야 하는 경우에만 이동됩니다. 노드 3을 온라인 상태로 만든 후 LIF가 정상 작동하고 적절한 포트에 있는지 확인하십시오.

.단계
. iSCSI LIF는 내 성 검사를 통해 올바른 홈 포트를 자동으로 찾습니다. FC 및 NVMe/FC SAN LIF는 자동으로 이동하지 않습니다. 업그레이드 전에 홈 포트가 계속 표시됩니다.
+
노드 3에서 SAN LIF 확인:

+
.. "다운" 작업 상태를 새 데이터 포트로 보고하는 모든 iSCSI SAN LIF 수정:
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <iscsi_san_lif>
----
.. 새 컨트롤러의 집에 있는 FC 및 NVMe/FC SAN LIF를 수정하고 새 컨트롤러의 FCP 포트에 "중단" 운영 상태를 보고합니다.
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> admin down
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif> port <new_port> node <node>
----
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <fc_san_lif>
----


. 재배치 작업 재개:
+
[source, cli]
----
system controller replace resume
----
+
시스템은 다음 작업을 수행합니다.

+
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


+
이 단계에서 네트워크 도달 가능성 점검에서 작업이 일시 중지됩니다.

. 재배치 작업 재개:
+
[source, cli]
----
system controller replace resume
----
+
시스템에서 다음 검사를 수행합니다.

+
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


+
이러한 확인을 수행한 후 시스템은 노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 3의 새 컨트롤러로 재배치합니다. 리소스 재배치가 완료된 후 컨트롤러 교체 작업이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
[source, cli]
----
system controller replace show-details
----
+
컨트롤러 교체 절차가 일시 중지된 경우 오류를 확인하고 수정한 다음 문제를 해결하십시오 `resume` 를 눌러 작업을 계속합니다.

. 필요한 경우, 위치가 변경된 LIF를 복원 및 되돌리거나, 자동으로 노드3으로 재배치되지 못한 노드1의 LIF를 수동으로 마이그레이션하고 수정하십시오.
+
[role="tabbed-block"]
====
.위치가 어긋난 LIF를 복원하고 되돌립니다.
--
.. 위치가 변경된 LIF를 모두 나열하십시오:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF가 대체된 경우 홈 노드를 노드 3으로 다시 복원합니다.
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIF를 수동으로 마이그레이션하고 수정합니다.
--
.. 자동으로 재배치되지 못한 LIF를 노드3으로 마이그레이션합니다.
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. 마이그레이션된 LIF의 홈 노드와 홈 포트를 수정합니다.
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
[source, cli]
----
system controller replace resume
----
+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검
** 볼륨 확인




.다음 단계
node1이 소유한 루트가 아닌 애그리게이트 및 NAS 데이터 LIF를 node2에서 node3으로 이동한 후link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트가 아닌 애그리게이트 및 NAS 데이터 LIF를 노드2에서 노드3으로 재배치합니다"].
