---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/prepare_for_netboot.html 
keywords: preparing, netboot, ndac, ontap 
summary: '를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 netboot node3 및 node4를 준비합니다 `system controller replace` 명령.' 
---
= netboot를 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
절차의 나중에 노드 3과 노드 4를 물리적으로 랙에 설치한 후 해당 노드들을 netboot 해야 할 수도 있습니다. "netboot"는 원격 서버에 저장된 ONTAP 이미지에서 부팅함을 의미합니다. netboot를 준비할 때 시스템이 액세스할 수 있는 웹 서버에 ONTAP 9 부트 이미지 사본을 넣습니다.

USB 부팅 옵션을 사용하여 NetBoot을 수행할 수도 있습니다. 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["시스템의 초기 설정을 위해 ONTAP를 설치하는 데 boot_recovery Loader 명령을 사용하는 방법"^].

.시작하기 전에
* 시스템에서 HTTP 서버에 액세스할 수 있는지 확인합니다.
* 을 참조하십시오 link:other_references.html["참조"] 를 방문하여 귀하의 플랫폼에 필요한 시스템 파일과 올바른 버전의 ONTAP를 다운로드하십시오.


.이 작업에 대해
원래 컨트롤러에 설치된 것과 동일한 버전의 ONTAP 9가 없는 경우 새 컨트롤러를 netboot 해야 합니다. 각각의 새 컨트롤러를 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 시스템을 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다.

.단계
. NetApp Support 사이트에 액세스하여 시스템 netboot에 사용되는 파일을 다운로드합니다.
. NetApp Support 사이트의 소프트웨어 다운로드 섹션에서 해당 ONTAP 소프트웨어를 다운로드하고 를 저장합니다 `<ontap_version>_image.tgz` 웹 액세스 가능 디렉터리에 있는 파일입니다.
. 웹 액세스 가능 디렉토리로 변경하고 필요한 파일을 사용할 수 있는지 확인합니다.
+
디렉토리 목록에는 다음 파일이 포함되어야 합니다.
`<ontap_version>_image.tgz`

+

NOTE: 의 내용을 추출할 필요는 없습니다 `<ontap_version>_image.tgz` 파일.

+
의 디렉토리에 있는 정보를 사용합니다 link:install_boot_node3.html["3단계"].


