---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/relocate-failed-or-vetoed-aggr-node3.html 
keywords: relocating, failed, vetoed, aggregates, relocation, operation 
summary: 'ONTAP 9.15.1 이상을 실행하는 컨트롤러를 업그레이드할 때 실패하거나 거부된 집계를 수동으로 node3로 다시 이동하려면 다음을 사용합니다. `system controller replace` 명령.' 
---
= 실패하거나 거부된 집계를 node3로 다시 이동합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
집계가 이전되지 않거나 거부된 경우 집계를 수동으로 node3으로 이전하거나 필요한 경우 거부 또는 대상 확인을 재정의해야 합니다.

.이 작업에 대해
오류로 인해 시스템이 이전 작업을 일시 중지합니다.

.단계
. EMS(이벤트 관리 시스템) 로그를 확인하여 Aggregate의 재배치 실패 또는 거부가 발생한 이유를 확인합니다.
. 장애가 발생하거나 거부되는 애그리게이트를 재배치합니다.
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list <aggregate_name> -ndo-controller-upgrade true`

. 메시지가 표시되면 를 입력합니다 `y`.
. 다음 방법 중 하나를 사용하여 재배치를 수행할 수 있습니다.
+
[cols="35,65"]
|===
| 옵션을 선택합니다 | 설명 


| 거부권 확인 무시 | 다음 명령을 사용하세요:
`storage aggregate relocation start -node node2 -destination node3 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true` 


| 대상 확인을 재정의하는 중입니다 | 다음 명령을 사용하세요:
`storage aggregate relocation start -node node2 -destination node3 -aggregate-list <aggregate_list> -ndo-controller-upgrade true -override-vetoes true -override-destination-checks true` 
|===

