---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 'ARL을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 을(를) 사용하여 9.7로 업그레이드할지 여부를 결정합니다 `system controller replace` 명령.' 
---
= 이 집계 이전 절차를 사용할지 결정하십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하는 데에는 여러 가지 ARL(집계 재배치) 방법이 있습니다. 이 절차에서는 ONTAP 9.7, 9.6 또는 9.5를 실행하는 시스템에서 "시스템 컨트롤러 교체 명령"과 함께 ARL을 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다. 숙련된 ONTAP 관리자만 이 복잡한 절차를 사용해야 합니다.

이 ARL 절차가 컨트롤러 하드웨어 업그레이드에 적합한지 결정하는 데 도움이 되도록 지원되는 업그레이드에 대한 다음 모든 상황을 검토해야 합니다.

* ONTAP 9.5, 9.6 또는 9.7을 실행 중인 NetApp 컨트롤러를 업그레이드하려는 경우 이 문서는 ONTAP 9.8로의 업그레이드에는 적용되지 않습니다.
* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동을 사용하여 데이터를 마이그레이션하기를 원하지 않을 것입니다.
* ONTAP 관리에 대한 경험이 있으며 진단 권한 모드에서 작업할 때 발생할 수 있는 위험에 대해 잘 알 수 있습니다.
* 귀하의 하드웨어 업그레이드 조합은 다음에 나열되어 있습니다. <<sys_commands_95_97_supported_systems,지원되는 모델 매트릭스>> .
* MetroCluster 구성을 업그레이드할 경우 4노드 이상의 FC 구성이며 모든 노드에서 ONTAP 9.6 또는 9.7을 실행하고 있습니다.


[NOTE]
====
* . 이 ARL 절차에는 업그레이드 절차 중에 컨트롤러를 제거하고 설치할 때 내부 디스크가 섀시에 안전하게 고정되도록 하는 단계가 포함되어 있습니다
+
link:../upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["기존 시스템 섀시와 디스크를 유지하면서 ARL을 사용하여 지원되는 시스템 업그레이드 조합에 대해 알아보세요."]..

* 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.


====


== 지원되는 시스템 업그레이드 조합

다음 표는 이 ARL 절차를 사용하여 컨트롤러 업그레이드에 지원되는 모델 매트릭스를 보여줍니다.

[cols="50,50"]
|===
| 더 오래 된 컨트롤러 | 교체 컨트롤러 


| FAS8020, FAS8040, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| AFF8020, AFF8040, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700^1^, AFF A800^2^ 


| FAS8200 | FAS8700, FAS9000, FAS8300^4^, ^^5^ 


| AFF A300 | AFF A700^1^, AFF A800^2^^,^^3^, AFF A400^4^, ^^5^ 
|===

NOTE: 컨트롤러 업그레이드 모델 조합이 위 표에 없는 경우 기술 지원 부서에 문의하십시오.

AFF 9.7P2에서 ONTAP A700 시스템에 대한 ^1^ARL 자동 업그레이드가 지원됩니다.

^2^ 내부 및 외부 디스크를 지원하는 AFF A800 또는 시스템으로 업데이트하는 경우 내부 NVMe 디스크의 루트 애그리게이트에 대한 특정 지침을 따라야 합니다. 을 참조하십시오 link:set_fc_or_uta_uta2_config_on_node3.html#step14["노드 3, 14단계에서 UTA/UTA2 포트를 확인하고 구성합니다"] 및 link:set_fc_or_uta_uta2_config_node4.html#step14["노드 4, 14단계에서 UTA/UTA2 포트를 확인하고 구성합니다"].

^3^ARL AFF 9.7P5에서 AFF A300에서 ONTAP A800 시스템으로 자동 업그레이드가 지원됩니다.

^4^ARL AFF A300에서 AFF A400 및 FAS8200으로의 자동 업그레이드는 ONTAP 9.7P8에서 지원됩니다.

^5^ AFF A300에서 AFF A400 또는 FAS8200으로 2노드 스위치가 없는 클러스터 구성의 FAS8300 시스템으로 업그레이드하는 경우 컨트롤러 업그레이드를 위한 임시 클러스터 포트를 선택해야 합니다. AFF A400 및 FAS8300 시스템은 2개의 구성으로 제공됩니다. 메자닌 카드 포트는 이더넷 유형이고 메자닌 포트가 FC 유형인 FC 번들입니다.

* 이더넷 유형 구성이 있는 AFF A400 또는 FAS8300 의 경우 두 메자닌 포트 중 하나를 임시 클러스터 포트로 사용할 수 있습니다.
* FC 유형 구성을 사용하는 AFF A400 또는 FAS8300 의 경우 임시 클러스터 포트를 제공하려면 4포트 10GbE 네트워크 인터페이스 카드(부품 번호 X1147A)를 추가해야 합니다.
* 임시 클러스터 포트를 사용하여 컨트롤러 업그레이드를 완료한 후에는 FAS8300 시스템의 e3a 및 e3b, AFF A400 시스템의 100GbE 포트, e0c 및 e0d, 100GbE 포트로 클러스터 LIF를 중단 없이 마이그레이션할 수 있습니다.




== 다른 하드웨어 업그레이드 절차를 선택하세요

* link:../upgrade-arl/index.html["컨트롤러 하드웨어 업그레이드에 사용 가능한 대체 ARL 방법을 검토하세요."]..
* 컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.


.관련 정보
참조하다 link:other_references.html["참조"] _ONTAP 9 문서_에 링크합니다.
