---
sidebar: sidebar 
permalink: upgrade-arl-auto/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: Storage Encryption을 구성하고 클러스터 전체 인증 키를 설정하여 이전 노드 레벨 인증 키를 대체합니다 
---
= 스토리지 암호화를 위한 외부 키 관리 서버의 IP 주소를 가져옵니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
업그레이드 후에는 스토리지 암호화를 즉시 구성하고 클러스터 차원의 인증 키를 설정하여 이전 노드 레벨 인증 키를 교체해야 합니다.

.단계
. 키 관리 서버와 통신하는 데 필요한 클라이언트 및 서버 SSL(Secure Sockets Layer) 인증서를 설치합니다.
+
보안 인증서 설치

. 각 노드에서 다음 명령을 사용하여 모든 노드에서 스토리지 암호화 구성:
+
보안 키 관리자 설정

. 각 키 관리 서버의 IP 주소를 추가합니다.
+
보안 키 관리자 추가

. 클러스터의 모든 노드에서 동일한 키 관리 서버가 구성 및 사용 가능한지 확인합니다.
+
보안 키 관리자 표시 상태

. 새 클러스터 전체 인증 키를 생성합니다.
+
보안 키 관리자 만들기 키

. 새 인증 키 ID를 기록해 둡니다.
. 새 인증 키를 사용하여 모든 자체 암호화 드라이브를 다시 입력하다
+
'Storage encryption disk modify -disk * -data-key-id <authentication_key_id>'





== KMIP 서버를 사용하여 인증 관리

ONTAP 9.5 ~ 9.7에서는 KMIP(키 관리 상호 운용성 프로토콜) 서버를 사용하여 인증 키를 관리할 수 있습니다.

단계

. 새 컨트롤러 추가:
+
'Security key-manager setup-node <new_controller_name>'

. 키 관리자 추가:
+
'Security key-manager-add <key_management_server_ip_address>'를 선택합니다

. 키 관리 서버가 구성되어 있고 클러스터의 모든 노드에서 사용할 수 있는지 확인합니다.
+
보안 키 관리자 표시 상태

. 연결된 모든 키 관리 서버에서 새 노드로 인증 키를 복원합니다.
+
'Security key-manager restore-node <new_controller_name>'입니다

. 새 인증 키를 사용하여 모든 자체 암호화 디스크를 다시 입력하다
+
'Storage encryption disk modify -disk * [-data-key-id nonMSID AK]'

. FIPS(Federal Information Processing Standard)를 사용하는 경우 새 인증 키를 사용하여 모든 자체 암호화 디스크를 다시 입력하다
+
'Storage encryption disk modify -disk * [-FIPS-key-id nonMSID AK]'





== Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다

OKM을 사용하여 암호화 키를 관리할 수 있습니다. OKM을 사용하려면 업그레이드를 시작하기 전에 암호문과 백업 자료를 기록해야 합니다.

.단계
. 암호를 안전한 위치에 저장합니다.
. 복구를 위해 백업을 생성합니다. 다음 명령을 실행하고 출력을 저장합니다.
+
키 관리자 온보드 쇼 백업





== Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다

OKM을 사용하여 암호화 키를 관리할 수 있습니다. OKM을 사용하려면 업그레이드를 시작하기 전에 암호문과 백업 자료를 기록해야 합니다.

.단계
. 암호를 안전한 위치에 저장합니다.
. 복구를 위해 백업을 생성합니다. 다음 명령을 실행하고 출력을 저장합니다.
+
보안 키 관리자 온보드 쇼 백업





== SnapMirror 관계 중지(선택 사항)

절차를 계속하기 전에 모든 SnapMirror 관계가 중지되었는지 확인해야 합니다. SnapMirror 관계가 중지되면 재부팅 및 페일오버 시에도 계속 정지됩니다.

.단계
. 대상 클러스터에서 SnapMirror 관계 상태를 확인합니다.
+
스냅미러 쇼

+
[NOTE]
====
상태가 "전송 중"인 경우 '스냅샷 미러 중단 - 대상 - vserver <vserver_name>' 전송을 중단해야 합니다

====
+
SnapMirror 관계가 "전송 중" 상태가 아니면 중단이 실패합니다.

. 클러스터 간의 모든 관계 중지:
+
'sapmirror quiesce-destination-vserver <vserver_name>'


