---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드할 수 있는지 이해합니다 `system controller replace` 명령.' 
---
= ARL을 사용한 컨트롤러 업그레이드 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ARL(Aggregate Relocation)을 사용하여 ONTAP 9.5를 실행하는 컨트롤러 쌍을 ONTAP 9.7로 업그레이드할 수 있는지 여부를 이해하려면 플랫폼 및 원래 컨트롤러와 교체 컨트롤러 모두의 구성에 따라 다릅니다.



[[supported-upgrades-for-arl]]
== ARL에 대한 업그레이드가 지원됩니다

ONTAP 9.5에 대한 이 ARL 절차를 사용하여 노드 쌍을 ONTAP 9.7로 업그레이드할 때 원본 및 교체 컨트롤러에서 ARL을 수행할 수 있는지 확인해야 합니다.

기존 시스템에서 정의된 모든 애그리게이트의 크기와 지원하는 디스크 수를 확인해야 합니다. 그런 다음 기존 시스템의 애그리게이트 크기와 지원하는 디스크 수를 새 시스템의 애그리게이트 크기와 지원하는 디스크 수와 비교해야 합니다. 이 정보를 확인할 수 있는 _Hardware Universe_ 링크는 link:other-references.html["참조"]을 참조하십시오. 새 시스템에서 지원하는 애그리게이트 크기와 디스크 수는 기존 시스템에서 지원하는 애그리게이트 크기와 디스크 수와 같거나 커야 합니다.

기존 컨트롤러가 교체될 때 새 노드가 기존 노드와 함께 클러스터에 포함될 수 있는지 여부를 클러스터 혼합 규칙에서 검증해야 합니다. 클러스터 혼합 규칙에 대한 자세한 내용은 link:other-references.html["참조"]_Hardware Universe_ 링크를 참조하십시오.


NOTE: AFF 시스템 업그레이드를 수행하기 전에 ONTAP를 릴리스 버전 9.5P1 이상으로 업그레이드해야 합니다. 성공적인 업그레이드를 위해서는 이러한 릴리즈 수준이 필요합니다.


NOTE: 내부 드라이브를 지원하는 시스템(예: FAS2700 또는 AFF A250)을 업그레이드하지만 내부 드라이브가 없는 경우 link:other-references.html["참조"]을 참조하고 사용 중인 ONTAP 버전에 맞는 _Aggregate Relocation to Manually Upgrade Controller Hardware_ 콘텐츠의 절차를 사용하십시오.

ONTAP 9.6P11, 9.7P8 이상 릴리즈를 사용하는 경우 특정 노드 장애가 발생할 때 연결, 활성화 및 가용성 모니터(clam) 테이크오버가 클러스터를 쿼럼으로 반환하도록 설정하는 것이 좋습니다. 를 클릭합니다 `kernel-service` 명령에 고급 권한 레벨 액세스가 필요합니다. 자세한 내용은 다음을 참조하십시오. https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp KB 문서 SU436: clam takeover 기본 구성이 변경되었습니다"^].

ARL을 사용한 컨트롤러 업그레이드는 SnapLock Enterprise 및 SnapLock Compliance 볼륨으로 구성된 시스템에서 지원됩니다.



[[two-node-switchless-clusters]]
== 스위치가 없는 2노드 클러스터

스위치가 없는 2노드 클러스터에서 노드를 업그레이드할 경우 업그레이드를 수행하는 동안 스위치가 없는 클러스터에 노드를 그대로 둘 수 있습니다. 이러한 LUN을 스위치 클러스터로 변환할 필요는 없습니다.



[[upgrades-not-supported-for-arl]]
== ARL에 대한 업그레이드가 지원되지 않습니다

다음 업그레이드는 수행할 수 없습니다.

* 원래 컨트롤러에 연결된 디스크 쉘프를 지원하지 않는 컨트롤러 교체
+
link:other-references.html["참조"]를 참조하여 디스크 지원 정보에 대한 _Hardware Universe_ 링크를 확인하십시오.

* 내부 드라이브가 있는 엔트리 레벨 컨트롤러(예: FAS2750).
+
내부 드라이브가 있는 엔트리 레벨 컨트롤러를 업그레이드하려면 link:other-references.html["참조"]를 참조하여 _볼륨 또는 스토리지를 이동하여 업그레이드_ 링크로 이동하고 _볼륨을 이동하여 clustered Data ONTAP을 실행하는 노드 쌍 업그레이드_ 절차를 따르십시오.





[[metrocluster-fc-configuration]]
== MetroCluster FC 구성

MetroCluster FC 구성에서는 재해 복구/페일오버 사이트 노드를 최대한 빨리 교체해야 합니다. MetroCluster 구성 내 컨트롤러 모델 불일치는 지원되지 않습니다. 컨트롤러 모델 불일치로 인해 재해 복구 미러링이 오프라인 상태가 될 수 있기 때문입니다 .  `-skip-metrocluster-check true` 두 번째 사이트에서 노드를 교체할 때 MetroCluster 검사를 우회하는 명령입니다.



[[troubleshoot]]
== 문제 해결

노드 쌍을 업그레이드하는 동안 장애가 발생할 수 있습니다. 노드가 충돌하거나 애그리게이트가 재배치되지 않거나 LIF가 마이그레이션되지 않을 수 있습니다. 장애 원인 및 해결 방법은 업그레이드 절차 중 장애가 발생한 시기에 따라 다릅니다.

ARL 업그레이드 개요 섹션에서 절차의 다양한 단계를 설명하는 표를 참조하세요. 발생할 수 있는 오류에 대한 정보는 절차의 단계별로 나열됩니다.

컨트롤러 업그레이드 중 문제가 발생하면 다음을 참조하세요.link:aggregate_relocation_failures.html["문제 해결"] 부분.  발생할 수 있는 실패에 대한 정보는 절차의 단계별로 나열됩니다.link:overview_of_the_arl_upgrade.html["ARL 업그레이드 시퀀스"] .

발생한 문제에 대한 해결책을 찾지 못한 경우 기술 지원 부서에 문의하십시오.
