---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: '"시스템 컨트롤러 교체" 명령을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드할 때 node1의 물리적 포트가 node3에 올바르게 매핑되는지 확인합니다.' 
---
= 노드 1의 포트를 노드 3으로 매핑합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 1의 물리적 포트가 노드 3의 물리적 포트에 올바르게 매핑되는지 확인해야 합니다. 이렇게 하면 노드 3이 클러스터의 다른 노드 및 업그레이드 후 네트워크와 통신할 수 있습니다.

을 참조하십시오 link:other_references.html["참조"] 새 노드의 포트에 대한 정보를 캡처하기 위해 _Hardware Universe_에 연결합니다. 이 섹션의 뒷부분에서 정보를 사용합니다.

포트 설정은 노드 모델에 따라 다를 수 있습니다. 원래 노드의 포트 및 LIF 구성이 새 노드의 계획된 사용 및 구성과 호환되도록 해야 합니다. 이는 새 노드가 부팅될 때 동일한 구성을 재생하므로 노드 3을 부팅할 때 ONTAP은 노드 1에서 사용된 동일한 포트에 LIF를 호스팅하려고 하기 때문입니다.

따라서 노드 1의 물리적 포트가 노드 3의 물리적 포트에 직접 매핑되지 않으면 부팅 후 클러스터, 관리 및 네트워크 연결을 복원하기 위해 소프트웨어 구성을 변경해야 합니다. 또한 노드 1의 클러스터 포트가 노드 3의 클러스터 포트에 직접 매핑되지 않으면 소프트웨어 구성을 변경하여 클러스터 LIF를 올바른 물리적 포트에 호스팅하도록 변경할 때까지 노드 3이 재부팅될 때 쿼럼에 자동으로 다시 참가하지 않을 수 있습니다.

.단계
. 노드 1, 포트, 브로드캐스트 도메인 및 IPspace의 노드 1 케이블링 정보를 모두 표에 기록:
+
|===
| LIF | 노드1 포트 | 노드 1 IPspace | 노드1 브로드캐스트 도메인 | Node3 포트 | 노드 3 IPspace | Node3 브로드캐스트 도메인 


| 클러스터 1 |  |  |  |  |  |  


| 클러스터 2 |  |  |  |  |  |  


| 클러스터 3 |  |  |  |  |  |  


| 클러스터 4 |  |  |  |  |  |  


| 노드 관리 |  |  |  |  |  |  


| 클러스터 관리 |  |  |  |  |  |  


| 데이터 1 |  |  |  |  |  |  


| 데이터 2 |  |  |  |  |  |  


| 데이터 3 |  |  |  |  |  |  


| 데이터 4 |  |  |  |  |  |  


| 산 |  |  |  |  |  |  


| 인터클러스터 포트 |  |  |  |  |  |  
|===
. 노드 3, 포트, 브로드캐스트 도메인 및 IPspace의 모든 케이블 연결 정보를 표에 기록합니다.
. 스위치가 없는 2노드 클러스터인지 확인하려면 다음 단계를 수행하십시오.
+
.. 권한 수준을 고급으로 설정합니다.
+
'클러스터::> 고급 설정'

.. 스위치가 없는 2노드 클러스터인지 확인합니다.
+
'cluster:::> network options switchless-cluster show'

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
이 명령 출력의 값은 시스템의 물리적 상태와 일치해야 합니다.

.. 관리 권한 레벨로 돌아갑니다.
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. 노드 3을 쿼럼에 배치하려면 다음 단계를 수행하십시오.
+
.. 노드3 부팅. 을 참조하십시오 link:install_boot_node3.html["노드3을 설치하고 부팅합니다"] 아직 부팅하지 않은 경우 노드를 부팅합니다.
.. 새 클러스터 포트가 클러스터 브로드캐스트 도메인에 있는지 확인합니다.
+
'network port show-node_node_-port_port_-fields broadcast-domain

+
다음 예에서는 노드 3의 클러스터 도메인에 포트 "e0a"가 있음을 보여 줍니다.

+
[listing]
----
 cluster::> network port show -node _node3_ -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. 클러스터 포트가 Cluster broadcast-domain에 없는 경우 다음 명령을 사용하여 추가합니다.
+
'broadcast-domain add-ports-IPSpace Cluster-broadcast-domain Cluster-ports_node:port_'

+
이 예제에서는 노드 3에 클러스터 포트 "e1b"를 추가합니다.

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. 클러스터 브로드캐스트 도메인에 올바른 포트를 추가합니다.
+
네트워크 포트 수정-노드-포트-IPSpace 클러스터-MTU 9000

+
이 예제에서는 노드 4에 클러스터 포트 "e1b"를 추가합니다.

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. 클러스터 LIF를 각 LIF에 대해 한 번씩 새 포트로 마이그레이션합니다.
+
'network interface migrate-vserver cluster-lif_lif_name_-source-node_node3_-destination-node_node3_-destination-port_port_name_'

.. 클러스터 LIF의 홈 포트를 수정합니다.
+
'network interface modify -vserver cluster -lif_lif_name_ – home-port_port_name_'

.. 클러스터 브로드캐스트 도메인에서 이전 포트를 제거합니다.
+
네트워크 포트 브로드캐스트 도메인 제거 포트

+
다음 명령을 실행하면 노드 3에서 포트 "e0d"가 제거됩니다.

+
'네트워크 포트 브로드캐스트-도메인 제거-포트-IPSpace 클러스터-브로드캐스트-도메인 클러스터-포트 노드3:e0d'

.. 노드 3이 쿼럼에 다시 연결되었는지 확인합니다.
+
클러스터 show-node node3-fields 상태



. [[auto_map_3_step5]] 클러스터 LIF 및 노드 관리/클러스터 관리 LIF를 호스팅하는 브로드캐스트 도메인을 조정합니다. 각 브로드캐스트 도메인에 올바른 포트가 포함되어 있는지 확인합니다. LIF가 호스팅 중이거나 LIF의 홈 역할을 하는 브로드캐스트 도메인 간에 포트를 이동할 수 없으므로 다음과 같이 LIF를 마이그레이션 및 수정해야 할 수 있습니다.
+
.. LIF의 홈 포트를 표시합니다.
+
네트워크 인터페이스 보기 필드, 홈 노드, 홈 포트

.. 이 포트가 포함된 브로드캐스트 도메인을 표시합니다.
+
'network port broadcast-domain show-ports_node_name:port_name_'

.. 브로드캐스트 도메인에서 포트 추가 또는 제거:
+
네트워크 포트 브로드캐스트 도메인 추가 포트

+
네트워크 포트 브로드캐스트 도메인 제거 포트

.. LIF의 홈 포트 수정:
+
'network interface modify -vserver vserver -lif_lif_name_ – home-port_port_name_'



. 에 나와 있는 것과 동일한 명령을 사용하여 인터클러스터 LIF에 사용되는 네트워크 포트의 브로드캐스트 도메인 구성원을 조정합니다 <<auto_map_3_step5,5단계>>.
. 필요한 경우 에 나와 있는 것과 동일한 명령을 사용하여 다른 브로드캐스트 도메인을 조정하고 데이터 LIF를 마이그레이션합니다 <<auto_map_3_step5,5단계>>.
. 노드 1에 노드 3에 더 이상 존재하지 않는 포트가 있는 경우 다음 단계에 따라 포트를 삭제합니다.
+
.. 다음 두 노드 중 하나에서 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

.. 포트 삭제하기:
+
'network port delete-node_node_name_-port_port_name_

.. 관리자 수준으로 돌아가기:
+
'Set-Privilege admin'입니다



. 모든 LIF 페일오버 그룹을 조정합니다.
+
'network interface modify-failover-group_failover_group_-failover-policy_failover_policy_'

+
다음 명령은 페일오버 정책을 'broadcast-domain-wide'로 설정하고 노드 3의 LIF "data1"에 대한 페일오버 타겟으로 페일오버 그룹 "fg1"의 포트를 사용합니다.

+
'network interface modify -vserver node3-lif data1 failover-policy broadcast-domainwide-failover-group fg1'

+
을 참조하십시오 link:other_references.html["참조"] 자세한 내용은 _네트워크 관리_ 또는 _ONTAP 9 명령: 수동 페이지 참조_에 연결하십시오.

. 노드 3의 변경 사항을 확인합니다.
+
네트워크 포트 show-node node3

. 각 클러스터 LIF는 포트 7700에서 수신 대기 중이어야 합니다. 클러스터 LIF가 포트 7700에서 수신 중인지 확인합니다.
+
'::> 네트워크 연결 수신 표시 - vserver 클러스터'

+
클러스터 포트에서 수신 대기하는 포트 7700은 2노드 클러스터의 다음 예에 표시된 대로 예상되는 결과입니다.

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 필요한 경우 포트 7700에서 청취하지 않는 각 클러스터 LIF에 대해 LIF의 관리 상태를 '소유'로 설정한 다음 '설정'으로 설정합니다.
+
'::> net int modify -vserver Cluster-lif <cluster-lif> -status-admin down;net int modify -vserver Cluster-lif <cluster-lif> -status-admin up'

+
11단계를 반복하여 클러스터 LIF가 포트 7700에서 수신 대기 중인지 확인합니다.


