---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: '"시스템 컨트롤러 교체" 명령을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드할 때 노드 3의 NAS 데이터 LIF를 노드 3에서 노드 4로 이동합니다.' 
---
= 노드 2가 소유한 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 3에서 노드 4로 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 4의 설치를 확인하고 노드 3에서 노드 4로 애그리게이트를 재배치하려면, 현재 노드 3에 있는 노드 2에 속하는 NAS 데이터 LIF를 노드 3에서 노드 4로 이동해야 합니다. 또한 노드 4에 SAN LIF가 존재하는지 확인해야 합니다.

원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 4를 온라인으로 설정한 후 LIF가 정상 작동하는지 확인합니다.

.단계
. 재배치 작업 재개:
+
시스템 컨트롤러 교체 재개

+
시스템은 다음 작업을 수행합니다.

+
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


+
이 단계에서 네트워크 도달 가능성 점검에서 작업이 일시 중지됩니다.

. 네트워크 및 모든 VLAN, 인터페이스 그룹, 브로드캐스트 도메인이 올바르게 구성되었는지 수동으로 확인하십시오.
. 재배치 작업 재개:
+
시스템 컨트롤러 교체 재개

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes assigning network ports to the correct broadcast domains,creating any required ifgrps and VLANs, and modifying the home-port parameter of network interfaces to the appropriate ports.Refer to the "Using aggregate relocation to upgrade controller hardware on a pair of nodes running ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually completed? [y/n]
----
. 계속하려면 y를 입력하십시오.
. 시스템에서 다음 검사를 수행합니다.
+
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


+
이러한 확인을 수행한 후 시스템은 노드 2가 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 4의 새 컨트롤러로 재배치합니다. 리소스 재배치가 완료되면 시스템이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
'시스템 컨트롤러 교체 쇼 디테일

. 루트가 아닌 애그리게이트 및 NAS 데이터 LIF가 노드 4에 성공적으로 재배치되었는지 수동으로 확인하십시오.
+
Aggregate가 재배치되지 않거나 거부되면 Aggregate를 수동으로 재이동하거나 필요한 경우 거부나 대상 검사를 재정의해야 합니다. 섹션을 참조하십시오 link:relocate_failed_or_vetoed_aggr.html["장애가 발생하거나 거부권을 행사한 Aggregate를 재배치합니다"] 를 참조하십시오.

. 다음 하위 단계를 완료하여 SAN LIF가 노드 4의 올바른 포트에 있는지 확인합니다.
+
.. 다음 명령을 입력하고 출력을 검사합니다.
+
'network interface show-data-protocol iscsi | fcp-home-node <node4>'

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
        Logical    Status     Network           Current Current Is
Vserver Interface  Admin/Oper Address/Mask      Node    Port    Home
------- ---------- ---------- ----------------- ------- ------- ---
vs0
        a0a        up/down    10.63.0.53/24     node3   a0a     true
        data1      up/up      10.63.0.50/18     node3   e0c     true
        rads1      up/up      10.63.0.51/18     node3   e1a     true
        rads2      up/down    10.63.0.52/24     node3   e1b     true
vs1
        lif1       up/up      172.17.176.120/24 node3   e0c     true
        lif2       up/up      172.17.176.121/24 node3   e1a     true
----
.. 노드 4에 노드 2에 없는 포트에 있거나 다른 포트에 매핑해야 하는 SAN LIF 그룹이 있는 경우 다음 하위 단계를 완료하여 노드 4의 적절한 포트로 LIF를 이동합니다.
+
... 다음 명령을 입력하여 LIF 상태를 down으로 설정합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> -status -admin down'

... 포트 세트에서 LIF를 제거합니다.
+
' remove-vserver <vserver_name> - 포트셋 <포트셋_이름> -포트-이름 <포트_이름>'

... 다음 명령 중 하나를 입력합니다.
+
**** 다음 명령을 입력하여 단일 LIF를 이동합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <new_home_port>'

**** 다음 명령을 입력하여 존재하지 않거나 잘못된 포트 한 개에 있는 모든 LIF를 새 포트로 이동합니다.
+
'network interface modify {-home-port <port_on_node1>-home-node <node1>-role data} - home-port <new_home_port_on_node3>'

**** 포트 세트에 LIF를 다시 추가합니다.
+
'<add-vserver_name> - 포트셋 <포트셋_이름> -포트-이름 <포트_이름>'

+

NOTE: SAN LIF를 원래 포트와 링크 속도가 동일한 포트로 이동해야 합니다.





.. LIF가 다음 명령을 입력하여 노드에서 트래픽을 허용하고 전송할 수 있도록 모든 LIF의 상태를 "Up"으로 수정합니다.
+
'network interface modify -home-port <port_name> -home-node <node4> -lif data-statusadmin up'을 선택합니다

.. 다음 명령을 입력하고 출력을 검사하여 LIF가 올바른 포트로 이동되었으며, LIF가 두 노드 중 하나에 다음 명령을 입력하고 출력을 검사하여 'UP' 상태인지 확인하십시오.
+
'network interface show-home-node <node4> - role data'

.. LIF가 하나라도 다운되면 각 LIF에 대해 다음 명령을 한 번 입력하여 LIF의 관리 상태를 Up으로 설정합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> -status -admin up'



. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
시스템 컨트롤러 교체 재개

+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검



