---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드하는 절차를 이해합니다 `system controller replace` 명령이 작동합니다.' 
---
= ARL 업그레이드 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ARL을 사용하여 노드를 업그레이드하기 전에 절차가 어떻게 작동하는지 이해해야 합니다. 이 콘텐츠에서는 절차가 여러 단계로 나뉩니다.



== 노드 쌍을 업그레이드합니다

노드 쌍을 업그레이드하려면 원래 노드를 준비한 다음 원래 노드와 새 노드 모두에서 일련의 단계를 수행해야 합니다. 그런 다음 원래 노드를 서비스 해제할 수 있습니다.



== ARL 업그레이드 시퀀스 개요

이 절차를 수행하는 동안, 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 한 번에 하나씩 업그레이드하여 HA 쌍 구성을 활용하여 루트 이외의 애그리게이트에 대한 소유권을 재배치합니다. 모든 비루트 애그리게이트에는 두 개의 재배치가 수행되어 마지막 대상에 도달해야 합니다. 이것이 올바른 업그레이드 노드입니다.

각 집합에는 홈 소유자와 현재 소유자가 있습니다. 홈 소유자는 애그리게이트의 실제 소유자이며 현재 소유자는 임시 소유자입니다.

다음 표에서는 각 단계에서 수행하는 상위 수준의 작업과 단계 종료 시 총 소유권의 상태를 설명합니다. 자세한 단계는 절차의 뒷부분에서 제공됩니다.

[cols="25,75"]
|===
| 단계 | 단계 


| link:stage_1_index.html["1단계. 업그레이드를 준비합니다"]  a| 
1단계에서 사전 점검을 실행하고 필요한 경우 애그리게이트 소유권을 수정합니다. Onboard Key Manager를 사용하여 스토리지 암호화를 관리하는 경우 SnapMirror 관계를 중지하도록 선택할 수 있는 경우 특정 정보를 기록해야 합니다.

1단계 종료 시 소유권 집계:

* 노드 1은 노드 1 애그리게이트의 홈 소유자이며 현재 소유입니다.
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다.




| link:stage_2_index.html["2단계. 노드1을 재배치하거나 폐기합니다"]  a| 
2단계에서는 노드 1이 아닌 Aggregate 및 NAS 데이터 LIF를 노드 2로 이동합니다. 이 프로세스는 대부분 자동화되어 있으며 사용자가 상태를 확인할 수 있도록 작업이 일시 중지됩니다. 작업을 수동으로 재개해야 합니다. 필요한 경우 장애가 발생한 애그리게이트를 재이동하거나 거부권을 행사합니다. 나중에 사용할 수 있도록 필요한 노드1 정보를 기록한 다음 노드1을 폐기해야 합니다. 나중에 프로시저에서 netboot node3 및 node4를 준비할 수도 있습니다.

2단계 종료 시 소유권 집계:

* 노드 2는 노드 1 애그리게이트의 현재 소유자입니다.
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다.




| link:stage_3_index.html["3단계. 노드3을 설치하고 부팅합니다"]  a| 
3단계에서는 노드3를 설치 및 부팅하고, 노드1에서 노드3로 클러스터 및 노드 관리 포트를 매핑하고, 노드1 디스크를 노드3에 재할당하고, 노드3 설치를 확인합니다. 필요한 경우 노드 3에 FC 또는 UTA/UTA2 구성을 설정하고 노드 3이 쿼럼에 가입했는지 확인합니다. 또한 노드1 NAS 데이터 LIF 및 루트 이외의 애그리게이트를 노드 2에서 노드 3으로 재배치하고 노드 3에 SAN LIF가 있는지 확인합니다.

3단계 종료 시 소유권 집계:

* Node3는 노드 1 애그리게이트의 홈 소유자이며 현재 소유자입니다.
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다.




| link:stage_4_index.html["4단계. 노드 2를 재배치하거나 폐기합니다"]  a| 
4단계에서는 노드 2 루트 이외의 애그리게이트 및 SAN이 아닌 데이터 LIF를 노드 3으로 이동합니다. 또한 필요한 노드2 정보를 기록한 다음 노드2를 폐기합니다.

4단계 종료 시 소유권 집계:

* Node3는 노드 1에 원래 속해 있는 애그리게이트의 홈 소유자 및 현재 소유자입니다.
* 노드 2는 노드 2 애그리게이트의 홈 소유자입니다.
* Node3는 노드 2 애그리게이트의 현재 소유자입니다.




| link:stage_5_index.html["5단계. 노드 4를 설치하고 부팅합니다"]  a| 
단계 5에서는 node4를 설치 및 부팅하고, 클러스터 및 노드 관리 포트를 node2에서 node4로 매핑하고, node2 디스크를 node4에 재할당하고, node4 설치를 확인합니다. 필요한 경우 노드 4에 FC 또는 UTA/UTA2 구성을 설정하고 노드 4가 쿼럼에 가입했는지 확인합니다. 또한 노드2 NAS 데이터 LIF 및 루트 이외의 애그리게이트를 노드 3에서 노드 4로 재배치하고 노드 4에 SAN LIF가 있는지 확인합니다.

5단계 종료 시 소유권 집계:

* Node3는 노드 1에 원래 속해 있는 애그리게이트의 홈 소유자 및 현재 소유자입니다.
* Node4는 노드 2에 원래 속해 있는 애그리게이트의 홈 소유자이며 현재 소유자입니다.




| link:stage_6_index.html["6단계. 업그레이드를 완료합니다"]  a| 
6단계 동안 새 노드가 올바르게 설정되었는지 확인하고, 새 노드가 암호화를 사용하도록 설정된 경우 스토리지 암호화 또는 NetApp 볼륨 암호화를 구성하고 설정합니다. 또한 이전 노드의 사용을 중지하고 SnapMirror 작업을 다시 시작해야 합니다.

|===