---
sidebar: sidebar 
permalink: upgrade-arl-auto/reassign-node2-disks-to-node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 업그레이드할 때 노드 4 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성하십시오 `system controller replace` 명령.' 
---
= 노드2 디스크를 노드4에 재할당합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
node4 설치를 확인하기 전에 node2에 속한 디스크를 node4에 재할당해야 합니다.

.단계
. [[reassign-node2-node4-step1]]node2가 부팅 메뉴에서 중지되었는지 확인하고 node2의 디스크를 node4에 다시 할당합니다.
+
`boot_after_controller_replacement`

+
잠시 후에 교체되는 노드의 이름을 입력하라는 메시지가 표시됩니다. 공유 디스크(ADP(고급 디스크 파티셔닝) 또는 분할된 디스크라고도 함)가 있는 경우 HA 파트너의 노드 이름을 입력하라는 메시지가 표시됩니다.

+
이러한 프롬프트는 콘솔 메시지에 묻힐 수 있습니다. 노드 이름을 입력하지 않거나 잘못된 이름을 입력하면 이름을 다시 입력하라는 메시지가 표시됩니다.

+
.콘솔 출력 예를 확장합니다
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----
====
. 시스템이 다음 메시지와 함께 재부팅 루프에 빠지면 `no disks found` 이는 포트를 대상 모드로 재설정했기 때문에 디스크를 볼 수 없기 때문입니다.  공연하다<<auto_check_4_step3,3단계>> ~을 통해<<auto_check_4_step8,8단계>> 이 문제를 해결하려면 node4로 이동하세요.
. [[auto_check_4_step3]] 자동 부팅 중에 Ctrl-C를 눌러 LOADER > 프롬프트에서 노드를 중지합니다.
. LOADER 프롬프트에서 유지보수 모드로 전환합니다.
+
`boot_ontap maint`

. 유지보수 모드에서 현재 타겟 모드에 있는 이전에 설정된 이니시에이터 포트를 모두 표시합니다.
+
`ucadmin show`

+
포트를 다시 이니시에이터 모드로 변경합니다.

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. 포트가 이니시에이터 모드로 변경되었는지 확인합니다.
+
`ucadmin show`

. 유지보수 모드 종료:
+
`halt`

+
[NOTE]
====
외부 디스크를 지원하는 시스템에서 외부 디스크도 지원하는 시스템으로 업그레이드하려면 로 이동하십시오<<auto_check_4_step8,8단계>>.

외부 디스크를 사용하는 시스템에서 내부 및 외부 디스크(예: AFF A800 시스템<<auto_check_4_step9,9단계>>)를 모두 지원하는 시스템으로 업그레이드하려면 로 이동하십시오.

====
. [[auto_check_4_step8]] LOADER 프롬프트에서 부팅합니다.
+
`boot_ontap menu`

+
이제 부팅 시 노드에서 이전에 할당되었으며 예상대로 부팅할 수 있는 모든 디스크를 감지할 수 있습니다.

+
교체할 클러스터 노드가 루트 볼륨 암호화를 사용하면 ONTAP가 디스크에서 볼륨 정보를 읽을 수 없습니다. 루트 볼륨에 대한 키를 복구합니다.

+
.. 특수 부팅 메뉴로 돌아갑니다.
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Onboard Key Manager 복구 비밀 설정 * 을 선택합니다
.. 를 입력합니다 `y` 다음 프롬프트에서 다음을 수행합니다.
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 프롬프트에서 키 관리자 암호를 입력합니다.
.. 메시지가 표시되면 백업 데이터를 입력합니다.
+

NOTE: 에서 암호 및 백업 데이터를 가져야만 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 섹션을 참조하십시오.

.. 시스템이 특수 부팅 메뉴로 다시 부팅된 후 옵션 * (1) Normal Boot * 를 실행합니다
+

NOTE: 이 단계에서 오류가 발생할 수 있습니다. 오류가 발생하면 의 하위 단계를 반복합니다 <<auto_check_4_step22,22단계>> 시스템이 정상적으로 부팅될 때까지 기다립니다.



. [[auto_check_4_step9]]외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node2 집계를 루트 집계로 설정하여 node4가 node2의 루트 집계에서 부팅되는지 확인합니다.  루트 집계를 설정하려면 node4의 부팅 메뉴로 이동하여 옵션을 선택하세요. `5` 유지 관리 모드로 들어가려면.
+

WARNING: * 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다. *

+
다음 절차에서는 노드 4가 노드 2의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 유지보수 모드로 전환:
+
`boot_ontap maint`

.. 노드 2 애그리게이트의 RAID, plex 및 체크섬 정보를 확인합니다.
+
`aggr status -r`

.. 노드 2 애그리게이트의 상태를 확인합니다.
+
`aggr status`

.. 필요한 경우 node2 애그리게이트를 온라인 상태로 전환합니다.
+
`aggr_online root_aggr_from___node2__`

.. 노드 4가 원래 루트 애그리게이트로부터 부팅하지 않도록 합니다.
+
`aggr offline _root_aggr_on_node4_`

.. 노드 2의 루트 애그리게이트를 노드 4의 새 루트 애그리게이트로 설정합니다.
+
`aggr options aggr_from___node2__ root`




