---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html 
keywords: node4, interface group, VLANs, broadcast domains, re-create 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 업그레이드할 때 node4에서 node2의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 만듭니다 `system controller replace` 명령.' 
---
= 노드 4에서 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 4가 쿼럼에 있고 노드 3과 통신할 수 있는지 확인한 후 노드 4에서 노드 2의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 만들어야 합니다. 노드3 포트도 새로 다시 생성된 브로드캐스트 도메인에 추가해야 합니다.

.이 작업에 대해
VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 를 참조하십시오 link:other_references.html["참조"] 네트워크 관리 _ 에 대한 링크를 제공합니다.

.단계
. 에 기록된 노드 2 정보를 사용하여 노드 4에 VLAN을 다시 생성합니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port vlan create -node _node4_ -vlan _vlan-names_`

. 에 기록된 node2 정보를 사용하여 node4에 인터페이스 그룹을 다시 만듭니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port ifgrp create -node _node4_ -ifgrp _port_ifgrp_names_-distr-func`

. 에 기록된 node2 정보를 사용하여 node4에 브로드캐스트 도메인을 다시 만듭니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names_ -mtu _mtu_size_ -ports _node_name:port_name,node_name:port_name_`

. 새로 다시 생성된 브로드캐스트 도메인에 노드 4 포트를 추가합니다.
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_names_ -ports _node_name:port_name,node_name:port_name_`


