---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드할 때 node2의 비루트 애그리게이트를 노드 3으로 재배치합니다 `system controller replace` 명령.' 
---
= 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2를 노드 4로 바꾸기 전에 노드 2가 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 3으로 재배치합니다.

.시작하기 전에
이전 단계의 사후 검사가 완료되면 노드 2의 리소스 해제가 자동으로 시작됩니다. 루트가 아닌 애그리게이트 및 non-SAN 데이터 LIF는 노드 2에서 노드 3으로 마이그레이션됩니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다.

Aggregate 및 LIF가 마이그레이션되면 검증 목적으로 작업이 일시 중지됩니다. 이 단계에서는 모든 비루트 애그리게이트 및 비 SAN 데이터 LIF가 노드 3으로 마이그레이션되는지 여부를 확인해야 합니다.


NOTE: Aggregate 및 LIF의 홈 소유자는 수정되지 않으며 현재 소유자만 수정됩니다.

.단계
. 루트가 아닌 모든 애그리게이트가 온라인 상태이고 노드 3의 상태가 온라인인지 확인합니다.
+
`storage aggregate show -node _node3_ -state online -root false`

+
다음 예제에서는 노드 2의 루트 이외의 애그리게이트가 온라인 상태인 것을 보여 줍니다.

+
....
cluster::> storage aggregate show -node node3 state online -root false

Aggregate      Size         Available   Used%   State   #Vols  Nodes  RAID     Status
----------     ---------    ---------   ------  -----   -----  ------ -------  ------
aggr_1         744.9GB      744.8GB      0%     online  5      node2  raid_dp  normal
aggr_2         825.0GB      825.0GB      0%     online  1      node2  raid_dp  normal
2 entries were displayed.
....
+
노드 3에서 애그리게이트가 오프라인 상태가 되거나 노드 3에서 외부 상태가 된 경우, 각 애그리게이트에 대해 노드 3의 다음 명령을 사용하여 애그리게이트를 온라인 상태로 전환합니다.

+
`storage aggregate online -aggregate _aggr_name_`

. 노드 3에서 다음 명령을 사용하고 출력을 검사하여 노드 3에서 모든 볼륨이 온라인 상태인지 확인합니다.
+
`volume show -node _node3_ -state offline`

+
노드 3에서 오프라인 상태인 볼륨이 있는 경우 각 볼륨에 대해 한 번씩 노드 3에서 다음 명령을 사용하여 온라인으로 전환합니다.

+
`volume online -vserver _vserver_name_ -volume _volume_name_`

+
를 클릭합니다 `_vserver_name_` 이 명령과 함께 사용하려면 이전 의 출력에서 찾을 수 있습니다 `volume show` 명령.

. LIF가 올바른 포트로 이동되었으며 상태가 인지 확인합니다 `up`. LIF가 하나라도 다운되면 LIF의 관리 상태를 로 설정합니다 `up` 다음 명령을 각 LIF에 대해 한 번 입력합니다.
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node_name_ -status-admin up`

. 현재 데이터 LIF를 호스팅하는 포트가 새 하드웨어에 없으면 브로드캐스트 도메인에서 제거합니다.
+
`network port broadcast-domain remove-ports`



. [[step5]] 다음 명령을 입력하고 출력을 확인하여 노드 2에 남아 있는 데이터 LIF가 없는지 확인합니다.
+
`network interface show -curr-node _node2_ -role data`

. 인터페이스 그룹 또는 VLAN이 구성되어 있는 경우 다음 하위 단계를 완료합니다.
+
.. 노드 3이 부팅된 후 노드 3에서 VLAN 및 인터페이스 그룹을 다시 생성할 수 있도록 VLAN 및 인터페이스 그룹 정보를 기록합니다.
.. 인터페이스 그룹에서 VLAN을 제거합니다.
+
`network port vlan delete -node _nodename_ -port _ifgrp_ -vlan-id _VLAN_ID_`

.. 다음 명령어를 입력하여 해당 노드에 interface group이 구성되어 있는지 확인한다.
+
`network port ifgrp show -node _node2_ -ifgrp _ifgrp_name_ -instance`

+
다음 예에서와 같이 노드에 대한 인터페이스 그룹 정보가 표시됩니다.

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node3
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. 노드에 인터페이스 그룹이 구성되어 있는 경우 해당 그룹 및 그룹에 할당된 포트의 이름을 기록한 다음 각 포트에 대해 다음 명령을 한 번 입력하여 포트를 삭제합니다.
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




