---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: '"시스템 컨트롤러 교체" 명령을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 9.7로 업그레이드할 때 노드 4 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성하십시오.' 
---
= 노드 4에 FC 또는 UTA/UTA2 구성을 설정합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 4에 온보드 FC 포트, 온보드 UTA/UTA2(Unified Target Adapter) 포트 또는 UTA/UTA2 카드가 있는 경우, 나머지 절차를 완료하기 전에 설정을 구성해야 합니다.

를 완료해야 할 수도 있습니다 <<Configure FC ports on node4>> 섹션, 을 참조하십시오 <<Check and configure UTA/UTA2 ports on node4>>또는 두 섹션을 모두 선택합니다.


NOTE: 노드 4에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 없는 경우 스토리지 디스크를 사용하여 시스템을 업그레이드하는 경우 로 건너뛸 수 있습니다 link:map_ports_node2_node4.html["노드 2의 포트를 노드 4로 매핑합니다"] 섹션을 참조하십시오. 하지만 V 시리즈 시스템이 있거나 FlexArray 가상화 소프트웨어가 있고 스토리지 어레이에 연결되어 있는 경우, 노드 4에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 없는 경우 _ Install and boot node4_ 섹션으로 돌아가서 를 다시 시작해야 합니다 link:install_boot_node4.html#step22["22단계"]. 노드 4에 충분한 랙 공간이 있는지 확인합니다. 노드 4가 노드 2와 다른 섀시에 있는 경우 노드 4를 노드 3과 같은 위치에 배치할 수 있습니다. 노드 2와 노드 4가 동일한 섀시에 있는 경우 노드 4는 이미 해당 랙 위치에 있습니다.

.선택
* <<Configure FC ports on node4>>
* <<Check and configure UTA/UTA2 ports on node4>>




== 노드 4에서 FC 포트를 구성합니다

노드 4에 온보드 또는 FC 어댑터가 있는 FC 포트가 있는 경우 포트가 사전 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다. 포트가 구성되지 않은 경우 서비스가 중단될 수 있습니다.

섹션에 저장한 노드 2의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 어댑터가 있는 경우, 에서 포트를 구성합니다 <<Check and configure UTA/UTA2 ports on node4>>.

* 중요 *: 시스템에 스토리지 디스크가 있는 경우 이 섹션의 명령을 클러스터 프롬프트에 입력해야 합니다. V-Series 시스템이나 FlexArray 가상화 소프트웨어가 설치된 시스템이 스토리지 어레이에 연결되어 있는 경우, 유지보수 모드의 이 섹션에 명령을 입력하십시오.

.단계
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다 | '시스템 노드 하드웨어 통합 접속 쇼 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'ucadmin 쇼' 
|===
+
시스템에 있는 모든 FC 및 통합 네트워크 어댑터에 대한 정보가 표시됩니다.

. 노드 4의 FC 설정을 노드 1에서 앞서 캡처한 설정과 비교합니다.
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
필요에 따라 노드 4의 FC 포트를 수정합니다.

** 타겟 포트를 프로그래밍하려면
+
'ucadmin modify -m fc -t target <adapter>'을 선택합니다

** 이니시에이터 포트를 프로그래밍하려면:
+
'ucadmin modify -m fc -t initiator <adapter>'를 선택합니다



'-t'는 FC4 유형이며 타겟이나 이니시에이터입니다.



| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 필요에 따라 노드 4의 FC 포트를 수정합니다. 'ucadmin modify -m fc -t initiator -f <adapter_port_name>' -t'는 FC4 유형, 타겟 또는 이니시에이터입니다. * 참고 *: FC 포트는 이니시에이터로 프로그래밍해야 합니다. 
|===
. 유지 관리 모드 종료:
+
"중지"

. 로더 프롬프트에서 시스템을 부팅합니다.
+
boot_ontap 메뉴

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 유지보수 모드의 부팅 메뉴에서 옵션 '5'를 선택합니다.


. [[step8]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
** 이 섹션을 건너뛰고 로 이동합니다 link:map_ports_node2_node4.html["노드 2의 포트를 노드 4로 매핑합니다"] 노드 4에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우




| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다  a| 
** 로 이동합니다 link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["노드 4의 UTA/UTA2 포트를 확인하고 구성합니다"] 노드 4에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우
** node4에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우 section_Check 및 UTA/UTA2 포트를 구성하고, node4에서 다시 시작하려면 _Install and boot node4_섹션으로 돌아가서 UTA/UTA2 포트를 구성하십시오 link:install_boot_node4.html#step23["23단계"].


|===




== 노드 4의 UTA/UTA2 포트를 확인하고 구성합니다

노드 4에 온보드 UTA/UTA2 포트 또는 UTA/UTA2A 카드가 있는 경우 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 포트를 구성해야 합니다.

UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2A 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드를 사용하면 동시 NIC 및 FCoE 트래픽이 동일한 10GbE SFP+ 인터페이스를 공유하고 FC 타겟을 지원할 수 있습니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

UTA/UTA2 포트는 다음 구성을 사용하여 어댑터 또는 컨트롤러에 있을 수 있습니다.

* UTA/UTA2 카드를 컨트롤러와 동시에 주문했으며 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.


하지만 노드 4의 UTA/UTA2 포트 구성을 확인하고 필요한 경우 이를 변경해야 합니다.


WARNING: * 주의 *: 시스템에 스토리지 디스크가 있는 경우, 유지보수 모드로 들어가라는 지시가 없는 한 클러스터 프롬프트에서 이 섹션에 있는 명령을 입력합니다. 스토리지 어레이에 연결된 MetroCluster FC 시스템, V-Series 시스템 또는 FlexArray 가상화 소프트웨어가 설치된 시스템에서 UTA/UTA2 포트를 구성하려면 유지 관리 모드에 있어야 합니다.

.단계
. 노드 4에서 다음 명령 중 하나를 사용하여 포트가 현재 어떻게 구성되어 있는지 확인합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | '시스템 노드 하드웨어 통합 접속 쇼 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'ucadmin 쇼' 
|===
+
다음 예와 유사한 출력이 표시됩니다.

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 현재 SFP+ 모듈이 원하는 용과 일치하지 않는 경우 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. ucadmin show 명령의 출력을 확인하여 UTA/UTA2 포트가 원하는 특성을 갖고 있는지 확인합니다.
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| CNA 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 이동합니다 <<auto_check_4_step5,5단계>>. 


| 원하는 개성을 갖고 싶어하세요 | 단계 5에서 단계 12까지 건너뛰고 로 이동합니다 <<auto_check_4_step13,13단계>>. 
|===
. [[auto_check_4_step5] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 이동합니다 <<auto_check_4_step7,7단계>> 


| 온보드 UTA/UTA2 포트 | 7단계를 건너뛰고 로 이동합니다 <<auto_check_4_step8,8단계>>. 
|===
. 어댑터가 이니시에이터 모드에 있고 UTA/UTA2 포트가 온라인 상태인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
'스토리지 비활성화 어댑터 <adapter_name>'

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check_4_step7]] 현재 구성이 원하는 용과 일치하지 않으면 필요에 따라 구성을 변경합니다.
+
''ucadmin modify -m fc|CNA-t initiator|target<adapter_name>'

+
** M은 성격 모드, FC 또는 10GbE UTA입니다.
** t는 FC4형, target 또는 initiator입니다.
+

NOTE: 테이프 드라이브, FlexArray 가상화 시스템 및 MetroCluster 구성에 FC Initiator를 사용해야 합니다. SAN 클라이언트에 FC 타겟을 사용해야 합니다.



. [[auto_check_4_step8]] 다음 명령을 사용하여 설정을 확인하고 출력을 확인합니다.
+
'ucadmin 쇼'

. 설정을 확인합니다.
+
[cols="40,60"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 'ucadmin 쇼' 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'ucadmin 쇼' 
|===
+
다음 예제의 출력은 어댑터 "1b"의 FC4 유형이 "이니시에이터"로 변경되고 어댑터 "2a"와 "2b"의 모드가 "CNA"로 변경되었음을 보여줍니다.

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 각 포트에 대해 다음 명령 중 하나를 입력하여 타겟 포트를 온라인으로 전환합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 'network fcp adapter modify -node <node_name> - adapter <adapter_name> - state up' 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'fcp config <adapter_name> up' 
|===
. 포트에 케이블을 연결합니다.


. [[12단계]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 섹션으로 이동합니다 link:map_ports_node2_node4.html["노드 2의 포트를 노드 4로 매핑합니다"]. 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | install and boot node4_ 섹션으로 돌아가서 에서 다시 시작합니다 link:install_boot_node4.html#step23["23단계"]. 
|===
. [[auto_check_4_step13] 유지보수 모드 종료:
+
"중지"

. [[step14]] 부트 메뉴의 부트 노드:
+
boot_ontap 메뉴

+
A800으로 업그레이드할 경우 으로 이동하십시오 <<auto_check_4_step23,23단계>>.

. [[auto_check_4_step15]]노드 4에서 부팅 메뉴로 이동한 다음, 22/7을 사용하여 숨겨진 옵션 "boot_after_controller_replacement"를 선택합니다. 다음 예제와 같이 프롬프트에서 node2를 입력하여 node4에 노드 2의 디스크를 재할당합니다.
+
[listing]
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
.
.
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----
. 디스크를 찾을 수 없다는 메시지와 함께 시스템이 재부팅 루프에 들어갈 경우, 이는 포트가 타겟 모드로 다시 재설정되었기 때문에 디스크를 볼 수 없기 때문입니다. 를 계속 진행합니다 <<auto_check_4_step17,17단계>> 부터 까지 <<auto_check_4_step22,22단계>> 를 눌러 이 문제를 해결합니다.
. [[auto_check_4_step17]([auto_check_4_step17]) 자동 부팅 중에 'Ctrl-C'를 눌러 LOADER>(로더) 프롬프트에서 노드를 중지합니다.
. 로더 프롬프트에서 유지보수 모드로 전환합니다.
+
boot_ONTAP maint를 선택합니다

. 유지보수 모드에서 현재 타겟 모드에 있는 이전에 설정된 이니시에이터 포트를 모두 표시합니다.
+
'ucadmin 쇼'

+
포트를 다시 이니시에이터 모드로 변경합니다.

+
'ucadmin modify -m fc -t initiator -f <adapter name>'

. 포트가 이니시에이터 모드로 변경되었는지 확인합니다.
+
'ucadmin 쇼'

. 유지보수 모드 종료:
+
"중지"

. [[auto_check_4_step22]] 로더 프롬프트 부팅 시:
+
부트 ONTAP

+
이제 부팅 시 노드에서 이전에 할당되었으며 예상대로 부팅할 수 있는 모든 디스크를 감지할 수 있습니다.



. [[auto_check_4_step23] 외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node2 애그리게이트를 루트 애그리게이트로 설정하여 node4가 node2의 루트 애그리게이트에서 부팅되도록 하십시오. 루트 애그리게이트를 설정하려면 부팅 메뉴로 이동하여 옵션 '5'를 선택하여 유지보수 모드로 전환하십시오.
+

WARNING: * 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다. *

+
다음 절차에서는 노드 4가 노드 2의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 유지보수 모드로 전환:
+
boot_ONTAP maint를 선택합니다

.. 노드 2 애그리게이트의 RAID, plex 및 체크섬 정보를 확인합니다.
+
'gagr status-r'입니다

.. 노드 2 애그리게이트의 상태를 확인합니다.
+
'기정 상태'입니다

.. 필요한 경우 node2 애그리게이트를 온라인 상태로 전환합니다.
+
'aggr_online root_aggr_from_<node2>'

.. 노드 4가 원래 루트 애그리게이트로부터 부팅하지 않도록 합니다.
+
'<root_aggr_on_node4> 오프라인 집계'

.. 노드 2의 루트 애그리게이트를 노드 4의 새 루트 애그리게이트로 설정합니다.
+
'aggr options aggr_from_<node2> root'




