---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports, FlexArray Virtualization 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 업그레이드할 때 노드 3 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성하십시오 `system controller replace` 명령.' 
---
= 노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 3에 온보드 FC 포트, 온보드 UTA/UTA2(Unified Target Adapter) 포트 또는 UTA/UTA2 카드가 있는 경우, 나머지 절차를 완료하기 전에 설정을 구성해야 합니다.

.이 작업에 대해
이 섹션을 완료해야 할 수 있습니다 <<노드 3에서 FC 포트를 구성합니다>>섹션을 참조하십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>또는 두 섹션을 모두 선택합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 라는 용어를 사용하여 통합 네트워크 어댑터(CNA) 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

* 노드3에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 없는 경우 스토리지 디스크로 시스템을 업그레이드하려면 으로 건너뛸 수 있습니다.link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3에 재할당합니다"]
* 하지만 V-Series 시스템 또는 스토리지 어레이가 포함된 FlexArray 가상화 소프트웨어 시스템이 있고 노드3에 온보드 FC 포트, 온보드 UTA/UTA 포트 또는 UTA/UTA2 카드가 없는 경우 _ 설치 및 부팅 노드3_로 돌아가서 에서 재개할 수 있습니다.link:install_boot_node3.html#auto_install3_step23["23단계"]




== 노드 3에서 FC 포트를 구성합니다

노드 3에 온보드 또는 FC 어댑터의 FC 포트가 있는 경우 포트가 사전 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다. 포트가 구성되지 않은 경우 서비스가 중단될 수 있습니다.

.시작하기 전에
섹션에 저장한 노드 1의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 있는 경우, 에서 포트를 구성합니다 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 시스템에 스토리지 디스크가 있는 경우 이 섹션의 명령을 클러스터 프롬프트에 입력합니다. 'V-Series 시스템'이 있거나 FlexArray 가상화 소프트웨어가 설치되어 있고 스토리지 어레이에 연결되어 있는 경우, 유지보수 모드에서 이 섹션의 명령을 입력하십시오.

. [[step1]]노드 3의 FC 설정을 노드 1에서 이전에 캡처한 설정과 비교합니다.
. [[step2]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
유지보수 모드(부팅 메뉴의 옵션 5)에서 필요에 따라 노드 3의 FC 포트를 수정합니다.

** 타겟 포트를 프로그래밍하려면


`ucadmin modify -m fc -t target _adapter_`

** 이니시에이터 포트를 프로그래밍하려면:


`ucadmin modify -m fc -t initiator _adapter_`

`-t` FC4 유형: 타겟 또는 이니시에이터입니다.



| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다  a| 
유지보수 모드(부팅 메뉴의 옵션 5)에서 필요에 따라 노드 3의 FC 포트를 수정합니다.

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` FC4 유형, 타겟 또는 이니시에이터입니다.


NOTE: FC 포트는 이니시에이터로 프로그래밍해야 합니다.

|===
. [[step3]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다 | 다음 명령을 사용하여 출력을 검사하여 새 설정을 확인합니다.
`ucadmin show` 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 다음 명령을 사용하여 출력을 검사하여 새 설정을 확인합니다.
`ucadmin show` 
|===
. [[4단계]] 유지보수 모드 종료:
+
`halt`

. LOADER 프롬프트에서 시스템을 부팅합니다.
+
`boot_ontap menu`

. [[step6]] 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다립니다.
. 옵션을 선택합니다 `5` 를 참조하십시오.


. 다음 작업 중 하나를 수행합니다.
+
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우 로 이동하십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우 를 건너뛰고 로 이동합니다.<<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3에 재할당합니다"]




| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다  a| 
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우 로 이동하십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.
** 노드3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우, 건너 뛰고 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>_Install 및 부팅 node3_로 돌아가 에서 재시작 하십시오.link:install_boot_node3.html#auto_install3_step23["23단계"]


|===




== 노드 3의 UTA/UTA2 포트를 확인하고 구성합니다

노드 3에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드를 사용하는 경우, 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 필요에 따라 포트를 다시 구성해야 합니다.

.시작하기 전에
UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

.이 작업에 대해
FC에 UTA/UTA2(Unified Target Adapter) 포트를 사용하려면 먼저 포트 구성 방법을 확인해야 합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

를 사용할 수 있습니다 `ucadmin show` 현재 포트 구성을 확인하는 명령:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드는 동일한 10GbE SFP+ 인터페이스를 공유하는 NIC 및 FCoE 트래픽을 동시에 허용할 수 있으며 FC 타겟을 지원합니다.

UTA/UTA2 포트는 어댑터 또는 컨트롤러에서 찾을 수 있으며 다음과 같은 구성을 가지고 있지만 노드 3의 UTA/UTA2 포트 구성을 확인하고 필요에 따라 변경해야 합니다.

* 컨트롤러를 주문할 때 주문한 UTA/UTA2 카드는 사용자가 요청하는 Personality를 요청하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 배송 전에 사용자가 요청하는 Personality를 사용하도록 구성되었습니다.
+

WARNING: * 주의 *: 시스템에 스토리지 디스크가 있는 경우, 유지보수 모드로 들어가라는 지시가 없는 한 클러스터 프롬프트에서 이 섹션에 있는 명령을 입력합니다. V-Series 시스템이 있거나 FlexArray 가상화 소프트웨어가 있고 스토리지 어레이에 연결되어 있는 경우, 유지 관리 모드 프롬프트에서 이 섹션에 명령을 입력합니다. UTA/UTA2 포트를 구성하려면 유지보수 모드여야 합니다.



.단계
. [[step1]] 노드 3에서 다음 명령을 입력하여 포트가 현재 어떻게 구성되어 있는지 확인합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 별도의 조치가 필요 없습니다. 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | `ucadmin show` 
|===
+
다음 예와 유사한 출력이 표시됩니다.

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2]] 현재 SFP+ 모듈이 원하는 용과 일치하지 않으면 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. [[step3]]의 출력을 검사합니다 `ucadmin show` UTA/UTA2 포트가 원하는 특성을 가지고 있는지 여부를 확인합니다.
. [[4단계]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| UTA/UTA2 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 이동합니다 <<auto_check3_step5,5단계>>. 


| 원하는 개성을 갖고 싶어하세요 | 단계 5에서 단계 12까지 건너뛰고 로 이동합니다 <<auto_check3_step13,13단계>>. 
|===
. [[auto_check3_step5]]다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 이동합니다 <<auto_check3_step7,7단계>> 


| 온보드 UTA/UTA2 포트 | 7단계를 건너뛰고 로 이동합니다 <<auto_check3_step8,8단계>>. 
|===
. [[step6]] 어댑터가 이니시에이터 모드에 있고 UTA/UTA2 포트가 온라인 상태인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
`storage disable adapter _adapter_name_`

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check3_step7]] 현재 구성이 원하는 용과 일치하지 않으면 필요에 따라 구성을 변경합니다.
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` 성격 모드, `fc` 또는 `cna`.
** `-t` FC4형, `target` 또는 `initiator`.
+

NOTE: 테이프 드라이브, FlexArray 가상화 시스템 및 MetroCluster 구성에 FC Initiator를 사용해야 합니다. SAN 클라이언트에 FC 타겟을 사용해야 합니다.



. [[auto_check3_step8]] 설정을 확인합니다.
+
`ucadmin show`

. [[9단계]] 설정을 확인합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | `ucadmin show` 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | `ucadmin show` 
|===
+
다음 예제의 출력은 FC4 어댑터 "1b"의 유형이 로 변경되었음을 나타냅니다 `initiator` 어댑터 "2a"와 "2b"의 모드가 로 변경됩니다 `cna`:

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[10단계]] 각 포트에 대해 다음 명령 중 하나를 한 번 입력하여 대상 포트를 온라인으로 전환합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | `fcp config _adapter_name_ up` 
|===
. [[step11]] 포트에 케이블을 연결합니다.


. [[auto_check3_step12]]다음 작업 중 하나를 수행합니다.


[cols="35,65"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 로 이동합니다. link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3에 재할당합니다"] 


| V-시리즈 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 에서 _Install 및 boot node3_로 돌아가서 섹션을 다시 시작합니다 link:install_boot_node3.html#auto_install3_step23["23단계"]. 
|===
. [[auto_check3_step13]]유지보수 모드 종료:
+
`halt`

. [[step14]] 를 실행하여 노드를 부팅 메뉴로 부팅합니다. `boot_ontap menu` A800으로 업그레이드하는 경우 로 link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["노드1 디스크를 노드3, 9단계에 재할당합니다"]이동하십시오.

