---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, MetroCluster, stage 6 
summary: '를 사용하여 ARL 업그레이드를 위한 6단계 프로세스 시퀀스 `system controller replace` ONTAP 9.5 - 9.7을 실행하는 컨트롤러의 명령' 
---
= 6단계. 업그레이드를 완료합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
6단계 동안 새 노드가 올바르게 설정되었는지 확인하고, 새 노드가 암호화를 사용하도록 설정된 경우 스토리지 암호화 또는 NetApp 볼륨 암호화를 구성하고 설정합니다. 또한 이전 노드의 사용을 중지하고 SnapMirror 작업을 다시 시작해야 합니다.

.단계
. link:get_ip_address_of_external_kms_for_storage_encryption.html["스토리지 암호화를 위한 외부 키 관리 서버의 IP 주소를 가져옵니다"]
. link:ensure_new_controllers_are_set_up_correctly.html["새 컨트롤러가 올바르게 설정되었는지 확인합니다"]
. link:set_up_storage_encryption_new_module.html["새 컨트롤러 모듈에서 스토리지 암호화를 설정합니다"]
. link:set_up_netapp_volume_encryption_new_module.html["새 컨트롤러 모듈에 NetApp 볼륨 또는 애그리게이트 암호화를 설정합니다"]
. link:decommission_old_system.html["기존 시스템을 폐기합니다"]
. link:resume_snapmirror_operations.html["SnapMirror 작업을 재개합니다"]


.MetroCluster FC 구성의 경우
MetroCluster FC 구성의 경우 가능한 한 빨리 재해 복구/페일오버 사이트 노드를 교체해야 합니다. 컨트롤러 모델이 일치하지 않을 경우 재해 복구 미러링이 오프라인 상태가 될 수 있으므로 MetroCluster 내의 컨트롤러 모델이 일치하지 않을 수 있습니다. 명령을 사용합니다 -`skip-metrocluster-check true` 두 번째 사이트에서 노드를 교체할 때 MetroCluster 확인을 생략하는 옵션입니다.
