---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node3_installation.html 
keywords: install, boot, node3, join quorum 
summary: 노드 3을 설치하고 부팅한 후에는 올바르게 설치되었는지 확인해야 합니다. 
---
= 노드3 설치를 확인합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 3을 설치하고 부팅한 후에는 올바르게 설치되었는지 확인해야 합니다. 노드 3이 쿼럼에 참가할 때까지 기다린 다음 재배치 작업을 다시 시작해야 합니다.

절차의 이 시점에서 노드 3이 쿼럼을 조인할 때 작업이 일시 중지됩니다.

.단계
. 노드 3이 쿼럼에 연결되었는지 확인합니다.
+
클러스터 show-node node3-fields 상태

. 노드 3이 노드 2와 동일한 클러스터의 일부이고 정상 상태인지 확인합니다.
+
'클러스터 쇼'

. 작업 상태를 확인하고 노드 3의 구성 정보가 노드 1과 동일한지 확인합니다.
+
'시스템 컨트롤러 교체 쇼 디테일

+
노드 3의 구성이 다른 경우 나중에 시스템 중단이 발생할 수 있습니다.

. 교체된 컨트롤러가 MetroCluster 구성에 맞게 올바르게 구성되었는지 확인합니다. MetroCluster 구성은 스위치 오버 모드가 아닌 정상 상태여야 합니다. 을 참조하십시오 link:verify_health_of_metrocluster_config.html["MetroCluster 구성의 상태를 확인합니다"].




== 노드 3에서 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 생성합니다

노드 3이 쿼럼에 있고 노드 2와 통신할 수 있는지 확인한 후 노드 3에서 노드 1의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 만들어야 합니다. 노드3 포트도 새로 다시 생성된 브로드캐스트 도메인에 추가해야 합니다.

VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 를 참조하십시오 link:other_references.html["참조"] 네트워크 관리 _ 에 대한 링크를 제공합니다.

.단계
. 에 기록된 노드 1 정보를 사용하여 노드 3에서 VLAN을 다시 생성합니다 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2로 재배치합니다"] 섹션:
+
'network port vlan create-node <node_name>-vlan <vlan-names>'

. 에 기록된 node1 정보를 사용하여 node3에 인터페이스 그룹을 다시 만듭니다 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2로 재배치합니다"] 섹션:
+
'network port ifgrp create-node <node_name>-ifgrp <port_ifgrp_names>-Distr-func'

. 에 기록된 node1 정보를 사용하여 node3에 브로드캐스트 도메인을 다시 만듭니다 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2로 재배치합니다"] 섹션:
+
'network port broadcast-domain create-IPSpace Default-broadcast-domain <broadcast_domain_names> - MTU <mtu_size> - ports <node_name:port_name,node_name:port_name>'

. 새로 다시 생성된 브로드캐스트 도메인에 노드3 포트를 추가합니다.
+
'network port broadcast-domain add-ports-broadcast-domain <broadcast_domain_names> - ports <node_name:port_name,node_name:port_name>'





== 노드 3에서 키 관리자 구성을 복원합니다

NVE(NetApp Volume Encryption)를 사용하여 업그레이드 중인 시스템의 볼륨을 암호화하는 경우 암호화 구성을 새 노드와 동기화해야 합니다. 노드 2에서 노드 3으로 노드 1 애그리게이트에 대한 ARL이 완료되면 암호화된 볼륨이 오프라인 상태로 전환됩니다.

.단계
. Onboard Key Manager의 암호화 구성을 동기화하려면 클러스터 프롬프트에서 다음 명령을 실행합니다.
+
|===
| 이 ONTAP 버전의 경우… | 이 명령 사용... 


| ONTAP 9.6 또는 9.7 | 보안 키 관리자 온보드 동기화 


| ONTAP 9.5 | 보안 키 관리자 설정 노드 <node_name> 
|===
. Onboard Key Manager의 클러스터 전체 암호를 입력합니다.

