---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node4_installation.html 
keywords: verify, node4, installation, MetroCluster, restore, key, manager 
summary: '을 사용하여 ONTAP 9.5를 실행하는 컨트롤러를 업그레이드할 때 node4가 쿼럼에 가입되어 있고 node1의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 만들고 키 관리자 구성을 복원하는지 확인합니다 `system controller replace` 명령.' 
---
= 노드 4 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 4를 설치하고 부팅한 후에는 올바르게 설치되어 있고, 클러스터에 포함되어 있으며, 노드 3과 통신할 수 있는지 확인해야 합니다.

.이 작업에 대해
절차의 이 시점에서 노드 4가 쿼럼을 조인할 때 작업이 일시 중지됩니다.

.단계
. 노드 4가 쿼럼에 연결되었는지 확인합니다.
+
`cluster show -node node4 -fields health`

. 다음 명령을 입력하여 노드 4가 노드 3과 동일한 클러스터의 일부이고 상태가 양호한지 확인합니다.
+
`cluster show`

. 작업 상태를 확인하고 노드 4의 구성 정보가 노드 2와 동일한지 확인합니다.
+
`system controller replace show-details`

+
노드 4의 구성이 다른 경우 나중에 시스템 중단이 발생할 수 있습니다.

. 교체된 컨트롤러가 스위치 오버 모드가 아닌 MetroCluster 구성에 맞게 올바르게 구성되었는지 확인합니다.
+

CAUTION: * 주의: * 이 단계에서는 MetroCluster 구성이 정상 상태가 아니며 해결할 오류가 있을 수 있습니다. 을 참조하십시오 link:verify_health_of_metrocluster_config.html["MetroCluster 구성의 상태를 확인합니다"].





== 노드 4에서 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 생성합니다

노드 4가 쿼럼에 있고 노드 3과 통신할 수 있는지 확인한 후 노드 4에서 노드 2의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 다시 만들어야 합니다. 노드3 포트도 새로 다시 생성된 브로드캐스트 도메인에 추가해야 합니다.

.이 작업에 대해
VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 를 참조하십시오 link:other_references.html["참조"] 네트워크 관리 _ 에 대한 링크를 제공합니다.

.단계
. 에 기록된 노드 2 정보를 사용하여 노드 4에 VLAN을 다시 생성합니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port vlan create -node _node4_ -vlan _vlan-names_`

. 에 기록된 node2 정보를 사용하여 node4에 인터페이스 그룹을 다시 만듭니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port ifgrp create -node _node4_ -ifgrp _port_ifgrp_names_-distr-func`

. 에 기록된 node2 정보를 사용하여 node4에 브로드캐스트 도메인을 다시 만듭니다 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 재배치합니다"] 섹션:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names_ -mtu _mtu_size_ -ports _node_name:port_name,node_name:port_name_`

. 새로 다시 생성된 브로드캐스트 도메인에 노드 4 포트를 추가합니다.
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_names_ -ports _node_name:port_name,node_name:port_name_`





== 노드 4의 키 관리자 구성을 복원합니다

NVE(NetApp Volume Encryption)를 사용하여 업그레이드 중인 시스템의 볼륨을 암호화하는 경우 암호화 구성을 새 노드와 동기화해야 합니다. Key-Manager를 복원하지 않을 경우 ARL을 사용하여 노드 3에서 노드 4로 노드 2 애그리게이트를 재배치할 때 암호화된 볼륨은 오프라인 상태가 됩니다.

.단계
. Onboard Key Manager의 암호화 구성을 동기화하려면 클러스터 프롬프트에서 다음 명령을 실행합니다.
+
|===
| 이 ONTAP 버전의 경우… | 이 명령 사용... 


| ONTAP 9.6 또는 9.7 | `security key-manager onboard sync` 


| ONTAP 9.5 | `security key-manager setup -node _node_name_` 
|===
. Onboard Key Manager의 클러스터 전체 암호를 입력합니다.

