= 
:allow-uri-read: 


. 스토리지 시스템에 FC 이니시에이터 포트를 새 호스트로 추가하여 스토리지 LUN을 새 호스트에 매핑합니다.
+
자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. 스토리지 어레이의 어레이 LUN과 연결된 호스트 또는 볼륨 그룹에서 WWPN(Worldwide Port Name) 값을 수정합니다.
+
새 컨트롤러 모듈을 설치하면 각 온보드 FC 포트에 연결된 WWPN 값이 변경됩니다.

. 구성에서 스위치 기반 조닝을 사용하는 경우 새 WWPN 값이 반영되도록 조닝을 조정하십시오.
. [[step27]] 를 설정합니다 `bootarg.storageencryption.support` 및 `kmip.init.maxwait` node2 구성이 로드된 후 부트 루프를 방지하기 위한 변수입니다.
+
절차의 앞부분에서 아직 수행하지 않은 경우 기술 자료 문서를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["FIPS 드라이브가 설치되어 있는지 확인하는 방법"^] 사용 중인 자체 암호화 드라이브의 유형을 확인합니다.

+
[cols="35,65"]
|===
| 다음 드라이브를 사용 중인 경우… | 그러면... 


| NSE(NetApp Storage Encryption) 드라이브는 FIPS 140-2 레벨 2 자체 암호화 요구사항을 준수합니다  a| 
** `setenv bootarg.storageencryption.support *true*`
** `setenv kmip.init.maxwait off`




| NetApp 비 FIPS SED  a| 
** `setenv bootarg.storageencryption.support *false*`
** `setenv kmip.init.maxwait off`


|===
+

WARNING: * HA 쌍에서 컨트롤러 업그레이드가 완료되면 즉시 의 설정을 해제해야 합니다 `kmip.init.maxwait` 변수. 을 참조하십시오 link:ensure_new_controllers_are_set_up_correctly.html#unset_maxwait_system_commands["새 컨트롤러가 올바르게 설정되었는지 확인하고 12단계를 수행합니다"]. 그렇지 않으면 정전 발생 시 데이터가 손실될 수 있습니다.*

+
[NOTE]
====
동일한 노드 또는 HA 쌍에서 다른 유형의 드라이브와 FIPS 드라이브를 혼합할 수 없습니다.

동일한 노드 또는 HA 쌍에서 SED를 비암호화 드라이브와 혼합할 수 있습니다.

====
. 부팅 메뉴로 노드 부팅:
+
`boot_ontap menu`

+
FC 또는 UTA/UTA2 구성을 사용하지 않는 경우, 를 실행합니다 link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["노드 4, 15단계에서 UTA/UTA2 포트를 확인하고 구성합니다"] 따라서 노드 4는 노드 2의 디스크를 인식할 수 있습니다.


