= 노드 4에서 FC 포트를 구성합니다
:allow-uri-read: 




== 노드 4에서 FC 포트를 구성합니다

노드 4에 온보드 또는 FC 어댑터가 있는 FC 포트가 있는 경우 포트가 사전 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다. 포트가 구성되지 않은 경우 서비스가 중단될 수 있습니다.

.시작하기 전에
섹션에 저장한 노드 2의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 어댑터가 있는 경우, 에서 포트를 구성합니다 <<노드 4의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 시스템에 스토리지 디스크가 있는 경우 이 섹션의 명령을 클러스터 프롬프트에 입력해야 합니다. V-Series 시스템이나 FlexArray 가상화 소프트웨어가 설치된 시스템이 스토리지 어레이에 연결되어 있는 경우, 유지보수 모드의 이 섹션에 명령을 입력하십시오.

.단계
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다 | `system node hardware unified-connect show` 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | `ucadmin show` 
|===
+
시스템에 있는 모든 FC 및 통합 네트워크 어댑터에 대한 정보가 표시됩니다.

. 노드 4의 FC 설정을 노드 1에서 앞서 캡처한 설정과 비교합니다.
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
필요에 따라 노드 4의 FC 포트를 수정합니다.

** 타겟 포트를 프로그래밍하려면
+
`ucadmin modify -m fc -t target _adapter_`

** 이니시에이터 포트를 프로그래밍하려면:
+
`ucadmin modify -m fc -t initiator _adapter_`



`-t` FC4 유형: 타겟 또는 이니시에이터입니다.



| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다  a| 
필요에 따라 노드 4의 FC 포트를 수정합니다.

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` FC4 유형, 타겟 또는 이니시에이터입니다.


NOTE: FC 포트는 이니시에이터로 프로그래밍해야 합니다.

|===
. 유지 관리 모드 종료:
+
`halt`

. LOADER 프롬프트에서 시스템을 부팅합니다.
+
`boot_ontap menu`

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 옵션을 선택합니다 `5` 를 참조하십시오.

