= 노드 3의 UTA/UTA2 포트를 확인하고 구성합니다
:allow-uri-read: 




== 노드 3의 UTA/UTA2 포트를 확인하고 구성합니다

노드 3에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드를 사용하는 경우, 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 필요에 따라 포트를 다시 구성해야 합니다.

.시작하기 전에
UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

.이 작업에 대해
FC에 UTA/UTA2(Unified Target Adapter) 포트를 사용하려면 먼저 포트 구성 방법을 확인해야 합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

당신은 사용할 수 있습니다 `ucadmin show` 다음 예제 출력에서 볼 수 있듯이 현재 포트 구성을 보거나 확인하기 위한 명령입니다.

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드는 동일한 10GbE SFP+ 인터페이스를 공유하는 NIC 및 FCoE 트래픽을 동시에 허용할 수 있으며 FC 타겟을 지원합니다.

추가 어댑터나 컨트롤러 마더보드에서 UTA/UTA2 포트를 찾을 수 있으며 다음과 같은 구성을 가지고 있을 수 있지만, node3에서 UTA/UTA2 포트의 구성을 확인하고 필요한 경우 변경해야 합니다.

* 컨트롤러를 주문할 때 주문한 UTA/UTA2 카드는 사용자가 요청하는 Personality를 요청하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 배송 전에 사용자가 요청하는 Personality를 사용하도록 구성되었습니다.
+

WARNING: UTA/UTA2 포트를 구성하려면 유지 관리 모드에 있어야 합니다.  유지 관리 모드 셸 프롬프트에서 이 섹션의 명령을 입력합니다.



.단계
. 현재 SFP+ 모듈이 원하는 용과 일치하지 않는 경우 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. UTA/UTA2 포트 설정을 확인하세요.
+
`ucadmin show`

+
출력을 검토하여 UTA/UTA2 포트가 원하는 특성을 가지고 있는지 확인하세요.

+
다음 예제의 출력은 어댑터 "1b"의 유형이 개시자로 변경되고 어댑터 "2a"와 "2b"의 모드가 "cna"로 변경되는 것을 보여줍니다.  CNA 모드에서는 카드를 네트워크 어댑터로 사용할 수 있습니다.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| UTA/UTA2 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 가다<<auto_check3_step4,4단계>> . 


| 원하는 개성을 갖고 싶어하세요 | 4단계부터 8단계까지 건너뛰고 다음으로 이동하세요.<<auto_check3_step9,9단계>> . 
|===
. [[auto_check3_step4]]다음 작업 중 하나를 수행하세요.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 가다<<auto_check3_step5,5단계>> 


| 온보드 UTA/UTA2 포트 | 5단계를 건너뛰고 다음으로 이동하세요.<<auto_check3_step6,6단계>> . 
|===
. [[auto_check3_step5]]어댑터가 이니시에이터 모드이고 UTA/UTA2 포트가 온라인인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
`storage disable adapter <adapter_name>`

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check3_step6]]현재 구성이 원하는 용도와 일치하지 않으면 필요에 따라 구성을 변경하세요.
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` 성격 모드, `fc` 또는 `cna`.
** `-t` FC4형, `target` 또는 `initiator`.
+

NOTE: 테이프 드라이브와 MetroCluster 구성에는 FC 이니시에이터를 사용해야 합니다.  SAN 클라이언트의 경우 FC 대상을 사용해야 합니다.



. 각 포트에 대해 다음 명령을 한 번씩 입력하여 대상 포트를 온라인으로 전환합니다.
+
`storage enable adapter <adapter_name>`

. 포트에 케이블을 연결합니다.

