= 노드 3에서 FC 포트를 구성합니다
:allow-uri-read: 




== 노드 3에서 FC 포트를 구성합니다

노드3에 FC 포트가 있는 경우(온보드 또는 추가 FC 어댑터에 있음), 시스템이 배송될 때 포트가 미리 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다.  포트를 구성하지 않으면 서비스가 중단될 수 있습니다.

.시작하기 전에
섹션에 저장한 노드 1의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 있는 경우, 에서 포트를 구성합니다 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 유지 관리 모드 셸 프롬프트에서 이 섹션의 명령을 입력합니다.

.단계
. 노드 3의 FC 설정을 노드 1에서 이전에 캡처한 설정과 비교합니다.
. 필요에 따라 다음 작업 중 하나를 수행하여 node3의 FC 포트를 수정합니다.
+
유지 관리 모드에서(부팅 메뉴의 옵션 5):

+
** 대상 포트로 프로그래밍하려면:
+
`ucadmin modify -m fc -t target <adapter>`

+
예를 들어: `ucadmin modify -m fc -t target 2a`

** 이니시에이터 포트를 프로그래밍하려면:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
예를 들어: `ucadmin modify -m fc -t initator 2b`



. 다음 명령을 사용하여 새로운 설정을 확인하고 출력을 살펴보세요.
+
`ucadmin show`

. 노드 중단:
+
`halt`

. LOADER 프롬프트에서 시스템을 부팅합니다.
+
`boot_ontap menu`

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 옵션을 선택합니다 `5` 를 참조하십시오.

