= 노드 4의 UTA/UTA2 포트를 확인하고 구성합니다
:allow-uri-read: 




== 노드 4의 UTA/UTA2 포트를 확인하고 구성합니다

노드 4에 온보드 UTA/UTA2 포트 또는 UTA/UTA2A 카드가 있는 경우 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 포트를 구성해야 합니다.

.시작하기 전에
UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

.이 작업에 대해
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2A 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드를 사용하면 동시 NIC 및 FCoE 트래픽이 동일한 10GbE SFP+ 인터페이스를 공유하고 FC 타겟을 지원할 수 있습니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

UTA/UTA2 포트는 다음 구성을 사용하여 어댑터 또는 컨트롤러에 있을 수 있습니다.

* UTA/UTA2 카드를 컨트롤러와 동시에 주문했으며 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.


하지만 노드 4의 UTA/UTA2 포트 구성을 확인하고 필요한 경우 이를 변경해야 합니다.


WARNING: 유지 관리 모드 셸 프롬프트에서 이 섹션의 명령을 입력합니다.

.단계
. 현재 node4에서 포트가 어떻게 구성되어 있는지 확인하세요.
+
`system node hardware unified-connect show`

+
다음 예와 유사한 출력이 표시됩니다.

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 현재 SFP+ 모듈이 원하는 용과 일치하지 않는 경우 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. 설정을 확인합니다.
+
`ucadmin show`

+
의 출력을 검사합니다 `ucadmin show` UTA/UTA2 포트가 원하는 특성을 가지고 있는지 여부를 확인합니다.

+
다음 예제의 출력은 FC4 어댑터 "1b"의 유형이 로 변경되었음을 나타냅니다 `initiator` 어댑터 "2a"와 "2b"의 모드가 로 변경됩니다 `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| CNA 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 이동합니다 <<auto_check_4_step5,5단계>>. 


| 원하는 개성을 갖고 싶어하세요 | 5단계부터 9단계까지 건너뛰고 다음으로 이동하세요.<<auto_check_4_step10,10단계>> . 
|===
. [[auto_check_4_step5] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 가다<<auto_check_4_step6,6단계>> 


| 온보드 UTA/UTA2 포트 | 6단계를 건너뛰고 다음으로 이동하세요.<<auto_check_4_step7,7단계>> . 
|===
. [[auto_check_4_step6]]어댑터가 이니시에이터 모드에 있고 UTA/UTA2 포트가 온라인인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
`storage disable adapter _adapter_name_`

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check_4_step7]] 현재 구성이 원하는 용과 일치하지 않으면 필요에 따라 구성을 변경합니다.
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` 성격 모드, FC 또는 10GbE UTA입니다.
** `-t` FC4형, `target` 또는 `initiator`.
+

NOTE: 테이프 드라이브와 MetroCluster 구성에는 FC 이니시에이터를 사용해야 합니다.  SAN 클라이언트의 경우 FC 대상을 사용해야 합니다.



. 다음 명령을 각 포트에 대해 한 번씩 입력하여 대상 포트를 온라인으로 전환합니다.
+
`storage enable adapter <adapter_name>`

. 포트에 케이블을 연결합니다.

