= 사전 점검 단계 중에 재부팅, 패닉 또는 전원 사이클을 실행할 수 있습니다


업그레이드 단계가 서로 다를 경우 시스템이 충돌합니다(재부팅, 패닉 또는 전원 껐다 켜기).

이러한 문제의 해결 방법은 발생 시기에 따라 다릅니다.



== 사전 점검 단계 중에 재부팅, 패닉 또는 전원 사이클을 실행할 수 있습니다



=== HA 쌍의 사전 검사 단계가 계속 설정되기 전에 노드 1 또는 노드 2가 충돌합니다

사전 점검 단계 전에 노드 1이나 노드 2에 장애가 발생하면 이전에 애그리게이트를 재배치할 수 없으며 HA 쌍 구성이 아직 설정되어 있는 것입니다.

테이크오버 및 반환이 정상적으로 진행될 수 있습니다.

.단계
. 시스템에서 실행할 수 있는 EMS 메시지가 콘솔에 있는지 확인하고 권장되는 교정 조치를 취하십시오.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 첫 번째 리소스 릴리즈 단계에서 재부팅, 패닉 또는 전원을 껐다 켭니다



=== HA 쌍이 여전히 활성화된 첫 번째 리소스 릴리즈 단계에서 노드 1이 충돌합니다

일부 또는 모든 애그리게이트가 노드 1에서 노드 2로 재배치되었지만, HA 페어는 계속 사용하도록 설정되었습니다. 노드 2는 노드 1의 루트 볼륨과 재배치되지 않은 모든 루트 애그리게이트를 차지합니다.

재배치된 애그리게이트의 소유권은 홈 소유자가 변경되지 않았기 때문에 이전된 비루트 애그리게이트의 소유권과 동일합니다.

노드 1이 '반환 대기 중' 상태로 전환되면 노드 2에서 노드 1이 아닌 모든 애그리게이트를 되돌려 줍니다.

.단계
. 노드 1을 부팅한 후 노드 1의 모든 비루트 애그리게이트가 노드 1로 다시 이동했습니다. 노드 1에서 노드 2로 애그리게이트를 수동으로 재구성해야 합니다. 'storage aggregate relocation start-node node1-destination node2-aggregate-list * -ndocontroller-upgrade true'입니다
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== HA 쌍을 사용하지 않도록 설정한 상태에서 첫 번째 리소스 릴리즈 단계에서 노드 1이 충돌합니다

노드 2는 인수되지 않지만 모든 비루트 애그리게이트에서 데이터를 계속 처리하고 있습니다.

.단계
. 노드1을 불러옵니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== HA 쌍이 여전히 활성화된 첫 번째 리소스 릴리즈 단계에서는 노드 2에 장애가 발생합니다

노드 1은 해당 애그리게이트의 일부 또는 전부를 노드 2로 재배치했습니다. HA 쌍이 설정되었습니다.

노드 1은 노드 2에 재배치된 자체 애그리게이트뿐만 아니라 노드 2에 모두 적용됩니다. 노드 2가 부팅되면 애그리게이트 재배치가 자동으로 완료됩니다.

.단계
. 노드2를 위로 올립니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 첫 번째 리소스 릴리즈 단계와 HA 쌍이 사용되지 않도록 설정된 후에 노드 2가 충돌합니다

노드 1이 적용되지 않습니다.

.단계
. 노드2를 위로 올립니다.
+
노드 2가 부팅되는 동안 모든 애그리게이트에 대해 클라이언트 중단이 발생합니다.

. 나머지 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 첫 번째 검증 단계에서 재부팅, 패닉 또는 전원 사이클을 실행할 수 있습니다



=== HA 쌍이 비활성화된 첫 번째 검증 단계에서 노드 2가 충돌합니다

HA 쌍이 이미 사용되지 않아 노드 2의 장애가 발생한 경우에는 Node3가 노드 2를 인수하지 않습니다.

.단계
. 노드2를 위로 올립니다.
+
노드 2가 부팅되는 동안 모든 애그리게이트에 대해 클라이언트 중단이 발생합니다.

. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== HA 쌍이 비활성화된 첫 번째 검증 단계에서 Node3가 충돌합니다

노드 2는 인수되지 않지만 모든 비루트 애그리게이트에서 데이터를 계속 처리하고 있습니다.

.단계
. 노드3을 불러옵니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 첫 번째 리소스-다시 찾기 단계 중에 재부팅, 패닉 또는 전원 사이클을 실행할 수 있습니다



=== 집계 재배치 중에 첫 번째 리소스-다시 찾기 단계 중에 노드 2가 충돌합니다

노드 2는 일부 또는 모든 해당 애그리게이트를 노드 1에서 노드 3으로 재배치했습니다. Node3는 재배치된 애그리게이트의 데이터를 제공합니다. HA 쌍이 비활성화되므로 테이크오버가 없습니다.

재배치되지 않은 애그리게이트에는 클라이언트 운영 중단이 있습니다. 노드 2를 부팅할 때 노드 1의 애그리게이트는 노드 3으로 재배치됩니다.

.단계
. 노드2를 위로 올립니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== Node3는 집계 재배치 중에 첫 번째 리소스-다시 찾기 단계 중에 충돌합니다

노드 2가 애그리게이트를 노드 3으로 재배치하는 동안 노드 3이 충돌하면 노드 3이 부팅된 후에도 작업이 계속됩니다.

노드 2는 계속해서 나머지 애그리게이트를 제공하지만, 노드 3에 이미 재배치된 애그리게이트는 노드 3이 부팅되는 동안 클라이언트 중단을 겪게 됩니다.

.단계
. 노드3을 불러옵니다.
. 컨트롤러 업그레이드를 계속합니다.




== 사후 검사 단계에서 재부팅, 패닉 또는 전원 사이클을 수행합니다



=== 사후 검사 단계에서 노드 2 또는 노드 3이 충돌합니다

HA 쌍이 비활성화되므로 테이크오버가 불가능합니다. 재부팅된 노드에 속한 애그리게이트에는 클라이언트 중단이 있습니다.

.단계
. 노드를 불러옵니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 두 번째 리소스 릴리즈 단계에서 재부팅, 패닉 또는 전원을 껐다 켭니다



=== 두 번째 리소스 릴리즈 단계에서 Node3가 충돌합니다

노드 2에서 애그리게이트를 재배치하는 동안 노드 3이 충돌하면 노드 3이 부팅된 후에도 작업이 계속됩니다.

노드 2는 계속해서 나머지 애그리게이트를 제공하지만, 이미 노드 3에 재배치된 애그리게이트 및 노드 3의 자체 애그리게이트는 노드 3이 부팅되는 동안 클라이언트 운영 중단을 겪게 됩니다.

.단계
. 노드3을 불러옵니다.
. 컨트롤러 업그레이드 절차를 계속 진행합니다.




=== 두 번째 리소스 릴리즈 단계에서 노드 2가 충돌합니다

애그리게이트 재배치 중에 노드 2가 충돌하면 노드 2가 페일오버되지 않습니다.

Node3는 재배치된 애그리게이트를 계속 제공하지만, 노드 2가 소유한 애그리게이트에서 클라이언트 작동이 중단되는 경우

.단계
. 노드2를 위로 올립니다.
. 컨트롤러 업그레이드 절차를 계속 진행합니다.

