= 
:allow-uri-read: 


원래 노드를 교체하기 전에 해당 노드가 HA 쌍 안에 있는지, 누락된 디스크 또는 장애가 발생한 디스크가 없는지, 서로의 스토리지에 액세스할 수 있는지, 클러스터의 다른 노드에 할당된 데이터 LIF를 소유하지 않는지 확인해야 합니다. 또한 원래 노드에 대한 정보도 수집해야 하며, 클러스터가 SAN 환경에 있는 경우 클러스터의 모든 노드가 쿼럼에 있는지 확인해야 합니다.

.단계
. 테이크오버 모드 중에 두 노드의 워크로드를 적절하게 지원하는 데 필요한 리소스가 각 원래 노드에 있는지 확인하십시오.
+
HA Pair 관리 _ 링크를 참조하고 link:other_references.html["참조"]_ HA Pair에 대한 모범 사례 _ 섹션을 따르십시오. 원래 노드 중 어느 것도 50% 이상의 사용률로 실행되지 않아야 합니다. 50% 미만의 활용률로 실행 중인 노드는 컨트롤러 업그레이드 중에 두 노드의 부하를 처리할 수 있습니다.

. 원본 노드에 대한 성능 기준을 만들려면 다음 하위 단계를 완료하십시오.
+
.. 진단 사용자 계정이 잠금 해제되어 있는지 확인합니다.
+
[IMPORTANT]
====
진단 사용자 계정은 하위 수준 진단 목적으로만 사용해야 하며 기술 지원 부서의 안내에 따라서만 사용해야 합니다.

사용자 계정 잠금 해제에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 시스템 관리 참조 _ 에 대한 링크

====
.. 을 참조하십시오 link:other_references.html["참조"] 를 방문하여 _NetApp Support 사이트_에 연결하고 성능 및 통계 수집기(perfstat Converged)를 다운로드하십시오.
+
perfstat Converged 툴을 사용하면 업그레이드 후 비교를 위한 성능 기준을 설정할 수 있습니다.

.. NetApp Support 사이트의 지침에 따라 성능 기준을 만듭니다.


. 을 참조하십시오 link:other_references.html["참조"] 를 눌러 _NetApp Support 사이트_에 연결하고 NetApp Support 사이트에서 지원 케이스를 여십시오.
+
이 케이스를 사용하여 업그레이드 중에 발생할 수 있는 문제를 보고할 수 있습니다.

. 노드 3 및 노드 4의 NVMEM 또는 NVRAM 배터리가 충전되었는지 확인하고 충전되지 않은 경우 충전합니다.
+
NVMEM 또는 NVRAM 배터리가 충전되었는지 확인하려면 노드 3과 노드 4를 물리적으로 확인해야 합니다. 노드 3 및 노드 4 모델의 상태 표시등에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크

+

WARNING: NVRAM 내용을 지우려고 하지 마세요.  NVRAM 의 내용을 지워야 하는 경우 NetApp 기술 지원팀에 문의하세요.

. 노드 3과 노드 4에서 ONTAP 버전을 확인합니다.
+
새 노드에는 원래 노드에 설치된 동일한 버전의 ONTAP 9.x가 설치되어 있어야 합니다. 새 노드의 ONTAP 버전이 다른 설치된 경우 새 컨트롤러를 설치한 후 해당 컨트롤러를 netboot 해야 합니다. ONTAP를 업그레이드하는 방법에 대한 지침은 을 참조하십시오 link:other_references.html["참조"] ONTAP_ 업그레이드 링크

+
노드 3 및 노드 4의 ONTAP 버전에 대한 정보는 배송 상자에 포함되어 있어야 합니다. ONTAP 버전은 노드가 부팅될 때 표시되며, 노드를 유지보수 모드로 부팅하고 명령을 실행할 수 있습니다.

+
`version`

. 노드 1과 노드 2에 2개 또는 4개의 클러스터 LIF가 있는지 확인합니다.
+
`network interface show -role cluster`

+
다음 예제와 같이 시스템에서 모든 클러스터 LIF를 표시합니다.

+
....
cluster::> network interface show -role cluster
        Logical    Status     Network          Current  Current Is
Vserver Interface  Admin/Oper Address/Mask     Node     Port    Home
------- ---------- ---------- ---------------- -------- ------- ----
node1
        clus1      up/up      172.17.177.2/24  node1    e0c     true
        clus2      up/up      172.17.177.6/24  node1    e0e     true
node2
        clus1      up/up      172.17.177.3/24  node2    e0c     true
        clus2      up/up      172.17.177.7/24  node2    e0e     true
....
. 노드 1 또는 노드 2에 2개 또는 4개의 클러스터 LIF가 있는 경우 다음 하위 단계를 완료하여 사용 가능한 모든 경로에서 두 클러스터 LIF를 모두 Ping할 수 있는지 확인합니다.
+
.. 고급 권한 수준 입력:
+
`set -privilege advanced`

+
다음과 같은 메시지가 표시됩니다.

+
....
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you wish to continue? (y or n):
....
.. 를 입력합니다 `y`.
.. 노드를 ping하고 연결을 테스트합니다.
+
`cluster ping-cluster -node node_name`

+
다음 예와 유사한 메시지가 표시됩니다.

+
....
cluster::*> cluster ping-cluster -node node1
Host is node1
Getting addresses from network interface table...
Local = 10.254.231.102 10.254.91.42
Remote = 10.254.42.25 10.254.16.228
Ping status:
...
Basic connectivity succeeds on 4 path(s) Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 4 path(s):
Local 10.254.231.102 to Remote 10.254.16.228
Local 10.254.231.102 to Remote 10.254.42.25
Local 10.254.91.42 to Remote 10.254.16.228
Local 10.254.91.42 to Remote 10.254.42.25
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
....
+
노드가 2개의 클러스터 포트를 사용하는 경우 예에서와 같이 4개 경로에서 통신할 수 있어야 합니다.

.. 관리 레벨 권한으로 돌아가기:
+
`set -privilege admin`



. 노드 1과 노드 2가 HA 쌍 내에 있는지 확인하고 노드가 서로 연결되어 있으며 테이크오버가 가능한지 확인합니다.
+
`storage failover show`

+
다음 예는 노드가 서로 연결되고 테이크오버가 가능한 경우의 출력을 보여 줍니다.

+
....
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------
node1          node2          true     Connected to node2
node2          node1          true     Connected to node1
....
+
어느 노드도 부분 반환에 있어서는 안 됩니다. 다음 예제에서는 node1이 부분 반환에 있음을 보여 줍니다.

+
....
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------
node1          node2          true     Connected to node2, Partial giveback
node2          node1          true     Connected to node1
....
+
노드 중 하나가 부분 반환 상태인 경우 `storage failover giveback` 명령을 사용하여 기브백을 수행한 다음 명령을 사용하여 `storage failover show-giveback` 아직 애그리게이트를 다시 제공할 필요가 없는지 확인합니다. 명령에 대한 자세한 내용은 link:other_references.html["참조"]_HA Pair management_ 링크를 참조하십시오.

. [[man_prepare_nodes_step9]] 노드 1과 노드 2가 현재 소유자인 집계(홈 소유자가 아님)를 소유하고 있지 않은지 확인합니다.
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
노드 1과 노드 2가 현재 소유자인 Aggregate(홈 소유자가 아님)를 소유하지 않으면 시스템이 다음 예와 유사한 메시지를 반환합니다.

+
....
cluster::> storage aggregate show -node node2 -is-home false -fields owner-name,homename,state
There are no entries matching your query.
....
+
다음 예제에서는 node2라는 이름의 노드에 대한 명령 출력을 보여 줍니다. node2는 홈 소유이지만 현재 소유자가 아닌 4개의 애그리게이트로 구성됩니다.

+
....
cluster::> storage aggregate show -node node2 -is-home false
               -fields owner-name,home-name,state

aggregate     home-name    owner-name   state
------------- ------------ ------------ ------
aggr1         node1        node2        online
aggr2         node1        node2        online
aggr3         node1        node2        online
aggr4         node1        node2        online

4 entries were displayed.
....
. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 의 명령인 경우 <<man_prepare_nodes_step9,9단계>>... | 그러면... 


| 출력이 비어 있습니다 | 11단계를 건너뛰고 로 이동합니다 <<man_prepare_nodes_step12,12단계>>. 


| 출력이 있었습니다 | 로 이동합니다 <<man_prepare_nodes_step11,11단계>>. 
|===
. [[man_prepare_nodes_step11]] 노드 1 또는 노드 2가 현재 소유이지만 홈 소유자가 아닌 집계를 소유하고 있으면 다음 하위 단계를 완료합니다.
+
.. 파트너 노드가 현재 소유한 애그리게이트를 홈 소유자 노드로 반환:
+
`storage failover giveback -ofnode _home_node_name_`

.. 노드 1과 노드 2가 현재 소유자인 애그리게이트를 소유하지 않고 홈 소유자가 아닌 경우:
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
다음 예제는 노드가 Aggregate의 현재 소유자이자 홈 소유자인 경우 명령의 출력을 보여줍니다.

+
....
cluster::> storage aggregate show -nodes node1
          -is-home true -fields owner-name,home-name,state

aggregate     home-name    owner-name   state
------------- ------------ ------------ ------
aggr1         node1        node1        online
aggr2         node1        node1        online
aggr3         node1        node1        online
aggr4         node1        node1        online

4 entries were displayed.
....


. [[man_prepare_nodes_step12]] node1과 node2가 서로의 스토리지를 액세스할 수 있는지 확인하고 누락된 디스크가 없는지 확인합니다.
+
`storage failover show -fields local-missing-disks,partner-missing-disks`

+
다음 예에서는 디스크가 없는 경우의 출력을 보여 줍니다.

+
....
cluster::> storage failover show -fields local-missing-disks,partner-missing-disks

node     local-missing-disks partner-missing-disks
-------- ------------------- ---------------------
node1    None                None
node2    None                None
....
+
디스크가 누락된 경우 _ 디스크 및 CLI _, _ CLI _ 를 사용한 논리적 스토리지 관리 및 _HA 쌍 관리 _ 를 사용하여 HA 쌍의 스토리지를 구성합니다.link:other_references.html["참조"]

. 노드 1과 노드 2가 정상 상태이며 클러스터에 참여할 자격이 있는지 확인합니다.
+
`cluster show`

+
다음 예는 두 노드가 모두 정상이고 정상일 때의 출력을 보여줍니다.

+
....
cluster::> cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
....
. 권한 수준을 고급으로 설정합니다.
+
`set -privilege advanced`

. [[man_prepare_nodes_step15]] node1과 node2가 동일한 ONTAP 릴리즈를 실행하고 있는지 확인합니다.
+
`system node image show -node _node1,node2_ -iscurrent true`

+
다음 예제는 명령의 출력을 보여 줍니다.

+
....
cluster::*> system node image show -node node1,node2 -iscurrent true

                 Is      Is                Install
Node     Image   Default Current Version   Date
-------- ------- ------- ------- --------- -------------------
node1
         image1  true    true    9.1         2/7/2017 20:22:06
node2
         image1  true    true    9.1         2/7/2017 20:20:48

2 entries were displayed.
....
. 노드 1과 노드 2가 클러스터의 다른 노드에 속한 데이터 LIF를 소유하고 있지 않은지 확인한 다음 를 확인합니다 `Current Node` 및 `Is Home` 출력의 열:
+
`network interface show -role data -is-home false -curr-node _node_name_`

+
다음 예제에서는 node1에 클러스터의 다른 노드가 소유하는 LIF가 없는 경우의 출력을 보여 줍니다.

+
....
cluster::> network interface show -role data -is-home false -curr-node node1
 There are no entries matching your query.
....
+
다음 예제에서는 node1이 다른 노드가 소유한 데이터 LIF를 소유하는 경우의 출력을 보여 줍니다.

+
....
cluster::> network interface show -role data -is-home false -curr-node node1

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data1      up/up      172.18.103.137/24  node1         e0d     false
            data2      up/up      172.18.103.143/24  node1         e0f     false

2 entries were displayed.
....
. 의 출력인 경우 <<man_prepare_nodes_step15,15단계>> 에서는 노드 1이나 노드 2가 클러스터의 다른 노드에서 소유하는 데이터 LIF를 노드 1이나 노드 2에서 다른 데이터 LIF로 마이그레이션합니다.
+
`network interface revert -vserver * -lif *`

+
에 대한 자세한 내용은 를 참조하십시오 `network interface revert` 명령, 을 참조하십시오 link:other_references.html["참조"] _ONTAP 9 명령에 연결하려면 수동 페이지 참조 _.

. 노드 1이나 노드 2에 장애가 발생한 디스크가 있는지 확인합니다.
+
`storage disk show -nodelist _node1,node2_ -broken`

+
디스크에 오류가 발생한 경우, _ Disk 의 지침에 따라 디스크를 제거하고 CLI _ 을(를) 사용하여 관리를 통합합니다. (을 참조하십시오 link:other_references.html["참조"] CLI_를 사용하여 _ 디스크 및 애그리게이트 관리에 연결하려면 _.)

. 다음 하위 단계를 완료하고 각 명령의 출력을 기록하여 node1 및 node2에 대한 정보를 수집합니다.

