= 
:allow-uri-read: 


랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 또한 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 이전에 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

.이 작업에 대해
node1에 설치된 것과 동일한 버전의 ONTAP 9가 없는 경우 node3을 네트워크 부팅해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다. 을 link:prepare_for_netboot.html["netboot를 준비합니다"]참조하십시오.

하지만 node1에 설치된 ONTAP 9와 동일하거나 그 이후 버전이 있는 경우 node3을 네트워크 부팅할 필요는 없습니다.

[IMPORTANT]
====
* AFF A800 또는 AFF C800 컨트롤러를 업그레이드하는 경우, 노드1을 제거하기 전에 섀시의 모든 드라이브가 미드플레인에 단단히 고정되어 있는지 확인해야 합니다. 자세한 내용은 다음을 참조하세요. link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["AFF A800 또는 AFF C800 컨트롤러 모듈을 교체합니다"].
* 저장 디스크가 있는 시스템을 업그레이드하는 경우 이 섹션 전체를 완료한 다음 다음으로 이동해야 합니다. link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 그리고 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 클러스터 프롬프트에서 명령을 입력합니다.


====
.단계
. [[man_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치에 가까운 자체 랙 공간에 넣어야 합니다.

. [[step2]] 노드 모델의 _설치 및 설치 지침_ 에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면 노드 3을 부팅할 때 노드는 이중 섀시 구성에 있는 것처럼 작동하며 노드 4를 부팅할 때 노드 간의 상호 연결이 나타나지 않습니다.

. [[step3]] 노드 3을 케이블로 연결하고 노드 1에서 노드 3으로 연결을 이동합니다.
+
다음 참조는 올바른 케이블 연결에 도움이 됩니다. 로 이동합니다 link:other_references.html["참조"] 링크를 클릭합니다.

+
** node3 플랫폼에 대한 _설치 및 설정 지침_
** 디스크 쉘프 관련 절차
** HA Pair 관리 _ 설명서


+
다음 연결부에 케이블을 연결합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[man_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]에 경고 메시지가 표시되면 <<man_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: *지연 시간을 무시하지 마세요. 배터리 충전을 허용하지 않으면 데이터가 손실될 수 있습니다.*



. 유지 관리 모드 프롬프트에서 다음 명령을 입력합니다.
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드할 시스템이...에 있는 경우 | 그러면... 


| 이중 섀시 구성(다른 섀시 내 컨트롤러 포함) | 로 가다<<man_install3_step8,8단계>> . 


| 단일 섀시 구성(동일한 섀시 내 컨트롤러 포함)  a| 
.. 콘솔 케이블을 노드 3에서 노드 4로 전환합니다.
.. 노드 4의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단한 다음, 부팅 환경 프롬프트에 액세스합니다.
+
두 컨트롤러가 동일한 섀시에 있는 경우 전원이 이미 켜져 있어야 합니다.

+

NOTE: 부팅 환경 프롬프트에 node4를 그대로 두면 의 node4로 돌아갑니다 link:install_boot_node4.html["노드 4를 설치하고 부팅합니다"].

.. 에 경고 메시지가 표시되는 경우 <<man_install3_step4,4단계>>의 지침을 따릅니다 <<man_install3_step5,5단계>>
.. 콘솔 케이블을 노드 4에서 노드 3으로 다시 전환합니다.
.. 로 가다<<man_install3_step8,8단계>> .


|===
. [[man_install3_step8]] ONTAP 에 대한 node3 구성:
+
`set-defaults`


