= 
:allow-uri-read: 


랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 또한 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 이전에 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

.이 작업에 대해
노드 1에 설치된 ONTAP 9의 버전이 같지 않으면 netboot node3을 사용해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다. 을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].

그러나 노드 1에 설치된 ONTAP 9의 이후 버전이 같거나 동일한 경우에는 노드 3을 netboot 할 필요가 없습니다.

[IMPORTANT]
====
스토리지 어레이에 연결된 V-Series 시스템이나 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어를 사용하여 시스템을 업그레이드하려면 시스템을 완료해야 합니다 <<man_install3_step1,1단계>> 부터 까지 <<man_install3_step5,5단계>>에서 이 섹션을 그대로 둡니다 <<man_install3_step6,6단계>> 및 의 지침을 따릅니다 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 필요에 따라 유지보수 모드에서 명령을 입력합니다. 그런 다음 이 섹션으로 돌아가서 을(를) 다시 시작해야 합니다 <<man_install3_step7,7단계>>.

그러나 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 이 전체 섹션을 완료한 다음 로 이동해야 합니다 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"], 클러스터 프롬프트에서 명령 입력

====
.단계
. [[man_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치에 가까운 자체 랙 공간에 넣어야 합니다.

. [[step2]] 노드 모델의 _설치 및 설치 지침_ 에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면 노드 3을 부팅할 때 노드는 이중 섀시 구성에 있는 것처럼 작동하며 노드 4를 부팅할 때 노드 간의 상호 연결이 나타나지 않습니다.

. [[step3]] 노드 3을 케이블로 연결하고 노드 1에서 노드 3으로 연결을 이동합니다.
+
다음 참조는 올바른 케이블 연결에 도움이 됩니다. 로 이동합니다 link:other_references.html["참조"] 링크를 클릭합니다.

+
** _설치 및 설치 지침_ 또는 _FlexArray 가상화 설치 요구 사항 및 노드3 플랫폼에 대한 참조_
** 디스크 쉘프 관련 절차
** HA Pair 관리 _ 설명서


+
다음 연결부에 케이블을 연결합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[man_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]에 경고 메시지가 표시되면 <<man_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

NOTE: * 주의 *: 지연을 무시하지 마십시오. 배터리를 충전하지 않으면 데이터가 손실될 수 있습니다.



. [[man_install3_step6]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 시스템이... | 그러면... 


| 디스크 및 백엔드 스토리지가 없습니다 | 7단계부터 12단계까지 건너뛰고 로 이동합니다 <<man_install3_step13,13단계>>. 


| 는 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어가 설치된 V-Series 시스템 또는 시스템입니다  a| 
.. 로 이동합니다 link:set_fc_uta_uta2_config_node3.html["노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다"] 하위 섹션을 완료합니다 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"]시스템에 맞게.
.. 이 섹션으로 돌아가 나머지 단계를 완료합니다 <<man_install3_step7,7단계>>.



IMPORTANT: FlexArray 가상화 소프트웨어를 사용하여 V-Series 또는 시스템에서 ONTAP를 부팅하기 전에 FC 온보드 포트, CNA 온보드 포트 및 CNA 카드를 재구성해야 합니다.

|===
. [[man_install3_step7]] 새 노드의 FC 이니시에이터 포트를 스위치 영역에 추가합니다.
+
시스템에 테이프 SAN이 있는 경우 이니시에이터에 대해 조닝이 필요합니다. 자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. [[man_install3_step8]] 스토리지 시스템에 FC 이니시에이터 포트를 새 호스트로 추가하여 스토리지 LUN을 새 호스트에 매핑합니다.
+
자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. [[man_install3_step9]] 스토리지 배열의 어레이 LUN과 연결된 호스트 또는 볼륨 그룹에서 WWPN(World Wide Port Name) 값을 수정합니다.
+
새 컨트롤러 모듈을 설치하면 각 온보드 FC 포트에 연결된 WWPN 값이 변경됩니다.

. [[man_install3_step10]] 구성에서 스위치 기반 조닝을 사용하는 경우 새 WWPN 값을 반영하도록 조닝을 조정합니다.
. [[man_install3_step11]] 이제 스토리지 LUN이 노드 3에 표시되는지 확인합니다.
+
`sysconfig -v`

+
각 FC 이니시에이터 포트에 표시되는 모든 스토리지 LUN이 표시됩니다. 어레이 LUN이 표시되지 않으면 이 섹션의 뒷부분에 있는 노드 1에서 노드 3으로 디스크를 재할당할 수 없습니다.

. [[man_install3_step12]] Ctrl-C를 눌러 부팅 메뉴를 표시하고 유지보수 모드를 선택합니다.
. [[man_install3_step13]] 유지보수 모드 프롬프트에서 다음 명령을 입력합니다.
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. [[man_install3_step14]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드할 시스템이...에 있는 경우 | 그러면... 


| 이중 섀시 구성(다른 섀시 내 컨트롤러 포함) | 로 이동합니다 <<man_install3_step15,15단계>>. 


| 단일 섀시 구성(동일한 섀시 내 컨트롤러 포함)  a| 
.. 콘솔 케이블을 노드 3에서 노드 4로 전환합니다.
.. 노드 4의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단한 다음, 부팅 환경 프롬프트에 액세스합니다.
+
두 컨트롤러가 동일한 섀시에 있는 경우 전원이 이미 켜져 있어야 합니다.

+

NOTE: 부팅 환경 프롬프트에 node4를 그대로 두면 의 node4로 돌아갑니다 link:install_boot_node4.html["노드 4를 설치하고 부팅합니다"].

.. 에 경고 메시지가 표시되는 경우 <<man_install3_step4,4단계>>의 지침을 따릅니다 <<man_install3_step5,5단계>>
.. 콘솔 케이블을 노드 4에서 노드 3으로 다시 전환합니다.
.. 로 이동합니다 <<man_install3_step15,15단계>>.


|===
. [[man_install3_step15]]ONTAP에 대한 노드 3을 구성합니다.
+
`set-defaults`


