= 
:allow-uri-read: 


랙에 노드 4를 설치하고, 노드 2의 연결을 노드 4로 전송하고, 노드 4를 부팅해야 합니다. 또한 노드 2 스페어, 루트에 속한 디스크, 이전에 노드 3에 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

.이 작업에 대해
노드 2에 설치된 것과 동일한 ONTAP 9 버전이 노드 4에 설치되어 있지 않으면 네트워크 부팅을 해야 합니다. 노드 4를 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 다음 지침에 따라 부팅 미디어 장치에 올바른 파일을 다운로드하여 다음 시스템 부팅에 사용할 수 있습니다. link:prepare_for_netboot.html["netboot를 준비합니다"] .

하지만 node2에 설치된 ONTAP 9와 동일하거나 그 이후 버전이 있는 경우 node4를 네트워크 부팅할 필요는 없습니다.

[IMPORTANT]
====
* AFF A800 또는 AFF C800 컨트롤러를 업그레이드하는 경우, 노드2를 제거하기 전에 섀시의 모든 드라이브가 중앙판에 단단히 고정되어 있는지 확인해야 합니다. 자세한 내용은 을 link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["AFF A800 또는 AFF C800 컨트롤러 모듈을 교체합니다"]참조하십시오.
* 저장 디스크가 있는 시스템을 업그레이드하는 경우 이 섹션 전체를 완료한 다음 섹션으로 진행해야 합니다. link:set_fc_uta_uta2_config_node4.html["노드 4에 FC 또는 UTA/UTA2 구성을 설정합니다"] 클러스터 프롬프트에서 명령을 입력합니다.


====
.단계
. [[man_install4_Step1]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드 4가 다음과 같은 경우 | 그러면... 


| 노드 3과 분리된 섀시 | 로 이동합니다 <<man_install4_Step2,2단계>>. 


| 노드 3의 동일한 섀시 | 2단계와 3단계를 건너뛰고 로 이동합니다 <<man_install4_Step4,4단계>>. 
|===
. [[man_install4_Step2]] 노드 4에 충분한 랙 공간이 있는지 확인합니다.
+
노드 4가 노드 3과 다른 섀시에 있는 경우 노드 4를 노드 2와 같은 위치에 배치할 수 있습니다. 노드 3과 노드 4가 동일한 섀시에 있는 경우 노드 4는 이미 적절한 랙 위치에 있습니다.

. 노드 모델의 _설치 및 설치 지침_ 에 나온 지침에 따라 랙에 노드 4를 설치합니다.
. [[man_install4_Step4]] 노드 4를 케이블로 연결하여 노드 2에서 노드 4로 연결을 이동합니다.
+
다음 참조는 올바른 케이블 연결에 도움이 됩니다. 로 이동합니다 link:other_references.html["참조"] 링크를 클릭합니다.

+
** node4 플랫폼에 대한 _설치 및 설정 지침_
** 디스크 쉘프 관련 절차
** HA Pair 관리 _ 설명서
+
다음 연결부에 케이블을 연결합니다.

** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트


+

NOTE: 대부분의 플랫폼 모델에 고유한 상호 연결 카드 모델이 있으므로 노드 2에서 노드 4로 상호 연결 카드/FC_VI 카드 또는 상호 연결/FC_VI 케이블 연결을 이동할 필요가 없습니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드 4가 다음과 같은 경우 | 그러면... 


| 노드 3과 동일한 섀시 | 로 이동합니다 <<man_install4_Step8,8단계>>. 


| 노드 3과 분리된 섀시 | 로 이동합니다 <<man_install4_Step6,6단계>>. 
|===
. [[man_install4_step6]] node4의 전원을 켠 다음 Ctrl-C를 눌러 부팅 환경 프롬프트에 액세스하여 부팅을 중단합니다.
+

NOTE: 노드 4를 부팅할 때 다음 메시지가 나타날 수 있습니다.

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]] 6단계에서 경고 메시지가 나타나면 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: *지연을 무시하지 마세요.  배터리 충전에 실패하면 데이터가 손실될 수 있습니다.*



. [[man_install4_Step8]]유지 관리 모드 프롬프트에서 다음 명령을 입력합니다.
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. ONTAP용 노드 4 구성:
+
`set-defaults`


