= 2단계 중에 재부팅, 패닉 또는 전원 사이클을 수행할 수 있습니다


업그레이드 단계가 서로 다를 경우 시스템이 충돌합니다(재부팅, 패닉 또는 전원 껐다 켜기). 이러한 문제의 해결 방법은 발생 시기에 따라 다릅니다.



== 2단계 중에 재부팅, 패닉 또는 전원 사이클을 수행할 수 있습니다

2단계 전후에 충돌이 발생할 수 있습니다. 이 경우 노드 1에서 노드 2로 애그리게이트를 재배치하고, 노드 1이 소유한 데이터 LIF 및 SAN LIF를 노드 2로 이동하고, 노드 1 정보를 기록하고, 노드 1을 폐기합니다.



=== HA가 활성화된 상태에서 2단계 전에 노드 1 또는 노드 2가 충돌합니다

2단계 전에 노드 1이나 노드 2가 충돌하는 경우 아직 재배치된 애그리게이트가 없고 HA 구성이 여전히 활성화되어 있습니다.

테이크오버 및 반환이 정상적으로 진행될 수 있습니다.

.단계
. 시스템에서 실행할 수 있는 EMS 메시지가 콘솔에 있는지 확인하고 권장되는 교정 조치를 취하십시오.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== HA가 활성화된 상태에서 2단계 도중 또는 직후에 노드 1이 충돌합니다

일부 또는 모든 애그리게이트가 노드 1에서 노드 2로 재배치되었지만, HA는 계속 사용하도록 설정되었습니다. 노드 2는 노드 1의 루트 볼륨과 재배치되지 않은 모든 루트 애그리게이트를 대신 사용합니다.

재배치된 애그리게이트의 소유권은 홈 소유자가 변경되지 않았기 때문에 페일오버된 비루트 애그리게이트의 소유권과 동일합니다. 노드 1이 '반환 대기 중 상태'로 전환되면 노드 2가 노드 1이 아닌 모든 Aggregate를 되돌려 줍니다.

.단계
. 완료 link:relocate_non_root_aggr_node1_node2.html#step1["1단계"] section_Relocate node1에서 node2_again으로 비루트 애그리게이트를 재배치합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== HA가 사용되지 않는 동안 2단계 후에 노드 1이 충돌합니다

노드 2는 인수되지 않지만 모든 비루트 애그리게이트에서 데이터를 계속 처리하고 있습니다.

.단계
. 노드1을 불러옵니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.
+
'storage failover show' 명령의 출력에 일부 변경 사항이 있을 수 있지만 이는 일반적인 것으로 절차에 영향을 미치지 않습니다. 문제 해결 섹션을 참조하십시오 link:issues_multiple_stages_of_procedure.html#Unexpected-storage-failover-show-command-output["예기치 않은 스토리지 페일오버 표시 명령 출력입니다"].





=== HA가 활성화된 상태에서 2단계 중 또는 이후에 노드 2에 장애가 발생합니다

노드 1은 해당 애그리게이트의 일부 또는 전부를 노드 2로 재배치했습니다. HA가 활성화되었습니다.

노드 1은 노드 2에 재배치된 자체 애그리게이트뿐만 아니라 노드 2에 모두 테이크오버됩니다. 노드 2가 '기브백 대기 중' 상태로 전환되면 노드 1은 노드 2의 모든 애그리게이트를 되돌려 줍니다.

.단계
. 완료 link:relocate_non_root_aggr_node1_node2.html#step1["1단계"] section_Relocate node1에서 node2_again으로 비루트 애그리게이트를 재배치합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 2단계 이후 및 HA를 사용하지 않도록 설정한 후 노드 2가 충돌합니다

노드 1은(는) 인수되지 않습니다.

.단계
. 노드2를 위로 올립니다.
+
노드 2가 부팅되는 동안 모든 애그리게이트에 대해 클라이언트 중단이 발생합니다.

. 나머지 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 3단계 중에 재부팅, 패닉 또는 전원 사이클을 수행할 수 있습니다

노드 3을 설치 및 부팅하고, 노드 1에서 노드 3으로 포트를 매핑하고, 노드 1과 노드 2에 속하는 데이터 LIF 및 SAN LIF를 노드 3으로 이동한 다음, 노드 2에서 노드 3으로 모든 애그리게이트를 재배치하는 동안 또는 3단계 직후에 장애가 발생할 수 있습니다.



=== 3단계에서 HA를 사용하지 않도록 설정하고 애그리게이트를 재배치할 때 노드 2가 충돌합니다

HA가 이미 비활성화되어 있기 때문에 노드 3이 노드 2 충돌 후 작동하지 않습니다.

.단계
. 노드2를 위로 올립니다.
+
노드 2가 부팅되는 동안 모든 애그리게이트에 대해 클라이언트 중단이 발생합니다.

. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 일부 또는 모든 애그리게이트를 재배치하고 3단계에서 노드 2가 충돌합니다

노드 2는 일부 또는 모든 애그리게이트를 노드 3으로 재배치하여 재배치된 애그리게이트의 데이터를 제공합니다. HA가 비활성화되었습니다.

재배치되지 않은 애그리게이트에는 클라이언트 운영 중단이 있습니다.

.단계
. 노드2를 위로 올립니다.
. 를 완료하여 나머지 애그리게이트를 재배치합니다 link:relocate_non_root_aggr_node2_node3.html#step1["1단계"] 부터 까지  section_Relocate node2에서 node3_로 비루트 애그리게이트를 이동합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 노드 3이 3단계 중에 또는 노드 2가 애그리게이트를 재배치하기 전에 노드 3이 충돌합니다

노드 2는 인수되지 않지만 모든 비루트 애그리게이트에서 데이터를 계속 처리하고 있습니다.

.단계
. 노드3을 불러옵니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 노드 3은 애그리게이트 재배치 중에 3단계 중에 충돌합니다

노드 2가 애그리게이트를 노드 3으로 재배치하는 동안 노드 3이 충돌하면 노드 2에서 나머지 애그리게이트의 재배치를 중단합니다.

노드 2는 계속해서 나머지 애그리게이트를 제공하지만, 노드 3에 이미 재배치된 애그리게이트는 노드 3이 부팅되는 동안 클라이언트 중단을 겪게 됩니다.

.단계
. 노드3을 불러옵니다.
. 완료 link:relocate_non_root_aggr_node2_node3.html#step3["3단계"] section_Relocate node2에서 node3_로 비루트 애그리게이트를 이동합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 단계 3에서 충돌 후 Node3가 부팅되지 않습니다

3단계에서는 심각한 장애로 인해 장애가 발생한 후 노드 3을 부팅할 수 없습니다.

.단계
. 기술 지원 부서에 문의하십시오.




=== 3단계 후 5단계 전에 노드 2가 충돌합니다

NODE3은 계속해서 모든 애그리게이트에서 데이터를 제공합니다. HA 쌍이 사용되지 않습니다.

.단계
. 노드2를 위로 올립니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== Node3은 3단계 후 5단계 전에 충돌합니다

Node3은 3단계 후 5단계 전에 충돌합니다. HA 쌍이 사용되지 않습니다.

.단계
. 노드3을 불러옵니다.
+
모든 애그리게이트에서 클라이언트 작동이 중단될 것입니다.

. 노드 쌍 업그레이드 절차를 계속 진행합니다.




== 5단계 중에 재부팅, 패닉 또는 전원 사이클을 수행할 수 있습니다

노드 4를 설치 및 부팅하고, 노드 2에서 노드 4로 포트를 매핑하고, 노드 2에 속하는 데이터 LIF 및 SAN LIF를 노드 3에서 노드 4로 이동한 다음, 노드 3의 모든 애그리게이트를 노드 4로 재배치하는 단계 5에서 충돌이 발생할 수 있습니다.



=== 5단계 중에 Node3이 충돌합니다

Node3는 노드 2의 일부 또는 전부를 노드 4로 재배치했습니다. Node4는 인수되지 않지만, 노드 3이 이미 재배치된 비루트 애그리게이트를 계속 제공합니다. HA 쌍이 사용되지 않습니다.

노드 3이 다시 부팅될 때까지 나머지 애그리게이트는 중단 상태가 됩니다.

.단계
. 노드3을 불러옵니다.
. 반복하여 노드 2에 속한 나머지 애그리게이트를 재배치합니다 link:relocate_node2_non_root_aggr_node3_node4.html#Step1["1단계"] 부터 까지  section_Relocate node3에서 node4_로 node2의 비 루트 애그리게이트를 이동합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.




=== 5단계 중에 Node4가 충돌합니다

Node3는 노드 2의 일부 또는 전부를 노드 4로 재배치했습니다. Node3는 인수된 것이 아니라, 노드 3이 소유한 비루트 애그리게이트뿐만 아니라 재배치되지 않은 Aggregate를 계속 제공합니다. HA가 비활성화되었습니다.

노드 4를 다시 부팅할 때까지 이미 재배치되었던 루트 이외의 애그리게이트는 운영 중단이 있습니다.

.단계
. 노드4를 위로 올립니다.
. 를 다시 완료하여 노드 2에 속한 나머지 애그리게이트를 재배치합니다 link:relocate_node2_non_root_aggr_node3_node4.html#Step1["1단계"] 부터 까지  in_Relocate node3에서 node4_로 node2의 비루트 애그리게이트를 이동합니다.
. 노드 쌍 업그레이드 절차를 계속 진행합니다.

