= 노드 3에서 FC 포트를 구성합니다
:allow-uri-read: 




== 노드 3에서 FC 포트를 구성합니다

노드3에 FC 포트가 있는 경우(온보드 또는 추가 FC 어댑터에 있음), 시스템이 배송될 때 포트가 미리 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다.  포트를 구성하지 않으면 서비스가 중단될 수 있습니다.

.시작하기 전에
에 저장한 노드 1의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 있는 경우, 에서 포트를 구성합니다 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 클러스터 프롬프트에서 이 섹션의 명령을 입력하세요.

.단계
. 시스템의 모든 FC 및 컨버지드 네트워크 어댑터에 대한 정보를 표시합니다.
+
`system node hardware unified-connect show`

. node3의 FC 설정을 node1에서 이전에 캡처한 설정과 비교합니다.
. [[man_config_3_step3]]다음 작업 중 하나를 수행하세요.
+
[cols="35,65"]
|===
| 새 노드의 기본 FC 설정이... | 그러면... 


| 노드 1에서 캡처한 것과 동일합니다 | 로 가다<<man_config_3_step9,9단계>> . 


| 노드 1에서 캡처한 것과 다릅니다 | 로 가다<<man_config_3_step4,4단계>> . 
|===
. 다음 명령 중 하나를 입력하여 필요에 따라 node3의 FC 포트를 수정합니다.
+
** 타겟 포트를 프로그래밍하려면
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 이니시에이터 포트를 프로그래밍하려면:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` FC4 유형: 타겟 또는 이니시에이터입니다.



. 다음 명령을 입력하고 출력을 검토하여 새로운 설정을 확인하세요.
+
`system node hardware unified-connect show`

. 유지 관리 모드 종료:
+
`halt`

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 부트 환경 프롬프트에서 노드3을 부트합니다.
+
`boot_ontap`

. [[man_config_3_step9]]다음 작업 중 하나를 수행하세요.
+
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우 로 이동하십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우 건너뛰십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>> 로 이동합니다 link:map_ports_node1_node3.html["노드 1의 포트를 노드 3으로 매핑합니다"].



