= 
:allow-uri-read: 


원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 3을 온라인으로 설정한 후 LIF가 정상 작동하는지 확인합니다.

.단계
. [[step1]] 노드 중 하나에 다음 명령을 입력하고 출력을 캡처하여 node2가 소유하지 않는 모든 NAS 데이터 LIF를 나열합니다.
+
'network interface show-role data-curr-node_node2_-is-home false-home-node_node3_'

. [[Worksheet_step2]] SAN LIF에 클러스터가 구성되어 있으면 SAN LIF의 어댑터 및 '스위치 포트' 구성 정보를 여기에 기록합니다 link:worksheet_information_before_moving_san_lifs_node3.html["워크시트"] 나중에 사용할 수 있습니다.
+
.. 노드 2의 SAN LIF를 나열하고 출력을 검사합니다.
+
'network interface show-data-protocol fc *'

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 기존 설정을 나열하고 출력을 검사합니다.
+
FCP 어댑터 show-fields switch-port, fc-WWPN입니다

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. [[step3]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드 1인 경우 | 그러면... 


| 인터페이스 그룹 또는 VLAN이 구성되어 있었습니다 | 로 이동합니다 <<man_lif_verify_3_step3,4단계>>. 


| 인터페이스 그룹 또는 VLAN이 구성되지 않았습니다 | 4단계를 건너뛰고 로 이동합니다 <<man_lif_verify_3_step4,5단계>>. 
|===
. [[man_lif_verify_3_step3]] 다음 하위 단계를 수행하여 노드 2에서 노드 3으로 노드 1에 원래 있던 인터페이스 그룹 및 VLAN에 호스팅된 NAS 데이터 LIF를 모두 마이그레이션합니다.
+
.. [[man_lif_verify_3_substa]] 인터페이스 그룹의 노드 1에 있던 노드 2에 호스팅된 데이터 LIF를 노드 3의 포트로 마이그레이션: 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
'network interface migrate-vserver_vserver_name_-lif_LIF_name_-destination-node_node3_ – destination-port_NetPort|ifgrp_'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_3_substepa,하위 단계 A>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver_vserver_name_-lif_LIF_name_-home-node_node3_-home-port_NetPort|ifgrp_'

.. [[man_lif_verify_3_substeepc]] 이전에 VLAN 포트의 노드 1에 속해 있던 노드 2에 호스팅된 데이터 LIF를 노드 3의 포트로 마이그레이션: 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
'network interface migrate-vserver_vserver_name_-lif_LIF_name_-destination-node_node3_ – destination-port_NetPort|ifgrp_'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_3_substepc,하위 단계 c>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver_vserver_name_-lif_LIF_name_-home-node_node3_-home-port_NetPort|ifgrp_'



. [[man_lif_verify_3_step4]] 다음 작업 중 하나를 수행합니다.
+
[cols="25,75"]
|===
| 클러스터가 구성된 경우... | 그러면... 


| NAS | 완료 <<man_lif_verify_3_step5,6단계>> 및 <<man_lif_verify_3_step6,7단계>>, 8단계를 건너뛰고 완료합니다 <<man_lif_verify_3_step8,9단계>> 부터 까지 <<man_lif_verify_3_step11,12단계>>. 


| 산 | 업그레이드 시 노드의 모든 SAN LIF를 사용하지 않도록 설정합니다. 'network interface modify -vserver_vserver_name_-lif_LIF_name_-home-node_to_upgrade_-home-port_NetPort | ifgrp_-status-admin down' 
|===

