---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: 수동 ARL 업그레이드 절차를 사용하여 ONTAP 9.7 이하를 실행하는 컨트롤러 하드웨어를 업그레이드하고 비 루트 애그리게이트를 재배치할 수 있습니다. 
---
= ARL 업그레이드 절차에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 절차에서는 ONTAP 9.7 또는 이전 버전을 실행하는 시스템에서 수동 집계 재배치(ARL)를 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다.

다음 업그레이드 중 하나를 수행하는 경우 이 ARL 절차를 사용할 수 있습니다.

* FAS 시스템에서 FAS 시스템으로
* AFF 시스템에서 AFF 시스템으로


이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 LIF(데이터 논리 인터페이스)를 마이그레이션하고 계속 진행할 때 새 컨트롤러의 네트워크 포트를 인터페이스 그룹에 할당합니다.


NOTE: 이 문서에서 원래 노드는 _node1_과 _node2_라고 하며, 새로운 노드는 _node3_과 _node4_라고 합니다.  설명된 절차 동안, node1은 node3으로 바뀌고, node2는 node4로 바뀌었습니다.  _node1_, _node2_, _node3_, _node4_라는 용어는 원래 노드와 새 노드를 구별하는 데에만 사용됩니다.  절차를 따를 때, 원래 노드와 새 노드의 실제 이름을 바꿔야 합니다.  하지만 실제로 노드의 이름은 변경되지 않습니다. 컨트롤러 하드웨어가 업그레이드된 후에는 node3의 이름이 node1이 되고, node4의 이름이 node2가 됩니다.

.중요 정보:
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 다음을 읽고 이해해야 합니다. link:guidelines_upgrade_with_arl.html["ARL을 사용한 컨트롤러 업그레이드 지침"] 그리고 link:arl_upgrade_workflow.html["ARL 업그레이드 워크플로"] 업그레이드를 시작하기 전에.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 사용한 경우, 특히 컨트롤러가 7-Mode에서 Data ONTAP를 실행 중인 경우 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA(고가용성) 쌍에 대해 이 절차를 별도로 수행해야 합니다.


* 이 절차는 ONTAP 9.5 이전 버전을 실행하는 MetroCluster 4노드 및 8노드 구성에 적용됩니다. ONTAP 9.6 이상을 실행하는 MetroCluster 구성의 경우 로 이동하십시오 link:other_references.html["참조"] "system controller replace" 명령을 사용하여 ONTAP 9.5를 실행하는 컨트롤러 하드웨어를 ONTAP 9.7_로 업그레이드하려면

