---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 수동 ARL 업그레이드 절차를 사용하여 ONTAP 9.7 이하를 실행하는 컨트롤러 하드웨어를 업그레이드하고 비 루트 애그리게이트를 재배치할 수 있습니다. 
---
= ARL 업그레이드 절차에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 절차에서는 ONTAP 9.7 또는 이전 버전을 실행하는 시스템에서 수동 집계 재배치(ARL)를 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다.

다음 업그레이드 중 하나를 수행하는 경우 이 ARL 절차를 사용할 수 있습니다.

* FAS 시스템에서 FAS 시스템으로
* FlexArray 가상화 소프트웨어 또는 V-Series 시스템을 사용하는 시스템에 FAS 시스템 구축
* AFF 시스템에서 AFF 시스템으로
* FlexArray 가상화 소프트웨어 또는 V 시리즈 시스템이 포함된 시스템에 어레이 LUN이 없는 경우 FlexArray 가상화 소프트웨어 또는 V-Series 시스템이 있는 시스템에서 FAS 시스템으로.
* V-Series 시스템을 FlexArray 가상화 소프트웨어 또는 V-Series 시스템이 포함된 시스템으로 관리


이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 LIF(데이터 논리 인터페이스)를 마이그레이션하고 계속 진행할 때 새 컨트롤러의 네트워크 포트를 인터페이스 그룹에 할당합니다.


NOTE: 이 문서에서는 원래 노드를 _node1_ 및 _node2_ 라고 하며 새 노드를 _node3_ 및 _node4_ 라고 합니다. 이 절차를 수행하는 동안 노드 1은 노드 3으로 대체되고 노드 2는 노드 4로 대체됩니다. _node1_,_node2_,_node3_ 및_node4_ 용어는 원래 노드와 새 노드를 구별하는 데만 사용됩니다. 절차를 따를 때는 원래 노드와 새 노드의 실제 이름을 대체해야 합니다. 그러나 실제로 노드 이름은 변경되지 않습니다. node3에는 node1이라는 이름이 있고, node4에는 컨트롤러 하드웨어를 업그레이드한 후 node2라는 이름이 있습니다. 이 문서에서는 FlexArray 가상화 소프트웨어가 설치된 _systems_라는 용어를 사용하여 이러한 새 플랫폼에 속하는 시스템을 참조합니다. 용어 _V-Series system_은 스토리지 어레이에 연결할 수 있는 별도의 하드웨어 시스템을 나타냅니다

.중요 정보:
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 다음을 읽고 이해해야 합니다. link:guidelines_upgrade_with_arl.html["ARL을 사용한 컨트롤러 업그레이드 지침"] 그리고 link:arl_upgrade_workflow.html["ARL 업그레이드 워크플로"] 업그레이드를 시작하기 전에.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 사용한 경우, 특히 컨트롤러가 7-Mode에서 Data ONTAP를 실행 중인 경우 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA(고가용성) 쌍에 대해 이 절차를 별도로 수행해야 합니다.
* 이 절차는 FAS 시스템, V-Series 시스템, AFF 시스템 및 FlexArray 가상화 소프트웨어가 설치된 시스템에 적용됩니다. ONTAP 9 이후 출시된 FAS 시스템은 필요한 라이센스가 설치된 경우 스토리지 시스템에 연결할 수 있습니다. 기존 V 시리즈 시스템은 ONTAP 9에서 지원됩니다. 스토리지 어레이 및 V-Series 모델에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 연결하고 _V 시리즈 지원 매트릭스_를 참조하십시오.


* 이 절차는 ONTAP 9.5 이전 버전을 실행하는 MetroCluster 4노드 및 8노드 구성에 적용됩니다. ONTAP 9.6 이상을 실행하는 MetroCluster 구성의 경우 로 이동하십시오 link:other_references.html["참조"] "system controller replace" 명령을 사용하여 ONTAP 9.5를 실행하는 컨트롤러 하드웨어를 ONTAP 9.7_로 업그레이드하려면

