---
sidebar: sidebar 
permalink: upgrade-arl-manual/install_boot_node3.html 
keywords: install, boot, node3, rack, transfer connections, v-series, storage disks 
summary: ONTAP 9.7 이하를 실행하는 컨트롤러에서 수동 ARL 업그레이드 중에 node3을 설치 및 부팅하고 ONTAP 소프트웨어를 설치합니다. 
---
= 노드3을 설치하고 부팅합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 또한 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 이전에 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

.이 작업에 대해
node1에 설치된 것과 동일한 버전의 ONTAP 9가 없는 경우 node3을 네트워크 부팅해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다. 을 link:prepare_for_netboot.html["netboot를 준비합니다"]참조하십시오.

하지만 node1에 설치된 ONTAP 9와 동일하거나 그 이후 버전이 있는 경우 node3을 네트워크 부팅할 필요는 없습니다.

[IMPORTANT]
====
* AFF A800 또는 AFF C800 컨트롤러를 업그레이드하는 경우, 노드1을 제거하기 전에 섀시의 모든 드라이브가 미드플레인에 단단히 고정되어 있는지 확인해야 합니다. 자세한 내용은 다음을 참조하세요. link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["AFF A800 또는 AFF C800 컨트롤러 모듈을 교체합니다"].
* 저장 디스크가 있는 시스템을 업그레이드하는 경우 이 섹션 전체를 완료한 다음 다음으로 이동해야 합니다. link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 그리고 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 클러스터 프롬프트에서 명령을 입력합니다.


====
.단계
. [[man_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치에 가까운 자체 랙 공간에 넣어야 합니다.

. [[step2]] 노드 모델의 _설치 및 설치 지침_ 에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면 노드 3을 부팅할 때 노드는 이중 섀시 구성에 있는 것처럼 작동하며 노드 4를 부팅할 때 노드 간의 상호 연결이 나타나지 않습니다.

. [[step3]] 노드 3을 케이블로 연결하고 노드 1에서 노드 3으로 연결을 이동합니다.
+
다음 참조는 올바른 케이블 연결에 도움이 됩니다. 로 이동합니다 link:other_references.html["참조"] 링크를 클릭합니다.

+
** node3 플랫폼에 대한 _설치 및 설정 지침_
** 디스크 쉘프 관련 절차
** HA Pair 관리 _ 설명서


+
다음 연결부에 케이블을 연결합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[man_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]에 경고 메시지가 표시되면 <<man_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: *지연 시간을 무시하지 마세요. 배터리 충전을 허용하지 않으면 데이터가 손실될 수 있습니다.*



. 유지 관리 모드 프롬프트에서 다음 명령을 입력합니다.
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드할 시스템이...에 있는 경우 | 그러면... 


| 이중 섀시 구성(다른 섀시 내 컨트롤러 포함) | 로 가다<<man_install3_step8,8단계>> . 


| 단일 섀시 구성(동일한 섀시 내 컨트롤러 포함)  a| 
.. 콘솔 케이블을 노드 3에서 노드 4로 전환합니다.
.. 노드 4의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단한 다음, 부팅 환경 프롬프트에 액세스합니다.
+
두 컨트롤러가 동일한 섀시에 있는 경우 전원이 이미 켜져 있어야 합니다.

+

NOTE: 부팅 환경 프롬프트에 node4를 그대로 두면 의 node4로 돌아갑니다 link:install_boot_node4.html["노드 4를 설치하고 부팅합니다"].

.. 에 경고 메시지가 표시되는 경우 <<man_install3_step4,4단계>>의 지침을 따릅니다 <<man_install3_step5,5단계>>
.. 콘솔 케이블을 노드 4에서 노드 3으로 다시 전환합니다.
.. 로 가다<<man_install3_step8,8단계>> .


|===
. [[man_install3_step8]] ONTAP 에 대한 node3 구성:
+
`set-defaults`

. [[man_install3_step16]]NetApp Storage Encryption(NSE) 드라이브가 설치되어 있는 경우 다음 단계를 수행하세요.
+

NOTE: 절차의 앞부분에서 아직 수행하지 않은 경우 기술 자료 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["드라이브가 FIPS 인증되었는지 확인하는 방법"^] 사용 중인 자체 암호화 드라이브의 유형을 확인합니다.

+
.. 설정 `bootarg.storageencryption.support` 를 선택합니다 `true` 또는 `false`:
+
[cols="35,65"]
|===
| 다음 드라이브를 사용 중인 경우… | 그러면... 


| NSE 드라이브가 FIPS 140-2 레벨 2 자체 암호화 요구사항을 충족합니다 | `setenv bootarg.storageencryption.support *true*` 


| NetApp 비 FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
동일한 노드 또는 HA 쌍에서 다른 유형의 드라이브와 FIPS 드라이브를 혼합할 수 없습니다.

동일한 노드 또는 HA 쌍에서 SED를 비암호화 드라이브와 혼합할 수 있습니다.

====
.. 온보드 키 관리 정보 복원에 대한 자세한 내용은 NetApp 지원에 문의하십시오.


. [[man_install3_step17]] 노드 3에 설치된 ONTAP 버전이 노드 1에 설치된 ONTAP 9 버전과 같거나 이후인 경우 디스크를 새 노드 3에 나열하고 재할당합니다.
+
`boot_ontap`

+

WARNING: 이 새 노드를 다른 클러스터 또는 HA 쌍에서 사용한 적이 있다면 를 실행해야 합니다 `wipeconfig` 계속 진행하기 전에 그렇지 않으면 서비스 운영 중단이나 데이터 손실이 발생할 수 있습니다. 교체 컨트롤러가 이전에 사용된 경우, 특히 7-Mode에서 ONTAP를 실행 중인 컨트롤러의 경우 기술 지원 부서에 문의하십시오.

. CTRL-C를 눌러 부팅 메뉴를 표시합니다.
. [[man_install3_step19]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| node3의 올바른 또는 현재 ONTAP 버전이 _NOT_에 있지 않습니다 | 로 가다<<man_install3_step13,13단계>> . 


| 노드 3의 ONTAP 버전이 올바르고 현재 버전입니다 | 로 가다<<man_install3_step18,18단계>> . 
|===
. [[man_install3_step13]]다음 작업 중 하나를 선택하여 네트워크 부팅 연결을 구성합니다.
+

NOTE: 관리 포트와 IP를 netboot 연결로 사용해야 합니다. 데이터 LIF IP를 사용하지 마십시오. 업그레이드를 수행하는 동안 데이터 중단이 발생할 수 있습니다.

+
[cols="35,65"]
|===
| DHCP(Dynamic Host Configuration Protocol)가 다음과 같은 경우 | 그러면... 


| 실행 중입니다 | 부팅 환경 프롬프트에 다음 명령을 입력하여 연결을 자동으로 구성합니다.
`ifconfig e0M -auto` 


| 실행 중이 아닙니다  a| 
부팅 환경 프롬프트에 다음 명령을 입력하여 연결을 수동으로 구성합니다.
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 스토리지 시스템의 IP 주소입니다(필수).
`_netmask_` 스토리지 시스템의 네트워크 마스크입니다(필수).
`_gateway_` 는 스토리지 시스템의 게이트웨이입니다(필수).
`_dns_addr_` 네트워크에 있는 이름 서버의 IP 주소입니다(선택 사항).
`_dns_domain_` DNS(Domain Name Service) 도메인 이름입니다. 이 선택적 매개 변수를 사용하는 경우 netboot 서버 URL에 정규화된 도메인 이름이 필요하지 않습니다. 서버의 호스트 이름만 있으면 됩니다.


NOTE: 인터페이스에 다른 매개 변수가 필요할 수 있습니다. 를 입력합니다 `help ifconfig` 펌웨어 프롬프트에서 세부 정보를 확인합니다.

|===
. node3에서 netboot를 수행합니다.
+
[cols="35,65"]
|===
| 대상... | 그러면... 


| FAS/AFF8000 시리즈 시스템 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| 기타 모든 시스템 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
를 클릭합니다 `<path_to_the_web-accessible_directory>` 를 다운로드한 위치로 이동합니다 `<ontap_version>_image.tgz` 인치 link:prepare_for_netboot.html#man_netboot_Step1["1단계"] netboot_에 대한 준비 섹션에서

+

NOTE: 부팅을 중단하지 마십시오.

. 부팅 메뉴에서 먼저 *(7) 새 소프트웨어 설치* 옵션을 선택하세요.
+
이 메뉴 옵션은 새 ONTAP 이미지를 다운로드하여 부팅 장치에 설치합니다.

+
다음 메시지는 무시하십시오.

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
참고 사항은 ONTAP의 무중단 업그레이드에는 적용되고 컨트롤러 업그레이드에는 적용되지 않습니다.

+

NOTE: 항상 netboot를 사용하여 새 노드를 원하는 이미지로 업데이트합니다. 다른 방법을 사용하여 새 컨트롤러에 이미지를 설치할 경우 잘못된 이미지가 설치될 수 있습니다. 이 문제는 모든 ONTAP 릴리스에 적용됩니다. 옵션과 결합된 netboot 절차 `(7) Install new software` 부팅 미디어를 지우고 두 이미지 파티션 모두에 동일한 ONTAP 버전 ONTAP를 배치합니다.

. 절차를 계속하라는 메시지가 표시되면 다음을 입력하십시오. `y` , 패키지를 입력하라는 메시지가 나타나면 다음 URL을 입력하세요.
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. 다음 하위 단계를 완료합니다.
+
.. 를 입력합니다 `n` 다음 프롬프트가 표시될 때 백업 복구를 건너뛰려면 다음을 수행합니다.
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 를 입력하여 재부팅합니다 `y` 다음과 같은 메시지가 표시될 때:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
부팅 장치가 다시 포맷되고 구성 데이터를 복원해야 하기 때문에 컨트롤러 모듈이 재부팅되지만 부팅 메뉴에서 중지됩니다.



. [[man_install3_step18]]*(5) 유지 관리 모드 부팅*을 입력하여 선택하십시오. `5` , 그리고 입력하세요 `y` 부팅을 계속할지 묻는 메시지가 표시됩니다.
. [[man_install3_step26]] 계속하기 전에 로 이동하십시오 link:set_fc_uta_uta2_config_node3.html["노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다"] 노드의 FC 또는 UTA/UTA2 포트를 필요에 따라 변경합니다.
+
이 섹션에서 권장한 대로 변경하고 노드를 재부팅한 다음 유지보수 모드로 전환합니다.

. node3의 시스템 ID를 찾으세요:
+
`disk show -a`

+
다음 예와 같이 노드의 시스템 ID와 해당 디스크에 대한 정보가 표시됩니다.

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: 메시지가 표시될 수 있습니다 `disk show: No disks match option -a.` 명령을 입력한 후 이 메시지는 오류 메시지가 아니므로 절차를 계속할 수 있습니다.

. [[man_install3_step21]]node1의 예비 디스크, 루트에 속하는 모든 디스크 및 이전에 node2로 재배치되지 않은 모든 비루트 집계를 다시 할당합니다.link:relocate_non_root_aggr_node1_node2.html["노드 1에서 노드 2로 비루트 애그리게이트를 재배치합니다"] .
+
의 적절한 양식을 입력합니다 `disk reassign` 시스템에 공유 디스크가 있는지 여부에 따른 명령:

+

NOTE: 시스템에서 공유 디스크, 하이브리드 애그리게이트 또는 둘 다 있는 경우 올바른 를 사용해야 합니다 `disk reassign` 다음 표에서 명령을 입력합니다.

+
[cols="35,65"]
|===
| 디스크 유형이... | 그런 다음 명령을 실행합니다... 


| 공유 디스크를 사용합니다 | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| 공유 디스크 사용 안 됨 | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
의 경우 `_node1_sysid_` 값, 에서 캡처한 정보를 사용합니다 link:record_node1_information.html["노드1 정보를 기록합니다"]. 를 눌러 에 대한 값을 얻습니다 `_node3_sysid_`, 를 사용합니다 `sysconfig` 명령.

+

NOTE: 를 클릭합니다 `-p` 옵션은 공유 디스크가 있는 경우에만 유지보수 모드에서 필요합니다.

+
를 클릭합니다 `disk reassign` 명령을 실행하면 가 할당된 디스크만 다시 할당됩니다 `_node1_sysid_` 현재 소유자입니다.

+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]] Enter 키를 누릅니다 `n`.
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]] Enter 키를 누릅니다 `y`
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]] Enter 키를 누릅니다 `y`.
. [[man_install3_step32] 외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node1 애그리게이트를 루트로 설정하여 node3이 node1의 루트 애그리게이트에서 부팅되는지 확인하십시오.
+

WARNING: * 경고 *: 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다.

+
다음 절차에서는 노드 3이 노드 1의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 노드 1 애그리게이트에 대한 RAID, plex 및 체크섬 정보를 확인합니다.
+
`aggr status -r`

.. node1 애그리게이트의 상태를 확인합니다.
+
`aggr status`

.. 필요한 경우 node1 애그리게이트를 온라인 상태로 전환합니다.
+
`aggr_online _root_aggr_from_node1_`

.. 노드 3이 원래 루트 애그리게이트로부터 부팅하지 않도록 합니다.
`aggr offline _root_aggr_on_node3_`
.. 노드 1의 루트 애그리게이트를 노드 3의 새 루트 애그리게이트로 설정합니다.
+
`aggr options _aggr_from_node1_ root`

.. 노드 3의 루트 애그리게이트가 오프라인 상태이고 노드 1에서 가져온 디스크의 루트 애그리게이트가 온라인 상태이고 루트:
+
`aggr status`

+

NOTE: 이전 하위 단계를 수행하지 않으면 노드 3이 내부 루트 애그리게이트에서 부팅되거나 시스템에서 새 클러스터 구성이 있다고 가정하거나 클러스터 구성을 확인하라는 메시지가 표시될 수 있습니다.

+
다음은 명령 출력의 예입니다.



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]] 컨트롤러와 섀시가 로 구성되었는지 확인합니다 `ha`:
+
`ha-config show`

+
다음 예제에서는 ha-config show 명령의 출력을 보여 줍니다.

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
시스템은 HA 쌍 또는 독립 실행형 구성에 관계없이 PROM(프로그래밍 가능한 ROM)으로 기록합니다. 독립 실행형 시스템 또는 HA 쌍 내의 모든 구성 요소에서 상태가 동일해야 합니다.

+
컨트롤러 및 섀시가 "ha"로 구성되지 않은 경우 다음 명령을 사용하여 구성을 수정하십시오.

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
MetroCluster 구성이 있는 경우 다음 명령을 사용하여 컨트롤러 및 섀시를 수정합니다.

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]] 노드 3의 메일박스를 제거합니다.
+
`mailbox destroy local`

+
콘솔에 다음 메시지가 표시됩니다.

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]] Enter 키를 누릅니다 `y` 로컬 사서함을 제거할 것인지 확인하는 메시지가 표시됩니다.
. [[man_install3_step36]] 유지보수 모드 종료:
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. [[man_install3_step37]] 노드2에서 시스템 날짜, 시간 및 시간대를 확인합니다.
+
`date`

. [[man_install3_step38]]노드 3에서 부팅 환경 프롬프트에서 날짜를 확인합니다.
+
`show date`

. [[man_install3_step39]] 필요한 경우 노드 3의 날짜를 설정합니다.
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]] 노드 3에서 부팅 환경 프롬프트에서 시간을 확인합니다.
+
`show time`

. [[man_install3_step41]] 필요한 경우 노드 3의 시간을 설정합니다.
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]파트너 시스템 ID가 다음에서 언급한 대로 올바르게 설정되었는지 확인하십시오.<<man_install3_step21,21단계>> -p 스위치에서:
+
`printenv partner-sysid`

. [[man_install3_step43]] 필요한 경우 노드 3의 파트너 시스템 ID를 설정합니다.
+
`setenv partner-sysid _node2_sysid_`

+
설정을 저장합니다.

+
`saveenv`

. [[man_install3_step44]] 부트 환경 프롬프트에서 부팅 메뉴에 액세스합니다.
+
`boot_ontap menu`

. [[man_install3_step45]] 부팅 메뉴에서 * (6) 백업 구성에서 플래시 업데이트 * 를 입력하여 선택합니다 `6` 메시지가 표시됩니다.
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]] Enter 키를 누릅니다 `y` 메시지가 표시됩니다.
+
부팅이 정상적으로 진행되면 시스템에서 시스템 ID 불일치를 확인하라는 메시지를 표시합니다.

+

NOTE: 시스템이 두 번 재부팅된 후 불일치 경고가 표시될 수 있습니다.

. [[man_install3_step47]] 다음 예와 같이 불일치를 확인합니다.
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
노드가 재부팅 1회 과정을 거치는 동안 정상적으로 부팅될 수 있습니다.

. [[man_install3_step48]]노드 3에 로그인합니다.

