---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node2_node4.html 
keywords: map, node2, node4, physical ports, cluster, network, connectivity 
summary: 노드 2의 물리적 포트가 노드 4의 물리적 포트에 올바르게 매핑되는지 확인합니다. 
---
= 노드 2의 포트를 노드 4로 매핑합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2의 물리적 포트가 노드 4의 물리적 포트에 올바르게 매핑되는지 확인해야 합니다. 이렇게 하면 노드 4가 클러스터의 다른 노드 및 업그레이드 후 네트워크와 통신할 수 있습니다.

이 정보에 액세스하려면 새 노드의 포트에 대한 정보가 이미 있어야 합니다. 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크 이 섹션의 뒷부분에서 정보를 사용합니다.

노드 4의 소프트웨어 구성은 노드 4의 물리적 연결과 일치해야 하며, 업그레이드를 계속하기 전에 IP 연결을 복원해야 합니다.

포트 설정은 노드 모델에 따라 다를 수 있습니다. 원래 노드의 포트 및 LIF 구성이 새 노드의 구성을 계획할 시스템과 호환되도록 해야 합니다. 이는 새 노드가 부팅될 때 동일한 구성을 재생하므로 Data ONTAP은 노드 4를 부팅할 때 노드 2에서 사용된 동일한 포트에 LIF를 호스팅하려고 시도하기 때문입니다.

따라서 노드 2의 물리적 포트가 노드 4의 물리적 포트에 직접 매핑되지 않으면 부팅 후 클러스터, 관리 및 네트워크 연결을 복구하기 위해 소프트웨어 구성을 변경해야 합니다. 또한 노드 2의 클러스터 포트가 노드 4의 클러스터 포트에 직접 매핑되지 않는 경우, 노드 4는 재부팅 시 올바른 물리적 포트에 클러스터 LIF를 호스팅하도록 소프트웨어 구성을 변경하기 전까지 쿼럼에 자동으로 다시 참가하지 않을 수 있습니다.

.단계
. 다음 표에서 노드 2, 포트, 브로드캐스트 도메인 및 IPspace의 노드 2 케이블링 정보를 모두 기록:
+
[cols="7*"]
|===
| LIF | 노드2 포트 | 노드2 IPspace | 노드2 브로드캐스트 도메인 | Node4 포트 | 노드 4 IPspace | Node4 브로드캐스트 도메인 


| 클러스터 1 |  |  |  |  |  |  


| 클러스터 2 |  |  |  |  |  |  


| 클러스터 3 |  |  |  |  |  |  


| 클러스터 4 |  |  |  |  |  |  


| 클러스터 5 |  |  |  |  |  |  


| 클러스터 6 |  |  |  |  |  |  


| 노드 관리 |  |  |  |  |  |  


| 클러스터 관리 |  |  |  |  |  |  


| 데이터 1 |  |  |  |  |  |  


| 데이터 2 |  |  |  |  |  |  


| 데이터 3 |  |  |  |  |  |  


| 데이터 4 |  |  |  |  |  |  


| 산 |  |  |  |  |  |  


| 인터클러스터 포트 |  |  |  |  |  |  
|===
+
이 정보를 얻는 단계는 "노드 2 기록 정보" 섹션을 참조하십시오.

. 에서 동일한 절차를 사용하여 이전 표에 노드 4, 포트, 브로드캐스트 도메인, IPspace의 모든 케이블 연결 정보를 기록합니다 link:record_node2_information.html["노드2 정보를 기록합니다"] 섹션을 참조하십시오.
. 스위치가 없는 2노드 클러스터인지 확인하려면 다음 단계를 수행하십시오.
+
.. 권한 수준을 고급으로 설정합니다.
.. 스위치가 없는 2노드 클러스터인지 확인합니다.
+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
이 명령의 값은 시스템의 물리적 상태와 일치해야 합니다.

.. 관리 권한 레벨로 돌아갑니다.
+
[listing]
----
cluster::*> set -privilege admin
cluster::>
----


. 다음 단계를 수행하여 노드 4를 쿼럼에 넣습니다.
+
.. 부팅 노드4. 을 참조하십시오 link:install_boot_node4.html["노드 4 설치 및 부팅"] 아직 부팅하지 않은 경우 노드를 부팅합니다.
.. 새 클러스터 포트가 클러스터 브로드캐스트 도메인에 있는지 확인합니다.
+
'network port show -node <node> -port <port> -fields broadcast-domain' 다음 예에서는 node4의 클러스터 도메인에 포트 "e0a"가 있음을 보여 줍니다.

+
[listing]
----
cluster::> network port show -node node4 -port e0a -fields broadcast-domain

node       port broadcast-domain
---------- ---- ----------------
node4      e1a  Cluster
----
.. 클러스터 포트가 Cluster broadcast-domain에 없는 경우 다음 명령을 사용하여 추가합니다.
+
'broadcast-domain add-ports-IPSpace Cluster-broadcast-domain Cluster-ports <node:port>'

.. 클러스터 브로드캐스트 도메인에 올바른 포트를 추가합니다.
+
네트워크 포트 수정-노드-포트-IPSpace 클러스터-MTU 9000

+
이 예제에서는 노드 4에 클러스터 포트 "e1b"를 추가합니다.

+
네트워크 포트 수정 노드 노드4포트 e1b-IPSpace 클러스터-MTU 9000

+

NOTE: MetroCluster 구성의 경우, 포트가 동기화 대상 SVM의 LIF를 호스팅하는 포트 및 다음에 대한 오류(이에 제한되지 않음)와 연결되어 있으므로 포트의 브로드캐스트 도메인을 변경하지 못할 수 있습니다.

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
원격 사이트의 해당 동기화 소스 SVM에서 다음 명령을 입력하여 동기화 대상 LIF를 적절한 포트에 재할당합니다.

+
'MetroCluster vserver resync -vserver <vserver_name>'

.. 클러스터 LIF를 각 LIF에 대해 한 번씩 새 포트로 마이그레이션합니다.
+
'network interface migrate-vserver cluster-lif <lif_name>-source-node node4-destination-node node4-destination-port <port_name>'

.. 클러스터 LIF의 홈 포트를 수정합니다.
+
'network interface modify -vserver Cluster-lif <lif_name> – home-port <port_name>'

.. 클러스터 브로드캐스트 도메인에서 이전 포트를 제거합니다.
+
네트워크 포트 브로드캐스트 도메인 제거 포트

+
이 명령을 실행하면 노드 4의 '네트워크 포트 브로드캐스트-도메인 제거-포트-IPSpace 클러스터-브로드캐스트-도메인 클러스터-포트 노드4:e0d'에서 포트 "e0d"가 제거됩니다

.. 노드 4가 쿼럼에 다시 연결되었는지 확인합니다.
+
클러스터 show-node node4-fields 상태



. [[man_map_2_step5]] 클러스터 LIF 및 노드 관리/클러스터 관리 LIF를 호스팅하는 브로드캐스트 도메인을 조정합니다. 각 브로드캐스트 도메인에 올바른 포트가 포함되어 있는지 확인합니다. 호스팅 중이거나 LIF의 홈 단계에 있는 브로드캐스트 도메인 간에 포트를 이동할 수 없으므로 다음 단계에 표시된 대로 LIF를 마이그레이션 및 수정해야 할 수 있습니다.
+
.. LIF의 홈 포트를 표시합니다.
+
네트워크 인터페이스 보기 필드, 홈 노드, 홈 포트

.. 이 포트가 포함된 브로드캐스트 도메인을 표시합니다.
+
'network port broadcast-domain show-ports <node_name:port_name>'

.. 브로드캐스트 도메인에서 포트 추가 또는 제거:
+
네트워크 포트 브로드캐스트 도메인 추가 포트

+
네트워크 포트 브로드캐스트 도메인 제거 포트

.. LIF의 홈 포트 수정:
+
'network interface modify -vserver <vserver_name> -lif <lif_name> – home-port <port_name>'



. 필요한 경우 에 나와 있는 것과 동일한 명령을 사용하여 인터클러스터 브로드캐스트 도메인을 조정하고 인터클러스터 LIF를 마이그레이션합니다 <<man_map_2_step5,5단계>>.
. 필요한 경우 에 나와 있는 것과 동일한 명령을 사용하여 다른 브로드캐스트 도메인을 조정하고 데이터 LIF를 마이그레이션합니다 <<man_map_2_step5,5단계>>.
. 노드 2에 노드 4에 더 이상 존재하지 않는 포트가 있는 경우 다음 단계에 따라 포트를 삭제합니다.
+
.. 다음 두 노드 중 하나에서 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

.. 포트 삭제하기:
+
'network port delete-node <node_name> - port <port_name>'

.. 관리자 수준으로 돌아가기:
+
'Set-Privilege admin'입니다



. 모든 LIF 페일오버 그룹 'network interface modify -failover -group <failover_group> -failover -policy <failover_policy>'을 조정합니다
+
다음 명령을 실행하면 페일오버 정책이 브로드캐스트 도메인 전체에 대해 설정되고 페일오버 그룹 fg1의 포트가 노드 4의 LIF data1의 페일오버 타겟으로 사용됩니다.

+
'network interface modify -vserver node4-lif data1 failover-policy broadcast-domain-wide-failover-group fg1'을 참조하십시오

+
자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 네트워크 관리_ 또는 _ONTAP 9 명령(수동 페이지 참조_)에 연결하려면 _LIF_에서 페일오버 설정 구성 으로 이동하십시오.

. 노드 4의 변경 사항을 확인합니다.
+
네트워크 포트 show-node node4


