---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html 
keywords: move, aggregates, nas, lif, node2, node3, node4 
summary: ONTAP 9.7 이하를 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 노드 3의 NAS 데이터 LIF를 노드 3에서 노드 4로 이동합니다. 
---
= 노드 2가 소유한 NAS 데이터 LIF를 노드 3에서 노드 4로 이동하고 노드 4의 SAN LIF를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 4의 설치를 확인하고 노드 3에서 노드 4로 노드 2의 애그리게이트를 재배치하려면 현재 노드 3에 있는 노드 2가 소유한 NAS 데이터 LIF를 노드 3에서 노드 4로 이동해야 합니다. 노드 4의 SAN LIF도 확인해야 합니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 4를 온라인으로 설정한 후 LIF가 정상 작동하는지 확인합니다.

.단계
. 노드 3에서 소유하지 않은 모든 NAS 데이터 LIF를 표시하려면 두 노드 중 하나에 다음 명령을 입력하고 출력을 캡처합니다.
+
`network interface show -role data -curr-node node3 -is-home false`

. [[Worksheet_step2_node2]] 클러스터가 SAN LIF에 대해 구성되어 있으면 이 문서에 SAN LIF 및 기존 구성 정보를 기록합니다 link:worksheet_information_before_moving_san_lifs_node4.html["워크시트"] 나중에 사용할 수 있습니다.
+
.. 노드 3의 SAN LIF를 나열하고 출력을 조사합니다.
+
`network interface show -data-protocol fc*`

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 기존 설정을 나열하고 출력을 검사합니다.
+
`fcp adapter show -fields switch-port,fc-wwpn`

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드2의 경우 | 설명 


| 인터페이스 그룹 또는 VLAN이 구성되어 있었습니다 | 로 이동합니다 <<man_lif_verify_4_Step3,4단계>>. 


| 인터페이스 그룹 또는 VLAN이 구성되지 않았습니다 | 4단계를 건너뛰고 로 이동합니다 <<man_lif_verify_4_Step4,5단계>>. 
|===
. [[man_lif_verify_4_Step3] 다음 단계에 따라 원래 노드 3에서 노드 4로 노드 2에 있던 인터페이스 그룹 및 VLAN에 호스팅된 NAS 데이터 LIF를 모두 마이그레이션합니다.
+
.. [[man_lif_verify_4_substa]] 인터페이스 그룹의 node2에 이미 속해 있는 node3에 호스팅된 모든 LIF를 노드 4의 포트로 마이그레이션: 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node node4 –destination-port _netport|ifgrp_`

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_4_substepa,하위 단계 A>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-node node4 home-port _netport|ifgrp_`

.. [[man_lif_verify_4_substeepc]] 이전에 VLAN 포트의 node2에 속해 있던 node3에 호스팅된 모든 LIF를 노드 4의 포트로 마이그레이션합니다. 노드 4에서는 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에 LIF를 호스팅할 수 있습니다.
+
`network interface migrate -vserver _vserver_name_ -lif _datalif_name_ -destination-node node4 –destination-port _netport|ifgrp_`

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_4_substepc,하위 단계 c>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-node _node4_ home-port _netport|ifgrp_`



. [[man_lif_verify_4_Step4]]다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가 구성된 경우... | 그러면... 


| NAS | 완료 <<man_lif_verify_4_Step5,6단계>> 부터 까지 <<man_lif_verify_4_Step8,9단계>>10단계를 건너뛰고 완료합니다 <<man_lif_verify_4_Step10,11단계>> 부터 까지 <<man_lif_verify_4_Step13,14단계>>. 


| 산 | 6단계부터 9단계까지 건너뛰고 완료합니다 <<man_lif_verify_4_Step9,10단계>> 부터 까지 <<man_lif_verify_4_Step13,14단계>>. 


| NAS 및 SAN 모두 지원 | 완료 <<man_lif_verify_4_Step5,6단계>> 부터 까지 <<man_lif_verify_4_Step13,14단계>>. 
|===
. [[man_lif_verify_4_Step5]] 플랫폼에서 동일하지 않은 데이터 포트가 있는 경우 다음 명령을 입력하여 브로드캐스트 도메인에 포트를 추가합니다.
+
`network port broadcast-domain add-ports -ipspace _IPspace_name_ -broadcast-domain mgmt ports _node:port_`

+
다음 예에서는 노드 "6280-1"의 포트 "e0a"와 노드 "8060-1"의 포트 "e0i"를 IPspace에서 브로드캐스트 도메인 관리에 추가합니다. 기본값:

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. 각 LIF에 대해 다음 명령을 한 번 입력하여 각 NAS 데이터 LIF를 노드 4로 마이그레이션합니다.
+
`network interface migrate -vserver _vserver-name_ -lif _datalif-name_ -destination-node _node4_ -destination-port _netport|ifgrp_ -home-node _node4_`

. 데이터 마이그레이션이 영구한지 확인:
+
`network interface modify -vserver _vserver_name_ -lif _datalif_name_ -home-port _netport|ifgrp_`

. [[man_lif_verify_4_Step8]]로 모든 링크의 상태를 확인합니다 `up` 다음 명령을 입력하여 모든 네트워크 포트를 나열하고 해당 출력을 확인합니다.
+
`network port show`

+
다음 예제는 의 출력을 보여 줍니다 `network port show` 명령을 실행하면 일부 LIF가 작동 중지되며 다른 LIF는 작동 중지되기도 합니다.

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. [[man_lif_verify_4_Step9]]의 출력이 인 경우 `network port show` 명령 새 노드에서 사용할 수 없고 이전 노드에 있는 네트워크 포트를 표시합니다. 다음 하위 단계를 완료하여 이전 네트워크 포트를 삭제합니다.
+
.. 다음 명령을 입력하여 고급 권한 수준을 입력합니다.
+
`set -privilege advanced`

.. 각 이전 네트워크 포트에 대해 다음 명령을 한 번 입력합니다.
+
`network port delete -node _node_name_ -port _port_name_`

.. 다음 명령을 입력하여 admin 레벨로 돌아갑니다.
+
`set -privilege admin`



. [[man_lif_verify_4_Step10]] 다음 하위 단계를 완료하여 SAN LIF가 노드 4의 올바른 포트에 있는지 확인합니다.
+
.. 다음 명령을 입력하고 출력을 검사합니다.
+
`network interface show -data-protocol iscsi|fcp -home-node node4`

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node4         a0a     true
            data1        up/up    10.63.0.50/18      node4         e0c     true
            rads1        up/up    10.63.0.51/18      node4         e1a     true
            rads2        up/down  10.63.0.52/24      node4         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node4         e0c     true
            lif2         up/up    172.17.176.121/24  node4
----
.. 새 가 맞는지 확인합니다 `adapter` 및 `switch-port` 의 출력을 비교하여 구성이 올바른지 확인합니다 `fcp adapter show` 의 워크시트에 기록한 새 구성 정보를 사용하여 명령을 실행합니다 <<worksheet_step2_node2,2단계>>.
+
노드 4의 새로운 SAN LIF 구성을 나열합니다.

+
`fcp adapter show -fields switch-port,fc-wwpn`

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----
+

NOTE: 새 구성의 SAN LIF가 아직 연결된 어댑터에 없는 경우 `switch-port`노드를 재부팅할 때 시스템이 중단될 수 있습니다.

.. 노드 4에 SAN LIF 또는 SAN LIF 그룹이 노드 2에 없는 포트에 있는 경우 다음 명령 중 하나를 입력하여 해당 LIF를 노드 4의 적절한 포트로 이동합니다.
+
... LIF 상태를 아래로 설정합니다.
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin down`

... 포트 세트에서 LIF를 제거합니다.
+
`portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

... 다음 명령 중 하나를 입력합니다.
+
**** 단일 LIF 이동:
+
`network interface modify -lif _lif_name_ -home-port _new_home_port_`

**** 존재하지 않거나 잘못된 단일 포트에 있는 모든 LIF를 새 포트로 이동:
+
`network interface modify {-home-port _port_on_node2_ -home-node _node2_ -role data} -home-port _new_home_port_on_node4_`

**** 포트 세트에 LIF를 다시 추가합니다.
+
`portset add -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`







+

NOTE: SAN LIF를 원래 포트와 동일한 링크 속도를 가진 포트로 이동해야 합니다.

. 모든 LIF의 상태를 로 수정합니다 `up` 따라서 LIF는 다음 명령을 입력하여 노드에서 트래픽을 허용하고 전송할 수 있습니다.
+
`network interface modify -vserver _vserver_name_ -home-port _port_name_ -home-node _node4_ lif _lif_name_ -status-admin up`

. SAN LIF가 올바른 포트로 이동되었으며 LIF의 상태가 인지 확인합니다 `up` 두 노드 중 하나에서 다음 명령을 입력하고 출력을 검사하여,
+
`network interface show -home-node _node4_ -role data`

. [[man_lif_verify_4_Step13] LIF가 다운된 경우 LIF의 관리 상태를 로 설정합니다 `up` 다음 명령을 각 LIF에 대해 한 번 입력합니다.
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`


