---
sidebar: sidebar 
permalink: upgrade-arl-manual/prepare_for_netboot.html 
keywords: prepare, netboot, rack, node3, node4 
summary: ONTAP 9.7 이하를 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 netboot node3 및 node4에 대비합니다. 
---
= netboot를 준비합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
절차의 나중에 노드 3과 노드 4를 물리적으로 랙에 설치한 후 해당 노드들을 netboot 해야 할 수도 있습니다. term_netboot_는 원격 서버에 저장된 ONTAP 이미지에서 부팅함을 의미합니다. netboot를 준비할 때 시스템이 액세스할 수 있는 웹 서버에 ONTAP 9 부트 이미지 사본을 넣어야 합니다.

.시작하기 전에
* 시스템에서 HTTP 서버에 액세스할 수 있는지 확인합니다.
* 을 참조하십시오 link:other_references.html["참조"] 를 방문하여 귀하의 플랫폼에 필요한 시스템 파일과 올바른 버전의 ONTAP를 다운로드하십시오.


원래 컨트롤러에 설치된 것과 동일한 버전의 ONTAP 9가 없는 경우 새 컨트롤러를 netboot 해야 합니다. 각각의 새 컨트롤러를 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 시스템을 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다.

하지만 원래 컨트롤러에 설치된 것과 동일한 버전의 ONTAP 9가 설치된 경우 컨트롤러를 netboot 하지 않아도 됩니다. 이 경우 이 섹션을 건너뛰고 로 진행할 수 있습니다 link:stage_3_install_boot_node3.html["3단계: 노드 3을 설치하고 부팅합니다"].

.단계
. [[man_netboot_Step1]]NetApp Support 사이트에 액세스하여 시스템 넷부팅을 수행하는 데 사용되는 파일을 다운로드합니다.
. NetApp Support 사이트의 소프트웨어 다운로드 섹션에서 해당 ONTAP 소프트웨어를 다운로드하고 웹 액세스 가능한 디렉토리에 '<ONTAP_version>_image.tgz' 파일을 저장합니다.
. 웹 액세스 가능 디렉토리로 변경하고 필요한 파일을 사용할 수 있는지 확인합니다.
+
[cols="35,65"]
|===
| 대상... | 그러면... 


| FAS/AFF8000 시리즈 시스템 | '<ONTAP_VERSION>_IMAGE.tgz' 파일의 압축을 대상 디렉토리에 풉니다. 'tar-zxvf<ONTAP_VERSION>_IMAGE.tgz' * 참고 *: Windows에서 컨텐츠를 추출하는 경우 7-Zip 또는 WinRAR을 사용하여 netboot 이미지를 추출합니다. 디렉토리 목록에는 커널 파일 'netboot/kernel'이 있는 netboot 폴더가 포함되어야 합니다 


| 기타 모든 시스템 | 디렉토리 목록에는 '<ONTAP_VERSION>_IMAGE.tgz' 파일이 포함되어야 합니다. * 참고 *: "<ONTAP_VERSION>_IMAGE.tgz" 파일의 내용은 추출할 필요가 없습니다. 
|===
+
의 디렉토리에 있는 정보를 사용합니다 link:stage_3_install_boot_node3.html["3단계"].


