---
sidebar: sidebar 
permalink: upgrade-arl-manual/verify_node3_installation.html 
keywords: verify, node3, install, installation, node4 
summary: ONTAP 9.7 이하를 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 node3 설치 및 node2와의 통신을 확인합니다. 
---
= 노드3 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 3을 설치하고 부팅한 후에는 올바르게 설치되어 있고, 클러스터의 일부이며, 노드 2와 통신할 수 있는지 확인해야 합니다.

.단계
. [[step1]] 시스템 프롬프트에서 node3에 로그인합니다. 그런 다음 노드 3이 모두 노드 2와 동일한 클러스터의 일부이고 정상 상태인지 확인합니다.
+
'클러스터 쇼'

. [[step2]] 노드 3이 노드 2와 통신할 수 있고 모든 LIF가 작동 중인지 확인합니다.
+
'network interface show-curr-node <node3>'

. [[step3]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가... | 그러면... 


| SAN 환경에 구축되고 있습니다 | 완료 <<step4,4단계>> 섹션으로 이동합니다 link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["노드 1이 소유한 NAS 데이터 LIF를 노드 2에서 노드 3으로 이동하고 노드 3의 SAN LIF를 검증합니다"]. 


| SAN 환경에서는 | 4단계를 건너뛰고 로 이동합니다 link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["노드 1이 소유한 NAS 데이터 LIF를 노드 2에서 노드 3으로 이동하고 노드 3의 SAN LIF를 검증합니다"]. 
|===
. [[step4]] 노드 중 하나에 다음 명령을 입력하고 출력을 검사하여 node2와 node3이 쿼럼에 있는지 확인합니다.
+
이벤트 로그 show-messagename scsiblade. *

+
다음 예에서는 클러스터의 노드가 quorum에 있을 때의 출력을 보여 줍니다.

+
[listing]
----
cluster::> event log show -messagename scsiblade.*
Time                Node   Severity      Event
------------------- ------ ------------- --------------------------
8/13/2012 14:03:51  node1  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:51  node2  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:48  node3  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:43  node4  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
----

