---
sidebar: sidebar 
permalink: upgrade-arl-manual/verify_node4_installation.html 
keywords: install, node4, node3, verify, communicate 
summary: ONTAP 9.7 이하를 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 node4 설치 및 node3과의 통신을 확인합니다. 
---
= 노드 4 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 4를 설치하고 부팅한 후에는 올바르게 설치되어 있고, 클러스터에 포함되어 있으며, 노드 3과 통신할 수 있는지 확인해야 합니다.

.단계
. 시스템 프롬프트에서 node4에 로그인합니다.
. 노드 4가 모두 노드 3과 동일한 클러스터의 일부이고 정상 상태인지 확인합니다.
+
'클러스터 쇼'

. 노드 4가 노드 3과 통신할 수 있고 모든 LIF가 작동 중인지 확인합니다.
+
네트워크 인터페이스 show-curr-node_node4_

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드 4가 다음과 같은 경우 | 그러면... 


| 노드 3과 분리된 섀시  a| 
다음 단계를 완료하여 노드 간 HA 인터커넥트를 연결합니다.

.. 노드 3의 위쪽 상호 연결 포트를 노드 4의 위쪽 상호 연결 포트에 연결합니다.
.. 노드 3의 하단 상호 연결 포트를 노드 4의 하단 상호 연결 포트에 연결합니다.
.. 로 이동합니다 ,5단계.




| 노드 3과 동일한 섀시에 | 로 이동합니다 ,5단계. HA 인터커넥트를 노드 간에 수동으로 연결할 필요는 없습니다. 동일한 섀시 구성에서 HA 인터커넥트는 백플레인을 통해 자동으로 연결됩니다. 
|===
. [[5단계]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가... | 그러면... 


| SAN 환경에 구축되고 있습니다 | 완료 ,6단계 섹션으로 이동합니다 link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["노드 2가 소유한 NAS 데이터 LIF를 노드 3에서 노드 4로 이동하고 노드 4의 SAN LIF를 확인합니다"]. 


| SAN 환경에서는 | 6단계 건너뛰기 섹션으로 이동합니다 link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["노드 2가 소유한 NAS 데이터 LIF를 노드 3에서 노드 4로 이동하고 노드 4의 SAN LIF를 확인합니다"]. 
|===
. [[6단계] 노드 중 하나에 다음 명령을 입력하여 노드 3과 노드 4가 모두 쿼럼에 있는지 확인합니다.
+
이벤트 로그 show-messagename scsiblade. *

+
다음 예에서는 클러스터의 노드가 quorum에 있을 때의 출력을 보여 줍니다.

+
[listing]
----
cluster::> event log show -messagename scsiblade.*
Time                Node   Severity      Event
------------------- ------ ------------- --------------------------
8/13/2012 14:03:51  node1  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:51  node2  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:48  node3  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
8/13/2012 14:03:43  node4  INFORMATIONAL scsiblade.in.quorum: The scsi-blade ...
----

