---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: '을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 스토리지 암호화를 구성 및 관리하고 인증 키를 관리하고 SnapMirror 관계를 중지합니다 `system controller replace` 명령.' 
---
= 업그레이드 준비를 완료합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 라이선싱 및 온보드 키 관리자(OKM)를 사용한 스토리지 암호화 관리 방법에 대해 알아보세요. 필요에 따라 SnapMirror 관계를 중지할 수 있습니다.



== ONTAP 라이센스에 대해 알아보십시오

일부 기능은 하나 이상의 기능을 포함하는 _packages_로 발급된 라이센스를 필요로 합니다. 클러스터의 각 노드에는 클러스터에서 사용되는 각 기능에 대한 자체 키가 있어야 합니다.

새 라이센스 키가 없는 경우, 클러스터에서 현재 라이센스가 부여된 기능을 새 컨트롤러에서 사용할 수 있습니다. 그러나 컨트롤러에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 업그레이드가 완료된 후 새 컨트롤러의 새 라이센스 키 또는 키를 설치해야 합니다.

을 참조하십시오 link:other_references.html["참조"] ONTAP에 대한 새로운 28자 라이센스 키를 얻을 수 있는 _NetApp Support 사이트_에 대한 링크입니다. 키는 _ 소프트웨어 라이센스 _ 의 _ My Support _ 섹션에서 사용할 수 있습니다. 사이트에 필요한 라이센스 키가 없는 경우 NetApp 세일즈 담당자에게 문의하십시오.

ONTAP 라이센스에 대한 자세한 내용은 link:other_references.html["참조"]를 참조하여 _시스템 관리 참조_에 연결하십시오.



== Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다

Onboard Key Manager(OKM)를 사용하여 암호화 키를 관리하십시오. OKM이 설정되어 있는 경우 업그레이드를 시작하기 전에 암호와 백업 자료를 기록해야 합니다.

.단계
. 클러스터 전체 암호를 기록합니다.
+
OKM을 구성하거나 CLI 또는 REST API를 사용하여 업데이트할 때 입력한 암호입니다.

. 암호와 키 관리자 작동을 확인하십시오.
+
`security key-manager onboard sync`

+
메시지가 표시되면 이전 단계에서 기록한 클러스터 전체 OKM 암호를 입력합니다.

. 다음 명령의 출력을 검토하여 cc-mode가 활성화되었는지 확인하십시오.
+
`security key-manager config show`

. 키 관리자 정보를 백업합니다.
+
`security key-manager onboard show-backup`





== 선택적으로 SnapMirror 관계를 중지할 수 있습니다

절차를 계속하기 전에 모든 SnapMirror 관계가 중지되었는지 확인해야 합니다. SnapMirror 관계가 중지되면 재부팅 및 페일오버 시에도 계속 정지됩니다.

.단계
. 대상 클러스터에서 SnapMirror 관계 상태를 확인합니다.
+
`snapmirror show`

+
[NOTE]
====
상태가 "전송 중"인 경우 이러한 전송을 중단해야 합니다.
`snapmirror abort -destination-vserver _vserver_name_`

====
+
SnapMirror 관계가 "전송 중" 상태가 아니면 중단이 실패합니다.

. 클러스터 간의 모든 관계 중지:
+
`snapmirror quiesce -destination-vserver *`



.다음 단계
업그레이드 준비를 마친 후 link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["node1이 소유한 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 node2로 재배치합니다"].
