---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'ARL을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할지 여부를 로 결정합니다 `system controller replace` 명령.' 
---
= 이 집계 이전 절차를 사용할지 결정하십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하는 데에는 여러 가지 집계 재배치(ARL) 방법이 있습니다. 이 절차에서는 ONTAP 9.8 이상을 실행하는 시스템에서 "시스템 컨트롤러 교체 명령"을 사용하여 집계 재배치(ARL)를 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다. 숙련된 ONTAP 관리자만 이 복잡한 절차를 사용해야 합니다.

이 ARL 절차가 컨트롤러 하드웨어 업그레이드에 적합한지 결정하는 데 도움이 되도록 지원되는 업그레이드에 대한 다음 모든 상황을 검토해야 합니다.

* ONTAP 9.8 이상을 실행하고 있습니다.
* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동을 사용하여 데이터를 마이그레이션하기를 원하지 않을 것입니다.
* ONTAP 관리 경험이 있으며 진단 권한 모드에서 작업할 때의 위험에 익숙합니다.
* MetroCluster 구성을 업그레이드하는 경우 4노드 이상의 FC 구성을 사용하며 모든 노드에서 ONTAP 9.8 이상을 실행하고 있습니다.
+
MetroCluster IP 구성을 업그레이드하려면 link:other_references.html["참조"]_MetroCluster 업그레이드 및 확장_ 링크를 참조하십시오.



[NOTE]
====
* AFF A800 또는 AFF C800 과 같이 동일한 섀시에서 컨트롤러 모듈을 교체하여 시스템을 업그레이드하는 경우 NetApp 다음 업그레이드 절차를 사용하는 것이 좋습니다.link:../upgrade-arl-auto-in-chassis/index.html["ARL을 사용하여 기존 시스템 섀시 및 디스크를 유지하면서 컨트롤러 모델을 업그레이드합니다."] .  이 ARL 절차에는 업그레이드 절차 중에 컨트롤러를 제거하고 설치할 때 내부 디스크가 섀시에 안전하게 고정되도록 하는 단계가 포함되어 있습니다.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["기존 시스템 섀시와 디스크를 유지하면서 ARL을 사용하여 지원되는 시스템 업그레이드 조합에 대해 알아보세요."].

* 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.


====


== 지원되는 시스템 업그레이드 조합

다음 표는 이 ARL 절차를 사용하여 컨트롤러 업그레이드를 수행하기 위한 지원되는 시스템 매트릭스를 보여줍니다.

|===
| 더 오래 된 컨트롤러 | 교체 컨트롤러 


| FAS8020 ^3^, FAS8040^3^, FAS8060, FAS8080 | FAS8200, FAS8300, FAS8700, FAS9000 


| FAS8060^4^, FAS8080^4^ | FAS9500 


| AFF8020^3^, AFF8040^3^, AFF8060, AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800^1^ 


| AFF8060^4^, AFF8080^4^ | AFF A900 


| FAS8200 | FAS8300^2^, FAS8700, FAS9000, FAS9500 


| FAS8300, FAS8700, FAS9000 | FAS9500 


| AFF A300 | AFF A400^2^, AFF A700, AFF A800^1^, AFF A900 


| AFF A320^4^ | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===

NOTE: 컨트롤러 업그레이드 모델 조합이 위 표에 없는 경우 기술 지원 팀에 문의하십시오.

AFF A800 시스템에 필요한 추가 단계는link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["노드1 디스크를 노드3, 9단계에 재할당합니다"], 또는 섹션의 A800을 참조하는 단계로 이동합니다link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["노드2 디스크를 노드4, 9단계에 재할당합니다"].

(2) 스위치 없는 2노드 클러스터 구성에서 AFF A300에서 AFF A400로 또는 FAS8200에서 FAS8300 시스템으로 업그레이드하는 경우 컨트롤러를 업그레이드할 때 임시 클러스터 포트를 선택해야 합니다. AFF A400 및 FAS8300 시스템은 2개의 구성으로 제공됩니다. 메자닌 카드 포트는 이더넷 유형이고 메자닌 포트가 FC 유형인 FC 번들입니다.

* 이더넷 유형 구성이 있는 AFF A400 또는 FAS8300 의 경우 두 메자닌 포트 중 하나를 임시 클러스터 포트로 사용할 수 있습니다.
* FC 유형 구성을 사용하는 AFF A400 또는 FAS8300 의 경우 임시 클러스터 포트를 제공하려면 4포트 10GbE 네트워크 인터페이스 카드(부품 번호 X1147A)를 추가해야 합니다.
* 임시 클러스터 포트를 사용하여 컨트롤러 업그레이드를 완료한 후에는 FAS8300 시스템의 e3a 및 e3b, AFF A400 시스템의 100GbE 포트, e0c 및 e0d, 100GbE 포트로 클러스터 LIF를 중단 없이 마이그레이션할 수 있습니다.


^3^ FAS8020, FAS8040, AFF8020, AFF8040 시스템을 위 표에 나와 있는 타겟 교체 컨트롤러로 업그레이드하는 경우, 교체 컨트롤러가 이전 컨트롤러와 동일한 ONTAP 버전을 실행해야 합니다. FAS8020, FAS8040, AFF8020 및 AFF8040 시스템은 ONTAP 9.8 이후 버전의 ONTAP를 지원하지 않습니다.

^4^ 다음 표에서는 이러한 컨트롤러 업그레이드 조합에 대해 지원되는 최소 및 이후 ONTAP 버전을 보여 줍니다.

[cols="20,30,20,30"]
|===
2+| 더 오래 된 컨트롤러 2+| 교체 컨트롤러 


| 시스템 | ONTAP 버전입니다 | 시스템 | ONTAP 버전입니다 


| AFF A320 | 9.9.1 이상 | AFF A400 | 9.9.1 이상 


| AFF8060 | 9.8P13 이상 패치 | AFF A900 | 9.10.1 ~ 9.12.1 


| AFF8080 | 9.8P10 이상 패치 | AFF A900 | 9.10.1 ~ 9.12.1 


| FAS8060 | 9.8P13 이상 패치 | FAS9500 | 9.10.1P3 ~ 9.12.1 


| FAS8080 | 9.8P12 이상 패치 | FAS9500 | 9.10.1P3 ~ 9.12.1 
|===
[NOTE]
====
위 표에 표시된 업그레이드 조합의 경우:

* 기존 컨트롤러와 교체 컨트롤러에서 동일한 ONTAP 버전을 사용할 필요가 없습니다. ONTAP 소프트웨어 업그레이드는 컨트롤러 업그레이드로 수행됩니다.
* 업그레이드할 때 지원되는 ONTAP 버전 및 패치 레벨로 교체 컨트롤러를 설치해야 합니다.
* 절차를 시작하고 첫 번째 노드를 업그레이드한 후에는 컨트롤러 업그레이드를 취소하거나 되돌릴 수 없습니다.


====


== 다른 하드웨어 업그레이드 절차를 선택하세요

* link:../upgrade-arl/index.html["컨트롤러 하드웨어 업그레이드에 사용 가능한 대체 ARL 방법을 검토하세요."]..
* 컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.


.관련 정보
참조하다 link:other_references.html["참조"] _ONTAP 9 문서_에 링크합니다.
