---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: '을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 스토리지 암호화를 구성 및 관리하고 인증 키를 관리하고 SnapMirror 관계를 중지합니다 `system controller replace` 명령.' 
---
= 스토리지 암호화를 위한 외부 키 관리 서버의 IP 주소를 가져옵니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
업그레이드 후에는 스토리지 암호화를 즉시 구성하고 클러스터 차원의 인증 키를 설정하여 이전 노드 레벨 인증 키를 교체해야 합니다.

.단계
. 키 관리 서버와 통신하는 데 필요한 클라이언트 및 서버 SSL(Secure Sockets Layer) 인증서를 설치합니다.
+
`security certificate install`

. 각 노드에서 다음 명령을 사용하여 모든 노드에서 스토리지 암호화 구성:
+
`security key-manager external enable`

. 각 키 관리 서버의 IP 주소를 추가합니다.
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. 클러스터의 모든 노드에서 동일한 키 관리 서버가 구성 및 사용 가능한지 확인합니다.
+
`security key-manager external show-status`

. 새 클러스터 전체 인증 키를 생성합니다.
+
`security key-manager key create`

. 새 인증 키 ID를 기록해 둡니다.
. 새 인증 키를 사용하여 모든 자체 암호화 드라이브를 다시 입력하다
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`





== KMIP 서버를 사용하여 인증 관리

ONTAP 9.8 이상에서는 키 관리 상호 운용성 프로토콜(KMIP) 서버를 사용하여 인증 키를 관리할 수 있습니다.

.단계
. 새 컨트롤러 추가:
+
`security key-manager external enable`

. 키 관리자 추가:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. 키 관리 서버가 구성되어 있고 클러스터의 모든 노드에서 사용할 수 있는지 확인합니다.
+
`security key-manager external show-status`

. 연결된 모든 키 관리 서버에서 새 노드로 인증 키를 복원합니다.
+
`security key-manager external restore -node _new_controller_name_`

. 새 인증 키를 사용하여 모든 자체 암호화 디스크를 다시 입력하다
+
`storage encryption disk modify -disk * [-data-key-id nonMSID AK]`

. FIPS(Federal Information Processing Standard)를 사용하는 경우 새 인증 키를 사용하여 모든 자체 암호화 디스크를 다시 입력하다
+
`storage encryption disk modify -disk * [-fips-key-id nonMSID AK]`


