---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, metrocluster, terminology 
summary: 'ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어는 를 사용하여 업그레이드할 수 있습니다 `system controller replace` 명령을 실행하여 루트 이외의 애그리게이트에 대한 소유권을 재배치하십시오.' 
---
= ARL 업그레이드 절차에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하는 데에는 여러 가지 집계 재배치(ARL) 방법이 있습니다. 이 절차에서는 ONTAP 9.8 이상을 실행하는 시스템에서 "시스템 컨트롤러 교체 명령"을 사용하여 집계 재배치(ARL)를 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 LIF(데이터 논리 인터페이스)를 마이그레이션하고 계속 진행할 때 새 컨트롤러의 네트워크 포트를 인터페이스 그룹에 할당합니다.

.이 정보에 사용된 용어
이 정보에서 원래 노드를 "node1"과 "node2"라고 하며 새 노드를 "node3"과 "node4"라고 합니다. 이 절차를 수행하는 동안 노드 1은 노드 3으로 대체되고 노드 2는 노드 4로 대체됩니다.

"node1", "node2", "node3" 및 "node4"라는 용어는 원래 노드와 새 노드를 구별하는 데만 사용됩니다. 절차를 따를 때는 원래 노드와 새 노드의 실제 이름을 대체해야 합니다. 그러나 실제로 노드 이름은 변경되지 않습니다. node3에는 node1이라는 이름이 있고, node4에는 컨트롤러 하드웨어를 업그레이드한 후 node2라는 이름이 있습니다.

.중요 정보:
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 다음을 읽고 이해해야 합니다. link:guidelines_for_upgrading_controllers_with_arl.html["ARL을 사용한 컨트롤러 업그레이드 지침"] 그리고 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 시퀀스"] 업그레이드를 시작하기 전에.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 사용한 경우, 특히 컨트롤러가 7-Mode에서 Data ONTAP를 실행 중인 경우 기술 지원 부서에 문의해야 합니다.
* ARL을 사용하여 업그레이드할 클러스터에서 실행 중인 버전보다 더 높은 ONTAP 버전을 실행 중인 새 컨트롤러로 중단 없이 단순한 컨트롤러 업그레이드를 수행할 수 있습니다. 기존 및 새 컨트롤러의 ONTAP 버전 조합은 ONTAP 소프트웨어 릴리즈 NDU Cadence 모델에 의해 결정됩니다. 예를 들어, ONTAP 9.8을 실행하는 컨트롤러가 있고 해당 컨트롤러에 대해 마지막으로 지원되는 버전인 경우, ONTAP 9.8 이후 버전의 ONTAP를 실행하는 새로운 컨트롤러로 업그레이드할 수 있습니다.
+
이 업그레이드 절차는 주로 교체할 컨트롤러 모델이 최신 ONTAP 버전을 지원하지 않고 새 컨트롤러가 이전 ONTAP 버전을 지원하지 않는 업그레이드 시나리오에 적용됩니다.

* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA(고가용성) 쌍에 대해 이 절차를 별도로 수행해야 합니다.
* 이 절차는 FAS 시스템과 AFF 시스템에 적용됩니다.
* 이 절차는 4노드 NetApp MetroCluster 구성 이상을 실행하는 시스템에 적용됩니다. MetroCluster 구성 사이트는 물리적으로 서로 다른 두 위치에 있을 수 있으므로 HA Pair용 각 MetroCluster 사이트에서 컨트롤러 자동 업그레이드를 개별적으로 수행해야 합니다.
* HA 클러스터와 같은 비 MetroCluster 시스템의 경우 ARL 업그레이드만 지원되는 절차입니다.
* AFF A320 시스템에서 업그레이드하는 경우, 볼륨 이동을 사용하여 컨트롤러 하드웨어를 업그레이드하거나 기술 지원 부서에 문의할 수 있습니다. 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

