---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: '를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 node3을 설치 및 부팅하고 ONTAP 소프트웨어를 설치합니다 `system controller replace` 명령.' 
---
= 노드3을 설치하고 부팅합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 그런 다음 이 섹션에 설명된 대로 프로세스 초기에 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

.이 작업에 대해
이 단계를 시작할 때 재배치 작업이 일시 중지됩니다. 이 프로세스는 대부분 자동화되어 있으며 사용자가 상태를 확인할 수 있도록 작업이 일시 중지됩니다. 작업을 수동으로 재개해야 합니다. 또한 SAN LIF가 노드 3으로 성공적으로 이동했는지 확인해야 합니다.

노드 1에 설치된 ONTAP 9의 버전이 같지 않으면 노드 3을 netboot 해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 의 지침에 따라 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다 link:prepare_for_netboot.html["netboot를 준비합니다"].

[IMPORTANT]
====
* AFF A800 또는 AFF C800 컨트롤러를 업그레이드하는 경우, 노드1을 제거하기 전에 섀시의 모든 드라이브가 미드플레인에 단단히 고정되어 있는지 확인해야 합니다. 자세한 내용은 다음을 참조하세요. link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["AFF A800 또는 AFF C800 컨트롤러 모듈을 교체합니다"].
* 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 이 전체 섹션을 완료한 다음 로 이동하십시오 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 섹션에서 클러스터 프롬프트에 명령 입력


====
.단계
. [[auto_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치와 가까운 자체 랙 공간에 넣어야 합니다.

. [[auto_install3_step2]] 노드 모델의 _Installation and Setup Instructions_에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면, 노드 3을 부팅할 때 노드가 듀얼 섀시 구성인 것처럼 동작하고, 노드 4를 부팅할 때 노드 간의 상호 연결이 이루어지지 않습니다.

. [[auto_install3_step3]] 노드 3을 케이블로 연결하여 노드 1에서 노드 3으로 연결을 이동합니다.
+
node3 플랫폼의 _설치 및 설정 지침_, 해당 디스크 쉘프 문서, _HA 쌍 관리_ 문서를 사용하여 다음 연결을 케이블로 연결합니다.

+
참조하다link:other_references.html["참조"] _HA 쌍 관리_에 연결합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[auto_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]에 경고 메시지가 표시되는 경우 <<auto_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: *지연 시간을 무시하지 마세요. 배터리 충전을 허용하지 않으면 데이터가 손실될 수 있습니다.*

+

NOTE: 을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].





. [[step6]] 다음 작업 중 하나를 선택하여 netboot 연결을 구성합니다.
+

NOTE: 관리 포트와 IP를 netboot 연결로 사용해야 합니다. 업그레이드를 수행하는 동안 데이터 LIF IP를 사용하지 마십시오. 데이터 중단이 발생할 수 있습니다.

+
[cols="30,70"]
|===
| DHCP(Dynamic Host Configuration Protocol)가 다음과 같은 경우 | 그러면... 


| 실행 중입니다 | 부팅 환경 프롬프트에서 다음 명령을 사용하여 연결을 자동으로 구성합니다.
`ifconfig e0M -auto` 


| 실행 중이 아닙니다  a| 
부팅 환경 프롬프트에서 다음 명령을 사용하여 연결을 수동으로 구성합니다.
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 스토리지 시스템의 IP 주소입니다(필수).
`_netmask_` 스토리지 시스템의 네트워크 마스크입니다(필수).
`_gateway_` 는 스토리지 시스템의 게이트웨이입니다(필수).
`_dns_addr_` 네트워크에 있는 이름 서버의 IP 주소입니다(선택 사항).
`_dns_domain_` DNS(Domain Name Service) 도메인 이름입니다(선택 사항).


NOTE: 인터페이스에 다른 매개 변수가 필요할 수 있습니다. 를 입력합니다 `help ifconfig` 펌웨어 프롬프트에서 세부 정보를 확인합니다.

|===
. [[step7]]노드 3에서 netboot 수행:
+
[cols="30,70"]
|===
| 대상... | 그러면... 


| FAS/AFF8000 시리즈 시스템 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 기타 모든 시스템 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
를 클릭합니다 `<path_to_the_web-accessible_directory>` 에서 다운로드한 위치로 이동합니다 `<ontap_version>_image.tgz` 섹션을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].

+

NOTE: 부팅을 중단하지 마십시오.

. [[step8]] 부팅 메뉴에서 옵션을 선택합니다 `(7) Install new software first`.
+
이 메뉴 옵션은 새 ONTAP 이미지를 다운로드하여 부팅 장치에 설치합니다.

+
다음 메시지는 무시하십시오.

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
참고 사항은 ONTAP의 무중단 업그레이드에는 적용되고 컨트롤러 업그레이드에는 적용되지 않습니다.

+

NOTE: 항상 netboot를 사용하여 새 노드를 원하는 이미지로 업데이트합니다. 다른 방법을 사용하여 새 컨트롤러에 이미지를 설치할 경우 잘못된 이미지가 설치될 수 있습니다. 이 문제는 모든 ONTAP 릴리스에 적용됩니다. 옵션과 결합된 netboot 절차 `(7) Install new software` 부팅 미디어를 지우고 두 이미지 파티션에 동일한 ONTAP 버전을 배치합니다.

. [[step9]] 절차를 계속하라는 메시지가 나타나면 를 입력합니다 `y`, 패키지를 입력하라는 메시지가 나타나면 URL을 입력합니다.
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[10단계]] 다음 하위 단계를 완료하여 컨트롤러 모듈을 재부팅합니다.
+
.. 를 입력합니다 `n` 다음 프롬프트가 표시될 때 백업 복구를 건너뛰려면 다음을 수행합니다.
+
`Do you want to restore the backup configuration now? {y|n}`

.. 를 입력합니다 `y` 다음 메시지가 표시될 때 재부팅하려면 다음을 수행하십시오.
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
부팅 장치가 다시 포맷되어 구성 데이터가 복원되어야 하므로 컨트롤러 모듈이 재부팅되지만 부팅 메뉴에서 중지됩니다.



. [[11단계]] 유지보수 모드를 선택합니다 `5` 를 눌러 부팅 메뉴에서 으로 이동합니다 `y` 부팅 계속 메시지가 표시되면
. [[12단계] 컨트롤러 및 섀시가 ha로 구성되었는지 확인:
+
`ha-config show`

+
다음 예제는 의 출력을 보여 줍니다 `ha-config show` 명령:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: HA 쌍 또는 독립 실행형 구성에 관계없이 PROM에서 시스템 기록. 독립 실행형 시스템 또는 HA 쌍 내의 모든 구성 요소에서 상태가 동일해야 합니다.

. [[step13]] 컨트롤러와 섀시가 ha로 구성되지 않은 경우 다음 명령을 사용하여 구성을 수정하십시오.
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
MetroCluster 구성이 있는 경우 다음 명령을 사용하여 컨트롤러 및 섀시를 수정합니다.

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[pep14]] 유지보수 모드 종료:
+
`halt`

+
부팅 환경 프롬프트에서 Ctrl+C를 눌러 자동 부팅을 중단시킵니다.

. [[step15]] 노드 2에서 시스템 날짜, 시간 및 시간대를 확인합니다.
+
`date`

. [[step16]] 노드 3의 부팅 환경 프롬프트에서 다음 명령을 사용하여 날짜를 확인합니다.
+
`show date`

. [[step17]] 필요한 경우 노드 3의 날짜를 설정합니다.
+
`set date _mm/dd/yyyy_`

. [[step18]] 노드 3의 부팅 환경 프롬프트에서 다음 명령을 사용하여 시간을 확인합니다.
+
`show time`

. [[step19]] 필요한 경우 node3의 시간을 설정합니다.
+
`set time _hh:mm:ss_`

. [[step20]] 부트 로더에서 노드 3의 파트너 시스템 ID를 설정합니다.
+
`setenv partner-sysid _node2_sysid_`

+
노드 3의 경우 `partner-sysid` 노드 2의 것이어야 합니다.

+
.. 설정을 저장합니다.
+
`saveenv`



. [[auto_install3_step21]]를 확인합니다 `partner-sysid` 노드 3의 경우:
+
`printenv partner-sysid`



[[auto_install3_step22]]
. NetApp 스토리지 암호화(NSE) 드라이브가 설치된 경우 다음 단계를 수행하세요.
+

NOTE: 절차의 앞부분에서 아직 수행하지 않은 경우 기술 자료 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["드라이브가 FIPS 인증되었는지 확인하는 방법"^] 사용 중인 자체 암호화 드라이브의 유형을 확인합니다.

+
.. 설정 `bootarg.storageencryption.support` 를 선택합니다 `true` 또는 `false`:
+
[cols="35,65"]
|===
| 다음 드라이브를 사용 중인 경우… | 그러면... 


| NSE 드라이브가 FIPS 140-2 레벨 2 자체 암호화 요구사항을 충족합니다 | `setenv bootarg.storageencryption.support *true*` 


| NetApp 비 FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
동일한 노드 또는 HA 쌍에서 다른 유형의 드라이브와 FIPS 드라이브를 혼합할 수 없습니다. 동일한 노드 또는 HA 쌍에서 SED를 비암호화 드라이브와 혼합할 수 있습니다.

====
.. 특수 부팅 메뉴로 이동하여 옵션을 선택합니다 `(10) Set Onboard Key Manager recovery secrets`.
+
이전 절차에서 기록한 암호 및 백업 정보를 입력합니다. 을 참조하십시오 link:manage_storage_encryption_using_okm.html["Onboard Key Manager를 사용하여 스토리지 암호화를 관리합니다"].



. 노드를 부팅 메뉴로 부팅합니다.
+
`boot_ontap menu`



.다음 단계
* FC 또는 UTA/UTA2 구성이 있는 시스템이 있는 경우link:set_fc_or_uta_uta2_config_on_node3.html["node3에서 FC 또는 UTA/UTA2 포트를 설정하고 구성합니다."] .
* FC 또는 UTA/UTA2 구성이 없는 경우link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step1["node1 디스크를 node3에 다시 할당, 1단계"] 이렇게 하면 node3이 node1의 디스크를 인식할 수 있습니다.
* MetroCluster 구성이 있는 경우link:set_fc_or_uta_uta2_config_on_node3.html["node3에서 FC 또는 UTA/UTA2 포트를 설정하고 구성합니다."] 노드에 연결된 디스크를 감지합니다.

