---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: System controller replace 명령을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 node3을 설치 및 부팅하고 ONTAP 소프트웨어를 설치합니다. 
---
= 노드3을 설치하고 부팅합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 그런 다음 이 섹션에 설명된 대로 프로세스 초기에 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

이 단계를 시작할 때 재배치 작업이 일시 중지됩니다. 이 프로세스는 대부분 자동화되어 있으며 사용자가 상태를 확인할 수 있도록 작업이 일시 중지됩니다. 작업을 수동으로 재개해야 합니다. 또한 SAN LIF가 노드 3으로 성공적으로 이동했는지 확인해야 합니다.

노드 1에 설치된 ONTAP 9의 버전이 같지 않으면 노드 3을 netboot 해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 의 지침에 따라 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다 link:prepare_for_netboot.html["netboot를 준비합니다"].

.중요:
* 스토리지 어레이에 연결된 V-Series 시스템이나 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어를 사용하여 시스템을 업그레이드하려면 시스템을 완료해야 합니다 <<auto_install3_step1,1단계>> 부터 까지 <<auto_install3_step21,21단계>>그런 다음 이 섹션을 그대로 두고 의 지침을 따릅니다 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 필요한 경우 섹션을 유지 관리 모드로 명령 입력 그런 다음 이 섹션으로 돌아가서 을(를) 다시 시작해야 합니다 <<auto_install3_step23,23단계>>.
* 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 이 전체 섹션을 완료한 다음 로 이동하십시오 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 섹션에서 클러스터 프롬프트에 명령 입력


.단계
. [[auto_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치와 가까운 자체 랙 공간에 넣어야 합니다.

. [[auto_install3_step2]] 노드 모델의 _Installation and Setup Instructions_에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면 노드 3을 부팅할 때 노드는 이중 섀시 구성에 있는 것처럼 작동하며 노드 4를 부팅할 때 노드 간의 상호 연결이 나타나지 않습니다.

. [[auto_install3_step3]] 노드 3을 케이블로 연결하여 노드 1에서 노드 3으로 연결을 이동합니다.
+
노드 3 플랫폼의 _설치 및 설정 지침_ 또는 _FlexArray 가상화 설치 요구 사항 및 참조_를 사용하여 다음 연결을 케이블로 연결하십시오. 해당 디스크 쉘프 문서 및 _고가용성 관리_.

+
을 참조하십시오 link:other_references.html["참조"] FlexArray 가상화 설치 요구 사항 및 Reference_and_High Availability 관리 _ 에 대한 링크를 제공합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[auto_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]에 경고 메시지가 표시되는 경우 <<auto_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

WARNING: * 주의: 지연을 무시하지 마십시오. 배터리를 충전하지 않으면 데이터가 손실될 수 있습니다. *

+

NOTE: 을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].





. [[step6]] 다음 작업 중 하나를 선택하여 netboot 연결을 구성합니다.
+

NOTE: 관리 포트와 IP를 netboot 연결로 사용해야 합니다. 업그레이드를 수행하는 동안 데이터 LIF IP를 사용하지 않거나 데이터 중단이 발생할 수 있습니다.

+
[cols="30,70"]
|===
| DHCP(Dynamic Host Configuration Protocol)가 다음과 같은 경우 | 그러면... 


| 실행 중입니다 | 부팅 환경 프롬프트에서 'ifconfig e0M-auto'를 사용하여 연결을 자동으로 구성합니다 


| 실행 중이 아닙니다 | 부팅 환경 프롬프트에서 다음 명령을 사용하여 연결을 수동으로 구성합니다. 'ifconfig e0M -addr=filer_addr-mask=netmask-GW=gateway-dns=dns_addr domain=dns_domain''filer_addr'은 스토리지 시스템의 IP 주소입니다. 넷마스크는 스토리지 시스템의 네트워크 마스크입니다. 게이트웨이(gateway)는 스토리지 시스템의 관문입니다. dns_addr은 네트워크에 있는 이름 서버의 IP 주소입니다. 이 매개 변수는 선택 사항입니다. dns_domain은 DNS(Domain Name Service) 도메인 이름입니다. 이 매개 변수는 선택 사항입니다. * 참고 *: 인터페이스에 다른 매개 변수가 필요할 수 있습니다. 펌웨어 프롬프트에 "help ifconfig"를 입력하여 세부 정보를 확인합니다. 
|===
. [[step7]]노드 3에서 netboot 수행:
+
[cols="30,70"]
|===
| 대상... | 그러면... 


| FAS/AFF8000 시리즈 시스템 | "netboot\http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 기타 모든 시스템 | "netboot\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
"<path_to_the_web-Accessible_directory>"는 섹션에서 "<ONTAP_version>_image.tgz"를 다운로드한 위치로 이어져야 합니다 link:prepare_for_netboot.html["netboot를 준비합니다"].

+

NOTE: 부팅을 중단하지 마십시오.

. [[step8]] 부팅 메뉴에서 '(7) Install new software first' 옵션을 선택합니다.
+
이 메뉴 옵션은 새 ONTAP 이미지를 다운로드하여 부팅 장치에 설치합니다.

+

NOTE: 다음 메시지는 무시하십시오: "이 절차는 HA 쌍의 무중단 업그레이드를 지원하지 않습니다." 참고 사항은 ONTAP의 무중단 업그레이드에는 적용되고 컨트롤러 업그레이드에는 적용되지 않습니다. 항상 netboot를 사용하여 새 노드를 원하는 이미지로 업데이트합니다. 다른 방법을 사용하여 새 컨트롤러에 이미지를 설치할 경우 잘못된 이미지가 설치될 수 있습니다. 이 문제는 모든 ONTAP 릴리스에 적용됩니다.

. [[step9]] 절차를 계속하라는 메시지가 나타나면 "y"를 입력하고 패키지를 입력하라는 메시지가 나타나면 URL을 입력합니다.
+
'\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[10단계]] 다음 하위 단계를 완료하여 컨트롤러 모듈을 재부팅합니다.
+
.. 다음 프롬프트가 표시되면 "n"을 입력하여 백업 복구를 건너뜁니다.
+
"지금 백업 구성을 복원하시겠습니까? {y|n}'

.. 다음 프롬프트가 표시되면 재부팅하려면 "y"를 입력합니다.
+
새로 설치된 소프트웨어를 사용하려면 노드를 재부팅해야 합니다. 지금 재부팅하시겠습니까? {y|n}'

+
부팅 장치가 다시 포맷되어 구성 데이터가 복원되어야 하므로 컨트롤러 모듈이 재부팅되지만 부팅 메뉴에서 중지됩니다.



. [[11단계]] 부팅 메뉴에서 유지보수 모드 '5'를 선택하고 부팅을 계속하라는 메시지가 나타나면 'y'를 입력합니다.
. [[12단계] 컨트롤러 및 섀시가 ha로 구성되었는지 확인:
+
하구성 쇼

+
다음 예제는 "ha-config show" 명령의 출력을 보여줍니다.

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: HA 쌍 또는 독립 실행형 구성에 관계없이 PROM에서 시스템 기록. 독립 실행형 시스템 또는 HA 쌍 내의 모든 구성 요소에서 상태가 동일해야 합니다.

. [[step13]] 컨트롤러와 섀시가 ha로 구성되지 않은 경우 다음 명령을 사용하여 구성을 수정하십시오.
+
ha-config controller ha

+
하구성 수정 섀시 하

+
MetroCluster 구성이 있는 경우 다음 명령을 사용하여 컨트롤러 및 섀시를 수정합니다.

+
하구성 수정 컨트롤러 MCC

+
하구성 수정 새시 MCC

. [[pep14]] 유지보수 모드 종료:
+
"중지"

+
부팅 환경 프롬프트에서 Ctrl+C를 눌러 자동 부팅을 중단시킵니다.

. [[step15]] 노드 2에서 시스템 날짜, 시간 및 시간대를 확인합니다.
+
다

. [[step16]] 노드 3의 부팅 환경 프롬프트에서 다음 명령을 사용하여 날짜를 확인합니다.
+
날짜

. [[step17]] 필요한 경우 노드 3의 날짜를 설정합니다.
+
'날짜 설정 < mm/dd/yyyy>'

. [[step18]] 노드 3의 부팅 환경 프롬프트에서 다음 명령을 사용하여 시간을 확인합니다.
+
'시간'입니다

. [[step19]] 필요한 경우 node3의 시간을 설정합니다.
+
'세트 시간<hh:mm:ss>'

. [[step20]] 필요한 경우 노드 3의 파트너 시스템 ID를 설정합니다.
+
'setenv PARTNER-sysid <node2_sysid>'

+
.. 설정을 저장합니다.
+
'사베에프'



. [[auto_install3_step21]] 부트 로더에서 'partner-sysid' 매개 변수를 설정해야 합니다. 노드 3의 경우 'partner-sysid'가 노드 2의 syid여야 합니다. 노드 3의 'partner-sysid'를 확인합니다.
+
'printenv partner-sysid

. [[step22]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 시스템이... | 설명 


| 디스크 및 백엔드 스토리지가 없습니다 | 로 이동합니다 <<auto_install3_step23,23단계>> 


| 는 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어가 설치된 V-Series 시스템 또는 시스템입니다  a| 
.. 섹션으로 이동합니다 link:set_fc_or_uta_uta2_config_on_node3.html["노드 3에 FC 또는 UTA/UTA2 구성 설정"] 이 섹션의 하위 섹션을 완료하십시오.
.. 이 섹션으로 돌아가 나머지 단계를 완료합니다 <<auto_install3_step23,23단계>>.


* 중요 *: ONTAP 가상화 소프트웨어를 사용하여 V-Series 또는 시스템에서 FlexArray를 부팅하기 전에 FC 온보드 포트, CNA 온보드 포트 및 CNA 카드를 재구성해야 합니다.

|===
. [[auto_install3_step23]] 새 노드의 FC 이니시에이터 포트를 스위치 영역에 추가합니다.
+
시스템에 테이프 SAN이 있는 경우 이니시에이터에 대해 조닝이 필요합니다. 필요한 경우 을 참조하여 온보드 포트를 이니시에이터로 수정합니다 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트 구성"]. 조닝에 대한 자세한 내용은 스토리지 어레이 및 조닝 설명서를 참조하십시오.

. [[step24]] 스토리지 어레이에 새 호스트로 FC 이니시에이터 포트를 추가하여 스토리지 LUN을 새 호스트에 매핑합니다.
+
자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. [[step25] 스토리지 배열의 어레이 LUN과 연결된 호스트 또는 볼륨 그룹에서 WWPN(Worldwide Port Name) 값을 수정합니다.
+
새 컨트롤러 모듈을 설치하면 각 온보드 FC 포트에 연결된 WWPN 값이 변경됩니다.

. [[step26]] 구성에서 스위치 기반 조닝을 사용하는 경우 새 WWPN 값이 적용되도록 조닝을 조정하십시오.
. [[step27]] NSE(NetApp Storage Encryption)를 이 구성에서 사용 중인 경우, 'setup.storageenv.storageencryption.support'명령을 'true'로 설정해야 하며, node1 구성이 로드된 후 부트 루프를 방지하려면 kmip.init.maxwait` 변수를 'off'로 설정해야 합니다.
+
에테네 부타그 storageencryption.support true

+
'셋프 kmip.init.maxwait off'

. [[step28]] 부트 메뉴의 부트 노드:
+
boot_ontap 메뉴

+
FC 또는 UTA/UTA2 구성을 사용하지 않는 경우, 를 실행합니다 link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["노드 3, 15단계에서 UTA/UTA2 포트를 확인하고 구성합니다"] 따라서 노드 3은 노드 1의 디스크를 인식할 수 있습니다.



. [[step29]] MetroCluster 구성, 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어가 있는 V-Series 시스템 및 시스템의 경우, 노드에 연결된 디스크를 검색하려면 노드 3의 FC 또는 UTA/UTA2 포트를 설정하고 구성해야 합니다. 이 작업을 완료하려면 섹션으로 이동하십시오 link:set_fc_or_uta_uta2_config_on_node3.html["노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다"].

