---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: 노드 3의 네트워크 구성을 확인한 후 노드 2에서 노드 3으로 애그리게이트를 재배치합니다. 
---
= 노드 1이 소유하는 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2에서 노드 3으로 이동합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 3의 네트워크 구성을 확인하고 노드 2에서 노드 3으로 애그리게이트를 재배치된 후에는 노드 2에 있는 노드 1에 속하는 NAS 데이터 LIF가 노드 2에서 노드 3으로 재배치되어 있는지 확인해야 합니다. 또한 노드 3에 SAN LIF가 존재하는지 확인해야 합니다.

원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 3을 온라인으로 설정한 후 LIF가 정상 작동하는지 확인합니다.

.단계
. 재배치 작업 재개:
+
시스템 컨트롤러 교체 재개

+
시스템은 다음 작업을 수행합니다.

+
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


+
이 단계에서 네트워크 도달 가능성 점검에서 작업이 일시 중지됩니다.

. 재배치 작업 재개:
+
시스템 컨트롤러 교체 재개

+
시스템에서 다음 검사를 수행합니다.

+
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


+
이러한 확인을 수행한 후 시스템은 노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 3의 새 컨트롤러로 재배치합니다. 리소스 재배치가 완료된 후 컨트롤러 교체 작업이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
'시스템 컨트롤러 교체 쇼 디테일

+
컨트롤러 교체 절차가 일시 중지된 경우 오류를 확인 및 수정한 다음 다시 'RESSUME'를 발행하여 작업을 계속합니다.

. 필요한 경우 교체된 LIF를 복원하여 되돌리십시오. 교체된 LIF 나열:
+
'클러스터 컨트롤러 교체 네트워크 교체된 인터페이스 표시'

+
LIF가 대체된 경우 홈 노드를 노드 3으로 다시 복원합니다.

+
클러스터 컨트롤러 교체 네트워크 대체 인터페이스 복원-홈 노드

. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
시스템 컨트롤러 교체 재개

+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검
** 볼륨 확인



