---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: '를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 노드 3에 있는 노드 2의 NAS 데이터 LIF가 노드 3에서 노드 4로 재배치되는지 확인합니다 `system controller replace` 명령.' 
---
= 노드 2가 소유한 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 3에서 노드 4로 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드4의 네트워크 구성을 확인한 후, 노드2가 소유한 NAS 데이터 LIF를 노드3에서 노드4로 이동하고 노드4에 SAN LIF가 존재하는지 확인해야 합니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN으로의 트래픽을 처리합니다. 업그레이드 중 클러스터 또는 서비스 상태를 유지하기 위해 SAN LIF를 이동하는 것은 필요하지 않습니다. SAN LIF는 새 포트에 매핑해야 하는 경우를 제외하고는 이동되지 않습니다.

노드 4를 온라인 상태로 전환한 후 LIF가 정상 작동 중이고 올바른 포트에 있는지 확인합니다.


NOTE: T6 기반 이더넷 네트워크 인터페이스 카드 또는 마더보드 포트의 포트 속도를 변경하는 경우 속도 변환 후 잘못된 패킷이 수신될 수 있습니다. 을 참조하십시오 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp 버그 온라인 버그 ID 1570339"^] 기술 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["40GbE에서 100GbE로 변환한 후 T6 포트에서 CRC 오류가 발생했습니다"^] 참조하십시오.

.단계
. 재배치 작업 재개:
+
[source, cli]
----
system controller replace resume
----
+
시스템은 다음 작업을 수행합니다.

+
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


+
시스템은 네트워크 연결 가능성 확인 단계에서 작업을 일시 중지합니다.

. 재배치 작업 재개:
+
[source, cli]
----
system controller replace resume
----
+
시스템에서 다음 검사를 수행합니다.

+
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


+
이러한 확인을 수행한 후 시스템은 노드 2가 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 4의 새 컨트롤러로 재배치합니다. 리소스 재배치가 완료된 후 컨트롤러 교체 작업이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
[source, cli]
----
system controller replace show-details
----
+
컨트롤러 교체 절차가 일시 중지된 경우 오류를 확인하고 수정한 다음 문제를 해결하십시오 `resume` 를 눌러 작업을 계속합니다.

. 필요한 경우, 위치가 변경된 LIF를 복원 및 되돌리거나, 자동으로 노드4로 재배치되지 못한 노드2의 LIF를 수동으로 마이그레이션하고 수정하십시오.
+
[role="tabbed-block"]
====
.위치가 어긋난 LIF를 복원하고 되돌립니다.
--
.. 위치가 변경된 LIF를 모두 나열하십시오:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF가 대체된 경우 홈 노드를 노드 4로 복구합니다.
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIF를 수동으로 마이그레이션하고 수정합니다.
--
.. 자동으로 재배치되지 못한 LIF를 노드 4로 마이그레이션합니다.
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. 마이그레이션된 LIF의 홈 노드와 홈 포트를 수정합니다.
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
[source, cli]
----
system controller replace resume
----
+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검
** 볼륨 확인




.다음 단계
노드2가 소유한 루트가 아닌 애그리게이트 및 NAS 데이터 LIF를 노드3에서 노드4로 이동한 후link:manage-authentication-using-kmip-servers.html["KMIP 서버를 사용하여 인증 관리"].
