---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: '를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 노드를 준비하고 일련의 사전 점검을 실행합니다 `system controller replace` 명령.' 
---
= 업그레이드할 노드를 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
업그레이드할 노드를 준비하려면 다음 단계를 수행해야 합니다.

.단계
. ONTAP 명령줄에 다음 명령을 입력하여 컨트롤러 교체 프로세스를 시작합니다.
+
`system controller replace start -nodes _node_names_`

+
[NOTE]
====
** ONTAP 9.10.1부터 자동 협상 전환(통계청) 기반 업그레이드 절차가 4노드 MetroCluster FC 구성의 기본값입니다. 4노드 MetroCluster FC 구성을 업그레이드할 경우 를 실행할 때 `system controller replace start` 명령, 당신은 을 설정하여 통계청 기반 절차를 시작하는 것을 방지해야 한다 `-nso` 매개 변수 대상 `false`:
+
`system controller replace start -nodes _node_names_ -nso false`

** 를 클릭합니다 `system controller replace start` 명령은 고급 권한 수준에서만 실행할 수 있습니다.
+
`set -privilege advanced`



====
+
다음과 같은 출력이 표시됩니다.

+
....
Warning:
1. Current ONTAP version is 9.x
Before starting controller replacement operation, ensure that the new controllers are running the version 9.x

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

Do you want to continue? {y|n}: y
....
. 를 누릅니다 `y`, 다음과 같은 출력이 표시됩니다.
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
시스템에서 다음 사전 점검을 실행하고 각 사전 점검의 출력을 이 절차의 뒷부분에서 사용할 수 있도록 기록합니다.

+
[cols="35,65"]
|===
| 사전 점검 | 설명 


| 클러스터 상태 점검 | 클러스터의 모든 노드를 검사하여 정상 상태인지 확인합니다. 


| MCC 클러스터 검사 | 시스템이 MetroCluster 구성인지 확인합니다. 이 작업은 MetroCluster 구성인지 여부를 자동으로 감지하고 특정 사전 점검 및 검증 점검을 수행합니다. 4노드 MetroCluster FC 구성만 지원됩니다. 2노드 MetroCluster 구성 및 4노드 MetroCluster IP 구성의 경우, 검사에 실패합니다. MetroCluster 구성이 Switched Over 상태인 경우 검사가 실패합니다. 


| 애그리게이트 재배치 상태 점검 | 애그리게이트 재배치가 이미 진행 중인지 여부를 확인합니다. 다른 애그리게이트 재배치가 진행 중인 경우 검사에 실패합니다. 


| 모델 이름 확인 | 이 절차에서 컨트롤러 모델이 지원되는지 여부를 확인합니다. 모델이 지원되지 않으면 작업이 실패합니다. 


| 클러스터 쿼럼 점검 | 교체할 노드가 쿼럼에 있는지 확인합니다. 노드가 쿼럼에 없으면 작업이 실패합니다. 


| 이미지 버전 확인 | 교체되는 노드가 동일한 버전의 ONTAP를 실행하는지 확인합니다. ONTAP 이미지 버전이 다르면 작업이 실패합니다. 새 노드에는 원래 노드에 설치된 동일한 버전의 ONTAP 9.x가 설치되어 있어야 합니다. 새 노드의 ONTAP 버전이 다른 설치되어 있으면 새 컨트롤러를 설치한 후 netboot 해야 합니다. ONTAP를 업그레이드하는 방법에 대한 지침은 을 참조하십시오 link:other_references.html["참조"] ONTAP_ 업그레이드 링크 


| HA 상태 점검 | 교체할 두 노드가 고가용성(HA) 쌍 구성에 있는지 확인합니다. 컨트롤러에 대해 스토리지 페일오버가 설정되지 않으면 작업이 실패합니다. 


| 애그리게이트 상태 점검 | 대체되고 있는 노드가 홈 소유자가 아닌 자체 애그리게이트를 소유하는 경우 작업이 실패합니다. 노드는 비로컬 애그리게이트를 소유해서는 안 됩니다. 


| 디스크 상태 확인 | 교체할 노드에 누락된 디스크 또는 장애가 발생한 디스크가 있는 경우 작업이 실패합니다. 누락된 디스크가 있으면 을 참조하십시오 link:other_references.html["참조"] CLI_를 사용하여 _ 디스크 및 애그리게이트 관리를 _, _ CLI를 사용한 _ 논리적 스토리지 관리 및 _ 고가용성 관리 _ 에 연결하여 HA 쌍의 스토리지를 구성합니다. 


| 데이터 LIF 상태 점검 | 교체 중인 노드에 비로컬 데이터 LIF가 있는지 확인합니다. 노드에 홈 소유자가 아닌 데이터 LIF가 없어야 합니다. 노드 중 하나에 로컬이 아닌 데이터 LIF가 포함되어 있으면 작업이 실패합니다. 


| 클러스터 LIF 상태입니다 | 클러스터 LIF가 두 노드에 대해 작동 중인지 확인합니다. 클러스터 LIF가 작동 중지되면 작업이 실패합니다. 


| ASUP 상태 점검 | ASUP 알림이 구성되지 않으면 작업이 실패합니다. 컨트롤러 교체 절차를 시작하기 전에 ASUP를 활성화해야 합니다. 


| CPU 사용률 검사 | 교체할 노드에 대해 CPU 활용률이 50%를 초과하는지 확인합니다. CPU 사용량이 상당한 시간 동안 50% 이상인 경우 작업이 실패합니다. 


| 애그리게이트 재구성 검사 | 데이터 애그리게이트에서 재구성되는지 확인합니다. 애그리게이트 재구성이 진행 중인 경우 작업이 실패합니다. 


| 노드 선호도 작업 확인 | 노드 선호도 작업이 실행 중인지 확인합니다. 노드 선호도 작업이 실행 중이면 검사에 실패합니다. 
|===
. 컨트롤러 교체 작업이 시작되고 사전 점검을 완료한 후 노드 3을 구성할 때 나중에 필요할 수 있는 출력 정보를 수집할 수 있도록 작업이 일시 중지됩니다.
+

NOTE: 업그레이드를 시작하기 전에 FAS8080, AFF8080 시스템과 같이 노드당 클러스터 포트가 2개 이상인 시스템이 있는 경우 클러스터 LIF를 노드당 두 개의 클러스터 포트로 마이그레이션하고 재구성해야 합니다. 노드당 둘 이상의 클러스터 포트로 컨트롤러 업그레이드를 수행하는 경우 업그레이드 후 새 컨트롤러에 클러스터 LIF가 누락될 수 있습니다.

. 시스템 콘솔에서 컨트롤러 교체 절차의 지침에 따라 아래 명령 세트를 실행합니다.
+
각 노드에 연결된 시리얼 포트에서 다음 명령의 출력을 개별적으로 실행 및 저장합니다.

+
** `vserver services name-service dns show`
** `network interface show -curr-node _local_ -role _cluster,intercluster,node-mgmt,cluster-mgmt,data_`
** `network port show -node _local_ -type physical`
** `service-processor show -local -instance`
** `network fcp adapter show -node _local_`
** `network port ifgrp show`
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** `storage array config show -switch _switch_name_`
** `system license show -owner _local_`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `network port reachability show -detail`


+

NOTE: OKM(Onboard Key Manager)을 사용하는 NVE(NetApp Volume Encryption) 또는 NAE(NetApp Aggregate Encryption)가 사용 중인 경우 키 관리자 암호를 준비하여 절차의 후반부에서 키 관리자를 다시 동기화하는 작업을 완료하십시오.

. 시스템에서 자체 암호화 드라이브를 사용하는 경우 기술 자료 문서를 참조하십시오 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["드라이브가 FIPS 인증되었는지 확인하는 방법"^] 업그레이드하는 HA 쌍에서 사용 중인 자체 암호화 드라이브의 유형을 확인합니다. ONTAP 소프트웨어는 두 가지 유형의 자체 암호화 드라이브를 지원합니다.
+
--
** FIPS 인증 NSE(NetApp Storage Encryption) SAS 또는 NVMe 드라이브
** FIPS가 아닌 자체 암호화 NVMe 드라이브(SED)


[NOTE]
====
동일한 노드 또는 HA 쌍에서 다른 유형의 드라이브와 FIPS 드라이브를 혼합할 수 없습니다.

동일한 노드 또는 HA 쌍에서 SED를 비암호화 드라이브와 혼합할 수 있습니다.

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["지원되는 자체 암호화 드라이브에 대해 자세히 알아보십시오"^].

--




== ARL 사전 검사에 실패한 경우 애그리게이트 소유권을 수정하십시오

애그리게이트 상태 확인에 실패하면 파트너 노드가 소유한 애그리게이트를 홈 소유자 노드로 반환한 후 사전 확인 프로세스를 다시 시작해야 합니다.

.단계
. 파트너 노드가 현재 소유한 애그리게이트를 홈 소유자 노드로 반환:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. 노드 1과 노드 2가 현재 소유자인 애그리게이트를 소유하지 않고 홈 소유자가 아닌 경우:
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
다음 예제는 노드가 Aggregate의 현재 소유자이자 홈 소유자인 경우 명령의 출력을 보여줍니다.

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== 작업을 마친 후

컨트롤러 교체 프로세스를 다시 시작해야 합니다.

`system controller replace start -nodes _node_names_`



== 라이센스

클러스터를 설정할 때 설치 마법사에서 클러스터 기본 라이센스 키를 입력하라는 메시지가 표시됩니다. 그러나 일부 기능에는 하나 이상의 기능을 포함하는 _packages_로 발급된 추가 라이센스가 필요합니다. 클러스터의 각 노드에는 클러스터에서 사용되는 각 기능에 대한 자체 키가 있어야 합니다.

새 라이센스 키가 없는 경우, 클러스터에서 현재 라이센스가 부여된 기능을 새 컨트롤러에서 사용할 수 있습니다. 그러나 컨트롤러에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 업그레이드가 완료된 후 새 컨트롤러의 새 라이센스 키 또는 키를 설치해야 합니다.

을 참조하십시오 link:other_references.html["참조"] ONTAP에 대한 새로운 2자리 라이센스 키를 얻을 수 있는 _NetApp Support 사이트_에 대한 링크입니다. 키는 _ 소프트웨어 라이센스 _ 의 _ My Support _ 섹션에서 사용할 수 있습니다. 사이트에 필요한 라이센스 키가 없는 경우 NetApp 세일즈 담당자에게 문의하십시오.

라이센스에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 시스템 관리 참조 _ 에 대한 링크
