---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 "시스템 컨트롤러 교체" 명령을 사용하여 노드3 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성하십시오.' 
---
= 노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 3에 온보드 FC 포트, 온보드 UTA/UTA2(Unified Target Adapter) 포트 또는 UTA/UTA2 카드가 있는 경우, 나머지 절차를 완료하기 전에 설정을 구성해야 합니다.

이 섹션을 완료해야 할 수 있습니다  FC ports on node3섹션을 참조하십시오  and configure UTA/UTA2 ports on node3또는 두 섹션을 모두 선택합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 라는 용어를 사용하여 통합 네트워크 어댑터(CNA) 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

* 노드 3에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 없는 경우 스토리지 디스크를 사용하여 시스템을 업그레이드하는 경우 로 건너뛸 수 있습니다 link:verify_node3_installation.html["노드3 설치를 확인합니다"] 섹션을 참조하십시오.
* 하지만 스토리지 어레이가 있는 FlexArray 가상화 소프트웨어를 사용하는 V 시리즈 시스템이나 시스템이 있고 노드 3에 온보드 FC 포트, 온보드 UTA/UTA 포트 또는 UTA/UTA2 카드가 없는 경우, _Install and boot node3_섹션으로 돌아가서 섹션을 다시 시작하십시오 link:install_boot_node3.html#step23["23단계"].


.선택
*  FC ports on node3
*  and configure UTA/UTA2 ports on node3




== 노드 3에서 FC 포트를 구성합니다

노드 3에 온보드 또는 FC 어댑터의 FC 포트가 있는 경우 포트가 사전 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다. 포트가 구성되지 않은 경우 서비스가 중단될 수 있습니다.

섹션에 저장한 노드 1의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 있는 경우, 에서 포트를 구성합니다  and configure UTA/UTA2 ports on node3.

* 중요 *: 시스템에 스토리지 디스크가 있는 경우 이 섹션의 명령을 클러스터 프롬프트에 입력합니다. 'V-Series 시스템'이 있거나 FlexArray 가상화 소프트웨어가 설치되어 있고 스토리지 어레이에 연결되어 있는 경우, 유지보수 모드에서 이 섹션의 명령을 입력하십시오.

. [[step1]]노드 3의 FC 설정을 노드 1에서 이전에 캡처한 설정과 비교합니다.
. [[step2]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
유지보수 모드(부팅 메뉴의 옵션 5)에서 필요에 따라 노드 3의 FC 포트를 수정합니다.

** 타겟 포트를 프로그래밍하려면


'ucadmin modify -m fc-t target_adapter_'

** 이니시에이터 포트를 프로그래밍하려면:


'ucadmin modify -m fc -t initiator_adapter_'

'-t'는 FC4 유형이며 타겟이나 이니시에이터입니다.



| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 유지보수 모드(부팅 메뉴의 옵션 5)에서 필요에 따라 노드 3의 FC 포트를 수정합니다. 'ucadmin modify -m fc -t initiator -f_adapter_port_name_' -t'는 FC4 유형, 타겟 또는 이니시에이터입니다. * 참고 *: FC 포트는 이니시에이터로 프로그래밍해야 합니다. 
|===
. [[step3]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다 | 다음 명령을 사용하여 출력을 검사하여 새 설정을 확인합니다. 'ucadmin show 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 다음 명령을 사용하여 출력을 검사하여 새 설정을 확인합니다. 'ucadmin show 
|===
. [[4단계]] 유지보수 모드 종료:
+
"중지"

. 로더 프롬프트에서 시스템을 부팅합니다.
+
boot_ontap 메뉴

. [[step6]] 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다립니다.
. 유지보수 모드의 부팅 메뉴에서 옵션 '5'를 선택합니다.


. [[auto_check3_step8]]다음 작업 중 하나를 수행합니다.
+
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| 스토리지 디스크가 있습니다  a| 
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우 섹션으로 이동하십시오  and configure UTA/UTA2 ports on node3.
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우 섹션을 건너뛰십시오  and configure UTA/UTA2 ports on node3 섹션으로 이동합니다 link:verify_node3_installation.html["노드3 설치를 확인합니다"].




| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다  a| 
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있는 경우 섹션으로 이동하십시오  and configure UTA/UTA2 ports on node3.
** 노드 3에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우 섹션을 건너뛰십시오  and configure UTA/UTA2 ports on node3 그런 다음, _Install and boot node3_ 섹션으로 돌아가서 에서 다시 시작합니다 link:install_boot_node3.html#step23["23단계"].


|===




== 노드 3의 UTA/UTA2 포트를 확인하고 구성합니다

노드 3에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드를 사용하는 경우, 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 필요에 따라 포트를 다시 구성해야 합니다.

UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

FC에 UTA/UTA2(Unified Target Adapter) 포트를 사용하려면 먼저 포트 구성 방법을 확인해야 합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

'ucadmin show' 명령을 사용하여 현재 포트 구성을 확인할 수 있습니다.

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드는 동일한 10GbE SFP+ 인터페이스를 공유하는 NIC 및 FCoE 트래픽을 동시에 허용할 수 있으며 FC 타겟을 지원합니다.

UTA/UTA2 포트는 어댑터 또는 컨트롤러에서 찾을 수 있으며 다음과 같은 구성을 가지고 있지만 노드 3의 UTA/UTA2 포트 구성을 확인하고 필요에 따라 변경해야 합니다.

* 컨트롤러를 주문할 때 주문한 UTA/UTA2 카드는 사용자가 요청하는 Personality를 요청하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 배송 전에 사용자가 요청하는 Personality를 사용하도록 구성되었습니다.
+

WARNING: * 주의 *: 시스템에 스토리지 디스크가 있는 경우, 유지보수 모드로 들어가라는 지시가 없는 한 클러스터 프롬프트에서 이 섹션에 있는 명령을 입력합니다. V-Series 시스템이 있거나 FlexArray 가상화 소프트웨어가 있고 스토리지 어레이에 연결되어 있는 경우, 유지 관리 모드 프롬프트에서 이 섹션에 명령을 입력합니다. UTA/UTA2 포트를 구성하려면 유지보수 모드여야 합니다.



.단계
. [[step1]] 노드 3에서 다음 명령을 입력하여 포트가 현재 어떻게 구성되어 있는지 확인합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 별도의 조치가 필요 없습니다. 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'ucadmin 쇼' 
|===
+
다음 예와 유사한 출력이 표시됩니다.

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2]] 현재 SFP+ 모듈이 원하는 용과 일치하지 않으면 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. [[step3]]ucadmin show 명령의 출력을 확인하여 UTA/UTA2 포트가 원하는 특성을 갖고 있는지 확인합니다.
. [[4단계]] 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| UTA/UTA2 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 이동합니다 ,5단계. 


| 원하는 개성을 갖고 싶어하세요 | 단계 5에서 단계 12까지 건너뛰고 로 이동합니다 ,13단계. 
|===
. [[auto_check3_step5]]다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 이동합니다 ,7단계 


| 온보드 UTA/UTA2 포트 | 7단계를 건너뛰고 로 이동합니다 ,8단계. 
|===
. [[step6]] 어댑터가 이니시에이터 모드에 있고 UTA/UTA2 포트가 온라인 상태인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
'STORAGE DISABLE ADAPTER_ADAPTER_NAME_'

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check3_step7]] 현재 구성이 원하는 용과 일치하지 않으면 필요에 따라 구성을 변경합니다.
+
''ucadmin modify -m fc|CNA-t initiator|target_adapter_name_'

+
** m은 성격 모드, 즉 fc, CNA.
** t는 FC4형, target 또는 initiator입니다.
+

NOTE: 테이프 드라이브, FlexArray 가상화 시스템 및 MetroCluster 구성에 FC Initiator를 사용해야 합니다. SAN 클라이언트에 FC 타겟을 사용해야 합니다.



. [[auto_check3_step8]] 설정을 확인합니다.
+
'ucadmin 쇼'

. [[9단계]] 설정을 확인합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 'ucadmin 쇼' 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'ucadmin 쇼' 
|===
+
다음 예제의 출력은 어댑터 "1b"의 FC4 유형이 "이니시에이터"로 변경되고 어댑터 "2a"와 "2b"의 모드가 "CNA"로 변경되었음을 보여줍니다.

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[10단계]] 각 포트에 대해 다음 명령 중 하나를 한 번 입력하여 대상 포트를 온라인으로 전환합니다.
+
[cols="30,70"]
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 'network fcp adapter modify -node_node_name_-adapter_adapter_name_-state up 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | 'fcp config_adapter_name_up 
|===
. [[step11]] 포트에 케이블을 연결합니다.


. [[auto_check3_step12]]다음 작업 중 하나를 수행합니다.
+
|===
| 시스템이... | 그러면... 


| 스토리지 디스크가 있습니다 | 로 이동합니다 link:verify_node3_installation.html["노드3 설치를 확인합니다"]. 


| V-Series 시스템이거나 FlexArray 가상화 소프트웨어가 있으며 스토리지 어레이에 연결되어 있습니다 | Install and boot node3_ 섹션으로 돌아가서 에서 다시 시작합니다 link:install_boot_node3.html#step23["23단계"]. 
|===
. [[auto_check3_step13]]유지보수 모드 종료:
+
"중지"

. [[pep14]]boot_ONTAP 메뉴를 실행하여 부팅 메뉴로 노드를 부팅합니다. A800으로 업그레이드할 경우 으로 이동하십시오 ,23단계.


. [[auto9597_check_node3_step15]]노드 3에서 부팅 메뉴로 이동하여 22/7을 사용하여 숨겨진 옵션인 boot_after_controller_replacement를 선택합니다. 다음 예에 따라 프롬프트에 node1을 입력하여 node3에 노드 1의 디스크를 재할당합니다.
+
.콘솔 출력 예를 확장합니다
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: 위의 콘솔 출력 예에서 시스템이 ADP(고급 디스크 파티셔닝) 디스크를 사용하는 경우 ONTAP에서 파트너 노드 이름을 묻는 메시지를 표시합니다.

. 시스템이 "디스크를 찾을 수 없음" 메시지와 함께 재부팅 루프에 들어갈 경우 시스템이 FC 또는 UTA/UTA2 포트를 타겟 모드로 다시 설정했기 때문에 디스크를 볼 수 없음을 나타냅니다. 이 문제를 해결하려면 을 계속 진행합니다 ,17단계 를 선택합니다 ,22단계또는 섹션으로 이동합니다 link:verify_node3_installation.html["노드3 설치를 확인합니다"].
. [[auto_check3_step17]]로더의 프롬프트에서 노드를 중지하려면 자동 부팅 중에 'Ctrl-C'를 누릅니다.
. [[step18]] 로더 프롬프트에서 유지보수 모드로 전환합니다.
+
boot_ONTAP maint를 선택합니다

. [[19단계]] 유지보수 모드에서 현재 타겟 모드에 있는 이전에 설정된 이니시에이터 포트를 모두 표시합니다.
+
'ucadmin 쇼'

+
포트를 다시 이니시에이터 모드로 변경합니다.

+
'ucadmin modify -m fc -t initiator -f_adapter name _'

. [[step20]] 포트가 이니시에이터 모드로 변경되었는지 확인합니다.
+
'ucadmin 쇼'

. [[step21]]유지보수 모드 종료:
+
"중지"

+
[NOTE]
====
외부 디스크를 지원하는 시스템에서 외부 디스크도 지원하는 시스템으로 업그레이드하는 경우 로 이동합니다 ,22단계.

외부 디스크를 지원하는 시스템에서 AFF A800 시스템과 같은 내부 디스크와 외부 디스크를 모두 지원하는 시스템으로 업그레이드하는 경우 로 이동하십시오 ,23단계.

====
. [[auto_check3_step22]] 로더 프롬프트에서 다음 항목을 부팅합니다.
+
부트 ONTAP

+
이제 부팅 시 노드에서 이전에 할당되었으며 예상대로 부팅할 수 있는 모든 디스크를 감지할 수 있습니다.

. [[auto_check3_step23] 외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node1 애그리게이트를 루트 애그리게이트로 설정하여 node3이 node1의 루트 애그리게이트에서 부팅되는지 확인하십시오. 루트 애그리게이트를 설정하려면 부팅 메뉴로 이동하여 옵션 '5'를 선택하여 유지보수 모드로 전환하십시오.
+

CAUTION: * 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다. *

+
다음 절차에서는 노드 3이 노드 1의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 유지보수 모드로 전환:
+
boot_ONTAP maint를 선택합니다

.. 노드 1 애그리게이트에 대한 RAID, plex 및 체크섬 정보를 확인합니다.
+
'gagr status-r'입니다

.. node1 애그리게이트의 상태를 확인합니다.
+
'기정 상태'입니다

.. 필요한 경우 node1 애그리게이트를 온라인 상태로 전환합니다.
+
'aggr_online root_aggr_from___node1_'

.. 노드 3이 원래 루트 애그리게이트로부터 부팅하지 않도록 합니다.
+
'aggr offline_root_aggr_on_node3_'

.. 노드 1의 루트 애그리게이트를 노드 3의 새 루트 애그리게이트로 설정합니다.
+
'aggr 옵션 aggr_from____node1__root'

.. 노드 3의 루트 애그리게이트가 오프라인 상태이고 노드 1에서 가져온 디스크의 루트 애그리게이트가 온라인 상태이고 루트:
+
'기정 상태'입니다

+

NOTE: 이전 하위 단계를 수행하지 않으면 노드 3이 내부 루트 애그리게이트에서 부팅되거나 시스템에서 새 클러스터 구성이 있다고 가정하거나 클러스터 구성을 확인하라는 메시지가 표시될 수 있습니다.

+
다음은 명령 출력의 예입니다.

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



