---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: '을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 노드 3 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성하십시오 `system controller replace` 명령.' 
---
= 노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 3에 온보드 FC 포트, 온보드 UTA/UTA2(Unified Target Adapter) 포트 또는 UTA/UTA2 카드가 있는 경우, 나머지 절차를 완료하기 전에 설정을 구성해야 합니다.

.이 작업에 대해
이 섹션을 완료해야 할 수 있습니다 <<노드 3에서 FC 포트를 구성합니다>>섹션을 참조하십시오 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>또는 두 섹션을 모두 선택합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 라는 용어를 사용하여 통합 네트워크 어댑터(CNA) 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

node3에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드(예: ONTAP 9.15.1부터 도입된 AFF 및 FAS 시스템)가 없고 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 다음으로 건너뛸 수 있습니다.link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3에 재할당합니다"] .



== 노드 3에서 FC 포트를 구성합니다

노드3에 FC 포트가 있는 경우(온보드 또는 추가 FC 어댑터에 있음), 시스템이 배송될 때 포트가 미리 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다.  포트를 구성하지 않으면 서비스가 중단될 수 있습니다.

.시작하기 전에
섹션에 저장한 노드 1의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드가 있는 경우, 에서 포트를 구성합니다 <<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 유지 관리 모드 셸 프롬프트에서 이 섹션의 명령을 입력합니다.

.단계
. 노드 3의 FC 설정을 노드 1에서 이전에 캡처한 설정과 비교합니다.
. 필요에 따라 다음 작업 중 하나를 수행하여 node3의 FC 포트를 수정합니다.
+
유지 관리 모드에서(부팅 메뉴의 옵션 5):

+
** 대상 포트로 프로그래밍하려면:
+
`ucadmin modify -m fc -t target <adapter>`

+
예를 들어: `ucadmin modify -m fc -t target 2a`

** 이니시에이터 포트를 프로그래밍하려면:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
예를 들어: `ucadmin modify -m fc -t initator 2b`



. 다음 명령을 사용하여 새로운 설정을 확인하고 출력을 살펴보세요.
+
`ucadmin show`

. 노드 중단:
+
`halt`

. LOADER 프롬프트에서 시스템을 부팅합니다.
+
`boot_ontap menu`

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 옵션을 선택합니다 `5` 를 참조하십시오.


. [[auto_check3_step8]]다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| 노드 3의 경우... | 그러면... 


| UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 있습니다. | 로 가다<<노드 3의 UTA/UTA2 포트를 확인하고 구성합니다>> 


| UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없습니다. | _node3에서 UTA/UTA2 포트 확인 및 구성_을 건너뛰고 다음으로 이동합니다.link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3에 재할당합니다"] . 
|===




== 노드 3의 UTA/UTA2 포트를 확인하고 구성합니다

노드 3에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드를 사용하는 경우, 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 필요에 따라 포트를 다시 구성해야 합니다.

.시작하기 전에
UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

.이 작업에 대해
FC에 UTA/UTA2(Unified Target Adapter) 포트를 사용하려면 먼저 포트 구성 방법을 확인해야 합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

당신은 사용할 수 있습니다 `ucadmin show` 다음 예제 출력에서 볼 수 있듯이 현재 포트 구성을 보거나 확인하기 위한 명령입니다.

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드는 동일한 10GbE SFP+ 인터페이스를 공유하는 NIC 및 FCoE 트래픽을 동시에 허용할 수 있으며 FC 타겟을 지원합니다.

추가 어댑터나 컨트롤러 마더보드에서 UTA/UTA2 포트를 찾을 수 있으며 다음과 같은 구성을 가지고 있을 수 있지만, node3에서 UTA/UTA2 포트의 구성을 확인하고 필요한 경우 변경해야 합니다.

* 컨트롤러를 주문할 때 주문한 UTA/UTA2 카드는 사용자가 요청하는 Personality를 요청하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 배송 전에 사용자가 요청하는 Personality를 사용하도록 구성되었습니다.
+

WARNING: UTA/UTA2 포트를 구성하려면 유지 관리 모드에 있어야 합니다.  유지 관리 모드 셸 프롬프트에서 이 섹션의 명령을 입력합니다.



.단계
. 현재 SFP+ 모듈이 원하는 용과 일치하지 않는 경우 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. UTA/UTA2 포트 설정을 확인하세요.
+
`ucadmin show`

+
출력을 검토하여 UTA/UTA2 포트가 원하는 특성을 가지고 있는지 확인하세요.

+
다음 예제의 출력은 어댑터 "1b"의 유형이 개시자로 변경되고 어댑터 "2a"와 "2b"의 모드가 "cna"로 변경되는 것을 보여줍니다.  CNA 모드에서는 카드를 네트워크 어댑터로 사용할 수 있습니다.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 다음 작업 중 하나를 수행합니다.
+
[cols="30,70"]
|===
| UTA/UTA2 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 가다<<auto_check3_step4,4단계>> . 


| 원하는 개성을 갖고 싶어하세요 | 4단계부터 8단계까지 건너뛰고 다음으로 이동하세요.<<auto_check3_step9,9단계>> . 
|===
. [[auto_check3_step4]]다음 작업 중 하나를 수행하세요.
+
[cols="30,70"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2 카드 포트 | 로 가다<<auto_check3_step5,5단계>> 


| 온보드 UTA/UTA2 포트 | 5단계를 건너뛰고 다음으로 이동하세요.<<auto_check3_step6,6단계>> . 
|===
. [[auto_check3_step5]]어댑터가 이니시에이터 모드이고 UTA/UTA2 포트가 온라인인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
`storage disable adapter <adapter_name>`

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[auto_check3_step6]]현재 구성이 원하는 용도와 일치하지 않으면 필요에 따라 구성을 변경하세요.
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` 성격 모드, `fc` 또는 `cna`.
** `-t` FC4형, `target` 또는 `initiator`.
+

NOTE: 테이프 드라이브와 MetroCluster 구성에는 FC 이니시에이터를 사용해야 합니다.  SAN 클라이언트의 경우 FC 대상을 사용해야 합니다.



. 각 포트에 대해 다음 명령을 한 번씩 입력하여 대상 포트를 온라인으로 전환합니다.
+
`storage enable adapter <adapter_name>`

. 포트에 케이블을 연결합니다.


[[auto_check3_step9]]
. 유지보수 모드 종료:
+
`halt`

. [[14단계]] 노드를 부팅 메뉴로 부팅합니다.
+
`boot_ontap menu`



.다음 단계
* AFF A800 시스템으로 업그레이드하는 경우 다음으로 이동하세요.link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["노드1 디스크를 노드3, 9단계에 재할당합니다"] .
* 다른 모든 시스템 업그레이드의 경우 다음으로 이동하세요.link:reassign-node1-disks-to-node3.html["노드1 디스크를 노드3, 1단계에 재할당합니다"] .

