---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_node3_installation.html 
keywords: verifying, verify, node, install, installation 
summary: '를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 node1 물리적 포트가 노드 3에 올바르게 매핑되고 노드 3의 네트워크 구성을 복원하는지 확인합니다 `system controller replace` 명령.' 
---
= 노드3 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 1의 물리적 포트가 노드 3의 물리적 포트에 올바르게 매핑되는지 확인해야 합니다. 이렇게 하면 노드 3이 업그레이드 후 클러스터의 다른 노드 및 네트워크와 통신할 수 있습니다.

.이 작업에 대해
을 참조하십시오 link:other_references.html["참조"] 새 노드의 포트에 대한 정보를 캡처하기 위해 _Hardware Universe_에 연결합니다. 이 섹션의 뒷부분에서 정보를 사용합니다.

물리적 포트 레이아웃은 노드의 모델에 따라 다를 수 있습니다. 새 노드가 부팅되면 ONTAP는 자동으로 쿼럼에 진입하기 위해 클러스터 LIF를 호스팅할 포트를 결정합니다.

노드 1의 물리적 포트가 노드 3의 물리적 포트에 직접 매핑되지 않으면 다음 섹션을 참조하십시오 <<노드3에서 네트워크 구성을 복원합니다>> 네트워크 연결을 복구하는 데 사용해야 합니다.

노드 3을 설치하고 부팅한 후에는 올바르게 설치되었는지 확인해야 합니다. 노드 3이 쿼럼에 참가할 때까지 기다린 다음 재배치 작업을 다시 시작해야 합니다.

절차의 이 시점에서 노드 3이 쿼럼을 조인할 때 작업이 일시 중지됩니다.

.단계
. 노드 3이 쿼럼에 연결되었는지 확인합니다.
+
`cluster show -node node3 -fields health`

+
의 출력입니다 `health` 필드는 이어야 합니다 `true`.

. 노드 3이 노드 2와 동일한 클러스터의 일부이고 정상 상태인지 확인합니다.
+
`cluster show`

. 각 클러스터 LIF는 포트 7700에서 수신 대기 중이어야 합니다. 클러스터 LIF가 포트 7700에서 수신 중인지 확인합니다.
+
`::> network connections listening show -vserver Cluster`

+
클러스터 포트에서 수신 대기하는 포트 7700은 2노드 클러스터의 다음 예에 표시된 대로 예상되는 결과입니다.

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 필요한 경우 포트 7700에서 청취하지 않는 각 클러스터 LIF에 대해 LIF의 관리 상태를 로 설정합니다 `down` 그리고 나서 `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
3단계를 반복하여 클러스터 LIF가 포트 7700에서 수신 대기 중인지 확인합니다.

. 고급 권한 모드로 전환:
+
`set advanced`

. 컨트롤러 교체 작업의 상태를 확인하고 해당 상태가 노드 1이 중지되기 전의 일시 중지 상태와 동일한지 확인하여 새 컨트롤러 설치 및 케이블 이동에 대한 물리적 작업을 수행합니다.
+
`system controller replace show`

+
`system controller replace show-details`

. MetroCluster 시스템에서 작업하는 경우 교체된 컨트롤러가 MetroCluster 구성에 맞게 올바르게 구성되었는지 확인합니다. MetroCluster 구성은 양호한 상태여야 합니다. 을 참조하십시오 link:verify_health_of_metrocluster_config.html["MetroCluster 구성의 상태를 확인합니다"].
+
6단계로 진행하기 전에 MetroCluster 노드 노드 3의 인터클러스터 LIF를 재구성하고 클러스터 피어링을 확인하여 MetroCluster 노드 간의 통신을 복원합니다.

+
MetroCluster 노드 상태 확인:

+
`metrocluster node show`

. 컨트롤러 교체 작업을 재개합니다.
+
`system controller replace resume`

. 컨트롤러 교체는 다음 메시지와 함께 중재에 대해 일시 중지됩니다.
+
....
Cluster::*> system controller replace show
Node             Status                       Error-Action
---------------- ------------------------     ------------------------------------
Node1(now node3) Paused-for-intervention      Follow the instructions given in
                                              Step Details
Node2                      None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:

1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.

2 entries were displayed.
....
+

NOTE: 이 절차에서 _VLAN, ifgrp 및 브로드캐스트 도메인_을(를) 다시 생성하는 섹션이 node3_에서 _Restore 네트워크 구성 으로 변경되었습니다.

. 컨트롤러 교체가 일시 중지됨 상태인 경우 이 문서의 다음 섹션으로 진행하여 노드에서 네트워크 구성을 복원합니다.




== 노드3에서 네트워크 구성을 복원합니다

노드 3이 쿼럼에 있고 노드 2와 통신할 수 있는지 확인한 후 노드 1의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인이 노드 3에 표시되는지 확인합니다. 또한 모든 node3 네트워크 포트가 올바른 브로드캐스트 도메인에 구성되어 있는지 확인합니다.

.이 작업에 대해
VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 네트워크 관리 _ 에 대한 링크.

.단계
. [[step1]] 업그레이드된 노드1에 있는 모든 물리적 포트(node3이라고 함)를 나열합니다.
+
`network port show -node node3`

+
노드의 모든 물리적 네트워크 포트, VLAN 포트 및 인터페이스 그룹 포트가 표시됩니다. 이 출력에서 로 이동된 모든 물리적 포트를 볼 수 있습니다 `Cluster` ONTAP에 의한 브로드캐스트 도메인. 이 출력을 사용하면 인터페이스 그룹 구성원 포트, VLAN 기본 포트 또는 LIF 호스팅을 위한 독립 실행형 물리적 포트로 사용해야 하는 포트를 쉽게 결정할 수 있습니다.

. [[step2]] 클러스터의 브로드캐스트 도메인을 나열합니다.
+
`network port broadcast-domain show`

. [[step3]]노드 3의 모든 포트에 대한 네트워크 포트 도달 가능 여부 나열:
+
`network port reachability show`

+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
clusterA::*> reachability show -node node1_node3
(network port reachability show)
Node         Port       Expected Reachability   Reachability Status
-----------  ---------  ----------------------  ----------------------
node1_node3
             a0a        Default:Default         no-reachability
             a0a-822    Default:822             no-reachability
             a0a-823    Default:823             no-reachability
             e0M        Default:Mgmt            ok
             e0a        Cluster:Cluster         misconfigured-reachability
             e0b        Cluster:Cluster         no-reachability
             e0c        Cluster:Cluster         no-reachability
             e0d        Cluster:Cluster         no-reachability
             e0e        Cluster:Cluster         ok
             e0e-822    -                       no-reachability
             e0e-823    -                       no-reachability
             e0f        Default:Default         no-reachability
             e0f-822    Default:822             no-reachability
             e0f-823    Default:823             no-reachability
             e0g        Default:Default         misconfigured-reachability
             e0h        Default:Default         ok
             e0h-822    Default:822             ok
             e0h-823    Default:823             ok
18 entries were displayed.
----
+
앞의 예제에서 node1_node3은 컨트롤러 교체 직후에 부팅됩니다. 일부 포트는 예상 브로드캐스트 도메인에 대한 도달 능력이 없으므로 복구해야 합니다.

. [[auto_verify_3_step4]([auto_verify_3_step4]). 노드 3의 각 포트에 대한 내 상태를 이외의 다른 상태로 복구합니다 `ok`. 먼저 물리적 포트에서 다음 명령을 실행한 다음 VLAN 포트에서 한 번에 하나씩 실행합니다.
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Cluster ::> reachability repair -node node1_node3 -port e0h
----
+
[listing]
----
Warning: Repairing port "node1_node3: e0h" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
위에 표시된 것처럼, 현재 위치한 브로드캐스트 도메인의 도달 가능성 상태와 다를 수 있는 도달 가능성 상태의 포트에 대해 경고 메시지가 표시됩니다. 포트의 연결을 검토하고 응답합니다 `y` 또는 `n` 있습니다.

+
모든 물리적 포트에 예상되는 도달 능력이 있는지 확인합니다.

+
`network port reachability show`

+
도달 가능성 복구가 수행되면 ONTAP는 포트를 올바른 브로드캐스트 도메인에 배치하려고 시도합니다. 그러나 포트의 도달 가능 여부를 확인할 수 없고 기존 브로드캐스트 도메인에 속하지 않는 경우 ONTAP는 이러한 포트에 대한 새 브로드캐스트 도메인을 만듭니다.

. [[5단계]] 인터페이스 그룹 구성이 새 컨트롤러의 물리적 포트 레이아웃과 일치하지 않으면 다음 단계를 사용하여 수정하십시오.
+
.. 먼저 브로드캐스트 도메인 멤버쉽에서 인터페이스 그룹 구성원 포트여야 하는 물리적 포트를 제거해야 합니다. 이 작업은 다음 명령을 사용하여 수행할 수 있습니다.
+
`network port broadcast-domain remove-ports -broadcast-domain _broadcast-domain_name_ -ports _node_name:port_name_`

.. 인터페이스 그룹에 구성원 포트를 추가합니다.
+
`network port ifgrp add-port -node _node_name_ -ifgrp _ifgrp_ -port _port_name_`

.. 첫 번째 구성원 포트가 추가된 후 약 1분 후에 인터페이스 그룹이 브로드캐스트 도메인에 자동으로 추가됩니다.
.. 인터페이스 그룹이 적절한 브로드캐스트 도메인에 추가되었는지 확인합니다.
+
`network port reachability show -node _node_name_ -port _ifgrp_`

+
인터페이스 그룹의 도달 가능성 상태가 아닌 경우 `ok`에서 해당 브로드캐스트 도메인에 할당합니다.

+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_name_ -ports _node:port_`



. [[6단계]] 에 적절한 물리적 포트를 할당합니다 `Cluster` 다음 단계를 사용하여 도메인을 브로드캐스트합니다.
+
.. 에 대한 도달 가능한 포트를 확인합니다 `Cluster` 브로드캐스트 도메인:
+
`network port reachability show -reachable-broadcast-domains Cluster:Cluster`

.. 에 대한 연결 기능을 사용하여 모든 포트를 복구합니다 `Cluster` 브로드캐스트 도메인(내 상태 상태가 아닐 경우) `ok`:
+
`network port reachability repair -node _node_name_ -port _port_name_`



. [[7단계]] 다음 명령 중 하나를 사용하여 나머지 물리적 포트를 올바른 브로드캐스트 도메인으로 이동합니다.
+
`network port reachability repair -node _node_name_ -port _port_name_`

+
`network port broadcast-domain remove-port`

+
`network port broadcast-domain add-port`

+
연결할 수 없거나 예상치 못한 포트가 없는지 확인합니다. 다음 명령을 사용하여 출력을 검사하여 상태가 인지 확인하여 모든 물리적 포트의 도달 가능성 상태를 확인합니다 `ok`:

+
`network port reachability show -detail`

. [[8단계]] 다음 단계를 사용하여 대체될 수 있는 모든 VLAN을 복원합니다.
+
.. 교체된 VLAN 나열:
+
`cluster controller-replacement network displaced-vlans show`

+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Cluster::*> displaced-vlans show
(cluster controller-replacement network displaced-vlans show)
          Original
Node      Base Port   VLANs
--------  ----------  -----------------------------------------
Node1       a0a       822, 823
            e0e       822, 823
2 entries were displayed.
----
.. 이전 기본 포트에서 대체된 VLAN 복원:
+
`cluster controller-replacement network displaced-vlans restore`

+
다음은 인터페이스 그룹 "a0a"에서 동일한 인터페이스 그룹으로 다시 교체된 VLAN을 복원하는 예입니다.

+
[listing]
----
Cluster::*> displaced-vlans restore -node node1_node3 -port a0a -destination-port a0a
----
+
다음은 포트 "e0e"에서 'e0h'로 교체된 VLAN을 복원하는 예입니다.

+
[listing]
----
Cluster::*> displaced-vlans restore -node node1_node3 -port e0e -destination-port e0h
----
+
VLAN 복원이 성공하면 지정된 대상 포트에 교체된 VLAN이 생성됩니다. 대상 포트가 인터페이스 그룹의 구성원이거나 대상 포트가 다운된 경우 VLAN 복원이 실패합니다.

+
새로 복원된 VLAN이 해당 브로드캐스트 도메인에 배치될 때까지 약 1분 정도 기다립니다.

.. 에 없는 VLAN 포트에 필요한 경우 새 VLAN 포트를 생성합니다 `cluster controller-replacement network displaced-vlans show` 출력은 다른 물리적 포트에 구성해야 합니다.


. [[step9]] 모든 포트 수리가 완료된 후 빈 브로드캐스트 도메인을 삭제합니다.
+
`network port broadcast-domain delete -broadcast-domain _broadcast_domain_name_`

. [[10단계]] 포트 도달 가능성 확인:
+
`network port reachability show`

+
모든 포트가 올바르게 구성되고 올바른 브로드캐스트 도메인에 추가되면 가 `network port reachability show` 명령은 의 도달 가능성 상태를 보고해야 합니다 `ok` 연결된 모든 포트에 대해 및 상태를 로 표시합니다 `no-reachability` 물리적 연결이 없는 포트의 경우 이 두 포트가 아닌 다른 상태를 보고하는 포트가 있는 경우 의 지침에 따라 연결 가능성 복구를 수행하고 브로드캐스트 도메인에서 포트를 추가 또는 제거합니다 <<auto_verify_3_step4,4단계>>.

. 모든 포트가 브로드캐스트 도메인에 배치되었는지 확인합니다.
+
`network port show`

. 브로드캐스트 도메인의 모든 포트에 올바른 MTU(Maximum Transmission Unit)가 구성되어 있는지 확인합니다.
+
`network port broadcast-domain show`

. 복원 LIF 홈 포트: SVM 홈 포트 및 LIF 홈 포트(있는 경우)를 지정하고 다음 단계를 사용하여 복원해야 합니다.
+
.. 대체된 LIF를 나열합니다.
+
`displaced-interface show`

.. LIF 홈 노드 및 홈 포트를 복원합니다.
+
`cluster controller-replacement network displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. 모든 LIF에 홈 포트가 있고 관리상 작동하는지 확인합니다.
+
`network interface show -fields home-port, status-admin`


