---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_node4_installation.html 
keywords: verify, node4, installation, physical ports, node2, node, LIF, MetroCluster 
summary: System controller replace 명령을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러를 업그레이드할 때 node2의 물리적 포트가 node4에 올바르게 매핑되는지 확인하고 node4의 네트워크 구성을 복원하십시오. 
---
= 노드 4 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2의 물리적 포트가 노드 4의 물리적 포트에 올바르게 매핑되는지 확인해야 합니다. 이렇게 하면 노드 4가 업그레이드 후 클러스터의 다른 노드 및 네트워크와 통신할 수 있습니다.

을 참조하십시오 link:other_references.html["참조"] 새 노드의 포트에 대한 정보를 캡처하기 위해 _Hardware Universe_에 연결합니다. 이 섹션의 뒷부분에서 정보를 사용합니다.

물리적 포트 레이아웃은 노드의 모델에 따라 다를 수 있습니다. 새 노드가 부팅되면 ONTAP는 자동으로 쿼럼에 진입하기 위해 클러스터 LIF를 호스팅할 포트를 결정합니다.

노드 2의 물리적 포트가 노드 4의 물리적 포트에 직접 매핑되지 않으면 다음 섹션을 참조하십시오 <<Restore network configuration on node4>> 네트워크 연결을 복구하는 데 사용해야 합니다.

노드 4를 설치하고 부팅한 후 올바르게 설치되었는지 확인해야 합니다. 노드 4가 쿼럼에 참가할 때까지 기다린 다음 재배치 작업을 다시 시작해야 합니다.

절차의 이 시점에서 노드 4가 쿼럼을 조인할 때 작업이 일시 중지됩니다.

.단계
. 노드 4가 쿼럼에 연결되었는지 확인합니다.
+
클러스터 show-node node4-fields 상태

+
건강필드의 출력은 사실이어야 합니다.

. 노드 4가 노드 3과 동일한 클러스터에 포함되어 있고 정상 상태인지 확인합니다.
+
'클러스터 쇼'

. 각 클러스터 LIF는 포트 7700에서 수신 대기 중이어야 합니다. 클러스터 LIF가 포트 7700에서 수신 중인지 확인합니다.
+
'::> 네트워크 연결 수신 표시 - vserver 클러스터'

+
클러스터 포트에서 수신 대기하는 포트 7700은 2노드 클러스터의 다음 예에 표시된 대로 예상되는 결과입니다.

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 필요한 경우 포트 7700에서 청취하지 않는 각 클러스터 LIF에 대해 LIF의 관리 상태를 '소유'로 설정한 다음 '설정'으로 설정합니다.
+
'::> net int modify -vserver Cluster-lif <cluster-lif> -status-admin down;net int modify -vserver Cluster-lif <cluster-lif> -status-admin up'

+
3단계를 반복하여 클러스터 LIF가 포트 7700에서 수신 대기 중인지 확인합니다.

. 고급 권한 모드로 전환:
+
진일진일보한 것

. 컨트롤러 교체 작업의 상태를 확인하고 노드 2가 중지되기 전의 일시 중지 상태와 동일한 상태인지 확인하여 새 컨트롤러 설치 및 케이블 이동 등의 물리적 작업을 수행하십시오.
+
'시스템 컨트롤러 교체 쇼

+
'시스템 컨트롤러 교체 쇼 디테일

. MetroCluster 시스템에서 작업하는 경우 교체된 컨트롤러가 MetroCluster 구성에 맞게 올바르게 구성되었는지 확인합니다. MetroCluster 구성은 양호한 상태여야 합니다. 을 참조하십시오 link:verify_health_of_metrocluster_config.html["MetroCluster 구성의 상태를 확인합니다"].
+
MetroCluster 노드 노드 4의 인터클러스터 LIF를 재구성한 다음 로 진행하기 전에 클러스터 피어링을 확인하여 MetroCluster 노드 간의 통신을 복원합니다 <<auto_verify_4_Step6,6단계>>.

+
MetroCluster 노드 상태 확인:

+
'MetroCluster node show'

. [[auto_verify_4_Step6] 컨트롤러 교체 작업 재개:
+
시스템 컨트롤러 교체 재개

. 컨트롤러 교체는 다음 메시지와 함께 중재에 대해 일시 중지됩니다.
+
....
Cluster::*> system controller replace show
Node             Status                       Error-Action
---------------- ------------------------     ------------------------------------
Node2(now node4) Paused-for-intervention      Follow the instructions given in
                                              Step Details
Node2

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be
manually adjusted to match the new physical network configuration of the hardware.
This includes:

1. Re-create the interface group, if needed, before restoring VLANs. For detailed
commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast
domains" section of the upgrade controller hardware guide for the ONTAP version
running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show"
to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement
network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
....
+

NOTE: 이 절차에서 section_re-creating vLANs, ifgrp, broadcast domain_은 node4_에서 _Restoring network configuration 으로 변경되었습니다.

. 컨트롤러 교체가 일시 중지됨 상태인 경우 이 문서의 다음 섹션으로 진행하여 노드에서 네트워크 구성을 복원합니다.




== 노드 4에서 네트워크 구성을 복원합니다

노드 4가 쿼럼에 있고 노드 3과 통신할 수 있는지 확인한 후 노드 2의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인이 노드 4에 표시되는지 확인합니다. 또한 모든 node4 네트워크 포트가 올바른 브로드캐스트 도메인에 구성되어 있는지 확인합니다.

VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 네트워크 관리 _ 에 대한 링크.

.단계
. 업그레이드된 노드 2에 있는 모든 물리적 포트(노드4라고 함)를 나열합니다.
+
네트워크 포트 show-node node4

+
노드의 모든 물리적 네트워크 포트, VLAN 포트 및 인터페이스 그룹 포트가 표시됩니다. 이 출력에서는 ONTAP가 '클러스터' 브로드캐스트 도메인으로 이동한 모든 물리적 포트를 볼 수 있습니다. 이 출력을 사용하면 인터페이스 그룹 구성원 포트, VLAN 기본 포트 또는 LIF 호스팅을 위한 독립 실행형 물리적 포트로 사용할 포트를 쉽게 결정할 수 있습니다.

. 클러스터의 브로드캐스트 도메인을 나열합니다.
+
방송-도메인 쇼

. 노드 4의 모든 포트에 대한 네트워크 포트 도달 가능 여부 나열:
+
네트워크 포트 도달 가능성

+
명령의 출력은 다음 예제와 비슷합니다.

+
....
clusterA::*> reachability show -node node2_node4
  (network port reachability show)
Node         Port       Expected Reachability       Reachability Status
---------    --------  ---------------------------  ---------------------
node2_node4
             a0a        Default:Default             no-reachability
             a0a-822    Default:822                 no-reachability
             a0a-823    Default:823                 no-reachability
             e0M        Default:Mgmt                ok
             e0a        Cluster:Cluster             misconfigured-reachability
             e0b        Cluster:Cluster             no-reachability
             e0c        Cluster:Cluster             no-reachability
             e0d        Cluster:Cluster             no-reachability
             e0e        Cluster:Cluster             ok
             e0e-822    -                           no-reachability
             e0e-823    -                           no-reachability
             e0f        Default:Default             no-reachability
             e0f-822    Default:822                 no-reachability
             e0f-823    Default:823                 no-reachability
             e0g        Default:Default             misconfigured-reachability
             e0h        Default:Default             ok
             e0h-822    Default:822                 ok
             e0h-823    Default:823                 ok
18 entries were displayed.
....
+
위 예제에서 node2_node4는 컨트롤러 교체 후 방금 부팅되었습니다. 여기에는 연결 기능이 없고 연결 가능성 검사를 대기 중인 여러 포트가 있습니다.

. [[auto_restore_4_Step4] 노드 4의 각 포트에 대한 연결 상태를 'ok' 이외의 다른 상태로 복구합니다. 먼저 물리적 포트에서 다음 명령을 실행한 다음 VLAN 포트에서 한 번에 하나씩 실행합니다.
+
'network port reachability repair-node_name-port port port_name'

+
출력은 다음 예제와 같습니다.

+
....
Cluster ::> reachability repair -node node2_node4 -port e0h
....
+
....
Warning: Repairing port "node2_node4: e0h" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
....
+
위에 표시된 것처럼, 현재 위치한 브로드캐스트 도메인의 도달 가능성 상태와 다를 수 있는 도달 가능성 상태의 포트에 대해 경고 메시지가 표시됩니다.

+
포트의 연결을 검토하고 필요에 따라 y 또는 n으로 대답합니다.

+
모든 물리적 포트에 예상되는 도달 능력이 있는지 확인합니다.

+
네트워크 포트 도달 가능성

+
도달 가능성 복구가 수행되면 ONTAP는 포트를 올바른 브로드캐스트 도메인에 배치하려고 시도합니다. 그러나 포트의 도달 가능 여부를 확인할 수 없고 기존 브로드캐스트 도메인에 속하지 않는 경우 ONTAP는 이러한 포트에 대한 새 브로드캐스트 도메인을 만듭니다.

. 인터페이스 그룹 구성이 새 컨트롤러의 물리적 포트 레이아웃과 일치하지 않으면 다음 단계를 사용하여 수정하십시오.
+
.. 먼저 브로드캐스트 도메인 멤버쉽에서 인터페이스 그룹 구성원 포트여야 하는 물리적 포트를 제거해야 합니다. 이 작업은 다음 명령을 사용하여 수행할 수 있습니다.
+
'network port broadcast-domain remove-ports-broadcast-domain broadcast_domain_name-ports node_name:port_name'

.. 인터페이스 그룹에 구성원 포트를 추가합니다.
+
'network port ifgrp add-port-node_name-ifgrp ifgrp-port port_name'

.. 첫 번째 구성원 포트가 추가된 후 약 1분 후에 인터페이스 그룹이 브로드캐스트 도메인에 자동으로 추가됩니다.
.. 인터페이스 그룹이 적절한 브로드캐스트 도메인에 추가되었는지 확인합니다.
+
'network port reachability show-node_name-port ifgrp

+
인터페이스 그룹의 도달 가능성 상태가 '정상'이 아닌 경우 해당 브로드캐스트 도메인에 할당합니다.

+
'network port broadcast-domain add-ports-broadcast-domain broadcast_domain_name-ports node:port'



. 클러스터 브로드캐스트 도메인에 적절한 물리적 포트 할당:
+
.. 클러스터 브로드캐스트 도메인에 연결할 수 있는 포트를 결정합니다.
+
네트워크 포트 도달 가능성 표시-연결-브로드캐스트-도메인 클러스터:클러스터

.. 클러스터 브로드캐스트 도메인의 도달 가능 상태가 '정상'이 아닌 경우 해당 포트에 대한 복구 기능을 제공합니다.
+
'network port reachability repair-node_name-port port port_name'



. 다음 명령 중 하나를 사용하여 나머지 물리적 포트를 올바른 브로드캐스트 도메인으로 이동합니다.
+
'network port reachability repair-node_name-port port port_name'

+
네트워크 포트 브로드캐스트 도메인 제거 포트

+
네트워크 포트 브로드캐스트 도메인 추가 포트

+
연결할 수 없거나 예상치 못한 포트가 없는지 확인합니다. 다음 명령을 사용하여 출력을 검사하여 상태가 '확인'인지 확인하여 모든 물리적 포트의 도달 가능성 상태를 확인합니다.

+
네트워크 포트 도달 가능성 세부 정보

. 다음 단계를 사용하여 대체될 수 있는 VLAN을 복원합니다.
+
.. 교체된 VLAN 나열:
+
디세퍼드-VLAN 쇼

+
다음과 같은 출력이 표시됩니다.

+
....
Cluster::*> displaced-vlans show
(cluster controller-replacement network displaced-vlans show)
            Original
Node        Base Port     VLANs
---------   ---------     ------------------------------------------------------
Node1       a0a           822, 823
            e0e           822, 823
....
.. 이전 기본 포트에서 대체된 VLAN 복원:
+
디즈퍼스VLAN 복원

+
다음은 인터페이스 그룹 a0a에서 동일한 인터페이스 그룹으로 다시 교체된 VLAN을 복원하는 예입니다.

+
....
Cluster::*> displaced-vlans restore -node node2_node4 -port a0a -destination-port a0a
....
+
다음은 포트 "e0e"에서 "e0h"로 교체된 VLAN을 복원하는 예입니다.

+
....
Cluster::*> displaced-vlans restore -node node2_node4 -port e0e -destination-port e0h
....
+
VLAN 복원이 성공하면 지정된 대상 포트에 교체된 VLAN이 생성됩니다. 대상 포트가 인터페이스 그룹의 구성원이거나 대상 포트가 다운된 경우 VLAN 복원이 실패합니다.

+
새로 복원된 VLAN이 해당 브로드캐스트 도메인에 배치될 때까지 약 1분 정도 기다립니다.

.. disspled-vLANs show 출력에 포함되지 않지만 다른 물리적 포트에 구성해야 하는 VLAN 포트에 대해 필요에 따라 새 VLAN 포트를 생성합니다.


. 모든 포트 수리가 완료된 후 비어 있는 브로드캐스트 도메인을 삭제합니다.
+
'broadcast-domain delete-broadcast-domain broadcast_domain_name'

. 포트 도달 가능성 확인:
+
네트워크 포트 도달 가능성

+
모든 포트가 올바르게 구성되어 정확한 브로드캐스트 도메인에 추가되면 네트워크 포트 도달 가능성 표시 명령은 연결된 모든 포트에 대한 도달 가능성 상태를 '확인'으로 보고하고 물리적 연결이 없는 포트에 대해서는 상태를 '사용 불가'로 보고해야 합니다. 이러한 두 포트가 아닌 다른 상태를 보고하는 포트가 있는 경우 의 지침에 따라 연결 가능성 복구를 수행하고 브로드캐스트 도메인에서 포트를 추가 또는 제거합니다 <<auto_restore_4_Step4,4단계>>.

. 모든 포트가 브로드캐스트 도메인에 배치되었는지 확인합니다.
+
네트워크 포트 쇼

. 브로드캐스트 도메인의 모든 포트에 올바른 MTU(Maximum Transmission Unit)가 구성되어 있는지 확인합니다.
+
네트워크 포트 브로드캐스트 도메인 쇼

. 복원 LIF 홈 포트, 복원해야 하는 SVM 홈 포트 및 LIF 홈 포트(있는 경우)를 지정합니다.
+
.. 대체된 LIF를 나열합니다.
+
디시퍼인터페이스 쇼

.. LIF 홈 포트 복원:
+
disspled-interface restore-home-node-node_name-vserver vserver_name-lif-name LIF_name'입니다



. 모든 LIF에 홈 포트가 있고 관리상 작동하는지 확인합니다.
+
네트워크 인터페이스 show-fields home-port, status-admin


