---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/aggregate_relocation_failures.html 
keywords: aggregate, relocation, failures, arl, stage 2, stage 3, stage 5 
summary: '업그레이드 중에 ARL(Aggregate relocation)이 다른 지점에서 실패할 수 있습니다.' 
---
= 애그리게이트 재배치 실패
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
업그레이드 중에 ARL(Aggregate relocation)이 다른 지점에서 실패할 수 있습니다.



== 애그리게이트 재배치 실패 여부를 확인합니다

절차 중에 ARL은 2단계, 3단계 또는 5단계에서 실패할 수 있습니다.

.단계
. 다음 명령을 입력하고 출력을 검사합니다.
+
스토리지 골재 재배치 쇼

+
'storage aggregate relocation show' 명령은 성공적으로 재배치된 애그리게이트와 그렇지 않은 애그리게이트가 장애 원인과 함께 표시됩니다.

. 콘솔에 EMS 메시지가 있는지 확인합니다.
. 다음 작업 중 하나를 수행합니다.
+
** Storage aggregate relocation show 명령의 출력 및 EMS 메시지의 출력 결과에 따라 적절한 수정 조치를 취합니다.
** 'Storage aggregate relocation start' 명령의 'override-vetoes' 옵션 또는 'override-destination-checks' 옵션을 사용하여 애그리게이트나 애그리게이트를 강제로 재배치할 수 있습니다.


+
스토리지 집계 재배치 시작, 오버라이드-베트레인, 오버라이드-대상 검사 옵션에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] _ONTAP 9 명령에 연결하려면 수동 페이지 참조 _.





== 노드 1의 원래 애그리게이트는 업그레이드 완료 후 노드 2가 소유합니다

업그레이드 절차를 마치면 노드 1이 원래 노드 1을 홈 노드로 사용했던 새로운 애그리게이트 홈 노드가 됩니다. 업그레이드 후에 재배치할 수 있습니다.

다음과 같은 상황에서 Aggregate는 노드 2를 노드 1이 아닌 홈 노드로 올바르게 재배치할 수 없습니다.

* 3단계에서는 애그리게이트를 노드 2에서 노드 1로 재배치합니다.
+
재배치되는 일부 애그리게이트는 노드 1을 홈 노드로 사용합니다. 예를 들어, 이러한 집계를 aggr_node_1이라고 할 수 있습니다. 3단계 중에 aggr_node_1의 재배치가 실패하고 재배치를 강제 적용할 수 없는 경우 해당 애그리게이트는 노드 2에 남겨집니다.

* 4단계 후 노드 2를 AFF A900 컨트롤러 모듈 및 NVS로 교체할 때
+
노드 2가 교체되면 노드 1이 노드 2가 아닌 홈 노드로 온라인 상태가 됩니다.



스토리지 페일오버를 사용하도록 설정한 후 6단계 이후에 잘못된 소유권 문제를 해결하려면 다음 단계를 수행하십시오.

.단계
. 애그리게이트 목록 가져오기:
+
'스토리지 집계 표시 노드2'는 홈 true입니다

+
올바르게 재배치되지 않은 애그리게이트를 확인하려면 섹션에서 가져온 노드 1의 홈 소유자가 있는 애그리게이트 목록을 참조하십시오 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 그런 다음 위의 명령의 출력과 비교합니다.

. 1단계의 출력과 섹션에서 node1에 대해 캡처한 출력을 비교합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 그리고 올바르게 재배치되지 않은 모든 애그리게이트를 확인할 수 있습니다.
. 노드 2의 왼쪽에 있는 애그리게이트를 재배치합니다.
+
'storage aggregate relocation start-node node2-aggr aggr_node_1 - destination node1'

+
이 재배치 작업 중에 -ndo-controller-upgrade 매개 변수를 사용하지 마십시오.

. 노드 1이 이제 애그리게이트의 홈 소유자가 되는지 확인합니다.
+
'Storage aggregate show-aggregate <aggr1, aggr2, aggr3...> - fields home-name'이 있습니다

+
'<aggr1, aggr2, aggr3...>'은 노드 1을 원래 홈 소유자로 가지고 있는 집계 목록입니다.

+
노드 1이 홈 소유자로 없는 애그리게이트는 3단계의 동일한 재배치 명령을 사용하여 노드 1로 재배치할 수 있습니다.


