---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: 이전에 AFF A800 노드 1에 연결되었던 클러스터, HA, 스토리지 및 데이터 연결을 새로 설치된 AFF A90 또는 AFF A70 노드1에 연결합니다 
---
= 공유 클러스터 - HA 및 스토리지를 위한 케이블 노드1(AFF A800 업그레이드만 해당)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이전에 AFF A800 노드 1에 연결되었던 클러스터, HA, 스토리지, 데이터 및 관리 연결을 새로 설치된 AFF A90 또는 AFF A70 노드1에 연결합니다.



== e0M과 BMC 포트를 연결합니다

AFF A800에는 관리 포트(e0M) 및 BMC 포트가 있습니다. AFF A90 및 AFF A70에서 e0M과 BMC 포트는 결합되고 "렌치" 포트를 통해 액세스됩니다. AFF A90 또는 AFF A70에 연결하기 전에 e0M 및 BMC 포트가 AFF A800의 동일한 스위치 및 서브넷에 연결되어 있는지 확인해야 합니다.

[cols="35,65"]
|===
| 만약... | 그러면... 


| e0M과 BMC IP 주소는 같은 IP 서브넷에 있습니다 | AFF A800의 e0M 또는 BMC 포트를 AFF A90 또는 AFF A70의 "렌치" 포트에 연결합니다. 


| e0M과 BMC IP 주소가 서로 다른 서브넷에 있습니다  a| 
. e0M과 BMC IP 주소를 하나의 IP 서브넷으로 통합합니다.
. AFF A800의 e0M 또는 BMC 포트를 AFF A90 또는 AFF A70의 "렌치" 포트에 연결합니다.


|===


== 스위치가 없는 2노드 클러스터에 연결합니다

다음 표에서는 스위치가 없는 2노드 클러스터 구성의 스위치 포트 사용량을 보여 줍니다.

|===
| 포트 | AFF A800 노드 | AFF A90 노드 | AFF A70 노드 


| 클러스터 | e0a를 참조하십시오 | e1a를 참조하십시오 | e1a를 참조하십시오 


| 클러스터 | e1a를 참조하십시오 | e7a(e7a가 없는 경우 e1b 사용) | e1b를 참조하십시오 


| HA | e0b를 참조하십시오 | 연결하지 마십시오 | 연결하지 마십시오 


| HA | e1b를 참조하십시오 | 연결하지 마십시오 | 연결하지 마십시오 


| SAS 스토리지 포트(있고 사용되는 경우) | 사용 가능한 모든 포트 | 사용 가능한 모든 포트 | 사용 가능한 모든 포트 


| NS224 쉘프용 이더넷 스토리지 포트 | 사용 가능한 모든 포트 | 이더넷 스토리지 접속 매핑을 참조하십시오 | 이더넷 스토리지 접속 매핑을 참조하십시오 
|===


== 스위치 연결 클러스터에 연결합니다

스위치 연결 클러스터의 경우 다음 요구사항을 충족하는지 확인하십시오.

* AFF A90 또는 AFF A70 노드의 동일한 클러스터 포트가 동일한 스위치에 있습니다. 예를 들어, 업그레이드가 완료되면 노드1의 E1A와 노드2의 E1A가 하나의 클러스터 스위치에 연결되어야 합니다. 마찬가지로, 양쪽 노드의 두 번째 클러스터 포트를 두 번째 클러스터 스위치에 연결해야 합니다. 공유 클러스터 HA 포트를 교차 연결하면 노드 1의 E1A가 스위치 A에 연결되고 노드 2의 E1A가 스위치 B에 연결되어 HA 통신 장애가 발생합니다.
* AFF A90 및 AFF A70 노드는 공유 클러스터 HA 이더넷 포트를 사용합니다. 클러스터 스위치가 공유 클러스터 HA 포트를 지원하는 RCF(Reference Configuration File)와 함께 설치되었는지 확인합니다.

