---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 동일한 섀시에서 컨트롤러 모델을 업그레이드하는 ARL 절차를 사용할지 여부를 결정합니다. 
---
= 집계 재배치 절차를 사용할지 여부를 결정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 내용은 기존 데이터 및 디스크를 모두 유지하면서 HA 쌍에서 스토리지 컨트롤러를 업그레이드하는 방법을 설명합니다. 이는 숙련된 관리자만 사용해야 하는 복잡한 절차입니다.

다음과 같은 상황에서 이 절차를 사용할 수 있습니다.

* 다음 컨트롤러 업그레이드 중 하나를 수행 중입니다.
+
[cols="50,50"]
|===
| 더 오래 된 컨트롤러 | 교체 컨트롤러 


| ASA으로 구성된 AFF A220입니다 | ASA A150 


| AFF A220, AFF A200 또는 AFF C190 | AFF A150 


| FAS2620 또는 FAS2720 | FAS2820 


| ASA로 구성된 AFF A700 | ASA A900 


| AFF A700 | AFF A900 


| FAS9000 | FAS9500 
|===
* NetApp 세일즈 담당자에게 컨트롤러 업그레이드용 하드웨어를 수령했는지 확인했습니다.
+
** ASA A150, AFF A150 또는 FAS2820 컨트롤러
** ASA A900, AFF A900 또는 FAS9500 컨트롤러 및 NVRAM 모듈, 업그레이드에 필요한 부품


* 업그레이드를 위한 최소 ONTAP 버전을 실행하고 있습니다. 자세한 내용은 을 참조하십시오 link:index.html["개요"].
* 새 컨트롤러를 새 HA 쌍으로 클러스터에 추가하고 볼륨 이동을 사용하여 데이터를 마이그레이션하지 않으려는 경우
* ONTAP 관리에 대한 경험이 있으며 진단 권한 모드에서 작업할 때 발생할 수 있는 위험에 대해 잘 알 수 있습니다.


다음과 같은 경우에는 이 절차를 사용할 수 없습니다.

* AFF A700 또는 FAS9000 시스템에서 FlexArray 가상화 소프트웨어를 사용하고 있습니다.
* 클러스터 인터커넥트 및 이더넷 연결 스토리지에 공유 스위치를 사용하고 있습니다.


AFF A700 또는 FAS9000 시스템에서 패브릭 MetroCluster 또는 MetroCluster IP 구성을 업그레이드하려면 를 참조하십시오 link:other_references.html["참조"] MetroCluster 업그레이드 및 Expansion_content에 대한 링크


NOTE: 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.

컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

을 참조하십시오 link:other_references.html["참조"] ONTAP 9 제품 설명서에 액세스할 수 있는 _ONTAP 9 문서 센터_에 연결합니다.
