---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 동일한 섀시에서 컨트롤러 모델을 업그레이드하는 ARL 절차를 사용할지 여부를 결정합니다. 
---
= 이 집계 이전 절차를 사용할지 결정하십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하는 데에는 여러 가지 집계 재배치(ARL) 방법이 있습니다. 이 문서에서는 기존 시스템 섀시와 디스크를 유지하면서 기존 시스템을 교체 시스템으로 변환하여 HA 쌍의 스토리지 컨트롤러를 업그레이드하는 방법을 설명합니다. 이 복잡한 절차는 숙련된 ONTAP 관리자만 사용해야 합니다.

이 ARL 절차가 컨트롤러 하드웨어 업그레이드에 적합한지 결정하는 데 도움이 되도록 지원되는 업그레이드와 지원되지 않는 업그레이드에 대한 다음 모든 상황을 검토해야 합니다.



== 이 ARL 업그레이드에 지원됨

다음과 같은 상황에서 이 ARL 절차를 사용할 수 있습니다.

* 컨트롤러 업그레이드는 다음에 나열됩니다. <<supported-systems,지원되는 시스템 매트릭스>> .
* 컨트롤러 업그레이드에 필요한 하드웨어를 수령했음을 NetApp 세일즈 담당자에게 확인했습니다.
+
** AFF A90, AFF A70 또는 AFF C80 컨트롤러 2개와 모든 I/O 모듈 필요한 길이 100GbE 케이블
** AFF A50, AFF A30, AFF C30 또는 AFF C60 컨트롤러 2개와 I/O 모듈 및 필요한 케이블
** ASA A150, AFF A150 또는 FAS2820 컨트롤러
** ASA A900, AFF A900 또는 FAS9500 컨트롤러와 NVRAM 모듈 및 부품


* 업그레이드를 위해 최소 ONTAP 버전을 실행하고 있습니다. 자세한 내용은 를 <<supported-systems,지원되는 시스템 업그레이드 조합>>참조하십시오.
* ONTAP 관리 경험이 있으며 진단 권한 모드에서 작업할 때의 위험에 익숙합니다.
* 시스템에서 ONTAP 9.15.1 이상을 실행하고 있으며 이더넷 스위치를 사용하여 이더넷 연결 스토리지에 연결합니다.



NOTE: 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.



== 이 ARL 업그레이드에서는 지원되지 않습니다.

다음과 같은 상황에서는 이 ARL 절차를 사용할 수 없습니다.

* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동을 사용하여 데이터를 마이그레이션하려고 합니다.
* 업그레이드되는 기존 시스템에서 FlexArray 가상화 소프트웨어를 사용하고 있습니다.
* MetroCluster IP 구성을 업그레이드하는 중입니다.
+
MetroCluster IP 구성을 업그레이드하려면 _MetroCluster 업그레이드 및 확장_컨텐츠 링크를 참조하십시오.link:other_references.html["참조"]





== 지원되는 시스템 업그레이드 조합

다음 표는 기존 시스템을 교체 시스템으로 변환하고 기존 시스템 섀시와 디스크를 유지하여 컨트롤러 업그레이드를 수행하기 위한 지원되는 시스템 매트릭스를 보여줍니다.


CAUTION: 이 절차는 다음 업그레이드 구성에 엄격히 적용됩니다. 이 절차를 사용하여 다른 시스템 조합 간에 업그레이드를 수행하지 마십시오. 다른 모든 컨트롤러 모델의 경우, ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 업그레이드하려면 " system controller replace " 명령 링크 및 _ aggregate relocation을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 수동으로 업그레이드하려면 _ 을(를) 참조하십시오link:other_references.html["참조"].

[cols="20,20,40"]
|===
| 기존 시스템 | 교체 시스템 | 지원되는 ONTAP 버전 


| AFF C250 1호 | AFF C30, AFF C60 | 9.16.1 


| AFF A250 1호 | AFF A30, AFF A50 | 9.16.1 


| AFF C800 1호 | AFF C80 를 참조하십시오 | 9.16.1 


| AFF A800 1호 | AFF A90 또는 AFF A70 | 9.15.1 이상 


| All SAN 어레이로 구성된 AFF A220(ASA) | ASA A150 | 9.13.1P1 이상 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 이상



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| FAS2620 | FAS2820  a| 
9.11.1P7 이상 패치 릴리스(FAS2620

9.13.1 이상(FAS2820)



| FAS2720 | FAS2820 | 9.13.1 이상 


| ASA로 구성된 AFF A700 | ASA A900 | 9.13.1P1 이상 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 이상 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 이상 
|===
1. ONTAP 9.15.1 이상에 도입된 시스템으로 업그레이드할 때 ONTAP는 스토리지 효율성을 사용하지 않는 볼륨을 포함하여 기존의 모든 씬 프로비저닝된 볼륨의 스토리지 효율성을 변환하고 하드웨어 오프로드 기능을 사용하는 새로운 스토리지 효율성 기능을 적용합니다. 이 프로세스는 자동 백그라운드 프로세스이며 시스템에 성능에 영향을 주지 않습니다. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["자세한 정보"^]..

^2^ AFF A200 및 FAS2620 시스템은 9.11.1 이후의 ONTAP 버전을 지원하지 않습니다.

[NOTE]
====
NetApp는 가능하면 이전 시스템과 교체 시스템에 동일한 ONTAP 버전을 설치할 것을 권장합니다.

위 표의 최소 ONTAP 버전은 필수입니다. 이러한 ONTAP 버전에는 업그레이드 중에 섀시 내에서 컨트롤러 유형을 혼합하는 데 필요한 서비스 프로세서 또는 BMC(베이스보드 관리 컨트롤러) 펌웨어 버전이 있습니다.

====


== 다른 하드웨어 업그레이드 절차를 선택하세요

* link:../upgrade-arl/index.html["컨트롤러 하드웨어 업그레이드에 사용 가능한 대체 ARL 방법을 검토하세요."]..
* 컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.


.관련 정보
참조하다 link:other_references.html["참조"] _ONTAP 9 문서_에 링크합니다.
