---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 업그레이드 구성을 위해 기존 시스템 섀시 및 디스크를 유지하면서 ARL을 사용할 수 있는지 파악합니다. 
---
= 컨트롤러 업그레이드 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기존 시스템 섀시 및 디스크를 유지하면서 ARL(Aggregate Relocation)을 사용할 수 있는지 알아보려면 시스템 업그레이드 구성 및 ONTAP 버전에 따라 달라집니다.



== ARL에 대한 업그레이드가 지원됩니다

컨트롤러 업그레이드는 특정 시스템 구성에 대해 지원됩니다. 지원되는 시스템 및 최소 ONTAP 버전 목록을 보려면 를 참조하십시오 link:index.html["개요"].

새 섀시를 포함한 전체 시스템으로 새 AFF A30, AFF A150 A50, AFF A900, AFF, AFF, AFF A70, AFF A90 C30, AFF C60, AFF C80, FAS2820 또는 FAS9500를 받은 경우 link:other_references.html["참조"]" system controller replace" 명령 사용 링크를 참조하여 ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 업그레이드합니다_.

ARL을 사용한 컨트롤러 업그레이드는 SnapLock 엔터프라이즈 및 SnapLock 규정 준수 볼륨으로 구성된 시스템에서 지원됩니다.



== 스위치가 없는 2노드 클러스터

스위치가 없는 2노드 클러스터에서 노드를 업그레이드할 경우 업그레이드를 수행하는 동안 스위치가 없는 클러스터에 노드를 그대로 둘 수 있습니다. 스위치 클러스터로 변환할 필요가 없습니다.



== 연결된 클러스터 전환

클러스터 스위치에 연결된 클러스터에서 노드를 업그레이드할 경우 스위치에서 실행 중인 make, model, 펌웨어 버전, RCF 및 ONTAP 버전이 업그레이드 후 교체 컨트롤러에서 실행 중인 버전과 동일한지 확인해야 합니다. 필요한 경우 ARL을 사용하여 컨트롤러를 업그레이드하기 전에 스위치 업그레이드를 수행해야 합니다.

자세한 내용은 을 link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["스위치 연결 클러스터에 연결합니다"]참조하십시오.



== 문제 해결

컨트롤러를 업그레이드하는 동안 문제가 발생하면 을 참조하십시오 link:troubleshoot_index.html["문제 해결"] 자세한 내용 및 가능한 해결 방법은 절차 끝 부분의 섹션을 참조하십시오.

발생한 문제에 대한 해결책을 찾지 못한 경우 기술 지원 부서에 문의하십시오.
