---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: ARL을 사용하여 AFF A700을 AFF A900으로 업그레이드할 수 있는지 이해합니다. 
---
= 컨트롤러 업그레이드 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL을 사용하여 ONTAP 9.10.1P10, 9.11.1P6 또는 다음 시스템 구성에서 이후 릴리스를 실행하는 컨트롤러 쌍을 업그레이드합니다.

* AFF A700 컨트롤러를 AFF A900 시스템으로
* FAS9500 시스템에 FAS9000 컨트롤러




== ARL에 대한 업그레이드가 지원됩니다

ARL과 NVRAM 모듈을 사용하여 AFF A700에서 AFF A900으로 또는 FAS9000에서 FAS9500으로 컨트롤러를 업그레이드할 수 있습니다. 새 섀시를 포함하여 전체 시스템으로 새로운 AFF A900 또는 FAS9500 시스템을 받은 경우 을 참조하십시오 link:other_references.html["참조"] "system controller replace" 명령을 사용하여 ONTAP 9.8 이상_content를 실행하는 컨트롤러 하드웨어를 업그레이드하려면 _ 명령을 사용하십시오.


WARNING: 이 절차는 AFF A700에서 AFF A900으로 또는 ONTAP 9.10.1P10, 9.11.1P6 또는 이후 릴리스를 실행하는 FAS9500 업그레이드용 FAS9000에 엄격히 적용됩니다. 다른 시스템 조합 간에 업그레이드를 수행하려면 이 절차를 사용하지 마십시오.

ARL을 사용한 컨트롤러 업그레이드는 SnapLock 엔터프라이즈 및 SnapLock 규정 준수 볼륨으로 구성된 시스템에서 지원됩니다.



== 스위치가 없는 2노드 클러스터

스위치가 없는 2노드 클러스터에서 노드를 업그레이드할 경우 업그레이드를 수행하는 동안 스위치가 없는 클러스터에 노드를 그대로 둘 수 있습니다. 이러한 LUN을 스위치 클러스터로 변환할 필요는 없습니다.



== 문제 해결

컨트롤러를 업그레이드하는 동안 문제가 발생하면 을 참조하십시오 link:troubleshoot_index.html["문제 해결"] 자세한 내용 및 가능한 해결 방법은 절차 끝 부분의 섹션을 참조하십시오.

발생한 문제에 대한 해결책을 찾지 못한 경우 기술 지원 부서에 문의하십시오.
