---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 이전 시스템 섀시 및 디스크를 유지하면서 이전 시스템을 교체 시스템으로 전환하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 절차에서는 다음 시스템 구성에 대해 ARL(Aggregate Relocation)을 사용하여 HA 쌍의 컨트롤러 하드웨어를 중단 없이 업그레이드하는 방법에 대해 설명합니다. 이 절차는 이전 시스템 섀시 및 디스크를 유지하면서 이전 시스템을 교체 시스템으로 변환합니다.


WARNING: 이 절차는 다음 업그레이드 구성에 엄격히 적용됩니다. Do * Not * 이 절차를 사용하여 다른 시스템 조합 간에 업그레이드를 수행합니다.

[cols="20,20,40"]
|===
| 더 이상 없습니다 | 교체 시스템 | 지원되는 ONTAP 버전 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 이상(AFF A200 및 AFF A150)


NOTE: AFF A200은 9.11.1 이후의 ONTAP 버전을 지원하지 않습니다.



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| FAS2620 | FAS2820  a| 
9.11.1P7 이상(FAS2620)


NOTE: FAS2620은 9.11.1 이후의 ONTAP 버전을 지원하지 않습니다.

9.13.1 이상(FAS2820)



| FAS2720 | FAS2820 | 9.13.1 이상 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 이상 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 이상 
|===
[NOTE]
====
가능하면 이전 시스템과 교체 시스템에서 동일한 ONTAP 버전을 사용하는 것이 좋습니다. NetApp

위 표의 최소 ONTAP 버전은 필수입니다. 이러한 ONTAP 버전에는 업그레이드 중에 섀시 내에서 컨트롤러 유형을 혼합하는 데 필요한 서비스 프로세서 또는 BMC(베이스보드 관리 컨트롤러) 펌웨어 버전이 있습니다.

====
이 절차를 수행하는 동안 루트가 아닌 애그리게이트를 이전 컨트롤러 노드 간에 마이그레이션합니다. 설치 후 비루트 애그리게이트를 이전 컨트롤러 노드에서 교체 컨트롤러 노드로 마이그레이션합니다. 업그레이드 절차 중에 업그레이드 중인 노드에서 호스팅되는 데이터에 액세스할 수 있습니다.

.이 작업에 대해
이 컨트롤러 업그레이드 절차 중에 다음 업그레이드 중 하나를 수행합니다.

* AFF A220, AFF A200 또는 AFF C190 시스템의 각 노드에서 컨트롤러 모듈을 새 AFF A150 모듈로 교체하십시오.
* FAS2620 또는 FAS2720 시스템의 각 노드에 있는 컨트롤러 모듈을 새 FAS2820 모듈로 바꾸십시오.
* AFF A700 또는 FAS9000 시스템의 각 노드에서 2개의 컨트롤러 및 NVRAM 모듈을 새로운 AFF A900 또는 FAS9500 모듈로 교체합니다.



NOTE: I/O 카드, 데이터 케이블, 디스크 쉘프 및 디스크를 이동, 분리 또는 다시 연결할 필요가 없습니다.

이 절차에서는 HA 구성을 활용하는 ARL(Aggregate Relocation) 방법을 사용하여 동일한 클러스터 내에서 스토리지를 공유하는 경우 비루트 애그리게이트의 소유권을 다른 노드로 이동할 수 있습니다.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 계속 진행하면서 클러스터의 노드 간에 데이터 LIF를 마이그레이션할 수 있습니다.


NOTE: node1 * 및 * node2 * 라는 용어는 이 문서의 노드 이름에 대한 참조용으로만 사용됩니다. 이 절차를 따를 때는 노드의 실제 이름을 대체해야 합니다.

.중요 정보
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 을 읽고 이해해야 합니다 link:guidelines_for_upgrading_controllers_with_arl.html["컨트롤러 업그레이드 지침"] 및 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 개요"] 섹션을 참조하십시오.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 다른 시스템에서 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 다른 ONTAP 클러스터의 일부로 사용한 경우 또는 독립 실행형 단일 노드 시스템으로 사용한 경우에는 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA 2노드에 대해 절차를 별도로 수행해야 합니다.
* ONTAP 버전에서 지원되지 않는 스위치와 업그레이드하려는 교체 시스템이 있는 경우 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크
* 이 절차는 AFF A200, AFF A220, AFF C190, FAS2620, FAS2720에만 적용됩니다. AFF A700 및 FAS9000 시스템 AFF A150, FAS2820, AFF A900 또는 FAS9500 시스템으로 업그레이드해야 하는 다른 모든 컨트롤러 모델은 을 참조하십시오 link:other_references.html["참조"] 에 연결하려면 _ "system controller replace" 명령을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 업그레이드하고 _ 를 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 수동으로 업그레이드하십시오.
* AFF A900 및 FAS9500 시스템은 하이 라인 전원(200V~240V)만 지원합니다. AFF A700 또는 FAS9000 시스템이 낮은 전력(100V에서 120V로)에서 실행되는 경우 이 절차를 사용하기 전에 AFF A700 또는 FAS9000 입력 전원을 변환해야 합니다.
* AFF A200, AFF A220, AFF C190, FAS2620, FAS2720에서 업그레이드할 경우 AFF A700 또는 FAS9000 시스템 다운타임. 스토리지를 이동하거나 기술 지원 팀에 문의하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.




== 컨트롤러 업그레이드 프로세스를 자동화합니다

이 절차는 자동 디스크 할당 및 네트워크 포트 도달 가능성 검사를 사용하여 컨트롤러 업그레이드 환경을 단순화하는 자동화된 절차를 단계별로 설명합니다.
