---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 이전 시스템 섀시 및 디스크를 유지하면서 이전 시스템을 교체 시스템으로 전환하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 
---
= ARL 업그레이드 절차에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨트롤러 하드웨어를 업그레이드하는 데에는 여러 가지 집계 재배치(ARL) 방법이 있습니다. 이 절차에서는 기존 시스템을 교체 시스템으로 전환하고 기존 시스템 섀시와 디스크는 그대로 유지하여 HA 쌍의 스토리지 컨트롤러를 업그레이드하는 방법을 설명합니다.

ARL은 HA 구성과 클러스터 인터커넥트 통신을 활용합니다. 따라서 동일한 클러스터 내에서 스토리지를 공유하는 경우 비 루트 애그리게이트의 소유권을 다른 노드로 이동할 수 있습니다.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 루트가 아닌 애그리게이트를 이전 컨트롤러 노드 간에 마이그레이션합니다. 교체 노드를 설치한 후 이전 컨트롤러 노드에서 교체 컨트롤러 노드로 비 루트 애그리게이트를 마이그레이션합니다. 업그레이드 절차 중에 업그레이드 중인 노드에서 호스팅되는 데이터에 액세스할 수 있습니다. 또한 계속 진행하면서 클러스터의 노드 간에 데이터 LIF를 마이그레이션할 수 있습니다.

교체하는 컨트롤러 하드웨어는 기존 시스템 모델 유형에 따라 다릅니다.

[cols="30,70"]
|===
| 기존 시스템이 다음과 같은 경우... | 그러면... 


| AFF A250, AFF C250 | AFF A250 또는 AFF C250 컨트롤러 2개를 새로운 컨트롤러 및 I/O 모듈로 바꿉니다. 


| AFF A800, AFF C800 | AFF A800 또는 AFF C800 컨트롤러 2개를 새로운 컨트롤러 및 I/O 모듈로 바꿉니다. 


| AFF A220, AFF A200, AFF C190, FAS2620 또는 FAS2720 | 이전 컨트롤러의 각 노드에 있는 컨트롤러 모듈을 새 모듈로 바꿉니다. 


| AFF A700 또는 FAS9000 | 이전 컨트롤러의 각 노드에 있는 컨트롤러와 NVRAM 모듈을 새 모듈로 바꿉니다. * 참고 *: I/O 카드, 데이터 케이블, 디스크 선반 및 디스크를 이동, 분리 또는 재연결할 필요가 없습니다. 
|===

NOTE: node1 * 및 * node2 * 라는 용어는 이 문서의 노드 이름에 대한 참조용으로만 사용됩니다. 이 절차를 수행할 때는 노드의 실제 이름을 바꿔야 합니다.



== 요구 사항 및 제한 사항

업그레이드 절차를 시작하기 전에 중요한 요소를 고려해야 합니다.


NOTE: 업그레이드 절차를 시작하기 전에 다음의 모든 중요 정보를 검토해야 합니다.

* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 다음을 읽고 이해해야 합니다. link:guidelines_for_upgrading_controllers_with_arl.html["컨트롤러 업그레이드 지침"] 그리고 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 시퀀스"] 업그레이드를 시작하기 전에.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 다른 시스템에서 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 다른 ONTAP 클러스터의 일부로 사용한 경우 또는 독립 실행형 단일 노드 시스템으로 사용한 경우에는 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA 2노드에 대해 절차를 별도로 수행해야 합니다.
* ONTAP 버전에서 지원되지 않는 스위치와 업그레이드하려는 교체 시스템이 있는 경우 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크
* AFF A250 및 AFF C250 시스템은 클러스터 상호 연결을 위해 10/25GbE 온보드 포트를 사용합니다. AFF A250 또는 AFF C250 시스템의 2노드 스위치리스 클러스터를 AFF A50, AFF A30, AFF C60 또는 AFF C30 시스템으로 업그레이드하려면 두 노드의 슬롯 1에 X60132A 4포트 10/25GbE 카드를 사용해야 합니다. 이렇게 하면 클러스터 LIF(인터페이스)를 대상 플랫폼의 임시 포트에 클러스터 상호 연결시킬 수 있습니다.
* AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70, FAS90 시스템은 클러스터 및 HA 연결 모두에서 100GbE 네트워크 포트를 공유합니다. 이러한 시스템은 기존 클러스터 스위치에 대한 10GbE 또는 25GbE 클러스터 연결을 지원할 수 있습니다. 그러나 NetApp 10GbE 및 25GbE 스위치가 더 이상 필요하지 않은 경우 100GbE 클러스터 속도로 업데이트하는 것이 좋습니다. 자세한 내용은 다음 기술 문서를 참조하십시오.
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["새로운 클러스터 설정에서 10G 또는 25G 클러스터 포트를 구성하는 방법"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["기존 10G 또는 25G 클러스터 포트를 40G 또는 100G 클러스터 포트로 변환하는 방법"^]


--
+
기존 노드의 e0a 또는 e0b 클러스터 포트를 새 노드의 클러스터 포트에 연결할 수 없는 경우 다음을 참조하여 자세한 정보를 확인하십시오.

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp 버그 온라인 버그 ID CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["NetApp 버그 온라인 버그 ID 1127315"^]


* ASA A900, AFF A900 및 FAS9500 시스템은 하이 라인 전력(200V~240V)만 지원합니다. AFF A700 또는 FAS9000 시스템이 낮은 전력(100V에서 120V로)에서 실행되는 경우 이 절차를 사용하기 전에 AFF A700 또는 FAS9000 입력 전원을 변환해야 합니다.
* 에 포함된 다운타임이 있는 기존 시스템에서 업그레이드하는 <<supported-systems-in-chassis,지원되는 시스템 매트릭스>>경우, 스토리지를 이동하거나 기술 지원 부서에 문의하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. link:other_references.html["참조"]볼륨 또는 스토리지를 이동하여 업그레이드 _ 링크를 참조하십시오.




== 컨트롤러 업그레이드 프로세스를 자동화합니다

이 절차는 자동 디스크 할당 및 네트워크 포트 도달 가능성 검사를 사용하여 컨트롤러 업그레이드 환경을 단순화하는 자동화된 절차를 단계별로 설명합니다.
