---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 이전 시스템 섀시 및 디스크를 유지하면서 이전 시스템을 교체 시스템으로 전환하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL(Aggregate Relocation)을 사용하고 기존 시스템을 교체 시스템으로 변환하여 기존 시스템 섀시 및 디스크를 유지하면서 HA 쌍에서 컨트롤러 하드웨어를 중단 없이 업그레이드할 수 있습니다.


WARNING: 이 절차는 다음 업그레이드 구성에 엄격히 적용됩니다. 다른 시스템 조합 간 업그레이드를 수행하려면 * 이 절차를 사용하지 마십시오.

[cols="20,20,40"]
|===
| 기존 시스템 | 교체 시스템 | 지원되는 ONTAP 버전 


| AFF A800 1호 | AFF A90 또는 AFF A70 | 9.15.1 


| All SAN 어레이로 구성된 AFF A220(ASA) | ASA A150 | 9.13.1P1 이상 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 이상



| AFF C190 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 이상 


| FAS2620 | FAS2820  a| 
(2) (2) (2) (2

9.13.1 이상(FAS2820)



| FAS2720 | FAS2820 | 9.13.1 이상 


| ASA로 구성된 AFF A700 | ASA A900 | 9.13.1P1 이상 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 이상 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 이상 
|===
1. ONTAP 9.15.1에 도입된 시스템으로 업그레이드할 때 ONTAP는 스토리지 효율성을 사용하지 않는 볼륨을 포함하여 기존의 모든 씬 프로비저닝된 볼륨의 스토리지 효율성을 변환하고 하드웨어 오프로드 기능을 사용하는 새로운 스토리지 효율성 기능을 적용합니다. 이 프로세스는 자동 백그라운드 프로세스이며 시스템에 성능에 영향을 주지 않습니다. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["자세한 정보"^]..

AFF A200과 FAS2620 시스템은 9.11.1 이후 ONTAP 버전을 지원하지 않습니다.

[NOTE]
====
가능하면 이전 시스템과 교체 시스템에서 동일한 ONTAP 버전을 사용하는 것이 좋습니다. NetApp

위 표의 최소 ONTAP 버전은 필수입니다. 이러한 ONTAP 버전에는 업그레이드 중에 섀시 내에서 컨트롤러 유형을 혼합하는 데 필요한 서비스 프로세서 또는 BMC(베이스보드 관리 컨트롤러) 펌웨어 버전이 있습니다.

====
이 절차를 수행하는 동안 루트가 아닌 애그리게이트를 이전 컨트롤러 노드 간에 마이그레이션합니다. 설치 후 비루트 애그리게이트를 이전 컨트롤러 노드에서 교체 컨트롤러 노드로 마이그레이션합니다. 업그레이드 절차 중에 업그레이드 중인 노드에서 호스팅되는 데이터에 액세스할 수 있습니다.

.이 작업에 대해
이 컨트롤러 업그레이드 절차 중에 다음 업그레이드 중 하나를 수행합니다.

[cols="30,70"]
|===
| 기존 항목... | 다음을 수행합니다. 


| AFF A800 를 참조하십시오 | 2개의 AFF A800 컨트롤러, NVRAM 및 모든 I/O 모듈을 새로운 컨트롤러 및 I/O 모듈로 바꿉니다. 


| AFF A220, AFF A200, AFF C190, FAS2620 또는 FAS2720 | 이전 컨트롤러의 각 노드에 있는 컨트롤러 모듈을 새 모듈로 바꿉니다. ^1^ 


| AFF A700 또는 FAS9000 | 이전 컨트롤러의 각 노드에 있는 컨트롤러와 NVRAM 모듈을 새 모듈로 바꿉니다. ^1^ 
|===
1 I/O 카드, 데이터 케이블, 디스크 선반 및 디스크를 이동, 분리 또는 재연결할 필요가 없습니다.

이 절차에서는 ARL(Aggregate Relocation)이라는 메서드를 사용합니다. ARL은 HA 구성 및 클러스터 인터커넥트 통신을 활용하여 루트가 아닌 애그리게이트의 소유권을 동일한 클러스터 내에서 공유하는 경우 노드 간에 이동할 수 있습니다.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 노드에서 노드로 애그리게이트를 여러 번 마이그레이션하여 적어도 하나의 노드에서 애그리게이트에서 데이터를 처리하고 있는지 확인할 수 있습니다. 또한 계속 진행하면서 클러스터의 노드 간에 데이터 LIF를 마이그레이션할 수 있습니다.


NOTE: node1 * 및 * node2 * 라는 용어는 이 문서의 노드 이름에 대한 참조용으로만 사용됩니다. 이 절차를 수행할 때는 노드의 실제 이름을 바꿔야 합니다.

.중요 정보
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 을 읽고 이해해야 합니다 link:guidelines_for_upgrading_controllers_with_arl.html["컨트롤러 업그레이드 지침"] 및 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 개요"] 섹션을 참조하십시오.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 다른 시스템에서 사용되지 않은 것으로 가정합니다. 중고 컨트롤러를 와 함께 준비하는 데 필요한 단계입니다 `wipeconfig` 이 절차에는 명령이 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 다른 ONTAP 클러스터의 일부로 사용한 경우 또는 독립 실행형 단일 노드 시스템으로 사용한 경우에는 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA 2노드에 대해 절차를 별도로 수행해야 합니다.
* ONTAP 버전에서 지원되지 않는 스위치와 업그레이드하려는 교체 시스템이 있는 경우 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크
* 이 절차는 AFF A800, AFF A200, AFF A220, AFF C190, FAS2620, FAS2720, AFF A700 및 FAS9000 시스템 AFF A90, AFF A70, AFF A150, FAS2820, AFF A900으로 업그레이드해야 하는 다른 모든 컨트롤러 모델의 경우 또는 FAS9500 시스템의 경우, ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 업그레이드하려면 "system controller replace" 명령 사용 _ 및 _ aggregate relocation을 사용하여 ONTAP 9.8 이상 _content를 실행하는 컨트롤러 하드웨어를 수동으로 업그레이드하려면 을 참조하십시오 link:other_references.html["참조"] .
* ASA A900, AFF A900 및 FAS9500 시스템은 하이 라인 전력(200V~240V)만 지원합니다. AFF A700 또는 FAS9000 시스템이 낮은 전력(100V에서 120V로)에서 실행되는 경우 이 절차를 사용하기 전에 AFF A700 또는 FAS9000 입력 전원을 변환해야 합니다.
* AFF A800, AFF A200, AFF A220, AFF C190, FAS2620, FAS2720, AFF A700 또는 FAS9000 시스템은 다운타임이 있는 경우 스토리지를 이동하거나 기술 지원에 문의하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. link:other_references.html["참조"]볼륨 또는 스토리지를 이동하여 업그레이드 _ 링크를 참조하십시오.




== 컨트롤러 업그레이드 프로세스를 자동화합니다

이 절차는 자동 디스크 할당 및 네트워크 포트 도달 가능성 검사를 사용하여 컨트롤러 업그레이드 환경을 단순화하는 자동화된 절차를 단계별로 설명합니다.
