---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900 
summary: 컨트롤러 모듈과 NVS를 스와핑하여 AFF A700의 컨트롤러 하드웨어를 AFF A900으로 업그레이드할 수 있습니다. 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 절차에서는 다음 시스템 구성에 대해 ARL(Aggregate Relocation)을 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법에 대해 설명합니다.

[cols="30,20,20,30"]
|===
| 방법 | ONTAP 버전입니다 | 지원되는 시스템 | 설명 


| '시스템 컨트롤러 교체' 명령 사용 | 9.10 이상 | AFF A700에서 AFF A900으로 | 동일한 섀시를 유지하여 AFF A700을 AFF A900으로 변환합니다 
|===
컨트롤러 모듈과 NVRAM 모듈을 교체하여 AFF A700 노드의 고가용성(HA) 쌍에서 컨트롤러 하드웨어를 AFF A900 시스템으로 중단 없이 업그레이드할 수 있습니다. AFF A700 노드 간에 비루트 애그리게이트를 마이그레이션합니다. 설치 후 AFF A700 노드에서 비 루트 애그리게이트를 AFF A900 노드로 마이그레이션합니다. 업그레이드 절차 중에 업그레이드 중인 노드에서 호스팅되는 데이터에 액세스할 수 있습니다.

이 컨트롤러 업그레이드 절차에서는 AFF A700을 AFF A900 시스템으로 업그레이드합니다.


NOTE: AFF A700 시스템의 각 노드에서 2개의 현장 교체 장치(FRU)만 새 FRU로 스왑할 수 있습니다. I/O 카드, 데이터 케이블, 디스크 쉘프 및 디스크를 이동, 분리 또는 다시 연결할 필요가 없습니다.

이 절차에서는 HA 구성을 활용하는 ARL(Aggregate Relocation) 방법을 사용하여 동일한 클러스터 내에서 스토리지를 공유하는 경우 비루트 애그리게이트의 소유권을 다른 노드로 이동할 수 있습니다.

이 절차를 진행하는 동안 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 업그레이드하여 비 루트 애그리게이트를 재배치할 수 있습니다. 업그레이드 절차를 진행하는 동안 적어도 하나의 노드가 애그리게이트에서 데이터를 제공할 수 있도록 애그리게이트는 노드에서 노드로 여러 번 마이그레이션합니다. 또한 계속 진행하면서 클러스터의 노드 간에 데이터 LIF를 마이그레이션할 수 있습니다.


NOTE: node1 * 및 * node2 * 라는 용어는 이 문서의 노드 이름에 대한 참조용으로만 사용됩니다. 이 절차를 따를 때는 노드의 실제 이름을 대체해야 합니다.

.중요 정보
* 이 절차는 복잡하고 고급 ONTAP 관리 기술이 있다고 가정합니다. 또한 을 읽고 이해해야 합니다 link:guidelines_for_upgrading_controllers_with_arl.html["ARL이 있는 AFF A700에서 AFF A900으로 업그레이드하기 위한 지침"] 및 link:overview_of_the_arl_upgrade.html["ARL 업그레이드 개요"] 섹션을 참조하십시오.
* 이 절차에서는 교체 컨트롤러 하드웨어가 새 하드웨어이며 다른 시스템에서 사용되지 않은 것으로 가정합니다. 이 절차에는 사용된 컨트롤러를 "wipeconfig" 명령으로 준비하는 데 필요한 단계가 포함되어 있지 않습니다. 교체 컨트롤러 하드웨어를 이전에 다른 ONTAP 클러스터의 일부로 사용한 경우 또는 독립 실행형 단일 노드 시스템으로 사용한 경우에는 기술 지원 부서에 문의해야 합니다.
* 이 절차를 사용하여 2개 이상의 노드가 있는 클러스터에서 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 하지만 클러스터의 각 HA 2노드에 대해 절차를 별도로 수행해야 합니다.
* 이 절차는 AFF A700 시스템에만 적용됩니다. AFF A900 시스템으로 업그레이드해야 하는 다른 모든 컨트롤러 모델은 을 참조하십시오 link:other_references.html["참조"] "system controller replace" 명령을 사용하여 ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어와 _ONTAP 9.8 이상을 실행하는 컨트롤러 하드웨어를 수동으로 업그레이드하기 위해 Aggregate Relocation을 사용하여 _를 사용하십시오.
* AFF A900 시스템은 하이 라인 전원(200V ~ 240V)만 지원합니다. AFF A700 시스템이 낮은 전원(100V에서 120V로)에서 실행되는 경우 이 절차를 사용하기 전에 AFF A700 입력 전원을 변환해야 합니다.
* AFF A700 시스템에서 다운타임 때문에 업그레이드할 경우 스토리지를 이동하거나 기술 지원 부서에 문의하여 컨트롤러 하드웨어를 업그레이드할 수 있습니다. 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

