---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install_a900_nvs_and_controller_on_node2.html 
keywords: install, NVRAM, aff, a900, node2, controller, module 
summary: ARL 컨트롤러 업그레이드 절차 중 AFF A900 NVRAM 모듈 및 컨트롤러 모듈에 대한 설치 지침. 
---
= 노드2에 AFF A900 또는 FAS9500 NVRAM 및 컨트롤러 모듈을 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2에서 업그레이드하기 위해 받은 AFF A900 또는 FAS9500 NVRAM 및 컨트롤러 모듈을 설치합니다. 노드2는 시스템 뒷면에서 컨트롤러를 볼 때 섀시 오른쪽에 있는 컨트롤러 B입니다.

설치를 수행할 때 다음 사항에 주의해야 합니다.

* 슬롯 6-1과 6-2의 빈 필러 모듈을 모두 이전 NVRAM 모듈에서 새 NVRAM 모듈로 이동합니다.
* 코어 덤프 장치를 AFF A700 NVRAM 모듈에서 AFF A900 NVRAM 모듈로 이동하지 마십시오.
* FAS9000 NVRAM 모듈에 설치된 All-Flash 캐시 모듈을 FAS9500 NVRAM 모듈로 이동합니다.


.시작하기 전에
아직 접지되지 않은 경우 올바르게 접지하십시오.



== AFF A900 또는 FAS9500 NVRAM 모듈을 설치합니다

노드2의 슬롯 6에 AFF A900 또는 FAS9500 NVRAM 모듈을 설치하려면 다음 절차를 따르십시오.

.단계
. NVRAM 모듈을 슬롯 6의 섀시 입구 가장자리에 맞춥니다.
. 글자가 새겨진 번호가 매겨진 I/O 캠 래치가 I/O 캠 핀과 맞물릴 때까지 NVRAM 모듈을 슬롯에 부드럽게 밀어 넣은 다음 I/O 캠 래치를 끝까지 밀어 NVRAM 모듈을 제자리에 고정시킵니다.




== 노드2에 AFF A900 또는 FAS9500 컨트롤러 모듈을 설치합니다

노드2에 AFF A900 또는 FAS9500 컨트롤러 모듈을 설치하려면 다음 절차를 따르십시오.

.단계
. 컨트롤러 모듈의 끝을 섀시의 베이 B에 맞춘 다음 컨트롤러 모듈을 반쯤 가볍게 밀어 시스템에 넣습니다.
+

TIP: 베이 레이블은 컨트롤러 모듈 바로 위의 섀시에 있습니다.

+

NOTE: 절차의 뒷부분에서 컨트롤러 모듈을 삽입하라는 지시가 있을 때까지 섀시에 모듈을 완전히 삽입하지 마십시오.

. 노드2 컨트롤러 모듈에 관리 및 콘솔 포트를 케이블로 연결합니다.
+

NOTE: 섀시의 전원이 이미 켜져 있으므로 노드 2가 완전히 장착되면 바로 부팅됩니다. 노드 2가 부팅되지 않도록 하려면 컨트롤러 모듈을 슬롯에 완전히 삽입하기 전에 콘솔 및 관리 케이블을 노드2 컨트롤러 모듈에 연결하는 것이 좋습니다.

. 컨트롤러 모듈이 중앙판과 만나 완전히 장착될 때까지 섀시 안으로 단단히 밀어 넣습니다.
+
컨트롤러 모듈이 완전히 장착되면 잠금 래치가 올라갑니다.

+

WARNING: 커넥터의 손상을 방지하려면 컨트롤러 모듈을 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

. 모듈이 장착되면 즉시 직렬 콘솔을 연결하고 노드 1의 자동 부팅을 중단시킵니다.
. 자동 부팅을 중단하고 나면 로더 프롬프트에서 노드 2가 중지됩니다. 시간에 자동 부팅을 중단하지 않고 노드 2가 부팅을 시작하면 메시지가 표시될 때까지 기다린 다음 * Ctrl-C * 를 눌러 부팅 메뉴로 이동합니다. 부팅 메뉴에서 노드가 중지된 후 옵션을 사용합니다 `8` 재부팅 중 노드를 재부팅하고 자동 부팅을 중단하려면 다음 작업을 중단합니다.
. node2의 Loader> 프롬프트에서 기본 환경 변수를 설정합니다.
+
`set-defaults`

. 기본 환경 변수 설정을 저장합니다.
+
`saveenv`


