---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-asaa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 동일한 섀시에 있는 컨트롤러 모델의 ARL 업그레이드 중에 노드 2에 교체 시스템 모듈을 설치합니다. 
---
= ASA A150, AFF A150 또는 FAS2820 컨트롤러 모듈을 노드2에 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
업그레이드를 위해 받은 ASA A150, AFF A150 또는 FAS2820 컨트롤러 모듈을 노드2에 설치합니다. 노드2는 시스템 뒷면에서 컨트롤러를 볼 때 섀시 오른쪽에 있는 컨트롤러 B입니다.

.시작하기 전에
* 아직 접지되지 않은 경우 올바르게 접지하십시오.
* 분리할 컨트롤러에서 콘솔, 관리, SAS 스토리지 및 데이터 네트워크 케이블을 비롯한 모든 케이블을 분리합니다.


.단계
. 컨트롤러 모듈의 끝을 섀시의 베이 B에 맞춘 다음 컨트롤러 모듈을 반쯤 가볍게 밀어 시스템에 넣습니다.
+

TIP: 베이 B는 하단의 섀시에 있습니다.

+

WARNING: 절차의 뒷부분에서 지시가 있을 때까지 컨트롤러 모듈을 섀시에 완전히 삽입하지 마십시오.

. 노드2 컨트롤러 모듈에 관리 및 콘솔 포트를 케이블로 연결합니다.
+

NOTE: 섀시의 전원이 이미 켜져 있으므로 노드 2가 완전히 장착되면 바로 부팅됩니다. 노드 2가 부팅되지 않도록 하려면 NetApp 컨트롤러 모듈을 슬롯에 완전히 삽입하기 전에 콘솔 및 관리 케이블을 노드2 컨트롤러 모듈에 연결하는 것이 좋습니다.

. 컨트롤러 모듈이 중앙판과 만나 완전히 장착될 때까지 섀시 안으로 단단히 밀어 넣습니다.
+
컨트롤러 모듈이 완전히 장착되면 잠금 래치가 올라갑니다.

+

NOTE: 커넥터 손상을 방지하려면 컨트롤러 모듈을 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

. 모듈이 장착되면 즉시 직렬 콘솔을 연결하고 node2의 AUTOBOOT를 중단할 준비를 하세요.
. 자동 부팅을 중단하고 나면 로더 프롬프트에서 노드 2가 중지됩니다. 자동 부팅을 중지하고 노드2의 부팅을 시작하는 경우, 프롬프트가 표시될 때까지 기다린 다음 Ctrl-C를 눌러 부팅 메뉴로 이동합니다. 부팅 메뉴에서 노드가 중지되면 옵션을 사용하여 `8` 노드를 재부팅하고 재부팅 중 자동 부팅을 중단합니다.

