---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: ARL을 사용하여 동일한 섀시의 컨트롤러 모델을 업그레이드할 때 노드 1에 있는 node2의 NAS 데이터 LIF가 노드 1에서 노드 2로 재배치되는지 확인합니다. 
---
= 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2로 다시 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2의 네트워크 구성을 확인하고 노드 1에서 노드 2로 애그리게이트를 재배치된 후에는 노드 1에 있는 노드 2에 속하는 NAS 데이터 LIF가 노드 1에서 노드 2로 재배치되어 있는지 확인합니다. 또한 노드 2에 SAN LIF가 존재하는지 확인해야 합니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드2를 온라인으로 전환하는 경우 LIF가 정상 작동하는지, 해당 포트에 있는지 확인해야 합니다.

.단계
. 재배치 작업 재개:
+
`system controller replace resume`

+
시스템은 다음 작업을 수행합니다.

+
--
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


--
+
이 단계에서 네트워크 도달 가능성 점검에서 작업이 일시 중지됩니다.

. 재배치 작업 재개:
+
`system controller replace resume`

+
시스템에서 다음 검사를 수행합니다.

+
--
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


--
+
이러한 확인을 수행한 후 시스템에서는 루트가 아닌 애그리게이트와 NAS 데이터 LIF를 노드 2로 재배치하고 현재 교체 컨트롤러에서 실행되고 있습니다.

+
리소스 재배치가 완료된 후 컨트롤러 교체 작업이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
`system controller replace show-details`

+
컨트롤러 교체 절차가 일시 중지된 경우 오류를 확인하고 수정한 다음 문제를 해결하십시오 `resume` 를 눌러 작업을 계속합니다.

. 필요한 경우 교체된 LIF를 복원하여 되돌리십시오. 교체된 LIF 나열:
+
`cluster controller-replacement network displaced-interface show`

+
LIF가 대체된 경우 홈 노드를 노드 2로 다시 복원합니다.

+
`cluster controller-replacement network displaced-interface restore-home-node`

. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
`system controller replace resume`

+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검
** 볼륨 확인



