---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: ARL을 사용하여 동일한 섀시의 컨트롤러 모델을 업그레이드할 때 노드 2에 있는 node1 NAS 데이터 LIF가 노드 2에서 노드 1로 재배치되는지 확인합니다. 
---
= 노드 1이 소유하는 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2에서 업그레이드된 노드 1로 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 1의 네트워크 구성을 확인한 후 노드 2에서 노드 1로 애그리게이트를 재배치할 경우, 현재 노드 2에 있는 노드 1에 속하는 NAS 데이터 LIF가 노드 2에서 노드 1로 재배치되어 있는지 확인합니다. 또한 SAN LIF가 노드 1에 존재하는지 확인해야 합니다.

.이 작업에 대해
원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 1을 온라인으로 전환하는 경우 LIF가 정상 작동하는지, 해당 포트에 있는지 확인해야 합니다.

.단계
. 재배치 작업 재개:
+
`system controller replace resume`

+
시스템은 다음 작업을 수행합니다.

+
--
** 클러스터 쿼럼 검사
** 시스템 ID 확인
** 이미지 버전 확인
** 대상 플랫폼 확인
** 네트워크 도달 가능성 확인


--
+
이 단계에서 네트워크 도달 가능성 점검에서 작업이 일시 중지됩니다.

. 네트워크 연결 상태 확인 수행:
+
`network port reachability show -node node1`

+
인터페이스 그룹 및 VLAN 포트를 포함하여 연결된 모든 포트의 상태가 로 표시되는지 확인합니다 `OK`.

. 다음 업그레이드를 위해 FCP SAN LIF를 재할당해야 합니다.
+
[cols="35,65"]
|===
| 기존 시스템 | 교체 시스템 


| AFF A250 를 참조하십시오 | AFF A30, AFF A50 


| AFF C250 를 참조하십시오 | AFF C30, AFF C60 


| AFF A800 를 참조하십시오 | AFF A70, AFF A90 


| AFF C800 를 참조하십시오 | C80를 참조하십시오 
|===
+
다른 모든 시스템 업그레이드의 경우 로 <<resume_relocation_step4,4단계>>진행합니다.

+
.. FCP 또는 FC-NVMe 데이터 액세스에 사용되는 FCP SAN LIF를 올바른 홈 포트에 다시 할당합니다.
+
`network interface show -vserver <vserver_hosting_fcp_lifs>`

.. 업그레이드된 노드 1로 현재 노드가 있고 현재 포트에서 "status oper"를 "-"로 보고하는 LIF의 경우(AFF A800 노드에 포트가 있지만 AFF A90 노드에 존재하지 않음) 현재 포트를 수정하여 온라인으로 전환할 수 있습니다.
+
FC LIF를 이동해야 하는 FC 타겟 포트에 대한 물리적 연결이 설정되어 있는지 확인

+
--
... LIF 상태를 "아래쪽"으로 설정합니다.
+
`network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down`

... LIF의 홈 포트를 수정합니다.
+
`network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>`

... LIF 상태를 "설정"으로 설정:
+
`network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up`



--
+
노드 1의 홈 페이지인 각 FC SAN LIF에 대해 하위 단계 a 및 b를 반복합니다.



. [[RESUME_RELOCATION_STEP4]] 재배치 작업 재개:
+
`system controller replace resume`

+
시스템에서 다음 검사를 수행합니다.

+
--
** 클러스터 상태 점검
** 클러스터 LIF 상태 점검


--
+
이러한 확인을 수행한 후 시스템은 노드 1이 소유한 루트 이외의 Aggregate 및 NAS 데이터 LIF를 새 노드 1로 재배치합니다.

+
리소스 재배치가 완료된 후 컨트롤러 교체 작업이 일시 중지됩니다.

. 애그리게이트 재배치 및 NAS 데이터 LIF 이동 작업의 상태를 확인합니다.
+
`system controller replace show-details`

+
컨트롤러 교체 절차가 일시 중지된 경우 오류를 확인하고 수정한 다음 문제를 해결하십시오 `resume` 를 눌러 작업을 계속합니다.

. 필요한 경우 교체된 LIF를 복원하여 되돌리십시오. 교체된 LIF 나열:
+
`cluster controller-replacement network displaced-interface show`

+
LIF가 대체된 경우 홈 노드를 노드 1로 다시 복원합니다.

+
`cluster controller-replacement network displaced-interface restore-home-node`

. 작업을 재개하여 시스템에서 필요한 사후 검사를 수행하도록 합니다.
+
`system controller replace resume`

+
시스템은 다음과 같은 사후 검사를 수행합니다.

+
** 클러스터 쿼럼 검사
** 클러스터 상태 점검
** 재구성 검사를 집계합니다
** 집계 상태 확인
** 디스크 상태 점검
** 클러스터 LIF 상태 점검
** 볼륨 확인



