---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware, old, system, chassis, disk, disks 
summary: 동일한 섀시에서 컨트롤러 모델을 업그레이드하는 ARL 절차가 어떻게 작동하는지 이해합니다. 
---
= ARL 업그레이드 순서에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ARL을 사용하여 노드를 업그레이드하기 전에 절차가 어떻게 작동하는지 이해해야 합니다. 이 콘텐츠에서는 절차가 여러 단계로 나뉩니다.



== 노드 쌍을 업그레이드합니다

노드 쌍을 업그레이드하려면 원래 노드를 준비한 다음 원래 노드와 새 노드 모두에서 일련의 단계를 수행해야 합니다. 그런 다음 원래 노드를 서비스 해제할 수 있습니다.



== ARL 업그레이드 시퀀스 개요

이 절차를 수행하는 동안, 원래 컨트롤러 하드웨어를 교체 컨트롤러 하드웨어로 한 번에 하나씩 업그레이드하여 HA 쌍 구성을 활용하여 루트 이외의 애그리게이트에 대한 소유권을 재배치합니다. 모든 비루트 애그리게이트에는 두 개의 재배치가 수행되어 마지막 대상에 도달해야 합니다. 이것이 올바른 업그레이드 노드입니다.

각 집합에는 홈 소유자와 현재 소유자가 있습니다. 홈 소유자는 애그리게이트의 실제 소유자이며 현재 소유자는 임시 소유자입니다.

다음 표에서는 각 단계에서 수행하는 상위 수준의 작업과 단계 종료 시 총 소유권의 상태를 설명합니다. 자세한 단계는 절차의 뒷부분에서 제공됩니다.

[cols="35,65"]
|===
| 단계 | 단계 


| link:verify_upgrade_hardware.html["1단계: 업그레이드 준비"]  a| 
1단계에서는 사전 점검을 통해 업그레이드에 적합한 하드웨어가 있는지 확인하고, 필요한 경우 애그리게이트 소유권을 수정합니다. Onboard Key Manager를 사용하여 스토리지 암호화를 관리하는 경우 특정 정보를 기록해야 하며 SnapMirror 관계를 중지할 수 있습니다.

1단계 종료 시 소유권 집계:

* 노드 1은 노드 1 애그리게이트의 홈 소유자이며 현재 소유입니다
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다




| link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["2단계: 리소스를 재배치하고 노드1을 폐기합니다"]  a| 
2단계에서는 노드 1이 아닌 Aggregate 및 NAS 데이터 LIF를 노드 1에서 노드 2로 재배치합니다. 이 프로세스는 대부분 자동화되어 있으며 사용자가 상태를 확인할 수 있도록 작업이 일시 중지됩니다. 작업을 수동으로 재개해야 합니다. 필요한 경우 장애가 발생한 애그리게이트를 재이동하거나 거부권을 행사합니다. 노드 1을 폐기하기 전에 프로시저에서 나중에 사용할 수 있도록 노드1 정보를 기록합니다. 절차의 뒷부분에서 netboot node1을 준비할 수도 있습니다.

2단계 종료 시 소유권 집계:

* 노드 2는 노드 1 애그리게이트의 현재 소유자입니다
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다




| link:cable-node1-for-shared-cluster-HA-storage.html["3단계: 교체 시스템 모듈로 노드1을 부팅합니다"]  a| 
3단계에서는 업그레이드된 시스템 모듈로 노드 1을 부팅하고 업그레이드된 노드1 설치를 확인합니다. NVE(NetApp Volume Encryption)를 사용하는 경우 키 관리자 구성을 복원합니다. 또한 노드 1의 루트 이외의 Aggregate 및 NAS 데이터 LIF를 노드 2에서 업그레이드된 노드 1로 재배치하고 노드 1에 SAN LIF가 있는지 확인합니다.

3단계 종료 시 소유권 집계:

* 업그레이드된 노드1은 노드1 애그리게이트의 홈 소유자이며 현재 소유입니다
* 노드 2는 노드 2 애그리게이트의 홈 소유자이며 현재 소유입니다




| link:relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html["4단계: 리소스를 재배치하고 노드2를 폐기합니다"]  a| 
4단계에서는 루트가 아닌 애그리게이트와 NAS 데이터 LIF를 노드 2에서 업그레이드된 노드 1로 재배치하고 노드 2를 폐기합니다.

4단계 종료 시 소유권 집계:

* 업그레이드된 노드1은 노드1에 원래 속해 있는 애그리게이트의 홈 소유자 및 현재 소유입니다
* 업그레이드된 노드 1은 노드 2 애그리게이트의 현재 소유입니다




| link:install-aff-a30-a50-c30-c50-node2.html["5단계: 노드 2에 교체 시스템 모듈을 설치합니다"]  a| 
5단계에서는 업그레이드된 노드 2에 대해 받은 새 시스템 모듈을 설치한 다음 netboot 노드 2를 설치합니다.

5단계 종료 시 소유권 집계:

* 업그레이드된 노드1은 노드1에 원래 속해 있는 애그리게이트의 홈 소유자 및 현재 소유입니다.
* 업그레이드된 노드2는 노드2에 원래 속해 있는 애그리게이트의 홈 소유자 및 현재 소유입니다.




| link:boot_node2_with_a900_controller_and_nvs.html["6단계: 교체 시스템 모듈을 사용하여 노드 2를 부팅합니다"]  a| 
6단계에서는 업그레이드된 시스템 모듈로 node2를 부팅하고 업그레이드된 node2 설치를 확인합니다. NVE를 사용하는 경우 키 관리자 구성을 복원합니다. 스위치에 연결된 클러스터를 업그레이드하는 경우 클러스터 스위치 참조 구성 파일(RCF)이 공유 클러스터/HA 포트를 지원하는지 확인해야 합니다. 또한 node1의 루트가 아닌 집계 및 NAS 데이터 LIF를 node1에서 업그레이드된 node2로 이전하고 SAN LIF가 node2에 있는지 확인합니다.



| link:manage-authentication-using-kmip-servers.html["7단계: 업그레이드를 완료합니다"]  a| 
7단계에서는 새 노드가 올바르게 설정되었는지 확인하고, 새 노드가 암호화를 사용하도록 설정된 경우 Storage Encryption 또는 NVE를 구성하고 설정합니다. 또한 이전 노드의 사용을 중지하고 SnapMirror 작업을 다시 시작해야 합니다.

|===