---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1. aff, a900, NVRAM, controller 
summary: AFF A700에서 AFF A900으로 업그레이드하는 동안 노드 2의 비루트 애그리게이트를 노드 1로 재배치합니다. 
---
= 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 1로 재배치합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2를 AFF A900 컨트롤러 모듈 및 NVRAM 모듈로 교체하려면 먼저 노드 2가 소유한 비루트 애그리게이트를 노드 1로 재이동해야 합니다.

이전 단계의 사후 검사가 완료되면 노드 2의 리소스 해제가 자동으로 시작됩니다. 루트가 아닌 애그리게이트 및 non-SAN 데이터 LIF는 노드 2에서 새로운 노드 1로 마이그레이션됩니다.

Aggregate 및 LIF가 마이그레이션되면 검증 목적으로 작업이 일시 중지됩니다. 이 단계에서는 모든 비루트 애그리게이트 및 비 SAN 데이터 LIF가 새 노드 1로 마이그레이션되는지 확인해야 합니다.

Aggregate 및 LIF의 홈 소유자는 수정되지 않으며 현재 소유자만 수정됩니다.

.단계
. 루트가 아닌 모든 애그리게이트가 온라인 상태이고 노드 1의 상태가 온라인인지 확인합니다.
+
스토리지 집계 노드 노드 노드1-상태 online-root false

+
다음 예제에서는 노드 1의 루트 이외의 애그리게이트가 온라인 상태인 것을 보여 줍니다.

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	 #Vols	 Nodes	  RAID	   Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB      744.8GB	 0%	 online	  5	 node1	  raid_dp  normal
aggr_2	      825.0GB	    825.0GB	 0%	 online	  1	 node1	  raid_dp  normal
2 entries were displayed.
----
+
노드 1에서 애그리게이트가 오프라인 상태가 되거나 외부 상태가 된 경우, 각 애그리게이트에 대해 하나씩 새 노드 1에서 다음 명령을 사용하여 애그리게이트를 온라인 상태로 전환합니다.

+
'Storage aggregate online-aggregate <aggr_name>'

. node1에서 다음 명령을 사용하고 해당 출력을 검사하여 node1에서 모든 볼륨이 온라인 상태인지 확인합니다.
+
'볼륨 표시 노드 노드1 - 상태 오프라인'

+
노드 1에 오프라인 상태인 볼륨이 있는 경우 각 볼륨에 대해 한 번씩 노드 1에서 다음 명령을 사용하여 온라인으로 전환합니다.

+
'volume online-vserver <vserver-name> - volume <volume-name>'

+
이 명령에 사용할 vserver-name은 이전 'volume show' 명령의 출력에서 확인할 수 있습니다.

. LIF가 올바른 포트로 이동되었으며 'Up' 상태인지 확인합니다. LIF가 하나라도 다운되면 각 LIF에 대해 다음 명령을 한 번 입력하여 LIF의 관리 상태를 Up으로 설정합니다.
+
'network interface modify -vserver vserver_name -lif LIF_name -home-node nodename -status -admin up'을 선택합니다

. 다음 명령을 사용하여 출력을 검사하여 노드 2에 남아 있는 데이터 LIF가 없는지 확인합니다.
+
네트워크 인터페이스 show-curr-node <node2>-role data


