---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1, NVRAM, controller, module, modules 
summary: ARL을 사용하여 동일한 섀시의 컨트롤러 모델을 업그레이드할 때 node2의 비루트 애그리게이트를 노드 1로 재배치합니다. 
---
= 루트 이외의 애그리게이트 및 NAS 데이터 LIF를 노드 2에서 노드 1로 재배치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2를 교체 시스템 모듈로 교체하려면 먼저 노드 2가 소유한 비루트 애그리게이트를 노드 1로 재이동해야 합니다.

.시작하기 전에
이전 단계의 사후 검사가 완료되면 노드 2의 리소스 해제가 자동으로 시작됩니다. 루트가 아닌 애그리게이트 및 non-SAN 데이터 LIF는 노드 2에서 새로운 노드 1로 마이그레이션됩니다.

.이 작업에 대해
Aggregate 및 LIF가 마이그레이션되면 검증 목적으로 작업이 일시 중지됩니다. 이 단계에서는 모든 비루트 애그리게이트 및 비 SAN 데이터 LIF가 새 노드 1로 마이그레이션되는지 확인해야 합니다.

Aggregate 및 LIF의 홈 소유자는 수정되지 않으며 현재 소유자만 수정됩니다.

.단계
. 루트가 아닌 모든 애그리게이트가 온라인 상태이고 노드 1의 상태가 온라인인지 확인합니다.
+
`storage aggregate show -node node1 -state online -root false`

+
다음 예제에서는 노드 1의 루트 이외의 애그리게이트가 온라인 상태인 것을 보여 줍니다.

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	  #Vols	 Nodes	 RAID	  Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB     744.8GB	  0%	  online	  5	 node1   raid_dp  normal
aggr_2	      825.0GB	  825.0GB	  0%	  online	  1	 node1   raid_dp  normal
2 entries were displayed.
----
+
노드 1에서 애그리게이트가 오프라인 상태가 되거나 외부 상태가 된 경우, 각 애그리게이트에 대해 하나씩 새 노드 1에서 다음 명령을 사용하여 애그리게이트를 온라인 상태로 전환합니다.

+
`storage aggregate online -aggregate _aggr_name_`

. node1에서 다음 명령을 사용하고 해당 출력을 검사하여 node1에서 모든 볼륨이 온라인 상태인지 확인합니다.
+
`volume show -node node1 -state offline`

+
노드 1에 오프라인 상태인 볼륨이 있는 경우 각 볼륨에 대해 한 번씩 노드 1에서 다음 명령을 사용하여 온라인으로 전환합니다.

+
`volume online -vserver _vserver-name_ -volume _volume-name_`

+
를 클릭합니다 `_vserver-name_` 이 명령과 함께 사용하려면 이전 의 출력에서 찾을 수 있습니다 `volume show` 명령.

. LIF가 올바른 포트로 이동되었으며 상태가 인지 확인합니다 `up`. LIF가 하나라도 다운되면 LIF의 관리 상태를 로 설정합니다 `up` 다음 명령을 각 LIF에 대해 한 번 입력합니다.
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ - status-admin up`

. 다음 명령을 사용하여 출력을 검사하여 노드 2에 남아 있는 데이터 LIF가 없는지 확인합니다.
+
`network interface show -curr-node _node2_ -role data`


