---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node2_installation.html 
keywords: verifying, verify, node, install, installation, NVRAM, controller, module, modules 
summary: ARL을 사용하여 동일한 섀시에서 컨트롤러 모델을 업그레이드할 때 교체 모듈을 사용하여 node2 설치를 확인합니다. 
---
= 노드2 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
교체 시스템 모듈을 사용하여 node2 설치를 확인해야 합니다. 물리적 포트는 변경되지 않으므로 이전 노드 2에서 교체 노드 2로 물리적 포트를 매핑할 필요가 없습니다.

.이 작업에 대해
교체 시스템 모듈을 사용하여 노드 1을 부팅한 후 올바르게 설치되었는지 확인합니다. 노드 2가 쿼럼에 참가할 때까지 기다린 다음 컨트롤러 교체 작업을 다시 시작해야 합니다.

절차의 이 시점에서 노드 2가 쿼럼에 조인되는 동안 작업이 일시 중지됩니다.

.단계
. 노드 2가 쿼럼에 연결되었는지 확인합니다.
+
`cluster show -node node2 -fields health`

+
의 출력입니다 `health` 필드는 이어야 합니다 `true`.

. 이 단계는 다음 업그레이드 구성에 적용됩니다. 다른 모든 시스템 업그레이드의 경우 이 단계를 건너뛰고 다음으로 이동하세요. <<verify-node2-step3,3단계>> :
+
** 2노드 스위치리스 클러스터
** AFF A250 또는 AFF C250 시스템에 연결된 스위치를 AFF A50, AFF A30, AFF C30 또는 AFF C60 시스템으로 업그레이드합니다.


+
--
node2가 자동으로 쿼럼에 가입하지 않는 경우:

.. e1a 및 e1b 포트의 IP 공간을 확인하세요.
+
`network port show`

.. IPspace가 "클러스터"가 아닌 경우 e1a 및 e1b에서 IPspace를 "클러스터"로 변경합니다.
+
`network port modify -node <node_name> -port <port> -ipspace Cluster`

.. 포트 e1a 및 e1b의 IP 공간이 "클러스터"인지 확인하세요.
+
`network port show`

.. node2 클러스터 LIF를 e1a 및 e1b로 마이그레이션:
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node2_name> -destination-port <port_name`



--
. [[verify-node2-step3]]node2와 node1이 동일한 클러스터에 속해 있고 클러스터가 정상인지 확인합니다.
+
`cluster show`

. 고급 권한 모드로 전환:
+
`set advanced`

. 이 단계는 AFF A250 또는 AFF C250에서 AFF A50, AFF A30, AFF C60 또는 AFF C30으로의 2노드 스위치리스 구성 업그레이드에만 적용됩니다. 다른 모든 시스템 업그레이드의 경우 이 단계를 건너뛰고 다음으로 이동하십시오. <<verify-node2-step6,6단계>> :
+
"클러스터" 브로드캐스트 도메인의 클러스터 포트가 e4a, e2a, e1a, e1b 포트 또는 e4a, e4b, e1a, e1b 포트인지 확인하세요.

+
AFF A50, AFF A30, AFF C30 및 AFF C60 시스템은 클러스터 및 HA 포트를 공유합니다. 모든 클러스터 LIF를 node1과 node2의 e4a, e4b 또는 e4a, e2a로 안전하게 마이그레이션할 수 있습니다.

+
.. 모든 클러스터 LIF에 대한 홈 포트와 현재 포트를 나열합니다.
+
`network interface show -role Cluster -fields home-port,curr-port`

.. [[migrate-cluster-lif-step-4b]]node1과 node2에서 e1a를 홈 포트로 사용하는 클러스터 LIF를 e4a로 마이그레이션합니다.
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node> -destination-port e4a`

.. node1 및 node2에서 마이그레이션된 클러스터 LIF를 수정합니다. <<migrate-cluster-lif-step-4b,하위 단계 b>> e4a를 홈 포트로 사용하려면:
+
`network  interface modify -vserver Cluster -lif <cluster_lif> -home-port e4a`

.. 클러스터가 쿼럼에 있는지 확인하세요.
+
`cluster show`

.. 반복하다 <<migrate-cluster-lif-step-4b,하위 단계 b와 하위 단계 c>> 각 노드의 두 번째 클러스터 LIF를 e2a 또는 e4b로 마이그레이션하고 수정하려면:
+
e2a가 있고 100GbE 네트워크 포트인 경우, 이는 기본 두 번째 클러스터 포트입니다. e2a가 100GbE 네트워크 포트가 아닌 경우, ONTAP은 e4b를 두 번째 클러스터 및 HA 포트로 사용합니다.

.. "클러스터" 브로드캐스트 도메인에서 e1a 및 e1b를 제거합니다.
+
`broadcast-domain remove-ports -broadcast-domain Cluster -ipspace Cluster -ports <node_name>:e1a`

.. "클러스터" 브로드캐스트 도메인에 클러스터 포트 e4a, e2a 또는 e4a, e4b만 있는지 확인하십시오.
+
`broadcast domain show`

.. e1a node1과 e1a node2, e1b node1과 e1b node2 사이의 케이블 연결을 제거하여 유효한 클러스터 HA 연결만 사용되고 중복 연결이 없는지 확인합니다.


. [[verify-node2-step6]]컨트롤러 교체 작업의 상태를 확인하고 일시 정지 상태이며 노드2가 새 컨트롤러 설치 및 케이블 이동과 같은 물리적 작업을 수행하기 위해 중단되기 전 상태와 동일한지 확인합니다.
+
`system controller replace show`

+
`system controller replace show-details`

. 컨트롤러 교체 작업을 재개합니다.
+
`system controller replace resume`

. 컨트롤러 교체 작업이 중재를 위해 다음 메시지와 함께 일시 중지됩니다.
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node2         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node1         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: 이 절차에서 section_re-creating vLANs, ifgrp, broadcast domain_이 node2_의 _Restore 네트워크 구성 으로 변경되었습니다.

. 컨트롤러 교체가 일시 중지 상태인 경우 로 진행합니다 <<노드2에서 네트워크 구성을 복원합니다>>.




== 노드2에서 네트워크 구성을 복원합니다

노드 2가 쿼럼에 있고 노드 1과 통신할 수 있는지 확인한 후 노드 1의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인이 노드 2에 표시되는지 확인합니다. 또한 모든 node2 네트워크 포트가 올바른 브로드캐스트 도메인에 구성되어 있는지 확인합니다.

.이 작업에 대해
VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 를 눌러 _Network Management_content에 연결합니다.

.단계
. 업그레이드된 노드 2에 있는 모든 물리적 포트 나열:
+
`network port show -node node2`

+
노드의 모든 물리적 네트워크 포트, VLAN 포트 및 인터페이스 그룹 포트가 표시됩니다. 이 출력에서 로 이동된 모든 물리적 포트를 볼 수 있습니다 `Cluster` ONTAP에 의한 브로드캐스트 도메인. 이 출력을 사용하면 인터페이스 그룹 구성원 포트, VLAN 기본 포트 또는 LIF 호스팅을 위한 독립 실행형 물리적 포트로 사용할 포트를 쉽게 결정할 수 있습니다.

. 클러스터의 브로드캐스트 도메인을 나열합니다.
+
`network port broadcast-domain show`

. 노드 2의 모든 포트에 대한 네트워크 포트 도달 가능 여부 나열:
+
`network port reachability show -node node2`

+
다음 예제와 유사한 출력이 표시됩니다. 포트 및 브로드캐스트 이름은 다양합니다.

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
앞의 예제에서 노드 2는 컨트롤러 교체 후 쿼럼(quorum)으로 부팅되고 조인되었습니다. 여기에는 연결 기능이 없고 연결 가능성 검사를 대기 중인 여러 포트가 있습니다.

. [[restore_node2_step4] 노드 2의 각 포트에 대한 연결 상태를 이외의 다른 연결 상태로 복구합니다 `ok` 다음 명령을 사용하여 다음 순서로 명령을 실행합니다.
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. 물리적 포트
.. VLAN 포트


--
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Cluster ::> reachability repair -node node2 -port e9d
----
+
[listing]
----
Warning: Repairing port "node2:e9d" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
이전 예에 표시된 것처럼, 현재 위치한 브로드캐스트 도메인의 도달 가능성 상태와 다를 수 있는 도달 가능성 상태의 포트에 대해 경고 메시지가 표시될 것입니다. 포트의 연결을 검토하고 응답합니다 `y` 또는 `n` 있습니다.

+
모든 물리적 포트에 예상되는 도달 능력이 있는지 확인합니다.

+
`network port reachability show`

+
도달 가능성 복구가 수행되면 ONTAP는 포트를 올바른 브로드캐스트 도메인에 배치하려고 시도합니다. 그러나 포트의 도달 가능 여부를 확인할 수 없고 기존 브로드캐스트 도메인에 속하지 않는 경우 ONTAP는 이러한 포트에 대한 새 브로드캐스트 도메인을 만듭니다.

. 포트 도달 가능성 확인:
+
`network port reachability show`

+
모든 포트가 올바르게 구성되고 올바른 브로드캐스트 도메인에 추가되면 가 `network port reachability show` 명령은 의 도달 가능성 상태를 보고해야 합니다 `ok` 연결된 모든 포트에 대해 및 상태를 로 표시합니다 `no-reachability` 물리적 연결이 없는 포트의 경우 이 두 포트가 아닌 다른 상태를 보고하는 포트가 있는 경우 의 지침에 따라 연결 가능성 복구를 수행하고 브로드캐스트 도메인에서 포트를 추가 또는 제거합니다 <<restore_node2_step4,4단계>>.

. 모든 포트가 브로드캐스트 도메인에 배치되었는지 확인합니다.
+
`network port show`

. 브로드캐스트 도메인의 모든 포트에 올바른 MTU(Maximum Transmission Unit)가 구성되어 있는지 확인합니다.
+
`network port broadcast-domain show`

. 다음 단계를 사용하여 복원해야 하는 SVM 및 LIF 홈 포트(있는 경우)를 지정하여 LIF 홈 포트를 복원합니다.
+
.. 대체된 LIF를 나열합니다.
+
`displaced-interface show`

.. LIF 홈 노드 및 홈 포트를 복원합니다.
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. 모든 LIF에 홈 포트가 있고 관리상 작동하는지 확인합니다.
+
`network interface show -fields home-port,status-admin`


