---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, NVRAM, controller, module, modules 
summary: ARL을 사용하여 동일한 섀시에서 컨트롤러 모델을 업그레이드할 때 교체 모듈을 사용하여 node1 설치를 확인합니다. 
---
= 노드1 설치를 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
교체 컨트롤러 모듈로 노드1을 부팅한 후 올바르게 설치되었는지 확인합니다.

AFF A250, AFF C250, AFF A800 또는 AFF C800 업그레이드의 경우 물리적 포트가 기존 컨트롤러와 교체 컨트롤러 간에 변경되기 때문에 물리적 포트를 기존 노드1에서 교체 노드1로 매핑할 수 있습니다. 물리적 포트는 이 업그레이드 절차에서 지원하는 다른 시스템에 대해 변경되지 않습니다.

.이 작업에 대해
노드 1이 쿼럼에 참가할 때까지 기다린 다음 컨트롤러 교체 작업을 다시 시작해야 합니다.

절차의 이 시점에서 노드 1이 쿼럼 자동 연결을 시도할 때 컨트롤러 업그레이드 작업이 일시 중지되어야 합니다.

.단계
. 노드 1이 쿼럼에 연결되었는지 확인합니다.
+
`cluster show -node node1 -fields health`

+
의 출력입니다 `health` 필드는 이어야 합니다 `true`.

. 노드 1이 노드 2와 동일한 클러스터의 일부이고 정상 상태인지 확인합니다.
+
`cluster show`

+
[NOTE]
====
부팅 후 node1이 quorum에 연결되지 않은 경우 5분 동안 기다렸다가 다시 확인하십시오. 클러스터 연결에 따라 포트 연결 검사가 완료되고 LIF를 해당 홈 포트로 이동하는 데 시간이 걸릴 수 있습니다.

노드1이 5분 후에도 여전히 쿼럼에 있지 않으면 진단 권한 명령을 사용하여 새 노드의 클러스터 포트를 "클러스터 IPspace"에 배치하여 수정하는 `network port modify <port_name> -ipspace Cluster`것이 좋습니다.

====
. 고급 권한 모드로 전환:
+
`set advanced`

. 컨트롤러 교체 작업의 상태를 확인하고 해당 상태가 노드 1이 중지되기 전의 일시 중지 상태와 동일한지 확인하여 새 컨트롤러 설치 및 케이블 이동에 대한 물리적 작업을 수행합니다.
+
`system controller replace show`

+
`system controller replace show-details`

. 컨트롤러 교체 작업을 재개합니다.
+
`system controller replace resume`

. 컨트롤러 교체 작업이 중재를 위해 다음 메시지와 함께 일시 중지됩니다.
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: 이 절차에서 section_re-creating vLANs, ifgrp, broadcast domain_이 node1_의 _Restore 네트워크 구성 으로 변경되었습니다.

. 컨트롤러 교체가 일시 중지 상태인 경우 로 진행합니다 <<노드 1에서 네트워크 구성을 복원합니다>>.




== 노드 1에서 네트워크 구성을 복원합니다

노드 1이 쿼럼에 있고 노드 2와 통신할 수 있는지 확인한 후 노드 1의 VLAN, 인터페이스 그룹 및 브로드캐스트 도메인이 노드 1에 표시되는지 확인합니다. 또한 모든 node1 네트워크 포트가 올바른 브로드캐스트 도메인에 구성되어 있는지 확인합니다.

.이 작업에 대해
VLAN, 인터페이스 그룹 및 브로드캐스트 도메인을 만들고 다시 만드는 방법에 대한 자세한 내용은 을 참조하십시오 link:other_references.html["참조"] 를 눌러 _Network Management_content에 연결합니다.

.단계
. 업그레이드된 노드 1에 있는 모든 물리적 포트 나열:
+
`network port show -node node1`

+
노드의 모든 물리적 네트워크 포트, VLAN 포트 및 인터페이스 그룹 포트가 표시됩니다. 이 출력에서 로 이동된 모든 물리적 포트를 볼 수 있습니다 `Cluster` ONTAP에 의한 브로드캐스트 도메인. 이 출력을 사용하면 인터페이스 그룹 구성원 포트, VLAN 기본 포트 또는 LIF 호스팅을 위한 독립 실행형 물리적 포트로 사용할 포트를 쉽게 결정할 수 있습니다.

. 클러스터의 브로드캐스트 도메인을 나열합니다.
+
`network port broadcast-domain show`

. 노드 1의 모든 포트에 대한 네트워크 포트 도달 가능 여부 나열:
+
`network port reachability show -node node1`

+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
위의 예제에서 node1은 컨트롤러를 교체한 후 부팅되었습니다. "연결 불가"를 표시하는 포트는 물리적으로 연결되어 있지 않습니다. 연결 상태가 아닌 다른 모든 포트를 복구해야 `ok`합니다.

+

NOTE: 업그레이드 중에는 네트워크 포트와 해당 연결이 변경되어서는 안 됩니다. 모든 포트는 올바른 브로드캐스트 도메인에 상주해야 하며 네트워크 포트 도달 가능성을 변경해서는 안 됩니다. 그러나 노드 2에서 노드 1로 LIF를 다시 이동하기 전에 네트워크 포트의 연결 가능성 및 상태를 확인해야 합니다.

. [[restore_node1_step4] 노드 1의 각 포트에 대한 연결 상태를 이외의 다른 연결 상태로 복구합니다 `ok` 다음 명령을 사용하여 다음 순서로 명령을 실행합니다.
+
`network port reachability repair -node _node_name_  -port _port_name_`

+
--
.. 물리적 포트
.. VLAN 포트


--
+
다음과 같은 출력이 표시됩니다.

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e1b
----
+
[listing]
----
Warning: Repairing port "node1:e1b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
이전 예에 표시된 것처럼, 현재 위치한 브로드캐스트 도메인의 도달 가능성 상태와 다를 수 있는 도달 가능성 상태의 포트에 대해 경고 메시지가 표시될 것입니다. 포트의 연결을 검토하고 응답합니다 `y` 또는 `n` 있습니다.

+
모든 물리적 포트에 예상되는 도달 능력이 있는지 확인합니다.

+
`network port reachability show`

+
도달 가능성 복구가 수행되면 ONTAP는 포트를 올바른 브로드캐스트 도메인에 배치하려고 시도합니다. 그러나 포트의 도달 가능 여부를 확인할 수 없고 기존 브로드캐스트 도메인에 속하지 않는 경우 ONTAP는 이러한 포트에 대한 새 브로드캐스트 도메인을 만듭니다.

. 포트 도달 가능성 확인:
+
`network port reachability show`

+
모든 포트가 올바르게 구성되고 올바른 브로드캐스트 도메인에 추가되면 가 `network port reachability show` 명령은 의 도달 가능성 상태를 보고해야 합니다 `ok` 연결된 모든 포트에 대해 및 상태를 로 표시합니다 `no-reachability` 물리적 연결이 없는 포트의 경우 이 두 포트가 아닌 다른 상태를 보고하는 포트가 있는 경우 의 지침에 따라 연결 가능성 복구를 수행하고 브로드캐스트 도메인에서 포트를 추가 또는 제거합니다 <<restore_node1_step4,4단계>>.

. 모든 포트가 브로드캐스트 도메인에 배치되었는지 확인합니다.
+
`network port show`

. 브로드캐스트 도메인의 모든 포트에 올바른 MTU(Maximum Transmission Unit)가 구성되어 있는지 확인합니다.
+
`network port broadcast-domain show`

. 다음 단계를 사용하여 복원해야 하는 SVM 및 LIF 홈 포트(있는 경우)를 지정하여 LIF 홈 포트를 복원합니다.
+
.. 대체된 LIF를 나열합니다.
+
`displaced-interface show`

.. LIF 홈 노드 및 홈 포트를 복원합니다.
+
`displaced-interface restore-home-node -node _node_name_ -vserver _vserver_name_ -lif-name _LIF_name_`



. 모든 LIF에 홈 포트가 있고 관리상 작동하는지 확인합니다.
+
`network interface show -fields home-port,status-admin`


