---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: ONTAP 9.8 이상을 실행하는 새 컨트롤러가 있는 HA 쌍의 스토리지 컨트롤러를 업그레이드하기 위해 수동 ARL 절차를 사용할지 여부를 결정합니다. 
---
= 이 집계 이전 절차를 사용할지 결정하십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 절차에서는 ONTAP 9.8 이상을 실행하는 시스템에서 수동 집계 재배치(ARL)를 사용하여 컨트롤러 하드웨어를 업그레이드하는 방법을 설명합니다. 숙련된 ONTAP 관리자만 이 복잡한 절차를 사용해야 합니다.

다음과 같은 상황에서 이 콘텐츠를 사용하십시오.

* 새 컨트롤러를 클러스터에 새 HA 쌍으로 추가하고 볼륨 이동을 사용하여 데이터를 마이그레이션하기를 원하지 않을 것입니다.
* ONTAP 관리에 대한 경험이 있으며 진단 권한 모드에서 작업할 때 발생할 수 있는 위험에 대해 잘 알 수 있습니다.
* 컨트롤러는 ONTAP 9.8 이상을 실행하고 있습니다.
* MetroCluster 9.8 이상을 실행하는 패브릭 ONTAP 4노드 및 8노드 구성을 사용하는 시스템이 있습니다.
* 시스템에 하이브리드 애그리게이트가 있습니다.


[NOTE]
====
* AFF A800 또는 AFF C800 과 같이 동일한 섀시에서 컨트롤러 모듈을 교체하여 시스템을 업그레이드하는 경우 NetApp 다음 업그레이드 절차를 사용하는 것이 좋습니다.link:../upgrade-arl-auto-in-chassis/index.html["ARL을 사용하여 기존 시스템 섀시 및 디스크를 유지하면서 컨트롤러 모델을 업그레이드합니다."] .  이 ARL 절차에는 업그레이드 절차 중에 컨트롤러를 제거하고 설치할 때 내부 디스크가 섀시에 안전하게 고정되도록 하는 단계가 포함되어 있습니다.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["기존 시스템 섀시와 디스크를 유지하면서 ARL을 사용하여 지원되는 시스템 업그레이드 조합에 대해 알아보세요."].

* 이 절차를 통해 NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE), NetApp 애그리게이트 암호화(NAE)를 사용할 수 있습니다.


====
컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.

을 참조하십시오 link:other_references.html["참조"] ONTAP 9 제품 설명서에 액세스할 수 있는 _ONTAP 9 문서 센터_에 연결합니다.



== 다른 하드웨어 업그레이드 절차를 선택하세요

* link:../upgrade-arl/index.html["컨트롤러 하드웨어 업그레이드에 사용 가능한 대체 ARL 방법을 검토하세요."]..
* 컨트롤러 하드웨어를 업그레이드하는 다른 방법을 선호하고 볼륨 이동을 원할 경우 을 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지 _ 을(를) 이동하여 _ 업그레이드 에 연결합니다.


.관련 정보
참조하다 link:other_references.html["참조"] _ONTAP 9 문서_에 링크합니다.
