---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade 
summary: ONTAP 9.8 이상을 실행하는 한 쌍의 컨트롤러에 수동 ARL 업그레이드 절차를 사용할 수 있는지 이해합니다. 
---
= ARL을 사용한 컨트롤러 업그레이드 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL(Aggregate Relocation)을 사용하여 ONTAP 9.8을 실행하는 컨트롤러 쌍을 업그레이드할 수 있는지 여부를 이해하려면 플랫폼 및 원래 컨트롤러와 교체 컨트롤러 모두의 구성에 따라 다릅니다.



== ARL에 대한 업그레이드가 지원됩니다

다음 상황에서 ARL을 사용하여 노드 쌍을 업그레이드할 수 있습니다.

* 업그레이드 전에 원래 컨트롤러와 교체 컨트롤러 모두 동일한 버전의 ONTAP 9.8을 실행해야 합니다.
* 교체 컨트롤러의 용량은 원래 컨트롤러와 같거나 더 커야 합니다. 용량이 같거나 높으면 NVRAM 크기, 볼륨, LUN 또는 애그리게이트 개수 제한값과 같은 특성을 나타내며, 새 노드의 최대 볼륨 또는 애그리게이트 크기를 나타냅니다.
* 다음과 같은 유형의 시스템을 업그레이드할 수 있습니다.
+
** FAS 시스템에서 FAS 시스템으로
** FlexArray 가상화 소프트웨어 또는 V-Series 시스템을 사용하는 시스템에 FAS 시스템 구축
** AFF 시스템에서 AFF 시스템으로.
** FlexArray 가상화 소프트웨어 또는 V 시리즈 시스템이 포함된 시스템에 어레이 LUN이 없는 경우 FlexArray 가상화 소프트웨어 또는 V-Series 시스템이 있는 시스템에서 FAS 시스템으로.
** V-Series 시스템을 FlexArray 가상화 소프트웨어 또는 V-Series 시스템이 포함된 시스템으로


* 일부 ARL 컨트롤러 업그레이드의 경우 교체 컨트롤러의 임시 클러스터 포트를 사용하여 업그레이드할 수 있습니다. 예를 들어 AFF A300에서 AFF A400 시스템으로 업그레이드하는 경우 AFF A400 구성에 따라 2개의 메자닌 포트 또는 4포트 10GbE 네트워크 인터페이스 카드를 추가하여 임시 클러스터 포트를 제공할 수 있습니다. 임시 클러스터 포트를 사용하여 컨트롤러 업그레이드를 완료한 후 클러스터를 대체 컨트롤러의 100GbE 포트로 중단 없이 마이그레이션할 수 있습니다.
* ARL을 사용한 컨트롤러 업그레이드는 SnapLock 엔터프라이즈 및 SnapLock 규정 준수 볼륨으로 구성된 시스템에서 지원됩니다.


ARL이 원본 및 교체 컨트롤러에서 수행될 수 있는지 확인해야 합니다. 정의된 모든 애그리게이트의 크기와 원래 시스템에서 지원하는 디스크 수를 확인해야 합니다. 그런 다음 새 시스템에서 지원하는 애그리게이트 크기 및 디스크 수와 비교합니다. 이 정보에 액세스하려면 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크 새 시스템에서 지원하는 디스크 수와 애그리게이트 크기는 원래 시스템에서 지원하는 디스크 수와 같거나 그보다 커야 합니다.

클러스터 혼합 규칙에서 원래 컨트롤러를 교체할 때 새 노드가 기존 노드와 클러스터의 일부가 될 수 있는지 확인해야 합니다. 클러스터 혼합 규칙에 대한 자세한 내용은 를 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크


NOTE: 두 시스템 모두 고가용성(HA) 또는 비 HA입니다. 두 노드 모두 Personality를 설정 또는 해제해야만 합니다. 동일한 HA Pair에서 Personality를 설정하지 않은 노드로는 All Flash Optimized Personality를 활성화한 노드를 결합할 수 없습니다. 특성이 다른 경우 기술 지원 부서에 문의하십시오.


NOTE: 새 시스템의 슬롯 수가 원래 시스템보다 적거나 포트가 적거나 다른 경우 새 시스템에 어댑터를 추가해야 할 수 있습니다. 을 참조하십시오 link:other_references.html["참조"] 특정 플랫폼에 대한 자세한 내용은 NetApp Support 사이트에서 _Hardware Universe_에 대한 링크를 참조하십시오.

업그레이드를 시작하기 전에 FAS8080, AFF8080 시스템과 같이 노드당 클러스터 포트가 2개 이상인 시스템이 있는 경우 클러스터 LIF를 노드당 두 개의 클러스터 포트로 마이그레이션하고 재구성해야 합니다. 노드당 둘 이상의 클러스터 포트로 컨트롤러 업그레이드를 수행하는 경우 업그레이드 후 새 컨트롤러에 클러스터 LIF가 누락될 수 있습니다.



== ARL에 대한 업그레이드가 지원되지 않습니다

다음 업그레이드는 수행할 수 없습니다.

* ONTAP 9.8 이상을 실행할 수 없는 컨트롤러와 연결 또는 컨트롤러
* 원래 컨트롤러에 연결된 디스크 쉘프를 지원하지 않는 컨트롤러 교체
+
디스크 지원 정보는 을 참조하십시오 link:other_references.html["참조"] Hardware Universe_에 대한 링크

* 컨트롤러에서 루트 애그리게이트 또는 내부 드라이브의 데이터 애그리게이트를 사용합니다.
+
내부 디스크 드라이브에서 루트 애그리게이트 또는 데이터 애그리게이트로 컨트롤러를 업그레이드하려면 를 참조하십시오 link:other_references.html["참조"] 볼륨 또는 스토리지를 이동하여 _ 업그레이드 에 연결하고 _ 볼륨 _ 을(를) 이동하여 clustered Data ONTAP을 실행하는 노드 쌍 업그레이드 절차로 이동합니다.

+

NOTE: 클러스터의 노드에서 ONTAP를 업그레이드하려면 를 참조하십시오 link:other_references.html["참조"] ONTAP_ 업그레이드 링크





== 가정 및 용어

이 문서는 다음과 같은 가정 하에 작성되었습니다.

* 교체 컨트롤러 하드웨어는 새 하드웨어이며 사용되지 않았습니다.
+

WARNING: *주의*: 이 절차에서는 교체 컨트롤러 하드웨어가 새 것으로 간주되어 사용되지 않았으므로, "wipeconfig" 명령으로 사용한 컨트롤러를 준비하는 데 필요한 단계는 이 절차에 포함되지 않습니다. 교체 컨트롤러 하드웨어를 이전에 사용한 경우, 특히 컨트롤러가 7-Mode에서 Data ONTAP를 실행 중인 경우 기술 지원 부서에 문의해야 합니다.

* 노드 쌍을 업그레이드하기 위한 지침을 읽고 이해했습니다.
+

WARNING: * 주의 *: NVRAM 내용을 지우지 마십시오. NVRAM의 내용을 지우려면 NetApp 기술 지원 팀에 문의하십시오.

* '수정' 명령 전후에 적절한 명령을 수행하고 '수정' 명령이 성공했는지 확인하기 위해 'show' 명령의 출력을 비교하고 있습니다.
* SAN 구성을 사용하는 경우 HA 2노드에 각 SVM(스토리지 가상 머신)에 대한 로컬 및 파트너 LIF가 있습니다. 각 SVM에 대한 로컬 및 파트너 LIF가 없는 경우 업그레이드를 시작하기 전에 해당 SVM에 대한 원격 및 로컬 노드에 SAN 데이터 LIF를 추가해야 합니다.
* SAN 구성에 포트 세트가 있는 경우 각 바인딩된 포트 세트에 HA 쌍의 각 노드에서 적어도 하나의 LIF가 포함되어 있는지 확인해야 합니다.


이 절차에서는 node 재부팅, 인쇄 또는 환경 변수 설정과 같은 특정 작업을 수행할 수 있는 노드의 프롬프트를 _boot 환경 프롬프트_로 사용합니다. 프롬프트는 _ 부트 로더 프롬프트라고도 합니다.

부팅 환경 프롬프트가 다음 예에 표시됩니다.

[listing]
----
LOADER>
----


== ONTAP 9.8 이상의 라이센스

클러스터를 설정할 때 설치 마법사에서 클러스터 기본 라이센스 키를 입력하라는 메시지가 표시됩니다. 그러나 일부 기능에는 하나 이상의 기능을 포함하는 _packages_로 발급된 추가 라이센스가 필요합니다. 클러스터의 각 노드에는 클러스터에서 사용되는 각 기능에 대한 자체 키가 있어야 합니다.

새 라이센스 키가 없는 경우 클러스터에서 현재 라이센스가 부여된 기능을 새 컨트롤러에서 사용할 수 있으며 계속 작동합니다. 그러나 컨트롤러에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 업그레이드가 완료된 후 새 컨트롤러의 새 라이센스 키 또는 키를 설치해야 합니다.

모든 라이센스 키의 길이는 28자의 알파벳 대문자입니다. 을 참조하십시오 link:other_references.html["참조"] ONTAP 9.8에 대한 새로운 28자 라이센스 키를 얻을 수 있는 _NetApp Support 사이트_에 대한 링크입니다. 이상. 키는 _ 소프트웨어 라이센스 _ 의 _ My Support _ 섹션에서 사용할 수 있습니다. 사이트에 필요한 라이센스 키가 없는 경우 NetApp 세일즈 담당자에게 문의하십시오.

라이센스에 대한 자세한 내용은 를 참조하십시오 link:other_references.html["참조"] 시스템 관리 참조 _ 에 대한 링크



== 스토리지 암호화

스토리지 암호화에 원래 노드 또는 새 노드를 사용할 수 있습니다. 이 경우 스토리지 암호화가 올바르게 설정되었는지 확인하려면 이 절차의 추가 단계를 수행해야 합니다.

스토리지 암호화를 사용하려면 노드와 연결된 모든 디스크 드라이브에 자체 암호화 디스크 드라이브가 있어야 합니다.



== 스위치가 없는 2노드 클러스터

스위치가 없는 2노드 클러스터에서 노드를 업그레이드할 경우 업그레이드를 수행하는 동안 스위치가 없는 클러스터에 노드를 그대로 둘 수 있습니다. 이러한 LUN을 스위치 클러스터로 변환할 필요는 없습니다



== 문제 해결

이 절차에는 문제 해결 방법이 포함되어 있습니다.

컨트롤러를 업그레이드하는 동안 문제가 발생하면 을 참조하십시오 link:troubleshoot_index.html["문제 해결"] 자세한 내용 및 가능한 해결 방법은 절차 끝 부분의 섹션을 참조하십시오.

발생한 문제에 대한 해결책을 찾지 못한 경우 기술 지원 부서에 문의하십시오.
