---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node1_node2.html 
keywords: nas, node1, node2, lifs, cluster, san 
summary: 2노드 클러스터가 있는 경우 노드 1의 데이터 LIF를 노드 2로 이동하거나, 클러스터에 노드가 2개 이상인 경우 ONTAP 9.8 이상을 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 노드 1의 데이터 LIF를 노드 2로 이동합니다. 
---
= 노드 1이 소유한 NAS 데이터 LIF를 노드 2로 이동합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 1을 노드 3으로 교체하려면 먼저 노드 1이 소유한 NAS 데이터 LIF를 노드 2가 있는 경우 노드 2로 이동하거나, 클러스터에 노드가 2개 이상인 경우 노드 1을 노드 2로 이동해야 합니다. 사용하는 방법은 클러스터가 NAS에 대해 구성되었는지 SAN에 대해 구성되었는지 여부에 따라 다릅니다.

원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. 노드 3을 온라인으로 설정한 후 LIF가 정상 작동하는지 확인해야 합니다.

.단계
. 다음 명령을 입력하고 출력을 캡처하여 노드 1에서 호스팅되는 모든 NAS 데이터 LIF를 나열합니다.
+
'network interface show-data-protocol nfs|cifs-curr-node<node1>'

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. [[step2]]노드 1과 노드 2에 있는 모든 LIF의 자동 되돌리기 설정을 수정합니다.
+
'network interface modify -vserver Vserver_name -lif LIF_name -auto-revert false'

. [[step3]]노드 1의 인터페이스 그룹 및 VLAN에 호스팅된 NAS 데이터 LIF를 마이그레이션하려면 다음 단계를 수행하십시오.
+
.. [[subepa]] 노드 1의 인터페이스 그룹 및 VLAN에 호스팅된 LIF를 노드 2의 포트로 마이그레이션합니다. 노드 2의 포트는 각 LIF에 대해 다음 명령을 입력하여 인터페이스 그룹의 LIF와 동일한 네트워크에 LIF를 호스팅할 수 있습니다.
+
'network interface migrate-vserver <Vserver_NAME> -lif <LIF_name> -destination-node <node2> – destination-port <NetPort | ifgrp>'

.. 에서 LIF 및 VLAN의 홈 포트와 홈 노드를 수정합니다 <<substepa,하위 단계 A>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver <Vserver_NAME> -lif <LIF_name> -home-node <node2> -home-port <NetPort | ifgrp>'



. [[4단계]] 다음 작업 중 하나를 수행합니다.
+
[cols="20,80"]
|===
| 클러스터가 구성된 경우... | 그러면... 


| NAS | 완료 <<man_lif_1_2_step5,5단계>> 부터 까지 <<man_lif_1_2_step8,8단계>>. 


| 산 | 업그레이드 시 노드의 모든 SAN LIF를 비활성화:'network interface modify -vserver <Vserver-name> -lif <LIF_name> -home-node <node_to_upgrade> -home-port <NetPort | ifgrp> -status-admin down' 
|===
. [[man_lif_1_2_step5]] 각 데이터 LIF에 대해 다음 명령을 입력하여 노드 1에서 노드 2로 NAS 데이터 LIF를 마이그레이션합니다.
+
'network interface migrate-vserver <Vserver-name> -lif <LIF_name> -destination-node <node2> -destination-port <data_port>'

. [[step6]] 다음 명령을 입력하고 출력을 검사하여 LIF가 올바른 포트로 이동되었으며 LIF의 상태가 UP인지 확인하고, 두 노드 중 하나에 다음 명령을 입력하고 출력을 검사하여 확인합니다.
+
'network interface show-curr-node <node2> - data-protocol nfs | cifs'

. [[step7]]마이그레이션된 LIF의 홈 노드를 수정합니다.
+
'network interface modify -vserver <Vserver-name> -lif <LIF_name> -home-node <node2> -home-port <port_name>'

. [[man_lif_1_2_step8]] LIF가 포트를 홈 또는 현재 포트로 사용하고 있는지 확인합니다. 포트가 홈 또는 현재 포트가 아닌 경우 로 이동합니다 <<man_lif_1_2_step9,9단계>>:
+
'network interface show-home-node <node2> - home-port <port_name>'

+
'network interface show-curr-node <node_name>-curr-port <port_name>'

. [[man_lif_1_2_step9]] LIF가 포트를 홈 포트 또는 현재 포트로 사용하고 있는 경우, LIF를 수정하여 다른 포트를 사용하도록 합니다.
+
'network interface migrate-vserver <Vserver-name> -lif <LIF_name> -destination –node <node_name> -destination-port <port_name>'

+
'network interface modify -vserver <Vserver-name> -lif <LIF_name> -home –node <node_name> -home-port <port_name>'

. [[10단계]] LIF가 하나라도 다운되면 각 LIF에 대해 다음 명령을 한 번 입력하여 LIF의 관리 상태를 "작동"으로 설정하십시오.
+
'network interface modify -vserver <Vserver-name> -lif <LIF_name> -home-node <nodename> -status-admin up'

+

NOTE: MetroCluster 구성의 경우, 대상 SVM(스토리지 가상 머신)의 LIF를 호스팅하는 포트와 연결되어 있으므로 포트의 브로드캐스트 도메인을 변경하지 못할 수 있습니다. 대상 LIF를 적절한 포트에 재할당하려면 원격 사이트의 해당 소스 SVM에서 'MetroCluster vserver resync -vserver <Vserver_NAME>' 명령을 입력합니다

. [[step11]] 다음 명령을 입력하고 해당 출력을 확인하여 노드 1에 남아 있는 데이터 LIF가 없는지 확인합니다.
+
'network interface show-curr-node <node1> - role data'


