---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/relocate_node2_non_root_aggr_node3_node4.html 
keywords: relocate, non-root, aggregates, node3, node4 
summary: ONTAP 9.8 이상을 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 노드 2의 비루트 애그리게이트를 노드 3에서 노드 4로 재배치합니다. 
---
= 노드 2의 비 루트 애그리게이트를 노드 3에서 노드 4로 재배치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 2의 비루트 애그리게이트를 노드 3으로 재배치한 후 노드 3에서 노드 4로 재이동해야 합니다.

.단계
. [[man_relocate_3_4_Step1] 두 컨트롤러 중 하나에서 다음 명령을 입력하고 출력을 검사하여 재배치할 비루트 애그리게이트를 식별합니다.
+
'Storage aggregate show-owner-name_node3_-home-id_node2_system_id_'

. 다음 하위 단계를 완료하여 집계를 재배치합니다.
+
.. 두 노드 중 하나에서 다음 명령을 입력하여 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

.. 다음 명령을 입력합니다.
+
'스토리지 애그리게이트 재배치 시작 - node_node3_-destination_node4_-aggregate-list_aggr_name1, aggr_name2...- ndo-controller-upgrade TRUE'

+
Aggregate 목록은 에서 얻은 노드 4가 소유한 Aggregate 목록입니다 ,1단계.

.. 메시지가 나타나면 y를 입력합니다.
+
재배치가 백그라운드에서 실행됩니다. Aggregate를 재배치하는 데 몇 초에서 몇 분 정도 걸릴 수 있습니다. 여기에는 클라이언트 중단 및 무중단 부분 이 모두 포함됩니다. 명령을 실행해도 오프라인 또는 제한된 애그리게이트는 재배치되지 않습니다.

.. 관리자 수준으로 돌아가기:
+
'Set-Privilege admin'입니다



. [[step3]] 재배치 상태 확인:
+
'Storage aggregate relocation show -node_node3_'

+
이 출력은 재배치된 후 Aggregate에 대해 Done을 표시합니다.

+

NOTE: 다음 단계로 진행하기 전에 노드 2 애그리게이트를 노드 4로 재배치할 때까지 기다립니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 재배치 대상... | 그러면... 


| 모든 애그리게이트가 성공했습니다 | 로 이동합니다 ,5단계. 


| 모든 애그리게이트가 실패했거나 거부권을 행사한 경우  a| 
.. EMS 로그에서 수정 조치를 확인합니다.
.. 수정 조치를 수행합니다.
.. 두 노드 중 하나에서 다음 명령을 입력하여 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

.. 장애가 발생하거나 거부되는 애그리게이트를 재배치합니다.
+
'스토리지 애그리게이트 재배치 시작 - node_node3_destination_node4_-aggregate-list_aggr_name1, aggr_name2..._ndo-controller-upgrade TRUE'

+
애그리게이트 목록은 실패한 애그리게이트 또는 거부된 애그리게이트의 목록입니다.

.. 메시지가 나타나면 y를 입력합니다.
.. 다음 명령을 입력하여 admin 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



필요한 경우 다음 방법 중 하나를 사용하여 재배치를 수행할 수 있습니다.

** 거부권 확인 무시:
+
스토리지 골재 재배치 시작-오버라이드-베또-ndo-controller-upgrade

** 대상 검사 재정의:
+
'Storage aggregate relocation start-override-destination-checks-ndocontroller-upgrade'를 참조하십시오



스토리지 애그리게이트 재배치 명령에 대한 자세한 내용은 섹션을 참조하십시오 link:other_references.html["참조"] CLI_ 및 _ONTAP 9 명령을 사용하여 _ 디스크 및 애그리게이트 관리를 링크하려면 수동 페이지 참조 _.

|===
. [[man_relocate_3_4_Step5]] 모든 node2 비루트 애그리게이트가 온라인 상태이고 노드 4의 상태가 온라인인지 확인합니다.
+
'storage aggregate show -node_node4_ -state offline-root false'

+
에서 명령의 출력에 노드 2 애그리게이트가 나열되어 있습니다 ,1단계.

. Aggregate가 오프라인 상태가 되거나 외부 상태가 된 경우 각 Aggregate에 대해 다음 명령을 사용하여 온라인 상태로 전환합니다.
+
'Storage aggregate online-aggregate_agr_name_'

. 노드 4에서 노드 2 애그리게이트의 모든 볼륨이 온라인 상태인지 확인합니다.
+
'volume show-node_node4_-state offline

. 노드 4에서 오프라인 상태인 볼륨이 있는 경우 해당 볼륨을 온라인으로 전환합니다.
+
'volume online-vserver_vserver-name_-volume_volume_name_'

. 노드 4의 경우 업그레이드 후 AutoSupport 메시지를 NetApp에 보냅니다.
+
'System node AutoSupport invoke - node_node4_ -type all-message "_node2_successfully from_platform_old_to_platform_new_""를 입력합니다


