---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/relocate_non_root_aggr_node2_node3.html 
keywords: non-root, non-root, aggregates, relocate, node2, node3 
summary: ONTAP 9.8 이상을 실행하는 컨트롤러의 수동 ARL 업그레이드 중에 node2에 대한 AutoSupport 메시지를 보내고 노드 2의 비루트 애그리게이트를 노드 3으로 수동으로 재배치합니다. 
---
= 노드 2에서 노드 3으로 비루트 애그리게이트를 재배치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 2를 노드 4로 교체하려면 먼저 노드 2에 대한 AutoSupport 메시지를 보낸 다음 노드 2가 소유한 비루트 애그리게이트를 노드 3으로 재배치해야 합니다.

.단계
. [[1단계]] 노드 2에 대해 NetApp에 AutoSupport 메시지 보내기:
+
`system node autosupport invoke -node _node2_ -type all -message "Upgrading _node2_ from _platform_old_ to _platform_new_"`

. AutoSupport 메시지가 전송되었는지 확인합니다.
+
`system node autosupport show -node _node2_ -instance`

+
"마지막으로 보낸 제목:" 및 "마지막 보낸 시간:" 필드에는 마지막으로 보낸 메시지의 메시지 제목과 메시지를 보낸 시간이 포함됩니다.

. [[step3]] 비루트 애그리게이트를 재배치합니다.
+
.. 권한 수준을 고급으로 설정합니다.
+
`set -privilege advanced`

.. 노드 2가 소유한 애그리게이트 나열:
+
`storage aggregate show -owner-name _node2_`

.. 애그리게이트 재배치 시작:
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: 이 명령은 비루트 애그리게이트만 찾습니다.

.. 메시지가 표시되면 를 입력합니다 `y`.
+
재배치가 백그라운드에서 실행됩니다. Aggregate를 재배치하는 데 몇 초에서 몇 분 정도 걸릴 수 있습니다. 여기에는 클라이언트 중단 및 무중단 부분 이 모두 포함됩니다. 명령을 실행해도 오프라인 또는 제한된 애그리게이트는 재배치되지 않습니다.

.. 관리자 권한 레벨로 돌아갑니다.
+
`set -privilege admin`



. 노드 2의 재배치 상태를 확인합니다.
+
`storage aggregate relocation show -node _node2_`

+
재배치된 aggregate에 대해 출력에 "Done"이 표시됩니다.

+

NOTE: 다음 단계로 진행하기 전에 노드 2가 소유한 모든 애그리게이트를 노드 3으로 재배치할 때까지 기다려야 합니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 재배치 대상... | 그러면... 


| 모든 애그리게이트가 성공했습니다 | 로 이동합니다 <<man_relocate_2_3_step6,6단계>>. 


| 모든 애그리게이트가 실패했거나 거부권을 행사한 경우  a| 
.. 자세한 상태 메시지를 표시합니다.
+
`storage aggregate show -instance`

+
또한 EMS 로그를 확인하여 필요한 수정 조치를 확인할 수도 있습니다.

+

NOTE: 를 클릭합니다 `event log show` 명령은 발생한 모든 오류를 나열합니다.

.. 수정 조치를 수행합니다.
.. 권한 수준을 고급으로 설정합니다.
+
`set -privilege advanced`

.. 장애가 발생하거나 거부되는 애그리게이트를 재배치합니다.
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controllerupgrade true`

.. 메시지가 표시되면 를 입력합니다 `y`.
.. 관리자 권한 레벨로 돌아갑니다.
+
`set -privilege admin`



필요한 경우 다음 방법 중 하나를 사용하여 재배치를 강제 실행할 수 있습니다.

** 거부권 확인을 무시함으로써:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** 목적지 확인을 무시함으로써:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



스토리지 애그리게이트 재배치 명령에 대한 자세한 내용은 로 이동하십시오 link:other_references.html["참조"] CLI_ 및 _ONTAP 9 명령을 사용하여 _ 디스크 및 애그리게이트 관리를 링크하려면 수동 페이지 참조 _.

|===
. [[man_relocate_2_3_step6]]루트가 아닌 모든 애그리게이트가 노드 3에서 온라인 상태인지 확인:
+
`storage aggregate show -node _node3_ -state offline -root false`

+
애그리게이트가 오프라인 상태가 되거나 외부 애그리게이트로 전환된 경우, 각 애그리게이트에 대해 한 번씩 온라인 상태를 유지해야 합니다.

+
`storage aggregate online -aggregate _aggr_name_`

. 노드 3에서 모든 볼륨이 온라인 상태인지 확인합니다.
+
`volume show -node _node3_ -state offline`

+
노드 3에서 오프라인 상태인 볼륨이 있는 경우 각 볼륨에 대해 한 번씩 온라인 상태로 전환해야 합니다.

+
`volume online -vserver _Vserver-name_ -volume _volume-name_`

. 노드 2가 루트가 아닌 온라인 애그리게이트를 소유하지 않는지 확인합니다.
+
`storage aggregate show -owner-name _node2_ -ha-policy sfo -state online`

+
루트가 아닌 모든 온라인 애그리게이트가 이미 노드 3에 재배치되었기 때문에 명령 출력에 루트가 아닌 온라인 애그리게이트를 표시할 수 없습니다.


