---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: ONTAP 9.8 이상을 실행하는 컨트롤러에서 수동 ARL 업그레이드 중에 노드 4 온보드 FC 포트, UTA/UTA2 포트 또는 UTA/UTA2 카드를 구성합니다. 
---
= 노드 4에 FC 또는 UTA/UTA2 구성을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 4에 온보드 FC 포트, 온보드 UTA/UTA2(Unified Target Adapter) 포트 또는 UTA/UTA2 카드가 있는 경우, 나머지 절차를 완료하기 전에 설정을 구성해야 합니다.

.이 작업에 대해
완료해야 할 수도 있습니다<<노드 4에서 FC 포트를 구성합니다>> 또는<<노드 4의 UTA/UTA2 포트를 확인하고 구성합니다>> , 또는 두 섹션 모두.

node4에 온보드 FC 포트, 온보드 UTA/UTA2 포트 또는 UTA/UTA2 카드(예: ONTAP 9.15.1부터 도입된 AFF 및 FAS 시스템)가 없고 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 다음으로 건너뛸 수 있습니다.link:map_ports_node2_node4.html["노드 2의 포트를 노드 4로 매핑합니다"] .



== 노드 4에서 FC 포트를 구성합니다

노드 4에 온보드 또는 FC 어댑터가 있는 FC 포트가 있는 경우 포트가 사전 구성되어 있지 않으므로 서비스를 시작하기 전에 노드에서 포트 구성을 설정해야 합니다. 포트가 구성되지 않은 경우 서비스가 중단될 수 있습니다.

.시작하기 전에
섹션에 저장한 노드 2의 FC 포트 설정 값이 있어야 합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"].

.이 작업에 대해
시스템에 FC 구성이 없는 경우 이 섹션을 건너뛸 수 있습니다. 시스템에 온보드 UTA/UTA2 포트 또는 UTA/UTA2 어댑터가 있는 경우, 에서 포트를 구성합니다 <<노드 4의 UTA/UTA2 포트를 확인하고 구성합니다>>.


IMPORTANT: 클러스터 프롬프트에서 이 섹션의 명령을 입력하세요.

.단계
. 시스템의 모든 FC 및 컨버지드 네트워크 어댑터에 대한 정보를 표시합니다.
+
`system node hardware unified-connect show`

. 새 노드의 FC 설정을 원래 노드에서 이전에 캡처한 설정과 비교합니다.
. 필요에 따라 노드 4의 FC 포트를 수정합니다.
+
** 타겟 포트를 프로그래밍하려면
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 이니시에이터 포트를 프로그래밍하려면:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` FC4 유형, 타겟 또는 이니시에이터입니다.



. 다음 명령을 입력하고 출력을 검토하여 새로운 설정을 확인하세요.
+
`system node unified-connect show`

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 새 노드의 기본 FC 설정이... | 그러면... 


| 원래 노드에서 캡처한 노드와 동일합니다 | 로 가다<<man_config_4_Step9,9단계>> . 


| 원래 노드에서 캡처한 노드와 다릅니다 | 로 가다<<man_config_4_Step6,Step6>> . 
|===
. [[man_config_4_Step6]]유지 관리 모드 종료:
+
`halt`

. 명령을 입력한 후 부팅 환경 프롬프트에서 시스템이 중지될 때까지 기다리십시오.
. 부트 환경 프롬프트에서 다음 명령을 입력하여 node4를 부트합니다.
+
`boot_ontap`

. [[man_config_4_Step9]]다음 작업 중 하나를 수행하세요.
+
** 로 이동합니다 <<노드 4의 UTA/UTA2 포트를 확인하고 구성합니다>> 노드 4에 UTA/UTA2A 카드 또는 UTA/UTA2 온보드 포트가 있는 경우
** 섹션을 건너뛰고 로 이동합니다 link:map_ports_node2_node4.html["노드 2의 포트를 노드 4로 매핑합니다"] 노드 4에 UTA/UTA2 카드 또는 UTA/UTA2 온보드 포트가 없는 경우






== 노드 4의 UTA/UTA2 포트를 확인하고 구성합니다

노드 4에 온보드 UTA/UTA2 포트 또는 UTA/UTA2A 카드가 있는 경우 업그레이드 시스템을 사용할 방식에 따라 포트 구성을 확인하고 포트를 구성해야 합니다.

.시작하기 전에
UTA/UTA2 포트에 알맞은 SFP+ 모듈이 있어야 합니다.

.이 작업에 대해
UTA/UTA2 포트를 네이티브 FC 모드 또는 UTA/UTA2A 모드로 구성할 수 있습니다. FC 모드는 FC 이니시에이터 및 FC 타겟을 지원하며, UTA/UTA2 모드를 사용하면 동시 NIC 및 FCoE 트래픽을 지원하여 동일한 10GbE SFP+ 인터페이스를 공유하고 FC 타겟을 지원합니다.


NOTE: NetApp 마케팅 자료에서는 UTA2 용어를 사용하여 CNA 어댑터 및 포트를 참조할 수 있습니다. 그러나 CLI에서는 CNA라는 용어를 사용합니다.

UTA/UTA2 포트는 다음 구성을 사용하여 어댑터 또는 컨트롤러에 있을 수 있습니다.

* UTA/UTA2 카드를 컨트롤러와 동시에 주문했으며 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.
* 컨트롤러와 별도로 주문한 UTA/UTA2 카드는 기본 FC 대상 퍼스낼리티로 제공됩니다.
* 새 컨트롤러의 온보드 UTA/UTA2 포트는 사용자가 요청한 Personality를 구성하기 위해 배송 전에 구성되었습니다.


하지만 노드 4의 UTA/UTA2 포트 구성을 확인하고 필요한 경우 변경할 수 있습니다.


WARNING: 유지 관리 모드로 들어가라는 지시가 없는 한, 클러스터 프롬프트에서 이 섹션의 명령을 입력하세요.  MetroCluster FC 시스템이 있는 경우 UTA/UTA2 포트를 구성하려면 유지 관리 모드에 있어야 합니다.

.단계
. 현재 node4에서 포트가 어떻게 구성되어 있는지 확인하세요.
+
`system node hardware unified-connect show`

. 현재 SFP+ 모듈이 원하는 용과 일치하지 않는 경우 올바른 SFP+ 모듈로 교체하십시오.
+
올바른 SFP+ 모듈을 얻으려면 NetApp 담당자에게 문의하십시오.

. 의 출력을 검사합니다 `system node hardware unified-connect show` 또는 `ucadmin show` UTA/UTA2 포트가 원하는 특성을 가지고 있는지 여부를 확인합니다.
. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| CNA 포트... | 그러면... 


| 원하는 개성을 표현하지 마십시오 | 로 이동합니다 <<man_check_4_Step5,5단계>>. 


| 원하는 개성을 갖고 싶어하세요 | 단계 5에서 단계 12까지 건너뛰고 로 이동합니다 <<man_check_4_Step13,13단계>>. 
|===
. [[man_check_4_Step5]]시스템에 저장 디스크가 있고 Data ONTAP 8.3을 실행 중인 경우 node4를 부팅하고 유지 관리 모드로 들어갑니다.
+
`boot_ontap maint`

. 다음 명령을 입력하고 출력을 확인하여 설정을 확인합니다.
+
`ucadmin show`

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 구성 중인 경우... | 그러면... 


| UTA/UTA2A 카드의 포트 | 로 가다<<man_check_4_Step8,8단계>> . 


| 온보드 UTA/UTA2 포트 | 8단계를 건너뛰고 다음으로 이동하세요.<<man_check_4_Step9,9단계>> . 
|===
. [[man_check_4_Step8]]어댑터가 이니시에이터 모드이고 UTA/UTA2 포트가 온라인인 경우 UTA/UTA2 포트를 오프라인으로 전환합니다.
+
`storage disable adapter _adapter_name_`

+
대상 모드의 어댑터는 유지 관리 모드에서 자동으로 오프라인 상태가 됩니다.

. [[man_check_4_Step9]]현재 구성이 원하는 용도와 일치하지 않으면 다음 명령을 입력하여 필요에 따라 구성을 변경합니다.
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` 성격 모드: FC 또는 10GbE UTA
** `-t` FC4 유형: 타겟 또는 이니시에이터입니다.


+

NOTE: 테이프 드라이브에는 FC 이니시에이터를 사용해야 하고 SAN 클라이언트에는 FC 대상을 사용해야 합니다.

. 시스템에 저장 디스크가 있는 경우 다음 명령을 입력합니다.
+
`halt`

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

+
.. 다음 명령을 입력합니다.
+
`boot_ontap`



. 시스템에 저장 디스크가 있는 경우 다음 명령을 입력합니다.
+
`system node hardware unified-connect show`

+
다음 예제의 출력은 FC4 어댑터 "1b"의 유형이 로 변경되었음을 나타냅니다 `initiator` 어댑터 "2a"와 "2b"의 모드가 로 변경됩니다 `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. 각 포트에 대해 다음 명령 중 하나를 입력하여 타겟 포트를 온라인으로 전환합니다.
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_4_Step13]] 포트에 케이블을 연결합니다.

